### ISSUE TITLE
vulkan archlinux swapchain unreachable

### ISSUE THREAD

**Issue by m4b** [gfx-rs/wgpu#1022]
saw this panic occuring on archlinux vulkan machine with intel integrated; it seems random?
```
thread 'main' panicked at 'internal error: entered unreachable code', /home/m4b/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-core-0.6.5/src/swap_chain.rs:170:60
stack backtrace:
   0: std::panicking::begin_panic
             at /home/m4b/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:497
   1: wgpu_core::swap_chain::<impl wgpu_core::hub::Global<G>>::swap_chain_get_current_texture_view
             at /home/m4b/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-core-0.6.5/src/swap_chain.rs:170
   2: <wgpu::backend::direct::Context as wgpu::Context>::swap_chain_get_current_texture_view
             at /home/m4b/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.6.0/src/backend/direct.rs:1000
   3: wgpu::SwapChain::get_current_frame
             at /home/m4b/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.6.0/src/lib.rs:2530
```
random guess: could be related to low memory on the system? rust analyzer was using a lot of ram and caused some lockups in the system.
regardless, probably unreachable code paths shouldn't be triggered regardless of ram usage on the host machine if this guess is right.

**Comment by cwfitzgerald** [comment]
Closing as stale, please refile if it's still an issue.
