### ISSUE TITLE
Memory issue

### ISSUE THREAD

**Issue by lordnoriyuki** [gfx-rs/wgpu#1042]
Seeing another gpu-alloc issue:

```
thread 'main' panicked at 'Memory must not be used anywhere: Memory { heap: Public(MemoryTypeId(1), <GFX9AMD_MtlBuffer: 0x7fb98b808a60>
    label = <none> 
    length = 33554432 
    cpuCacheMode = MTLCPUCacheModeDefaultCache 
    storageMode = MTLStorageModeShared 
    hazardTrackingMode = MTLHazardTrackingModeTracked 
    resourceOptions = MTLResourceCPUCacheModeDefaultCache MTLResourceStorageModeShared MTLResourceHazardTrackingModeTracked  
    purgeableState = MTLPurgeableStateNonVolatile), size: 33554432 }', /Users/ln/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/549ea00/wgpu-core/src/device/alloc.rs:227:46
stack backtrace:
   0: rust_begin_unwind
             at /rustc/d9a105fdd46c926ae606777a46dd90e5b838f92f/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/d9a105fdd46c926ae606777a46dd90e5b838f92f/library/core/src/panicking.rs:92:14
   2: core::option::expect_none_failed
             at /rustc/d9a105fdd46c926ae606777a46dd90e5b838f92f/library/core/src/option.rs:1268:5
   3: gpu_alloc::linear::LinearAllocator<M>::dealloc
   4: gpu_alloc::allocator::GpuAllocator<M>::dealloc
   5: wgpu_core::device::life::LifetimeTracker<B>::cleanup
   6: wgpu_core::device::Device<B>::maintain
   7: wgpu_core::device::queue::<impl wgpu_core::hub::Global<G>>::queue_submit
   8: <wgpu::backend::direct::Context as wgpu::Context>::queue_submit
```

I'll get a trace.

**Comment by lordnoriyuki** [comment]
Too slow. Closing this one.
