### ISSUE TITLE
Panic on render pipeline creation with `thread 'main' panicked at 'no entry found for key'` if a render attachment is not written to in a frag shader

### ISSUE THREAD

**Issue by expenses** [gfx-rs/wgpu#1046]
**Description**

This happens on `wgpu-rs` `master` but not `0.6`.

Here's the full panic:

```rust
thread 'main' panicked at 'no entry found for key', /home/ashley/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/fd99466/wgpu-core/src/device/mod.rs:1995:31
stack backtrace:
   0: rust_begin_unwind
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:475
   1: core::panicking::panic_fmt
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/panicking.rs:85
   2: core::option::expect_failed
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/option.rs:1213
   3: core::option::Option<T>::expect
             at /home/ashley/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/option.rs:333
   4: <std::collections::hash::map::HashMap<K,V,S> as core::ops::index::Index<&Q>>::index
             at /home/ashley/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/collections/hash/map.rs:1050
   5: wgpu_core::device::Device<B>::create_render_pipeline
             at /home/ashley/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/fd99466/wgpu-core/src/device/mod.rs:1995
   6: wgpu_core::device::<impl wgpu_core::hub::Global<G>>::device_create_render_pipeline
             at /home/ashley/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/fd99466/wgpu-core/src/device/mod.rs:3502
   7: <wgpu::backend::direct::Context as wgpu::Context>::device_create_render_pipeline
             at /home/ashley/.cargo/git/checkouts/wgpu-rs-40ea39809c03c5d8/e59ea49/src/backend/direct.rs:940
   8: wgpu::Device::create_render_pipeline
             at /home/ashley/.cargo/git/checkouts/wgpu-rs-40ea39809c03c5d8/e59ea49/src/lib.rs:1473
   9: crash_example::main
             at ./src/main.rs:82
  10: core::ops::function::FnOnce::call_once
             at /home/ashley/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Repro steps**

Here's an example repo: https://github.com/expenses/wgpu-render-pipeline-attachment-panic. It should panic when you run it, but should work fine if you uncomment the two lines in `lines.frag` and recompile the shader.

**Expected vs observed behavior**

My understanding is that it should be legal (in vulkan at least) to not reference a render attachment in a shader at all, however if this is not meant to be allowed here, then a panic with a better explanation would be nice : )

**Platform**
Kernel: 5.9.9-arch1-1
GPU: Intel UHD Graphics 630
Vulkan Instance Version: 1.2.159

**Comment by kvark** [comment]
Thank you for filing! We'll figure out how to address this.
In the meantime, you can have those two lines in the shader but mask off the writes to these outputs via the color masks.
