### ISSUE TITLE
Debug assertion failed 'self.base < ra.end'

### ISSUE THREAD

**Issue by fintelia** [gfx-rs/wgpu#1116]
**Description**
I get a debug assertion failure inside wgpu when running in debug mode, but my application runs fine in release mode.

**Repro steps**

Run...
```
git clone https://github.com/fintelia/terra && cd terra
git checkout b8182fa3abe8a40ab83ccd82dfcfd3196fd86996
RUST_BACKTRACE=1 cargo run
```

To uninstall (not strictly necessary but frees up some disk space)...
```
rm -r ~/.cache/terra
```
**Expected vs observed behavior**

I would expect the program to run properly, as it does in release mode (`cargo run --release`). Instead it fails with:
```
$ RUST_BACKTRACE=1 cargo run
    Finished dev [optimized + debuginfo] target(s) in 0.08s
     Running `target/debug/preview`
thread 'main' panicked at 'assertion failed: self.base < ra.end', /home/jonathan/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/4ebe1f5/wgpu-core/src/track/range.rs:212:25                  
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7f9c43cf98cfe1c369045399929cb098155b8374/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/7f9c43cf98cfe1c369045399929cb098155b8374/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /rustc/7f9c43cf98cfe1c369045399929cb098155b8374/library/core/src/panicking.rs:50:5
   3: <wgpu_core::track::range::Merge<I,T> as core::iter::traits::iterator::Iterator>::next
   4: alloc::vec::Vec<T,A>::extend_desugared
             at /home/jonathan/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/vec.rs:2621:35
   5: <alloc::vec::Vec<T,A> as alloc::vec::SpecExtend<T,I>>::spec_extend
             at /home/jonathan/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/vec.rs:2544:9
   6: <alloc::vec::Vec<T,A> as core::iter::traits::collect::Extend<T>>::extend
             at /home/jonathan/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/vec.rs:2251:9
   7: <wgpu_core::track::texture::TextureState as wgpu_core::track::ResourceState>::merge
             at /home/jonathan/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/4ebe1f5/wgpu-core/src/track/texture.rs:197:13
   8: wgpu_core::track::ResourceTracker<S>::merge_replace
             at /home/jonathan/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/4ebe1f5/wgpu-core/src/track/mod.rs:393:21
   9: wgpu_core::command::CommandBuffer<B>::insert_barriers
             at /home/jonathan/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/4ebe1f5/wgpu-core/src/command/mod.rs:83:32
  10: wgpu_core::device::queue::<impl wgpu_core::hub::Global<G>>::queue_submit
             at /home/jonathan/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/4ebe1f5/wgpu-core/src/device/queue.rs:596:25
  11: <wgpu::backend::direct::Context as wgpu::Context>::queue_submit
             at /home/jonathan/.cargo/git/checkouts/wgpu-rs-40ea39809c03c5d8/3d60546/src/backend/direct.rs:1698:15
  12: wgpu::Queue::submit
             at /home/jonathan/.cargo/git/checkouts/wgpu-rs-40ea39809c03c5d8/3d60546/src/lib.rs:2605:9
  ...
```

**Platform**
Ubuntu 20.10
AMD RX 580
Latest wgpu-rs git version

**Comment by kvark** [comment]
Not able to repro, getting
> dyld: Library not loaded: /tmp/macos-sdk-build/shaderc/src/build/libshaderc/libshaderc_shared.1.dylib
  Referenced from: /Users/dmalyshau/Code/terra/target/debug/preview
  Reason: image not found

Could you perhaps attach a zipped [api trace](https://github.com/gfx-rs/wgpu/wiki/Debugging-wgpu-Applications#tracing-infrastructure)?

**Comment by fintelia** [comment]
I captured a trace here: [trace.zip](https://github.com/fintelia/terra/releases/download/wgpu-issue-1116-bug/trace.zip).

It still may not work on MacOS due to [using doubles in one of the shaders](https://github.com/fintelia/terra/issues/6#issuecomment-663931324).

**Comment by kvark** [comment]
What revision of `wgpu` was this recorded on? I'm getting an assert when replaying:
> thread 'main' panicked at 'InvalidUsages(STORAGE, Bc4RUnorm)', /hub/moz/wgpu/player/src/lib.rs:142:21

Looks like you are trying to create a `Bc4RUnorm` texture with `STORAGE` usage, which is clearly invalid.

**Comment by fintelia** [comment]
It was recorded on 4ebe1f50b057046e4d4f015eb006330d62f5fe91 which is the commit the github version of wgpu-rs is pinned to.
