### ISSUE TITLE
Error: `Global variable Handle(19) '' is invalid: InvalidStorageAccess { allowed: (empty), seen: (empty) }`

### ISSUE THREAD

**Issue by expenses** [gfx-rs/wgpu#1162]
On wgpu-rs branch 7273dba07a4f48558563983981ec62d77280b448 I get the following error trying to verify a spir-v module:
```
wgpu error: Validation Error

Caused by:
    In Device::create_shader_module
      note: label = `../static_model.vert.spv`
    Global variable Handle(19) '' is invalid: InvalidStorageAccess { allowed: (empty), seen: (empty) }


thread 'main' panicked at 'Handling wgpu errors as fatal by default', /home/ashley/.cargo/git/checkouts/wgpu-rs-40ea39809c03c5d8/7273dba/src/backend/direct.rs:1904:5
stack backtrace:
   0: std::panicking::begin_panic
             at /home/ashley/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:521:12
   1: wgpu::backend::direct::default_error_handler
             at /home/ashley/.cargo/git/checkouts/wgpu-rs-40ea39809c03c5d8/7273dba/src/backend/direct.rs:1904:5
   2: core::ops::function::Fn::call
             at /home/ashley/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:70:5
   3: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /home/ashley/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:1321:9
   4: wgpu::backend::direct::ErrorSinkRaw::handle_error
             at /home/ashley/.cargo/git/checkouts/wgpu-rs-40ea39809c03c5d8/7273dba/src/backend/direct.rs:1891:9
   5: wgpu::backend::direct::Context::handle_error
             at /home/ashley/.cargo/git/checkouts/wgpu-rs-40ea39809c03c5d8/7273dba/src/backend/direct.rs:109:9
   6: <wgpu::backend::direct::Context as wgpu::Context>::device_create_shader_module
             at /home/ashley/.cargo/git/checkouts/wgpu-rs-40ea39809c03c5d8/7273dba/src/backend/direct.rs:827:13
   7: wgpu::Device::create_shader_module
             at /home/ashley/.cargo/git/checkouts/wgpu-rs-40ea39809c03c5d8/7273dba/src/lib.rs:1512:17
   8: wgpu_test::main::{{closure}}
             at ./src/main.rs:25:31
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/ashley/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  10: futures_executor::local_pool::block_on::{{closure}}
             at /home/ashley/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.12/src/local_pool.rs:317:23
  11: futures_executor::local_pool::run_executor::{{closure}}
             at /home/ashley/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.12/src/local_pool.rs:87:37
  12: std::thread::local::LocalKey<T>::try_with
             at /home/ashley/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:272:16
  13: std::thread::local::LocalKey<T>::with
             at /home/ashley/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:248:9
  14: futures_executor::local_pool::run_executor
             at /home/ashley/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.12/src/local_pool.rs:83:5
  15: futures_executor::local_pool::block_on
             at /home/ashley/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.12/src/local_pool.rs:317:5
  16: wgpu_test::main
             at ./src/main.rs:2:5
  17: core::ops::function::FnOnce::call_once
             at /home/ashley/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
fish: 'cargo run' terminated by signal SIGSEGV (Address boundary error)
```

The spir-v that I'm to validate is the following:

```
; SPIR-V
; Version: 1.0
; Generator: Google Shaderc over Glslang; 10
; Bound: 123
; Schema: 0
               OpCapability Shader
          %1 = OpExtInstImport "GLSL.std.450"
               OpMemoryModel Logical GLSL450
               OpEntryPoint Vertex %main "main" %transform_1 %transform_2 %transform_3 %transform_4 %normal_transform_1 %normal_transform_2 %normal_transform_3 %pos %out_uv %uv %out_texture_index %texture_index %out_pos %out_normal %normal %out_emission %emission %_
               OpSource GLSL 450
               OpSourceExtension "GL_GOOGLE_cpp_style_line_directive"
               OpSourceExtension "GL_GOOGLE_include_directive"
               OpName %main "main"
               OpName %transform "transform"
               OpName %transform_1 "transform_1"
               OpName %transform_2 "transform_2"
               OpName %transform_3 "transform_3"
               OpName %transform_4 "transform_4"
               OpName %normal_transform "normal_transform"
               OpName %normal_transform_1 "normal_transform_1"
               OpName %normal_transform_2 "normal_transform_2"
               OpName %normal_transform_3 "normal_transform_3"
               OpName %transformed_pos "transformed_pos"
               OpName %pos "pos"
               OpName %out_uv "out_uv"
               OpName %uv "uv"
               OpName %out_texture_index "out_texture_index"
               OpName %texture_index "texture_index"
               OpName %out_pos "out_pos"
               OpName %out_normal "out_normal"
               OpName %normal "normal"
               OpName %out_emission "out_emission"
               OpName %emission "emission"
               OpName %gl_PerVertex "gl_PerVertex"
               OpMemberName %gl_PerVertex 0 "gl_Position"
               OpMemberName %gl_PerVertex 1 "gl_PointSize"
               OpMemberName %gl_PerVertex 2 "gl_ClipDistance"
               OpMemberName %gl_PerVertex 3 "gl_CullDistance"
               OpName %_ ""
               OpName %ProjectionView "ProjectionView"
               OpMemberName %ProjectionView 0 "projection_view"
               OpName %__0 ""
               OpDecorate %transform_1 Location 5
               OpDecorate %transform_2 Location 6
               OpDecorate %transform_3 Location 7
               OpDecorate %transform_4 Location 8
               OpDecorate %normal_transform_1 Location 9
               OpDecorate %normal_transform_2 Location 10
               OpDecorate %normal_transform_3 Location 11
               OpDecorate %pos Location 0
               OpDecorate %out_uv Location 0
               OpDecorate %uv Location 2
               OpDecorate %out_texture_index Flat
               OpDecorate %out_texture_index Location 1
               OpDecorate %texture_index Location 3
               OpDecorate %out_pos Location 2
               OpDecorate %out_normal Location 3
               OpDecorate %normal Location 1
               OpDecorate %out_emission Location 4
               OpDecorate %emission Location 4
               OpMemberDecorate %gl_PerVertex 0 BuiltIn Position
               OpMemberDecorate %gl_PerVertex 1 BuiltIn PointSize
               OpMemberDecorate %gl_PerVertex 2 BuiltIn ClipDistance
               OpMemberDecorate %gl_PerVertex 3 BuiltIn CullDistance
               OpDecorate %gl_PerVertex Block
               OpMemberDecorate %ProjectionView 0 ColMajor
               OpMemberDecorate %ProjectionView 0 Offset 0
               OpMemberDecorate %ProjectionView 0 MatrixStride 16
               OpDecorate %ProjectionView Block
       %void = OpTypeVoid
          %3 = OpTypeFunction %void
      %float = OpTypeFloat 32
    %v4float = OpTypeVector %float 4
%mat4v4float = OpTypeMatrix %v4float 4
%_ptr_Function_mat4v4float = OpTypePointer Function %mat4v4float
%_ptr_Input_v4float = OpTypePointer Input %v4float
%transform_1 = OpVariable %_ptr_Input_v4float Input
%transform_2 = OpVariable %_ptr_Input_v4float Input
%transform_3 = OpVariable %_ptr_Input_v4float Input
%transform_4 = OpVariable %_ptr_Input_v4float Input
    %float_1 = OpConstant %float 1
    %float_0 = OpConstant %float 0
    %v3float = OpTypeVector %float 3
%mat3v3float = OpTypeMatrix %v3float 3
%_ptr_Function_mat3v3float = OpTypePointer Function %mat3v3float
%_ptr_Input_v3float = OpTypePointer Input %v3float
%normal_transform_1 = OpVariable %_ptr_Input_v3float Input
%normal_transform_2 = OpVariable %_ptr_Input_v3float Input
%normal_transform_3 = OpVariable %_ptr_Input_v3float Input
%_ptr_Function_v4float = OpTypePointer Function %v4float
        %pos = OpVariable %_ptr_Input_v3float Input
    %v2float = OpTypeVector %float 2
%_ptr_Output_v2float = OpTypePointer Output %v2float
     %out_uv = OpVariable %_ptr_Output_v2float Output
%_ptr_Input_v2float = OpTypePointer Input %v2float
         %uv = OpVariable %_ptr_Input_v2float Input
       %uint = OpTypeInt 32 0
%_ptr_Output_uint = OpTypePointer Output %uint
%out_texture_index = OpVariable %_ptr_Output_uint Output
%_ptr_Input_uint = OpTypePointer Input %uint
%texture_index = OpVariable %_ptr_Input_uint Input
%_ptr_Output_v3float = OpTypePointer Output %v3float
    %out_pos = OpVariable %_ptr_Output_v3float Output
 %out_normal = OpVariable %_ptr_Output_v3float Output
     %normal = OpVariable %_ptr_Input_v3float Input
%_ptr_Output_float = OpTypePointer Output %float
%out_emission = OpVariable %_ptr_Output_float Output
%_ptr_Input_float = OpTypePointer Input %float
   %emission = OpVariable %_ptr_Input_float Input
     %uint_1 = OpConstant %uint 1
%_arr_float_uint_1 = OpTypeArray %float %uint_1
%gl_PerVertex = OpTypeStruct %v4float %float %_arr_float_uint_1 %_arr_float_uint_1
%_ptr_Output_gl_PerVertex = OpTypePointer Output %gl_PerVertex
          %_ = OpVariable %_ptr_Output_gl_PerVertex Output
        %int = OpTypeInt 32 1
      %int_0 = OpConstant %int 0
%ProjectionView = OpTypeStruct %mat4v4float
%_ptr_PushConstant_ProjectionView = OpTypePointer PushConstant %ProjectionView
        %__0 = OpVariable %_ptr_PushConstant_ProjectionView PushConstant
%_ptr_PushConstant_mat4v4float = OpTypePointer PushConstant %mat4v4float
%_ptr_Output_v4float = OpTypePointer Output %v4float
       %main = OpFunction %void None %3
          %5 = OpLabel
  %transform = OpVariable %_ptr_Function_mat4v4float Function
%normal_transform = OpVariable %_ptr_Function_mat3v3float Function
%transformed_pos = OpVariable %_ptr_Function_v4float Function
         %13 = OpLoad %v4float %transform_1
         %15 = OpLoad %v4float %transform_2
         %17 = OpLoad %v4float %transform_3
         %19 = OpLoad %v4float %transform_4
         %22 = OpCompositeExtract %float %13 0
         %23 = OpCompositeExtract %float %13 1
         %24 = OpCompositeExtract %float %13 2
         %25 = OpCompositeExtract %float %13 3
         %26 = OpCompositeExtract %float %15 0
         %27 = OpCompositeExtract %float %15 1
         %28 = OpCompositeExtract %float %15 2
         %29 = OpCompositeExtract %float %15 3
         %30 = OpCompositeExtract %float %17 0
         %31 = OpCompositeExtract %float %17 1
         %32 = OpCompositeExtract %float %17 2
         %33 = OpCompositeExtract %float %17 3
         %34 = OpCompositeExtract %float %19 0
         %35 = OpCompositeExtract %float %19 1
         %36 = OpCompositeExtract %float %19 2
         %37 = OpCompositeExtract %float %19 3
         %38 = OpCompositeConstruct %v4float %22 %23 %24 %25
         %39 = OpCompositeConstruct %v4float %26 %27 %28 %29
         %40 = OpCompositeConstruct %v4float %30 %31 %32 %33
         %41 = OpCompositeConstruct %v4float %34 %35 %36 %37
         %42 = OpCompositeConstruct %mat4v4float %38 %39 %40 %41
               OpStore %transform %42
         %49 = OpLoad %v3float %normal_transform_1
         %51 = OpLoad %v3float %normal_transform_2
         %53 = OpLoad %v3float %normal_transform_3
         %54 = OpCompositeExtract %float %49 0
         %55 = OpCompositeExtract %float %49 1
         %56 = OpCompositeExtract %float %49 2
         %57 = OpCompositeExtract %float %51 0
         %58 = OpCompositeExtract %float %51 1
         %59 = OpCompositeExtract %float %51 2
         %60 = OpCompositeExtract %float %53 0
         %61 = OpCompositeExtract %float %53 1
         %62 = OpCompositeExtract %float %53 2
         %63 = OpCompositeConstruct %v3float %54 %55 %56
         %64 = OpCompositeConstruct %v3float %57 %58 %59
         %65 = OpCompositeConstruct %v3float %60 %61 %62
         %66 = OpCompositeConstruct %mat3v3float %63 %64 %65
               OpStore %normal_transform %66
         %69 = OpLoad %mat4v4float %transform
         %71 = OpLoad %v3float %pos
         %72 = OpCompositeExtract %float %71 0
         %73 = OpCompositeExtract %float %71 1
         %74 = OpCompositeExtract %float %71 2
         %75 = OpCompositeConstruct %v4float %72 %73 %74 %float_1
         %76 = OpMatrixTimesVector %v4float %69 %75
               OpStore %transformed_pos %76
         %82 = OpLoad %v2float %uv
               OpStore %out_uv %82
         %88 = OpLoad %uint %texture_index
               OpStore %out_texture_index %88
         %91 = OpLoad %v4float %transformed_pos
         %92 = OpCompositeExtract %float %91 0
         %93 = OpCompositeExtract %float %91 1
         %94 = OpCompositeExtract %float %91 2
         %95 = OpCompositeConstruct %v3float %92 %93 %94
               OpStore %out_pos %95
         %97 = OpLoad %mat3v3float %normal_transform
         %99 = OpLoad %v3float %normal
        %100 = OpMatrixTimesVector %v3float %97 %99
               OpStore %out_normal %100
        %105 = OpLoad %float %emission
               OpStore %out_emission %105
        %117 = OpAccessChain %_ptr_PushConstant_mat4v4float %__0 %int_0
        %118 = OpLoad %mat4v4float %117
        %119 = OpLoad %v4float %transformed_pos
        %120 = OpMatrixTimesVector %v4float %118 %119
        %122 = OpAccessChain %_ptr_Output_v4float %_ %int_0
               OpStore %122 %120
               OpReturn
               OpFunctionEnd
```

compiled via `glslc` from this file:
```glsl
#version 450

layout(location = 0) in vec3 pos;
layout(location = 1) in vec3 normal;
layout(location = 2) in vec2 uv;
layout(location = 3) in uint texture_index;
layout(location = 4) in float emission;

layout(location = 5) in vec4 transform_1;
layout(location = 6) in vec4 transform_2;
layout(location = 7) in vec4 transform_3;
layout(location = 8) in vec4 transform_4;

layout(location = 9)  in vec3 normal_transform_1;
layout(location = 10) in vec3 normal_transform_2;
layout(location = 11) in vec3 normal_transform_3;

layout(location = 0) out vec2 out_uv;
layout(location = 1) out flat uint out_texture_index;
layout(location = 2) out vec3 out_pos;
layout(location = 3) out vec3 out_normal;
layout(location = 4) out float out_emission;

layout(push_constant) uniform ProjectionView {
    mat4 projection_view;
};

void main() {
    mat4 transform = mat4(transform_1, transform_2, transform_3, transform_4);
    mat3 normal_transform = mat3(normal_transform_1, normal_transform_2, normal_transform_3);

    vec4 transformed_pos = transform * vec4(pos, 1.0);

    out_uv = uv;
    out_texture_index = texture_index;
    out_pos = vec3(transformed_pos);
    out_normal = normal_transform * normal;
    out_emission = emission;

    gl_Position = projection_view * transformed_pos;
}
```

**Comment by kvark** [comment]
This looks like a push constants issue. Filed https://github.com/gfx-rs/naga/issues/362

**Comment by expenses** [comment]
As far as I'm aware, this should be solved after https://github.com/gfx-rs/wgpu/commit/91f5329b334384656f46e83196ee0c15a371e98c. I haven't been able to test it yet though.
