### ISSUE TITLE
Panic when trying to replay a stack trace on MacOS

### ISSUE THREAD

**Issue by francesco-cattoglio** [gfx-rs/wgpu#1256]
**Description**
Similar issue to https://github.com/gfx-rs/wgpu/issues/1253 but happening on MacOS: I run my program and record an API trace, but when I try to replay it panics. This time however I get the following error:
```
[0.472848 ERROR]()(no module): Missing binding for None
[0.472960 ERROR]()(no module): Error compiling the shader "MSL: Validation"
[0.472994 ERROR]()(wgpu_core::device): failed to create graphics pipeline: Implementation specific error occurred
thread 'main' panicked at 'Device(OutOfMemory)', /Users/francescocattoglio/wgpu/player/src/lib.rs:293:21

stack backtrace:
   0: rust_begin_unwind
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:495:5
   1: std::panicking::begin_panic_fmt
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:437:5
   2: <wgpu_core::hub::Global<player::IdentityPassThroughFactory> as player::GlobalPlay>::process
             at ./src/lib.rs:293:21
   3: play::main::{{closure}}
             at ./src/bin/play.rs:159:29
   4: <alloc::boxed::Box<F,A> as core::ops::function::FnMut<Args>>::call_mut
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/alloc/src/boxed.rs:1314:9
   5: <winit::platform_impl::platform::app_state::EventLoopHandler<T> as winit::platform_impl::platform::app_state::EventHandler>::handle_nonuser_event
             at /Users/francescocattoglio/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/platform_impl/macos/app_state.rs:71:9
   6: winit::platform_impl::platform::app_state::Handler::handle_nonuser_event
             at /Users/francescocattoglio/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/platform_impl/macos/app_state.rs:173:21
   7: winit::platform_impl::platform::app_state::AppState::cleared
             at /Users/francescocattoglio/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/platform_impl/macos/app_state.rs:333:17   8: winit::platform_impl::platform::observer::control_flow_end_handler
             at /Users/francescocattoglio/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/platform_impl/macos/observer.rs:135:13
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <() as objc::message::MessageArguments>::invoke
             at /Users/francescocattoglio/.cargo/registry/src/github.com-1ecc6299db9ec823/objc-0.2.7/src/message/mod.rs:128:17
  20: objc::message::platform::send_unverified
             at /Users/francescocattoglio/.cargo/registry/src/github.com-1ecc6299db9ec823/objc-0.2.7/src/message/apple/mod.rs:27:9
  21: objc::message::send_message
             at /Users/francescocattoglio/.cargo/registry/src/github.com-1ecc6299db9ec823/objc-0.2.7/src/message/mod.rs:178:5
  22: winit::platform_impl::platform::event_loop::EventLoop<T>::run_return
             at /Users/francescocattoglio/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/platform_impl/macos/event_loop.rs:106:25
  23: winit::platform_impl::platform::event_loop::EventLoop<T>::run
             at /Users/francescocattoglio/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/platform_impl/macos/event_loop.rs:93:9
  24: winit::event_loop::EventLoop<T>::run
             at /Users/francescocattoglio/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/event_loop.rs:154:9
  25: play::main
             at ./src/bin/play.rs:128:9
  26: core::ops::function::FnOnce::call_once
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/ops/function.rs:227:5
```

**Repro steps**
See the attached api trace

**Expected vs observed behavior**
I expected the player to not crash

**Extra materials**
[macos_trace.zip](https://github.com/gfx-rs/wgpu/files/6124531/macos_trace.zip)

**Platform**
MacOS 11.0, wgpu backend set to PRIMARY, only tried to replay the trace on the same Mac laptop
The trace was recorded on wgpu-rs revision b3efd07b20de55e7a1ef0abe30dd67e950b15b0b,
replay was attempted on wgpu revision https://github.com/gfx-rs/wgpu/commit/763c14a6d9c5adb8ba7b48801811a3f125c29147

**Comment by kvark** [comment]
Confirmed this is resolved with `cross` feature. Basically, we need to extract the shaders used here and file the relevant issue to Naga, so that it can work with those SPIR-V modules. Still a bug (in Naga), but not an urgent one.
