### ISSUE TITLE
Segfault during graphics pipeline creation on Linux/Intel/Vulkan

### ISSUE THREAD

**Issue by ashpil** [gfx-rs/wgpu#1337]
Not sure what's causing the issue, but I modified my shader fragment shader code and all of a sudden I'm getting a segfault on pipeline creation. This is on the latest git version.

Here's the backtrace:
```gdb
#0  0x00007ffff75dd6b1 in ?? () from /usr/lib64/libvulkan_intel.so
gfx-rs/wgpu-rs#1  0x00007ffff72e3f87 in ?? () from /usr/lib64/libvulkan_intel.so
gfx-rs/wgpu-rs#2  0x00007ffff72e4baa in ?? () from /usr/lib64/libvulkan_intel.so
gfx-rs/wgpu-rs#3  0x00007ffff72e67eb in ?? () from /usr/lib64/libvulkan_intel.so
gfx-rs/wgpu-rs#4  0x00007ffff7363a6b in ?? () from /usr/lib64/libvulkan_intel.so
gfx-rs/wgpu-rs#5  0x00007ffff646bd86 in ?? () from /usr/lib64/libVkLayer_khronos_validation.so
gfx-rs/wgpu-rs#6  0x00007ffff63e68ad in ?? () from /usr/lib64/libVkLayer_khronos_validation.so
gfx-rs/wgpu-rs#7  0x000055555621ca8a in ash::vk::features::DeviceFnV1_0::create_graphics_pipelines (self=0x55555748bb58, device=..., pipeline_cache=..., create_info_count=1, p_create_infos=0x7fffffff2830, p_allocator=0x0,
    p_pipelines=0x7fffffff3308) at /home/andrei/.cargo/registry/src/github.com-1ecc6299db9ec823/ash-0.32.1/src/vk/features.rs:4977
gfx-rs/wgpu-rs#8  0x00005555561e8cd4 in gfx_backend_vulkan::device::{{impl}}::create_graphics_pipeline (self=0x55555748c988, desc=0x7fffffff55a0, cache=...)
    at /home/andrei/.cargo/git/checkouts/gfx-e86e7f3ebdbc4218/99e75ef/src/backend/vulkan/src/device.rs:792
gfx-rs/wgpu-rs#9  0x0000555555c5c0f5 in wgpu_core::device::Device<gfx_backend_vulkan::Backend>::create_render_pipeline<gfx_backend_vulkan::Backend,wgpu_core::hub::IdentityManagerFactory> (self=0x55555748c988, self_id=...,
    desc=0x7fffffff72a0, implicit_context=..., hub=0x555556f11030, token=0x7fffffff68f8) at /home/andrei/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/11666be/wgpu-core/src/device/mod.rs:2405
gfx-rs/wgpu-rs#10 0x0000555555d55a9e in wgpu_core::hub::Global<wgpu_core::hub::IdentityManagerFactory>::device_create_render_pipeline<wgpu_core::hub::IdentityManagerFactory,gfx_backend_vulkan::Backend> (self=0x555556f10f00,
    device_id=..., desc=0x7fffffff72a0, id_in=..., implicit_pipeline_ids=...) at /home/andrei/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/11666be/wgpu-core/src/device/mod.rs:4038
gfx-rs/wgpu-rs#11 0x0000555555c2377b in wgpu::backend::direct::{{impl}}::device_create_render_pipeline (self=0x555556f10f00, device=0x7fffffff7c18, desc=0x7fffffff9148)
    at /home/andrei/.cargo/git/checkouts/wgpu-rs-40ea39809c03c5d8/14f7d7b/src/backend/direct.rs:1024
gfx-rs/wgpu-rs#12 0x0000555555df37f7 in wgpu::Device::create_render_pipeline (self=0x7fffffff7c10, desc=0x7fffffff9148) at /home/andrei/.cargo/git/checkouts/wgpu-rs-40ea39809c03c5d8/14f7d7b/src/lib.rs:1586
gfx-rs/wgpu-rs#13 0x0000555555773b56 in rasterization::context::{{impl}}::new::{{closure}} () at /home/andrei/Documents/Classes/2021S/CS5625/Rasterization/src/context.rs:335
gfx-rs/wgpu-rs#14 0x000055555576d897 in core::future::from_generator::{{impl}}::poll<generator-0> (self=..., cx=0x7fffffffb4c0) at /rustc/52e3dffa50cfffdcfa145c0cc0ba48b49abc0c07/library/core/src/future/mod.rs:80
gfx-rs/wgpu-rs#15 0x000055555573b7a0 in futures_executor::local_pool::block_on::{{closure}}<core::future::from_generator::GenFuture<generator-0>> (cx=0x7fffffffb4c0)
    at /home/andrei/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.13/src/local_pool.rs:317
gfx-rs/wgpu-rs#16 0x000055555573b5b9 in futures_executor::local_pool::run_executor::{{closure}}<core::result::Result<rasterization::context::Context, anyhow::Error>,closure-0> (thread_notify=0x7ffff7c6f778)
    at /home/andrei/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.13/src/local_pool.rs:87
gfx-rs/wgpu-rs#17 0x000055555577b002 in std::thread::local::LocalKey<alloc::sync::Arc<futures_executor::local_pool::ThreadNotify>>::try_with<alloc::sync::Arc<futures_executor::local_pool::ThreadNotify>,closure-0,core::result::Result<rasterization::context::Context, anyhow::Error>> (self=0x555556de7fe0, f=...) at /rustc/52e3dffa50cfffdcfa145c0cc0ba48b49abc0c07/library/std/src/thread/local.rs:272
gfx-rs/wgpu-rs#18 0x000055555577abba in std::thread::local::LocalKey<alloc::sync::Arc<futures_executor::local_pool::ThreadNotify>>::with<alloc::sync::Arc<futures_executor::local_pool::ThreadNotify>,closure-0,core::result::Result<rasterization::context::Context, anyhow::Error>> (self=0x555556de7fe0, f=...) at /rustc/52e3dffa50cfffdcfa145c0cc0ba48b49abc0c07/library/std/src/thread/local.rs:248
gfx-rs/wgpu-rs#19 0x000055555573b4cd in futures_executor::local_pool::run_executor<core::result::Result<rasterization::context::Context, anyhow::Error>,closure-0> (f=...)
    at /home/andrei/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.13/src/local_pool.rs:83
gfx-rs/wgpu-rs#20 0x000055555573b704 in futures_executor::local_pool::block_on<core::future::from_generator::GenFuture<generator-0>> (f=...)
    at /home/andrei/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.13/src/local_pool.rs:317
gfx-rs/wgpu-rs#21 0x000055555578cafe in rasterization::main () at src/main.rs:21
```

[Trace here.](https://github.com/gfx-rs/wgpu-rs/files/6332031/trace.zip)

**Comment by kvark** [comment]
Vulkan Validation helps to see what's up:
>    VALIDATION [UNASSIGNED-CoreValidation-Shader-InconsistentSpirv (0x6bbb14)] : Validation Error: [ UNASSIGNED-CoreValidation-Shader-InconsistentSpirv ] Object 0: handle = 0x5607ac66a7f8, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x6bbb14 | SPIR-V module not valid: OpConstantComposite Constituent <id> count does not match Result Type <id> '45[%mat3v3float]'s matrix column count.
      %XYZ2RGB = OpConstantComposite %mat3v3float %float_3_2404542 %float_n0_969265997 %float_0_0556433983 %float_n1_53713846 %float_1_87601078 %float_n0_204025894 %float_n0_498531401 %float_0_0415560007 %float_1_05722523

Filed https://github.com/gfx-rs/naga/issues/726 upstream to track this

**Comment by cwfitzgerald** [comment]
Closing as solved.
