### ISSUE TITLE
Segfault under Vulkan when dropping `wgpu::Instance` during a panic

### ISSUE THREAD

**Issue by Aaron1011** [gfx-rs/wgpu#1398]
**Description**

After calling (and awaiting) `instance.request_adapter`, triggering a `panic!` will cause a segfault when the `wgpu::Instance` is dropped. Dropping the `wgpu::Instace` normally (via `drop`, or automatically at the end of the scope) does not trigger a segfault.

**Repro steps**

Clone the repository https://github.com/Aaron1011/wgpu-panic, and run `cargo run`

**Expected vs observed behavior**

The `wgpu::Instance` should be dropped cleanly during a panic, without causing a segfault.

**Extra materials**

I obtained the following backtrace:

```
#0  0x00007f16e61b8790 in ?? ()
gfx-rs/wgpu-rs#1  0x000056233078e8b0 in ash::vk::extensions::ExtDebugUtilsFn::destroy_debug_utils_messenger_ext (self=0x562330ec08b8, instance=..., messenger=..., p_allocator=0x0) at /home/aaron/.cargo/registry/src/github.com-1ecc6299db9ec823/ash-0.32.1/src/vk/extensions.rs:10608
gfx-rs/wgpu-rs#2  0x0000562330795f44 in ash::extensions::ext::debug_utils::DebugUtils::destroy_debug_utils_messenger (self=0x562330ec08b0, messenger=..., allocator=...) at /home/aaron/.cargo/registry/src/github.com-1ecc6299db9ec823/ash-0.32.1/src/extensions/ext/debug_utils.rs:125
gfx-rs/wgpu-rs#3  0x000056233077a1e9 in gfx_backend_vulkan::{{impl}}::drop (self=0x562330ec07e0) at /home/aaron/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx-backend-vulkan-0.8.0/src/lib.rs:90
gfx-rs/wgpu-rs#4  0x000056233076670b in core::ptr::drop_in_place<gfx_backend_vulkan::RawInstance> () at /rustc/6d395a1c2946c79966490f5b1e6e619d3a713e6b/library/core/src/ptr/mod.rs:192
gfx-rs/wgpu-rs#5  0x0000562330762874 in alloc::sync::Arc<gfx_backend_vulkan::RawInstance>::drop_slow<gfx_backend_vulkan::RawInstance> (self=0x562330fe78b8) at /rustc/6d395a1c2946c79966490f5b1e6e619d3a713e6b/library/alloc/src/sync.rs:1051
gfx-rs/wgpu-rs#6  0x0000562330762e6c in alloc::sync::{{impl}}::drop<gfx_backend_vulkan::RawInstance> (self=0x562330fe78b8) at /rustc/6d395a1c2946c79966490f5b1e6e619d3a713e6b/library/alloc/src/sync.rs:1593
gfx-rs/wgpu-rs#7  0x0000562330766ddb in core::ptr::drop_in_place<alloc::sync::Arc<gfx_backend_vulkan::RawInstance>> () at /rustc/6d395a1c2946c79966490f5b1e6e619d3a713e6b/library/core/src/ptr/mod.rs:192
gfx-rs/wgpu-rs#8  0x0000562330766c77 in core::ptr::drop_in_place<gfx_backend_vulkan::physical_device::PhysicalDevice> () at /rustc/6d395a1c2946c79966490f5b1e6e619d3a713e6b/library/core/src/ptr/mod.rs:192
gfx-rs/wgpu-rs#9  0x0000562330766fd5 in core::ptr::drop_in_place<gfx_hal::adapter::Adapter<gfx_backend_vulkan::Backend>> () at /rustc/6d395a1c2946c79966490f5b1e6e619d3a713e6b/library/core/src/ptr/mod.rs:192
gfx-rs/wgpu-rs#10 0x0000562330634627 in core::ptr::drop_in_place<wgpu_core::instance::Adapter<gfx_backend_vulkan::Backend>> () at /rustc/6d395a1c2946c79966490f5b1e6e619d3a713e6b/library/core/src/ptr/mod.rs:192
gfx-rs/wgpu-rs#11 0x00005623306272ab in core::ptr::drop_in_place<wgpu_core::hub::Element<wgpu_core::instance::Adapter<gfx_backend_vulkan::Backend>>> () at /rustc/6d395a1c2946c79966490f5b1e6e619d3a713e6b/library/core/src/ptr/mod.rs:192
gfx-rs/wgpu-rs#12 0x00005623306294ef in core::ptr::drop_in_place<[wgpu_core::hub::Element<wgpu_core::instance::Adapter<gfx_backend_vulkan::Backend>>]> () at /rustc/6d395a1c2946c79966490f5b1e6e619d3a713e6b/library/core/src/ptr/mod.rs:192
gfx-rs/wgpu-rs#13 0x0000562330736f25 in alloc::vec::{{impl}}::drop<wgpu_core::hub::Element<wgpu_core::instance::Adapter<gfx_backend_vulkan::Backend>>,alloc::alloc::Global> (self=0x562330a568e0) at /rustc/6d395a1c2946c79966490f5b1e6e619d3a713e6b/library/alloc/src/vec/mod.rs:2715
gfx-rs/wgpu-rs#14 0x000056233062c267 in core::ptr::drop_in_place<alloc::vec::Vec<wgpu_core::hub::Element<wgpu_core::instance::Adapter<gfx_backend_vulkan::Backend>>, alloc::alloc::Global>> () at /rustc/6d395a1c2946c79966490f5b1e6e619d3a713e6b/library/core/src/ptr/mod.rs:192
gfx-rs/wgpu-rs#15 0x000056233062fceb in core::ptr::drop_in_place<wgpu_core::hub::Storage<wgpu_core::instance::Adapter<gfx_backend_vulkan::Backend>, wgpu_core::id::Id<wgpu_core::instance::Adapter<gfx_backend_empty::Backend>>>> () at /rustc/6d395a1c2946c79966490f5b1e6e619d3a713e6b/library/core/src/ptr/mod.rs:192
gfx-rs/wgpu-rs#16 0x000056233063035b in core::ptr::drop_in_place<core::cell::UnsafeCell<wgpu_core::hub::Storage<wgpu_core::instance::Adapter<gfx_backend_vulkan::Backend>, wgpu_core::id::Id<wgpu_core::instance::Adapter<gfx_backend_empty::Backend>>>>> () at /rustc/6d395a1c2946c79966490f5b1e6e619d3a713e6b/library/core/src/ptr/mod.rs:192
gfx-rs/wgpu-rs#17 0x000056233063141f in core::ptr::drop_in_place<lock_api::rwlock::RwLock<parking_lot::raw_rwlock::RawRwLock, wgpu_core::hub::Storage<wgpu_core::instance::Adapter<gfx_backend_vulkan::Backend>, wgpu_core::id::Id<wgpu_core::instance::Adapter<gfx_backend_empty::Backend>>>>> () at /rustc/6d395a1c2946c79966490f5b1e6e619d3a713e6b/library/core/src/ptr/mod.rs:192
gfx-rs/wgpu-rs#18 0x000056233063093a in core::ptr::drop_in_place<wgpu_core::hub::Registry<wgpu_core::instance::Adapter<gfx_backend_vulkan::Backend>, wgpu_core::id::Id<wgpu_core::instance::Adapter<gfx_backend_empty::Backend>>, wgpu_core::hub::IdentityManagerFactory>> () at /rustc/6d395a1c2946c79966490f5b1e6e619d3a713e6b/library/core/src/ptr/mod.rs:192
gfx-rs/wgpu-rs#19 0x00005623306276d7 in core::ptr::drop_in_place<wgpu_core::hub::Hub<gfx_backend_vulkan::Backend, wgpu_core::hub::IdentityManagerFactory>> () at /rustc/6d395a1c2946c79966490f5b1e6e619d3a713e6b/library/core/src/ptr/mod.rs:192
gfx-rs/wgpu-rs#20 0x0000562330635157 in core::ptr::drop_in_place<wgpu_core::hub::Hubs<wgpu_core::hub::IdentityManagerFactory>> () at /rustc/6d395a1c2946c79966490f5b1e6e619d3a713e6b/library/core/src/ptr/mod.rs:192
gfx-rs/wgpu-rs#21 0x0000562330635a81 in core::ptr::drop_in_place<wgpu_core::hub::Global<wgpu_core::hub::IdentityManagerFactory>> () at /rustc/6d395a1c2946c79966490f5b1e6e619d3a713e6b/library/core/src/ptr/mod.rs:192
gfx-rs/wgpu-rs#22 0x0000562330631e32 in core::ptr::drop_in_place<wgpu::backend::direct::Context> () at /rustc/6d395a1c2946c79966490f5b1e6e619d3a713e6b/library/core/src/ptr/mod.rs:192
gfx-rs/wgpu-rs#23 0x00005623306d3ef4 in alloc::sync::Arc<wgpu::backend::direct::Context>::drop_slow<wgpu::backend::direct::Context> (self=0x7ffc308601e8) at /rustc/6d395a1c2946c79966490f5b1e6e619d3a713e6b/library/alloc/src/sync.rs:1051
gfx-rs/wgpu-rs#24 0x00005623306d47bc in alloc::sync::{{impl}}::drop<wgpu::backend::direct::Context> (self=0x7ffc308601e8) at /rustc/6d395a1c2946c79966490f5b1e6e619d3a713e6b/library/alloc/src/sync.rs:1593
gfx-rs/wgpu-rs#25 0x00005623306331db in core::ptr::drop_in_place<alloc::sync::Arc<wgpu::backend::direct::Context>> () at /rustc/6d395a1c2946c79966490f5b1e6e619d3a713e6b/library/core/src/ptr/mod.rs:192
gfx-rs/wgpu-rs#26 0x000056233062232b in core::ptr::drop_in_place<wgpu::Instance> () at /rustc/6d395a1c2946c79966490f5b1e6e619d3a713e6b/library/core/src/ptr/mod.rs:192
gfx-rs/wgpu-rs#27 0x000056233062294b in wgpu_panic::main () at src/main.rs:11
```

**Platform**

OS: `Linux ArchLaptop 5.12.4-arch1-2 gfx-rs/wgpu-rs#1`
`wgpu` crate version: `0.8.1`
Adapater info: `AdapterInfo { name: "Intel(R) UHD Graphics 630 (CFL GT2)", vendor: 32902, device: 16027, device_type: IntegratedGpu, backend: Vulkan }`

**Comment by cwfitzgerald** [comment]
Transfering this issue over to wgpu-core. I am hitting this same issue when starting to build out the testing infrastructure. This is because we don't properly drop anything on panic to try to prevent a double panic.

We need to fix the double panics and start dropping things again properly.

**Comment by cwfitzgerald** [comment]
Filed #1400 for the first issue.
