### ISSUE TITLE
Panic on depth texture binding

### ISSUE THREAD

**Issue by creikey** [gfx-rs/wgpu#1406]
**Description**
When the depth texture is bound and used as a depth stencil, panic occurs. (I think the validation layer should catch this?)

```thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: PendingTransition { id: Valid((0, 1, Vulkan)), selector: TextureSelector { levels: 0..1, layers: 0..1 }, usage: SAMPLED..ATTACHMENT_WRITE }', C:\Users\camer\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-core-0.7.1\src\command\render.rs:976:18```

**Repro steps**
https://github.com/creikey/learn-wgpu/commit/4b97eadb9cfcf9d346a807163766c125cd1f8600
This commit causes the bug

**Extra materials**
Stacktrace:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: PendingTransition { id: Valid((0, 1, Vulkan)), selector: TextureSelector { levels: 0..1, layers: 0..1 }, usage: SAMPLED..ATTACHMENT_WRITE }', C:\Users\camer\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-core-0.7.1\src\command\render.rs:976:18
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/88f19c6dab716c6281af7602e30f413e809c5974\/library\std\src\panicking.rs:493
   1: core::panicking::panic_fmt
             at /rustc/88f19c6dab716c6281af7602e30f413e809c5974\/library\core\src\panicking.rs:92
   2: core::option::expect_none_failed
             at /rustc/88f19c6dab716c6281af7602e30f413e809c5974\/library\core\src\option.rs:1329
   3: core::result::Result<tuple<>, wgpu_core::track::PendingTransition<wgpu_core::track::texture::TextureState>>::unwrap<tuple<>,wgpu_core::track::PendingTransition<wgpu_core::track::texture::TextureState>>
             at C:\Users\camer\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\result.rs:1037
   4: wgpu_core::command::render::RenderPassInfo<gfx_backend_vulkan::Backend>::finish<gfx_backend_vulkan::Backend>
             at C:\Users\camer\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-core-0.7.1\src\command\render.rs:968
   5: wgpu_core::hub::Global<wgpu_core::hub::IdentityManagerFactory>::command_encoder_run_render_pass_impl<wgpu_core::hub::IdentityManagerFactory,gfx_backend_vulkan::Backend>
             at C:\Users\camer\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-core-0.7.1\src\command\render.rs:1852
   6: wgpu_core::hub::Global<wgpu_core::hub::IdentityManagerFactory>::command_encoder_run_render_pass<wgpu_core::hub::IdentityManagerFactory,gfx_backend_vulkan::Backend>
             at C:\Users\camer\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-core-0.7.1\src\command\render.rs:1005
   7: wgpu::backend::direct::{{impl}}::command_encoder_end_render_pass
             at C:\Users\camer\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.7.1\src\backend\direct.rs:1736
   8: wgpu::{{impl}}::drop
             at C:\Users\camer\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.7.1\src\lib.rs:2486
   9: core::ptr::drop_in_place<wgpu::RenderPass>
             at C:\Users\camer\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\ptr\mod.rs:187
  10: learn_wgpu::State::render
             at .\src\main.rs:675
  11: learn_wgpu::main::{{closure}}
             at .\src\main.rs:729
  12: winit::platform_impl::platform::event_loop::{{impl}}::run_return::{{closure}}<tuple<>,closure-0>
             at C:\Users\camer\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.24.0\src\platform_impl\windows\event_loop.rs:203
  13: alloc::boxed::{{impl}}::call_mut<tuple<winit::event::Event<tuple<>>, mut winit::event_loop::ControlFlow*>,FnMut<tuple<winit::event::Event<tuple<>>, mut winit::event_loop::ControlFlow*>>,alloc::alloc::Global>
             at C:\Users\camer\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\alloc\src\boxed.rs:1553
  14: winit::platform_impl::platform::event_loop::runner::{{impl}}::call_event_handler::{{closure}}<tuple<>>
             at C:\Users\camer\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.24.0\src\platform_impl\windows\event_loop\runner.rs:245
  15: std::panic::{{impl}}::call_once<tuple<>,closure-0>
             at C:\Users\camer\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\panic.rs:344
  16: std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure-0>,tuple<>>
             at C:\Users\camer\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\panicking.rs:379
  17: winit::platform_impl::platform::event_loop::{{impl}}::deref
  18: std::panicking::try<tuple<>,std::panic::AssertUnwindSafe<closure-0>>
             at C:\Users\camer\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\panicking.rs:343
  19: std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure-0>,tuple<>>
             at C:\Users\camer\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\panic.rs:431
  20: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<tuple<>>::catch_unwind<tuple<>,tuple<>,closure-0>
             at C:\Users\camer\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.24.0\src\platform_impl\windows\event_loop\runner.rs:152
  21: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<tuple<>>::call_event_handler<tuple<>>
             at C:\Users\camer\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.24.0\src\platform_impl\windows\event_loop\runner.rs:239
  22: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<tuple<>>::send_event<tuple<>>
             at C:\Users\camer\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.24.0\src\platform_impl\windows\event_loop\runner.rs:210
  23: winit::platform_impl::platform::event_loop::SubclassInput<tuple<>>::send_event<tuple<>>
             at C:\Users\camer\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.24.0\src\platform_impl\windows\event_loop.rs:93
  24: winit::platform_impl::platform::event_loop::public_window_callback::{{closure}}<tuple<>>
             at C:\Users\camer\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.24.0\src\platform_impl\windows\event_loop.rs:835
  25: core::ops::function::FnOnce::call_once<closure-0,tuple<>>
             at C:\Users\camer\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\ops\function.rs:227
  26: std::panic::{{impl}}::call_once<isize,closure-0>
             at C:\Users\camer\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\panic.rs:344
  27: std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure-0>,isize>
             at C:\Users\camer\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\panicking.rs:379
  28: std::panicking::try::do_catch<std::panic::AssertUnwindSafe<closure-0>,isize>
  29: std::panicking::try<isize,std::panic::AssertUnwindSafe<closure-0>>
             at C:\Users\camer\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\panicking.rs:343
  30: std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure-0>,isize>
             at C:\Users\camer\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\panic.rs:431
  31: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<tuple<>>::catch_unwind<tuple<>,isize,closure-0>
             at C:\Users\camer\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.24.0\src\platform_impl\windows\event_loop\runner.rs:152
  32: winit::platform_impl::platform::event_loop::public_window_callback<tuple<>>
             at C:\Users\camer\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.24.0\src\platform_impl\windows\event_loop.rs:1912
  33: DefSubclassProc
  34: DefSubclassProc
  35: CallWindowProcW
  36: CallWindowProcW
  37: glPushClientAttrib
  38: CallWindowProcW
  39: DispatchMessageW
  40: SendMessageTimeoutW
  41: KiUserCallbackDispatcher
  42: NtUserDispatchMessage
  43: DispatchMessageW
  44: winit::platform_impl::platform::event_loop::EventLoop<tuple<>>::run_return<tuple<>,closure-0>
             at C:\Users\camer\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.24.0\src\platform_impl\windows\event_loop.rs:218
  45: winit::platform_impl::platform::event_loop::EventLoop<tuple<>>::run<tuple<>,closure-0>
             at C:\Users\camer\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.24.0\src\platform_impl\windows\event_loop.rs:188
  46: winit::event_loop::EventLoop<tuple<>>::run<tuple<>,closure-0>
             at C:\Users\camer\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.24.0\src\event_loop.rs:154
  47: learn_wgpu::main
             at .\src\main.rs:703
  48: core::ops::function::FnOnce::call_once<fn(),tuple<>>
             at C:\Users\camer\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\ops\function.rs:227
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: process didn't exit successfully: `target\debug\learn-wgpu.exe` (exit code: 0xc000041d)
```

**Platform**
Windows and winit

**Comment by kvark** [comment]
This is in wgpu-0.7, which we probably will not be patching any more.

**Comment by creikey** [comment]
I upgraded to 0.8 and the validation now correctly complains

```wgpu error: Validation Error

Caused by:
    In Device::create_bind_group
      note: label = `depth_bind_group`
    texture binding 0 expects dimension = D2Array, but given a view with dimension = D2
```
