### ISSUE TITLE
[Meta] OpenGL backend on Android

### ISSUE THREAD

**Issue by Gordon-F** [gfx-rs/wgpu#1447]
Meta issue for tracking current status of OpenGL backend on Android. All examples were tested on a real device.

**Device Info**:
`GPU`: Mali-T830
`Android`: 8.0 (API 26)
`OpenGL ES`: 3.2

```log
gfx_backend_gl:
Supported Features: INDEPENDENT_BLENDING | INSTANCE_RATE | MUTABLE_COMPARISON_SAMPLER | NDC_Y_UP
Legacy Features: DRAW_INSTANCED | DRAW_INDEXED_INSTANCED | VERTEX_BASE | CONSTANT_BUFFER | COPY_BUFFER | SAMPLER_OBJECTS | EXPLICIT_LAYOUTS_IN_SHADER | INSTANCED_ATTRIBUTE_BINDING
Private capabilities: PrivateCaps {
        vertex_array: true,
        framebuffer: true,
        framebuffer_texture: false,
        index_buffer_role_change: true,
        buffer_storage: false,
        image_storage: false,
        clear_buffer: true,
        program_interface: false,
        frag_data_location: false,
        sync: true,
        emulate_map: true,
        depth_range_f64_precision: false,
        draw_buffers: true,
        per_slot_color_mask: false,
        get_tex_image: false,
}
```

| Example | GL | Vulkan |
|:-:|:-:|:-:|
| boids | ✔️  | ✔️  |
| capture | ❌ | ✔️ |
| cube |![cube_gl](https://user-images.githubusercontent.com/3227317/105423422-86984100-5c56-11eb-897b-89113c4feb63.png)|![cube_vulkan](https://user-images.githubusercontent.com/3227317/105423425-87c96e00-5c56-11eb-9a5c-9d6c766138d4.png)|
| hello-compute | ❌  | ✔️ |
| hello-triangle | ✔️ | ✔️ |
| ~~hello-windows~~ |  |  |
| hello | ✔️ | ✔️ |
| mipmap | ![mipmap_gl](https://user-images.githubusercontent.com/3227317/105465726-5bd4d980-5ca4-11eb-8de7-926481d5fd21.png)  | ![mipmap_vulkan](https://user-images.githubusercontent.com/3227317/105465730-5d060680-5ca4-11eb-84a9-9eea9fe7b6f1.png)  |
| msaa-line | ❌ | ✔️ |
| shadow | ![shadow_gl](https://user-images.githubusercontent.com/3227317/105423290-4df86780-5c56-11eb-940d-fbcf1b948280.png)  | ![shadow_vulkan](https://user-images.githubusercontent.com/3227317/105423293-4f299480-5c56-11eb-8a09-5592027d3d3b.png) |
| skybox | ❌ | ✔️ |
| texture-arrays | ❌ | ✔️  |
| water | ❌ | ✔️ |

#### Capture
```log
E/gfx_backend_gl::queue: CopyRenderbufferToBuffer is not implemented
I/RustStdoutStderr: thread '<unnamed>' panicked at 'called glGetBufferSubData but it was not loaded.', /Users/indish/.cargo/registry/src/github.com-1ecc6299db9ec823/glow-0.7.2/src/gl46.rs:4232:5
```

#### Hello-compute:
```log
I/RustStdoutStderr: thread '<unnamed>' panicked at 'called glGetBufferSubData but it was not loaded.', /Users/indish/.cargo/registry/src/github.com-1ecc6299db9ec823/glow-0.7.2/src/gl46.rs:4232:5
```

#### Msaa-line 
```log
E/gfx_backend_gl: [API/Error] ID 95 : Error:glClearBufferfv::currently bound framebuffer is not valid for this operation
I/RustStdoutStderr: thread '<unnamed>' panicked at 'Error InvalidFramebufferOperation executing command: ClearBufferColorF(0, [0.0, 0.0, 0.0, 1.0])', /Users/indish/Dev/RustProjects/gfx/src/backend/gl/src/queue.rs:1112:13
```

#### Skybox
```log
E/gfx_backend_gl: [API/Error] ID 82 : Error:glTexImage3D::<format>, <type> and <internalformat> are not a valid combination
E/gfx_backend_gl: [API/Error] ID 82 : Error:glTexImage3D::<format>, <type> and <internalformat> are not a valid combination
I/RustStdoutStderr: thread '<unnamed>' panicked at 'Error creating image: InvalidOperation for kind D2(128, 128, 6, 1) of Bgra8Srgb', /Users/indish/Dev/RustProjects/gfx/src/backend/gl/src/device.rs:1549:13
```

#### Texture-arrays
```log
I/RustStdoutStderr: thread '<unnamed>' panicked at 'Adapter does not support required features for this example: SAMPLED_TEXTURE_BINDING_ARRAY', examples/texture-arrays/../framework.rs:160:5
```

#### Water:
```log
E/gfx_backend_gl: [API/Error] ID 82 : Error:glTexImage2D::<format>, <type> and <internalformat> are not a valid combination
I/RustStdoutStderr: thread '<unnamed>' panicked at 'Error creating image: InvalidOperation for kind D2(2160, 1080, 1, 1) of Bgra8Srgb', /Users/indish/Dev/RustProjects/gfx/src/backend/gl/src/device.rs:1549:13
```

**Comment by Gordon-F** [comment]
Since `wgpu` is powered by`wgpu-hal` and `naga` is more stable, we can close this issue. Android supports much better now.
