### ISSUE TITLE
Panic when dropping a BufferMapping after dropping the mapped Buffer 

### ISSUE THREAD

**Issue by Healthire** [gfx-rs/wgpu#1455]
If you get a BufferWriteMapping through Buffer::map_write, drop the Buffer, then drop the BufferWriteMapping some time later, you get a panic at 'key not present'.

```
thread 'main' panicked at 'key not present', C:\Users\william\.cargo\registry\src\github.com-1ecc6299db9ec823\vec_map-0.8.2\src\lib.rs:834:9
stack backtrace:
   0: backtrace::backtrace::trace_unsynchronized
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.44\src\backtrace\mod.rs:66
   1: std::sys_common::backtrace::_print_fmt
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libstd\sys_common\backtrace.rs:78
   2: std::sys_common::backtrace::_print::{{impl}}::fmt
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libstd\sys_common\backtrace.rs:59
   3: core::fmt::write
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libcore\fmt\mod.rs:1063
   4: std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libstd\io\mod.rs:1426
   5: std::sys_common::backtrace::_print
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libstd\sys_common\backtrace.rs:62
   6: std::sys_common::backtrace::print
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libstd\sys_common\backtrace.rs:49
   7: std::panicking::default_hook::{{closure}}
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libstd\panicking.rs:204
   8: std::panicking::default_hook
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libstd\panicking.rs:224
   9: std::panicking::rust_panic_with_hook
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libstd\panicking.rs:470
  10: std::panicking::begin_panic_handler
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libstd\panicking.rs:378
  11: core::panicking::panic_fmt
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libcore\panicking.rs:85
  12: core::option::expect_failed
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\/src\libcore\option.rs:1203
  13: core::option::Option<mut (wgpu_core::resource::Buffer<gfx_backend_vulkan::Backend>, u32)*>::expect<mut (wgpu_core::resource::Buffer<gfx_backend_vulkan::Backend>, u32)*>
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\src\libcore\option.rs:347
  14: vec_map::{{impl}}::index_mut<(wgpu_core::resource::Buffer<gfx_backend_vulkan::Backend>, u32)>
             at C:\Users\william\.cargo\registry\src\github.com-1ecc6299db9ec823\vec_map-0.8.2\src\lib.rs:834
  15: wgpu_core::hub::{{impl}}::index_mut<wgpu_core::resource::Buffer<gfx_backend_vulkan::Backend>,wgpu_core::id::Id<wgpu_core::resource::Buffer<gfx_backend_empty::Backend>>>
             at C:\Users\william\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-core-0.5.5\src\hub.rs:92
  16: wgpu_core::hub::Global<wgpu_core::hub::IdentityManagerFactory>::buffer_unmap<wgpu_core::hub::IdentityManagerFactory,gfx_backend_vulkan::Backend>
             at C:\Users\william\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-core-0.5.5\src\device\mod.rs:2206
  17: wgpu_native::device::wgpu_buffer_unmap
             at C:\Users\william\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-native-0.5.0\src\device.rs:397
  18: wgpu::{{impl}}::drop
             at C:\Users\william\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.5.0\src\lib.rs:1066
  19: core::ptr::drop_in_place<wgpu::BufferWriteMapping>
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\src\libcore\ptr\mod.rs:177
  20: core::mem::drop<wgpu::BufferWriteMapping>
             at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd\src\libcore\mem\mod.rs:749
  21: wgpu_panic::main::{{closure}}::{{closure}}
             at .\src\main.rs:43
```

Code to reproduce the issue (uses tokio with `rt-core` and `time` features enabled):

```
use std::time::Duration;
use tokio::runtime::Runtime;

fn main() {
    let mut runtime = Runtime::new().unwrap();
    runtime.block_on(async {
        let adapter = wgpu::Adapter::request(
            &wgpu::RequestAdapterOptions {
                power_preference: wgpu::PowerPreference::Default,
                compatible_surface: None,
            },
            wgpu::BackendBit::PRIMARY,
        )
        .await
        .unwrap();

        let (device, _) = adapter
            .request_device(&wgpu::DeviceDescriptor {
                extensions: wgpu::Extensions {
                    anisotropic_filtering: false,
                },
                limits: wgpu::Limits::default(),
            })
            .await;

        let buffer = device.create_buffer(&wgpu::BufferDescriptor {
            size: 4,
            usage: wgpu::BufferUsage::MAP_WRITE | wgpu::BufferUsage::COPY_SRC,
            label: None,
        });

        tokio::spawn(async move {
            let mapping = buffer.map_write(0, 4).await.unwrap();

            std::mem::drop(buffer);
            tokio::time::delay_for(Duration::from_millis(10)).await;
            std::mem::drop(mapping);
        });

        loop {
            device.poll(wgpu::Maintain::Wait);
            tokio::time::delay_for(Duration::from_millis(1)).await;
        }
    });
}
```

**Comment by cwfitzgerald** [comment]
Closing as stale, if this is still an issue, please re-file.
