### ISSUE TITLE
Segmentation Fault on Hello Triangles Example

### ISSUE THREAD

**Issue by Id405** [gfx-rs/wgpu#1492]
**Description**
Running the hello triangles example gives:
```
    Finished dev [unoptimized + debuginfo] target(s) in 0.04s
     Running `target/debug/wpguvoxels`
thread 'main' panicked at 'failed to configure swap chain on creation: Window is in use', /home/lily/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-core-0.8.1/src/device/mod.rs:4477:29
stack backtrace:
   0: rust_begin_unwind
             at /rustc/657bc01888e6297257655585f9c475a0801db6d2/library/std/src/panicking.rs:515:5
   1: std::panicking::begin_panic_fmt
             at /rustc/657bc01888e6297257655585f9c475a0801db6d2/library/std/src/panicking.rs:457:5
   2: wgpu_core::device::<impl wgpu_core::hub::Global<G>>::device_create_swap_chain
             at /home/lily/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-core-0.8.1/src/device/mod.rs:4477:29
   3: <wgpu::backend::direct::Context as wgpu::Context>::device_create_swap_chain
             at /home/lily/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.8.1/src/backend/direct.rs:794:27
   4: wgpu::Device::create_swap_chain
             at /home/lily/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.8.1/src/lib.rs:1659:17
   5: wpguvoxels::run::{{closure}}
             at ./src/main.rs:75:26
   6: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/657bc01888e6297257655585f9c475a0801db6d2/library/core/src/future/mod.rs:80:19
   7: pollster::block_on
             at /home/lily/.cargo/registry/src/github.com-1ecc6299db9ec823/pollster-0.2.4/src/lib.rs:132:15
   8: wpguvoxels::main
             at ./src/main.rs:136:9
   9: core::ops::function::FnOnce::call_once
             at /rustc/657bc01888e6297257655585f9c475a0801db6d2/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[1]    567099 segmentation fault (core dumped)  RUST_BACKTRACE=1 cargo run
```

**Platform**
I am running this on Arch Linux x64 with BSPWM and an Nvidia 1070 driver version 465.31 (using nvidia-dkms package).

**Comment by kvark** [comment]
Is it the same on any example?
What about `vkcube`?

**Comment by Id405** [comment]
The cube example runs fine.

Does the hello triangle example crash on window resize?

**Comment by Supermath101** [comment]
I am literally in the same boat. I'm running Manjaro AMD64 with the Mate desktop environment. Git branch `v0.9` and Git commit `087253db`. Linux kernel version: `5.10.42-1-MANJARO`

Here's my GPU details (with driver version `465.31`):
```
01:00.0 VGA compatible controller: NVIDIA Corporation TU116M [GeForce GTX 1660 Ti Mobile] (rev a1) (prog-if 00 [VGA controller])
    DeviceName: NVIDIA GeForce GTX 1660 Ti
    Subsystem: Hewlett-Packard Company Device 8574
    Flags: bus master, fast devsel, latency 0, IRQ 162
    Memory at bb000000 (32-bit, non-prefetchable) [size=16M]
    Memory at 90000000 (64-bit, prefetchable) [size=256M]
    Memory at a0000000 (64-bit, prefetchable) [size=32M]
    I/O ports at 4000 [size=128]
    Expansion ROM at 000c0000 [virtual] [disabled] [size=128K]
    Capabilities: <access denied>
    Kernel driver in use: nvidia
    Kernel modules: nouveau, nvidia_drm, nvidia
```
The `cube` example runs fine, yet the `hello-triangle` example panics with this Rust stack backtrace:
```
thread 'main' panicked at 'failed to configure swap chain on creation: Window is in use', ./wgpu/wgpu-core/src/device/mod.rs:4547:29
stack backtrace:
   0: rust_begin_unwind
             at /rustc/24bdc6d73a75dce9a7013ebc7c037013ff4ea099/library/std/src/panicking.rs:515:5
   1: std::panicking::begin_panic_fmt
             at /rustc/24bdc6d73a75dce9a7013ebc7c037013ff4ea099/library/std/src/panicking.rs:457:5
   2: wgpu_core::device::<impl wgpu_core::hub::Global<G>>::device_create_swap_chain
             at ./wgpu-core/src/device/mod.rs:4547:29
   3: <wgpu::backend::direct::Context as wgpu::Context>::device_create_swap_chain
             at ./wgpu/src/backend/direct.rs:794:27
   4: wgpu::Device::create_swap_chain
             at ./wgpu/src/lib.rs:1672:17
   5: hello_triangle::run::{{closure}}
             at ./wgpu/examples/hello-triangle/main.rs:75:26
   6: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/24bdc6d73a75dce9a7013ebc7c037013ff4ea099/library/core/src/future/mod.rs:80:19
   7: pollster::block_on
             at ~/.cargo/registry/src/github.com-1ecc6299db9ec823/pollster-0.2.4/src/lib.rs:132:15
   8: hello_triangle::main
             at ./wgpu/examples/hello-triangle/main.rs:136:9
   9: core::ops::function::FnOnce::call_once
             at /rustc/24bdc6d73a75dce9a7013ebc7c037013ff4ea099/library/core/src/ops/function.rs:227:5
```

**Comment by kvark** [comment]
In this case, the path forward could be looking at differences between hello-triangle and the framework.

**Comment by dragly** [comment]
I am having the same issue. Explicitly setting up the instance with Vulkan resolves it. Which backend will be chosen by default?

Concretely, changing line 10 in hello-triangle/main.rs from
```rust
    let instance = wgpu::Instance::new(wgpu::BackendBit::all());
```
to
```rust
    let instance = wgpu::Instance::new(wgpu::BackendBit::VULKAN);
```
resolves the issue.

**Comment by kvark** [comment]
Oh interesting. `wgpu` would choose the adapter that matches the request closest. So in this case, sounds like it hello-triangle's preference ended up selecting GL backend, and it failed to initialize properly. The selection itself is not a bug, but GL beckend needs to generally work.

**Comment by PolyMeilex** [comment]
Stumble upon the same thing, the issue is present both in `0.9` and `master`:
`0.9`:  `failed to configure swap chain on creation: Window is in use`
`master`: `surface configuration failed: Native window is in use`

Not allowing a GLES backend (for example by using `PRIMARY`) does fix the problem 

Probably not related to the issue, but it's worth noting that forcing GLES backend by `GL` flag, yields black window (It is also possible to reproduce this by using `wgpu-hal` directly)

**Comment by kvark** [comment]
@PolyMeilex I'm a bit confused. So do you get `Native window is in use` error, or do you get the black screen on GLES?
What GPUs do you have?
We have a weird situation with Intel+Nvidia systems on linux, which fail to present with EGL. I think I'm just going to make GLES backend to say you don't get the presentation on them.

**Comment by PolyMeilex** [comment]
When running with `all()` flags, I get `Native window is in use`
```
[2021-07-13T14:53:18Z INFO  wgpu_hal::gles::egl] Loading Wayland library to get the current display
[2021-07-13T14:53:18Z INFO  wgpu_hal::gles::egl] Loading X11 library to get the current display
[2021-07-13T14:53:18Z INFO  wgpu_hal::gles::egl] Using X11 platform
[2021-07-13T14:53:18Z INFO  wgpu_hal::gles::egl] Enabling EGL debug output
[2021-07-13T14:53:18Z INFO  wgpu_hal::gles::egl] Display vendor "NVIDIA", version (1, 5)
[2021-07-13T14:53:18Z INFO  wgpu_hal::gles::egl] 	Trying native-render
[2021-07-13T14:53:18Z WARN  wgpu_hal::gles::egl] No config found!
[2021-07-13T14:53:18Z INFO  wgpu_hal::gles::egl] 	Trying presentation
[2021-07-13T14:53:18Z INFO  wgpu_hal::gles::egl] 	EGL context: +debug
[2021-07-13T14:53:18Z INFO  wgpu_hal::gles::egl] 	EGL context: +robust access
[2021-07-13T14:53:18Z INFO  wgpu_hal::gles::egl] 	EGL context: +surfaceless
[2021-07-13T14:53:18Z INFO  wgpu_hal::gles::egl] Max label length: 256
[2021-07-13T14:53:18Z INFO  wgpu_hal::gles::egl] Enabling GLES debug output
[2021-07-13T14:53:18Z INFO  wgpu_hal::gles::adapter] Vendor: NVIDIA Corporation
[2021-07-13T14:53:18Z INFO  wgpu_hal::gles::adapter] Renderer: NVIDIA GeForce GTX 970/PCIe/SSE2
[2021-07-13T14:53:18Z INFO  wgpu_hal::gles::adapter] Version: OpenGL ES 3.2 NVIDIA 465.31
[2021-07-13T14:53:18Z INFO  wgpu_hal::gles::adapter] SL version: OpenGL ES GLSL ES 3.20
[2021-07-13T14:53:18Z INFO  wgpu_core::instance] Adapter Vulkan AdapterInfo { name: "NVIDIA GeForce GTX 970", vendor: 4318, device: 5058, device_type: DiscreteGpu, backend: Vulkan }
[2021-07-13T14:53:18Z INFO  wgpu_hal::vulkan::instance] GENERAL [Loader Message (0x0)]
    	Inserted device layer VK_LAYER_KHRONOS_validation (libVkLayer_khronos_validation.so)
[2021-07-13T14:53:18Z INFO  wgpu_hal::vulkan::instance] 	objects: (type: INSTANCE, hndl: 0x556413b67a60, name: ?)
[2021-07-13T14:53:18Z INFO  wgpu_hal::vulkan::adapter] Private capabilities: PrivateCapabilities { flip_y_requires_shift: true, imageless_framebuffers: true, image_view_usage: true, timeline_semaphores: true, texture_d24: true, texture_d24_s8: true, non_coherent_map_mask: 63 }
[2021-07-13T14:53:18Z INFO  wgpu_core::device] creating swap chain SwapChainDescriptor { usage: RENDER_ATTACHMENT, format: Bgra8UnormSrgb, width: 800, height: 600, present_mode: Mailbox }
[2021-07-13T14:53:18Z WARN  wgpu_core::device] Requested size 800x600 is outside of the supported range: Extent3d { width: 945, height: 1023, depth_or_array_layers: 1 }..=Extent3d { width: 945, height: 1023, depth_or_array_layers: 1 }
[2021-07-13T14:53:18Z WARN  wgpu_core::device] Surface does not support present mode: Mailbox, falling back to FIFO
[2021-07-13T14:53:18Z ERROR wgpu_hal::vulkan::instance] VALIDATION [VUID-VkSwapchainCreateInfoKHR-imageExtent-01274 (0x7cd0911d)]
    	Validation Error: [ VUID-VkSwapchainCreateInfoKHR-imageExtent-01274 ] Object 0: handle = 0x5564145de278, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x7cd0911d | vkCreateSwapchainKHR() called with imageExtent = (800,600), which is outside the bounds returned by vkGetPhysicalDeviceSurfaceCapabilitiesKHR(): currentExtent = (945,1023), minImageExtent = (945,1023), maxImageExtent = (945,1023). The Vulkan spec states: imageExtent must be between minImageExtent and maxImageExtent, inclusive, where minImageExtent and maxImageExtent are members of the VkSurfaceCapabilitiesKHR structure returned by vkGetPhysicalDeviceSurfaceCapabilitiesKHR for the surface (https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VUID-VkSwapchainCreateInfoKHR-imageExtent-01274)
[2021-07-13T14:53:18Z ERROR wgpu_hal::vulkan::instance] 	objects: (type: DEVICE, hndl: 0x5564145de278, name: ?)
[2021-07-13T14:53:19Z ERROR wgpu_core::device] surface configuration failed: Native window is in use
thread 'main' panicked at 'Error in Device::create_swap_chain: invalid surface', wgpu/src/backend/direct.rs:118:9
```

When running with `PRIMARY` or `VULKAN` flags, everything works as expected.
When running with `GL` flag, I get a black screen.

My GPU is `GeForce GTX 970` (I also have Intel HD Graphics, but I intentionally disabled it in BIOS, so it should not affect results in any way)

**Comment by kvark** [comment]
Interesting! So it looks like our current approach to surfaces doesn't work for GL:
```rust
```

**Comment by littledivy** [comment]
Experiencing same issue on i3-gaps, Linux kernel `5.8.0-59-generic` and `cargo 1.54.0-nightly` with NVIDIA driver version 465.27

```
thread 'main' panicked at 'failed to configure swap chain on creation: Window is in use', /home/divy/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-core-0.7.0/src/device/mod.rs:4185:26
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Segmentation fault (core dumped)
```
Chaning `BackendBit::all()` to `BackendBit::VULKAN` fixed the issue.

**Comment by kvark** [comment]
Could you check what `raw_window_handle` has for this window?
I think one possible fix is to do `create_platform_window_surface` at `configure()` time instead of `create_surface` time.

**Comment by kvark** [comment]
I made #1656 but didn't test it. It can be totally failing.
Could you give it a shot?

**Comment by codeflo** [comment]
I ran into this exact error on Arch Linux with NVIDIA drivers (I found this thread by searching), and can confirm that restricting the backend to `PRIMARY` as @PolyMeilex suggested fixes the problem.

Is there any more testing I can help with?

**Comment by kvark** [comment]
The PR isn't complete, and I wasn't able to come back to it yet to finish it properly (sorry!). Taking over the PR would help.
