### ISSUE TITLE
Vulkan leaks around 25mb/s on bunnymark example

### ISSUE THREAD

**Issue by kvark** [gfx-rs/wgpu#1501]
**Description**
Vulkan backend is leaking memory. Valgrind doesn't show much.

**Repro steps**
```bash
cargo run --release --example bunnymark
# reach >50k bunnies
# observe the memory growth
```

**Expected vs observed behavior**
No leaks are expected, memory should stabilize

**Extra materials**
- c73ce25f426f18e61c34f2930b27e2ce9137a952 helped this to not crash, but hasn't fixed the leak
- `halmark` doesn't show the leak

**Platform**
Linux/Nv/proprietary

**Comment by mitchmindtree** [comment]
I think we're also running into this after updating from a nannou version that uses wgpu 0.6 or 0.7 to one that uses wgpu 0.9 in one of our recent installations.

Here's an example of one of the `panic!`s that can occur, though it seems it can occur in a few different places where wgpu allocates memory:

```
Running `/home/mindtree/programming/rust/morph/sw/target/release/morph-te`
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

thread 'main' panicked at 'Handling wgpu errors as fatal by default', /home/mindtree/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.9.0/src/backend/direct.rs:1978:5
stack backtrace:
   0:     0x5573f95aa8d0 - std::backtrace_rs::backtrace::libunwind::trace::h63b7a90188ab5fb3
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x5573f95aa8d0 - std::backtrace_rs::backtrace::trace_unsynchronized::h80aefbf9b851eca7
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5573f95aa8d0 - std::sys_common::backtrace::_print_fmt::hbef05ae4237a4d72
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x5573f95aa8d0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h28abce2fdb9884c2
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x5573f95cf26f - core::fmt::write::h3b84512577ca38a8
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/fmt/mod.rs:1092:17
   5:     0x5573f95a2f02 - std::io::Write::write_fmt::h465f8feea02e2aa1
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/io/mod.rs:1572:15
   6:     0x5573f95acdf5 - std::sys_common::backtrace::_print::h525280ee0d29bdde
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x5573f95acdf5 - std::sys_common::backtrace::print::h1f0f5b9f3ef8fb78
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x5573f95acdf5 - std::panicking::default_hook::{{closure}}::ha5838f6faa4a5a8f
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:208:50
   9:     0x5573f95ac8a3 - std::panicking::default_hook::hfb9fe98acb0dcb3b
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:225:9
  10:     0x5573f95ad3fd - std::panicking::rust_panic_with_hook::hb89f5f19036e6af8
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:591:17
  11:     0x5573f917b044 - std::panicking::begin_panic::{{closure}}::ha5ae9b3257c5581d
  12:     0x5573f917afdc - std::sys_common::backtrace::__rust_end_short_backtrace::hb64f2c3ad650bd7a
  13:     0x5573f89a73bc - std::panicking::begin_panic::h92eee0309daf140f
  14:     0x5573f92ddfca - wgpu::backend::direct::default_error_handler::hf7b613c00af3f4f7
  15:     0x5573f92d0f85 - core::ops::function::Fn::call::h9f8348ab9e3fb9cc
  16:     0x5573f92dacd1 - <wgpu::backend::direct::Context as wgpu::Context>::device_create_buffer::h1092181b61d3ce9b
  17:     0x5573f917058a - <wgpu::Device as wgpu::util::device::DeviceExt>::create_buffer_init::hb91419da84349c0c
  18:     0x5573f910d8f9 - conrod_wgpu::Renderer::render::he8165e0e38690caf
  19:     0x5573f8f26831 - nannou::ui::encode_render_pass::h9a685f61fe2eeb93
  20:     0x5573f8f2638c - nannou::ui::Ui::draw_to_frame::h5eb95b5da5072231
  21:     0x5573f8da6177 - morph_te::gui_view::h1f1470c68186ae83
  22:     0x5573f8d814fc - nannou::app::run_loop::{{closure}}::h99188ab502a70c2b
  23:     0x5573f8d80017 - winit::platform_impl::platform::x11::EventLoop<T>::run::h2e18c8e9e6c8c387
  24:     0x5573f8d7f966 - winit::platform_impl::platform::EventLoop<T>::run::h2b71813adcec3f0b
  25:     0x5573f8aca372 - winit::event_loop::EventLoop<T>::run::h4c475af8e91bedc4
  26:     0x5573f8ad09ee - nannou::app::Builder<M,E>::run::h781a7b60c52892c8
  27:     0x5573f8d99057 - morph_te::main::hab353410786781be
  28:     0x5573f8b7c7e3 - std::sys_common::backtrace::__rust_begin_short_backtrace::h8d2441e1aa7f383d
  29:     0x5573f8b7d3a9 - std::rt::lang_start::{{closure}}::h8acc0ab5a04b3108
  30:     0x5573f95ad8fa - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h44574effd2120c86
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/ops/function.rs:259:13
  31:     0x5573f95ad8fa - std::panicking::try::do_call::h10b0bd4879c8dfb0
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:379:40
  32:     0x5573f95ad8fa - std::panicking::try::h60c6780d33419e92
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:343:19
  33:     0x5573f95ad8fa - std::panic::catch_unwind::h111f33e08c52e2ce
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panic.rs:431:14
  34:     0x5573f95ad8fa - std::rt::lang_start_internal::h126f2e09345dbfda
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/rt.rs:51:25
  35:     0x5573f8dac902 - main
```

Confirmed this is occurring on both NixOS stable 20.09 and 21.05.

I'm guessing #1531 is probably related or the same issue.

Here's a pic of the memory usage climbing along with the two windows in the background to get an idea of the content:

![Screenshot from 2021-06-27 14-27-57](https://user-images.githubusercontent.com/4587373/123544558-2735e400-d754-11eb-841b-c1bcc3be9307.png)

**Comment by mitchmindtree** [comment]
After patching the `wgpu` dependency to point to the wgpu-rs `v0.8` branch instead it seems we no longer get any leakage at all, so it must have appeared quite recently.

**Comment by kvark** [comment]
With #1593, the `halmark` example is validation and leak free. It shows that at least at wgpu-hal level there is no problem. The problem is within wgpu-core logic. #1594 helps to confirm we aren't creating more objects than necessary.
Here is Valgrind's "massif" tool output - 
[massif.txt](https://github.com/gfx-rs/wgpu/files/6757916/massif.txt)

Basically, all the allocations that it detected are command buffer allocations. Maybe we aren't recycling them correctly?
