### ISSUE TITLE
Texture Array Examples Shaders Don't Parse

### ISSUE THREAD

**Issue by cwfitzgerald** [gfx-rs/wgpu#1532]
**Description**

Texture array examples have their spirv rejected by naga.

**Repro steps**

Run 0.9's texture array examples, they all fail in some way.

<details>
<summary>Errors</summary>

```
test texture_arrays_constant ... [2021-06-20T05:48:41Z WARN  wgpu_core::instance] The underlying API or device in use does not support enough features to be a fully compliant implementation of WebGPU. A subset of the features can still be used. If you are running this program on native and not in a browser and wish to limit the features you use to the supported subset, call Adapter::downlevel_properties or Device::downlevel_properties to get a listing of the features the current platform supports.
[2021-06-20T05:48:41Z ERROR wgpu_core::validation] Unexpected varying type: Array { base: [1], size: Constant([5]), stride: 4 }
[2021-06-20T05:48:41Z ERROR wgpu_core::validation] Unexpected varying type: Array { base: [1], size: Constant([5]), stride: 4 }
[2021-06-20T05:48:41Z WARN  wgpu_core::device] Failed to parse shader SPIR-V code for Some("constant.frag.spv"): InvalidGlobalVar(Access { base: [2], index: [12] })        
[2021-06-20T05:48:41Z ERROR wgpu::backend::direct] wgpu error: Validation Error

    Caused by:
        In Device::create_shader_module
          note: label = `constant.frag.spv`
        Failed to parse WGSL


thread 'main' panicked at 'Handling wgpu errors as fatal by default', wgpu\src\backend\direct.rs:1978:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'UNEXPECTED TEST FAILURE', wgpu\examples/texture-arrays\..\..\tests\common\mod.rs:255:13
FAILED
test texture_arrays_non_uniform ... [2021-06-20T05:48:41Z WARN  wgpu_core::instance] The underlying API or device in use does not support enough features to be a fully compliant implementation of WebGPU. A subset of the features can still be used. If you are running this program on native and not in a browser and wish to limit the features you use to the supported subset, call Adapter::downlevel_properties or Device::downlevel_properties to get a listing of the features the current platform supports.
[2021-06-20T05:48:41Z ERROR wgpu_core::validation] Unexpected varying type: Array { base: [1], size: Constant([5]), stride: 4 }
[2021-06-20T05:48:41Z ERROR wgpu_core::validation] Unexpected varying type: Array { base: [1], size: Constant([5]), stride: 4 }
[2021-06-20T05:48:41Z WARN  wgpu_core::device] Failed to parse shader SPIR-V code for Some("non-uniform.frag.spv"): UnsupportedCapability(ShaderNonUniform)
[2021-06-20T05:48:41Z ERROR wgpu::backend::direct] wgpu error: Validation Error

    Caused by:
        In Device::create_shader_module
          note: label = `non-uniform.frag.spv`
        Failed to parse WGSL


thread 'main' panicked at 'Handling wgpu errors as fatal by default', wgpu\src\backend\direct.rs:1978:5
thread 'main' panicked at 'UNEXPECTED TEST FAILURE', wgpu\examples/texture-arrays\..\..\tests\common\mod.rs:255:13
FAILED
test texture_arrays_uniform ... [2021-06-20T05:48:42Z WARN  wgpu_core::instance] The underlying API or device in use does not support enough features to be a fully compliant implementation of WebGPU. A subset of the features can still be used. If you are running this program on native and not in a browser and wish to limit the features you use to the supported subset, call Adapter::downlevel_properties or Device::downlevel_properties to get a listing of the features the current platform supports.
[2021-06-20T05:48:42Z ERROR wgpu_core::validation] Unexpected varying type: Array { base: [1], size: Constant([5]), stride: 4 }
[2021-06-20T05:48:42Z ERROR wgpu_core::validation] Unexpected varying type: Array { base: [1], size: Constant([5]), stride: 4 }
[2021-06-20T05:48:42Z WARN  wgpu_core::device] Failed to parse shader SPIR-V code for Some("uniform.frag.spv"): InvalidGlobalVar(Access { base: [3], index: [15] })
[2021-06-20T05:48:42Z ERROR wgpu::backend::direct] wgpu error: Validation Error

    Caused by:
        In Device::create_shader_module
          note: label = `uniform.frag.spv`
        Failed to parse WGSL


thread 'main' panicked at 'Handling wgpu errors as fatal by default', wgpu\src\backend\direct.rs:1978:5
thread 'main' panicked at 'UNEXPECTED TEST FAILURE', wgpu\examples/texture-arrays\..\..\tests\common\mod.rs:255:13
FAILED
test texture_arrays_unsized_non_uniform ... [2021-06-20T05:48:42Z WARN  wgpu_core::instance] The underlying API or device in use does not support enough features to be a fully compliant implementation of WebGPU. A subset of the features can still be used. If you are running this program on native and not in a browser and wish to limit the features you use to the supported subset, call Adapter::downlevel_properties or Device::downlevel_properties to get a listing of the features the current platform supports.   
[2021-06-20T05:48:42Z ERROR wgpu_core::validation] Unexpected varying type: Array { base: [1], size: Constant([5]), stride: 4 }
[2021-06-20T05:48:42Z ERROR wgpu_core::validation] Unexpected varying type: Array { base: [1], size: Constant([5]), stride: 4 }
[2021-06-20T05:48:42Z WARN  wgpu_core::device] Failed to parse shader SPIR-V code for Some("unsized-non-uniform.frag.spv"): UnsupportedCapability(ShaderNonUniform)
[2021-06-20T05:48:42Z ERROR wgpu::backend::direct] wgpu error: Validation Error

    Caused by:
        In Device::create_shader_module
          note: label = `unsized-non-uniform.frag.spv`
        Failed to parse WGSL


thread 'main' panicked at 'Handling wgpu errors as fatal by default', wgpu\src\backend\direct.rs:1978:5
thread 'main' panicked at 'UNEXPECTED TEST FAILURE', wgpu\examples/texture-arrays\..\..\tests\common\mod.rs:255:13
FAILED
```

</details>

This is tracked in naga [here](https://github.com/gfx-rs/naga/issues/265), but I wanted to file this here so I can point the failing tests here.

**Comment by cwfitzgerald** [comment]
Fixed a while ago
