### ISSUE TITLE
Another deadlock

### ISSUE THREAD

**Issue by rukai** [gfx-rs/wgpu#161]
OS: Arch Linux
GPU: GTX 960
Driver: Nvidia proprietary driver, version 418

The repro is more complicated this time.

https://github.com/rukai/wgpu/blob/9afd4f54cccd632a6af17b484249846344683ea1/examples/repro/main.rs

**Comment by kvark** [comment]
@rukai is unstoppable! Thank you for the test case :)

**Comment by rukai** [comment]
While the issue I reported was fixed, there is still another issue shown with this test case.
Before it reaches the point of the initialization failures, it reaches these panics.
It doesnt always hit them, but I found it more likely to when running in debug instead of release.
```
thread '<unnamed>' panicked at 'assertion failed: old.is_none()', wgpu-native/src/hub.rs:154:9
thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
  left: `11`,
 right: `10`', wgpu-native/src/hub.rs:168:9
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:70
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:58
             at src/libstd/panicking.rs:200
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:215
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:478
   5: std::panicking::begin_panic
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/panicking.rs:412
   6: <wgpu_native::hub::Registry<T, I>>::register
             at wgpu-native/src/hub.rs:154
   7: <wgpu_native::hub::Registry<T, I>>::register_local
             at wgpu-native/src/hub.rs:160
   8: wgpu_device_create_buffer
             at wgpu-native/src/device.rs:642
   9: wgpu::Device::create_buffer
             at wgpu-rs/src/lib.rs:486
  10: repro::main::{{closure}}
             at examples/repro/main.rs:33
  11: <rayon::iter::for_each::ForEachConsumer<'f, F> as rayon::iter::plumbing::Folder<T>>::consume_iter::{{closure}}
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.0.3/src/iter/for_each.rs:49
  12: <core::slice::Iter<'a, T> as core::iter::traits::iterator::Iterator>::fold
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libcore/slice/mod.rs:3003
  13: <rayon::iter::for_each::ForEachConsumer<'f, F> as rayon::iter::plumbing::Folder<T>>::consume_iter
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.0.3/src/iter/for_each.rs:49
  14: rayon::iter::plumbing::Producer::fold_with
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.0.3/src/iter/plumbing/mod.rs:108
  15: rayon::iter::plumbing::bridge_producer_consumer::helper
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.0.3/src/iter/plumbing/mod.rs:418
  16: rayon::iter::plumbing::bridge_producer_consumer::helper::{{closure}}
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.0.3/src/iter/plumbing/mod.rs:410
  17: rayon_core::join::join_context::{{closure}}::{{closure}}
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.4.1/src/join/mod.rs:128
  18: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/panic.rs:309
  19: std::panicking::try::do_call
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/panicking.rs:297
  20: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:87
  21: std::panicking::try
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/panicking.rs:276
  22: std::panic::catch_unwind
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/panic.rs:388
  23: rayon_core::unwind::halt_unwinding
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.4.1/src/unwind.rs:18
  24: rayon_core::join::join_context::{{closure}}
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.4.1/src/join/mod.rs:128
  25: rayon_core::registry::in_worker
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.4.1/src/registry.rs:705
  26: rayon_core::join::join_context
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.4.1/src/join/mod.rs:116
  27: rayon::iter::plumbing::bridge_producer_consumer::helper
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.0.3/src/iter/plumbing/mod.rs:409
  28: rayon::iter::plumbing::bridge_producer_consumer::helper::{{closure}}
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.0.3/src/iter/plumbing/mod.rs:410
  29: rayon_core::join::join_context::{{closure}}::{{closure}}
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.4.1/src/join/mod.rs:128
  30: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/panic.rs:309
  31: std::panicking::try::do_call
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/panicking.rs:297
  32: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:87
  33: std::panicking::try
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/panicking.rs:276
  34: std::panic::catch_unwind
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/panic.rs:388
  35: rayon_core::unwind::halt_unwinding
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.4.1/src/unwind.rs:18
  36: rayon_core::join::join_context::{{closure}}
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.4.1/src/join/mod.rs:128
  37: rayon_core::registry::in_worker
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.4.1/src/registry.rs:705
  38: rayon_core::join::join_context
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.4.1/src/join/mod.rs:116
  39: rayon::iter::plumbing::bridge_producer_consumer::helper
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.0.3/src/iter/plumbing/mod.rs:409
  40: rayon::iter::plumbing::bridge_producer_consumer::helper::{{closure}}
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.0.3/src/iter/plumbing/mod.rs:410
  41: rayon_core::join::join_context::{{closure}}::{{closure}}
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.4.1/src/join/mod.rs:128
  42: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/panic.rs:309
  43: std::panicking::try::do_call
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/panicking.rs:297
  44: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:87
  45: std::panicking::try
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/panicking.rs:276
  46: std::panic::catch_unwind
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/panic.rs:388
  47: rayon_core::unwind::halt_unwinding
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.4.1/src/unwind.rs:18
  48: rayon_core::join::join_context::{{closure}}
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.4.1/src/join/mod.rs:128
  49: rayon_core::registry::in_worker
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.4.1/src/registry.rs:705
  50: rayon_core::join::join_context
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.4.1/src/join/mod.rs:116
  51: rayon::iter::plumbing::bridge_producer_consumer::helper
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.0.3/src/iter/plumbing/mod.rs:409
  52: rayon::iter::plumbing::bridge_producer_consumer::helper::{{closure}}
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.0.3/src/iter/plumbing/mod.rs:410
  53: rayon_core::join::join_context::{{closure}}::{{closure}}
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.4.1/src/join/mod.rs:128
  54: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/panic.rs:309
  55: std::panicking::try::do_call
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/panicking.rs:297
  56: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:87
  57: std::panicking::try
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/panicking.rs:276
  58: std::panic::catch_unwind
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/panic.rs:388
  59: rayon_core::unwind::halt_unwinding
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.4.1/src/unwind.rs:18
  60: rayon_core::join::join_context::{{closure}}
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.4.1/src/join/mod.rs:128
  61: rayon_core::registry::in_worker
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.4.1/src/registry.rs:705
  62: rayon_core::join::join_context
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.4.1/src/join/mod.rs:116
  63: rayon::iter::plumbing::bridge_producer_consumer::helper
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.0.3/src/iter/plumbing/mod.rs:409
  64: rayon::iter::plumbing::bridge_producer_consumer::helper::{{closure}}
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.0.3/src/iter/plumbing/mod.rs:410
  65: rayon_core::join::join_context::{{closure}}::{{closure}}
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.4.1/src/join/mod.rs:128
  66: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/panic.rs:309
  67: std::panicking::try::do_call
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/panicking.rs:297
  68: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:87
  69: std::panicking::try
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/panicking.rs:276
  70: std::panic::catch_unwind
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/panic.rs:388
  71: rayon_core::unwind::halt_unwinding
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.4.1/src/unwind.rs:18
  72: rayon_core::join::join_context::{{closure}}
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.4.1/src/join/mod.rs:128
  73: rayon_core::registry::in_worker
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.4.1/src/registry.rs:705
  74: rayon_core::join::join_context
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.4.1/src/join/mod.rs:116
  75: rayon::iter::plumbing::bridge_producer_consumer::helper
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.0.3/src/iter/plumbing/mod.rs:409
  76: rayon::iter::plumbing::bridge_producer_consumer::helper::{{closure}}
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.0.3/src/iter/plumbing/mod.rs:413
  77: rayon_core::join::join_context::{{closure}}::{{closure}}
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.4.1/src/join/mod.rs:122
  78: <rayon_core::job::StackJob<L, F, R> as rayon_core::job::Job>::execute::{{closure}}
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.4.1/src/job.rs:113
  79: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/panic.rs:309
  80: std::panicking::try::do_call
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/panicking.rs:297
  81: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:87
  82: std::panicking::try
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/panicking.rs:276
  83: std::panic::catch_unwind
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/panic.rs:388
  84: rayon_core::unwind::halt_unwinding
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.4.1/src/unwind.rs:18
  85: <rayon_core::job::StackJob<L, F, R> as rayon_core::job::Job>::execute
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.4.1/src/job.rs:113
  86: rayon_core::job::JobRef::execute
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.4.1/src/job.rs:60
  87: rayon_core::registry::WorkerThread::execute
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.4.1/src/registry.rs:584
  88: rayon_core::registry::WorkerThread::wait_until_cold
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.4.1/src/registry.rs:568
  89: rayon_core::registry::WorkerThread::wait_until
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.4.1/src/registry.rs:544
  90: rayon_core::registry::main_loop
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.4.1/src/registry.rs:666
  91: rayon_core::registry::Registry::new::{{closure}}
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.4.1/src/registry.rs:135
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:70
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:58
             at src/libstd/panicking.rs:200
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:215
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:478
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:385
   6: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:340
   7: <wgpu_native::hub::Registry<T, I>>::unregister
             at wgpu-native/src/hub.rs:168
   8: <wgpu_native::device::PendingResources<gfx_backend_vulkan::Backend>>::triage_referenced
             at wgpu-native/src/device.rs:253
   9: <wgpu_native::device::Device<gfx_backend_vulkan::Backend>>::maintain
             at wgpu-native/src/device.rs:531
  10: wgpu_queue_submit
             at wgpu-native/src/device.rs:1356
  11: wgpu::Queue::submit
             at wgpu-rs/src/lib.rs:936
  12: repro::main::{{closure}}
             at examples/repro/main.rs:36
  13: <rayon::iter::for_each::ForEachConsumer<'f, F> as rayon::iter::plumbing::Folder<T>>::consume_iter::{{closure}}
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.0.3/src/iter/for_each.rs:49
  14: <core::slice::Iter<'a, T> as core::iter::traits::iterator::Iterator>::fold
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libcore/slice/mod.rs:3003
  15: <rayon::iter::for_each::ForEachConsumer<'f, F> as rayon::iter::plumbing::Folder<T>>::consume_iter
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.0.3/src/iter/for_each.rs:49
  16: rayon::iter::plumbing::Producer::fold_with
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.0.3/src/iter/plumbing/mod.rs:108
  17: rayon::iter::plumbing::bridge_producer_consumer::helper
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.0.3/src/iter/plumbing/mod.rs:418
  18: rayon::iter::plumbing::bridge_producer_consumer::helper::{{closure}}
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.0.3/src/iter/plumbing/mod.rs:410
  19: rayon_core::join::join_context::{{closure}}::{{closure}}
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.4.1/src/join/mod.rs:128
  20: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/panic.rs:309
  21: std::panicking::try::do_call
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/panicking.rs:297
  22: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:87
  23: std::panicking::try
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/panicking.rs:276
  24: std::panic::catch_unwind
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/panic.rs:388
  25: rayon_core::unwind::halt_unwinding
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.4.1/src/unwind.rs:18
  26: rayon_core::join::join_context::{{closure}}
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.4.1/src/join/mod.rs:128
  27: rayon_core::registry::in_worker
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.4.1/src/registry.rs:705
  28: rayon_core::join::join_context
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.4.1/src/join/mod.rs:116
  29: rayon::iter::plumbing::bridge_producer_consumer::helper
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.0.3/src/iter/plumbing/mod.rs:409
  30: rayon::iter::plumbing::bridge_producer_consumer::helper::{{closure}}
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.0.3/src/iter/plumbing/mod.rs:410
  31: rayon_core::join::join_context::{{closure}}::{{closure}}
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.4.1/src/join/mod.rs:128
  32: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/panic.rs:309
  33: std::panicking::try::do_call
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/panicking.rs:297
  34: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:87
  35: std::panicking::try
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/panicking.rs:276
  36: std::panic::catch_unwind
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/panic.rs:388
  37: rayon_core::unwind::halt_unwinding
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.4.1/src/unwind.rs:18
  38: rayon_core::join::join_context::{{closure}}
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.4.1/src/join/mod.rs:128
  39: rayon_core::registry::in_worker
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.4.1/src/registry.rs:705
  40: rayon_core::join::join_context
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.4.1/src/join/mod.rs:116
  41: rayon::iter::plumbing::bridge_producer_consumer::helper
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.0.3/src/iter/plumbing/mod.rs:409
  42: rayon::iter::plumbing::bridge_producer_consumer::helper::{{closure}}
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.0.3/src/iter/plumbing/mod.rs:410
  43: rayon_core::join::join_context::{{closure}}::{{closure}}
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.4.1/src/join/mod.rs:128
  44: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/panic.rs:309
  45: std::panicking::try::do_call
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/panicking.rs:297
  46: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:87
  47: std::panicking::try
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/panicking.rs:276
  48: std::panic::catch_unwind
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/panic.rs:388
  49: rayon_core::unwind::halt_unwinding
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.4.1/src/unwind.rs:18
  50: rayon_core::join::join_context::{{closure}}
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.4.1/src/join/mod.rs:128
  51: rayon_core::registry::in_worker
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.4.1/src/registry.rs:705
  52: rayon_core::join::join_context
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.4.1/src/join/mod.rs:116
  53: rayon::iter::plumbing::bridge_producer_consumer::helper
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.0.3/src/iter/plumbing/mod.rs:409
  54: rayon::iter::plumbing::bridge_producer_consumer::helper::{{closure}}
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.0.3/src/iter/plumbing/mod.rs:410
  55: rayon_core::join::join_context::{{closure}}::{{closure}}
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.4.1/src/join/mod.rs:128
  56: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/panic.rs:309
  57: std::panicking::try::do_call
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/panicking.rs:297
  58: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:87
  59: std::panicking::try
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/panicking.rs:276
  60: std::panic::catch_unwind
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/panic.rs:388
  61: rayon_core::unwind::halt_unwinding
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.4.1/src/unwind.rs:18
  62: rayon_core::join::join_context::{{closure}}
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.4.1/src/join/mod.rs:128
  63: rayon_core::registry::in_worker
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.4.1/src/registry.rs:705
  64: rayon_core::join::join_context
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.4.1/src/join/mod.rs:116
  65: rayon::iter::plumbing::bridge_producer_consumer::helper
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.0.3/src/iter/plumbing/mod.rs:409
  66: rayon::iter::plumbing::bridge_producer_consumer::helper::{{closure}}
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.0.3/src/iter/plumbing/mod.rs:410
  67: rayon_core::join::join_context::{{closure}}::{{closure}}
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.4.1/src/join/mod.rs:128
  68: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/panic.rs:309
  69: std::panicking::try::do_call
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/panicking.rs:297
  70: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:87
  71: std::panicking::try
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/panicking.rs:276
  72: std::panic::catch_unwind
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/panic.rs:388
  73: rayon_core::unwind::halt_unwinding
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.4.1/src/unwind.rs:18
  74: rayon_core::join::join_context::{{closure}}
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.4.1/src/join/mod.rs:128
  75: rayon_core::registry::in_worker
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.4.1/src/registry.rs:705
  76: rayon_core::join::join_context
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.4.1/src/join/mod.rs:116
  77: rayon::iter::plumbing::bridge_producer_consumer::helper
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.0.3/src/iter/plumbing/mod.rs:409
  78: rayon::iter::plumbing::bridge_producer_consumer::helper::{{closure}}
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.0.3/src/iter/plumbing/mod.rs:410
  79: rayon_core::join::join_context::{{closure}}::{{closure}}
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.4.1/src/join/mod.rs:128
  80: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/panic.rs:309
  81: std::panicking::try::do_call
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/panicking.rs:297
  82: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:87
  83: std::panicking::try
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/panicking.rs:276
  84: std::panic::catch_unwind
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/panic.rs:388
  85: rayon_core::unwind::halt_unwinding
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.4.1/src/unwind.rs:18
  86: rayon_core::join::join_context::{{closure}}
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.4.1/src/join/mod.rs:128
  87: rayon_core::registry::Registry::in_worker_cold::{{closure}}
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.4.1/src/registry.rs:356
  88: <rayon_core::job::StackJob<L, F, R> as rayon_core::job::Job>::execute::{{closure}}
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.4.1/src/job.rs:113
  89: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/panic.rs:309
  90: std::panicking::try::do_call
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/panicking.rs:297
  91: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:87
  92: std::panicking::try
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/panicking.rs:276
  93: std::panic::catch_unwind
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/panic.rs:388
  94: rayon_core::unwind::halt_unwinding
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.4.1/src/unwind.rs:18
  95: <rayon_core::job::StackJob<L, F, R> as rayon_core::job::Job>::execute
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.4.1/src/job.rs:113
  96: rayon_core::job::JobRef::execute
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.4.1/src/job.rs:60
  97: rayon_core::registry::WorkerThread::execute
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.4.1/src/registry.rs:584
  98: rayon_core::registry::WorkerThread::wait_until_cold
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.4.1/src/registry.rs:568
  99: rayon_core::registry::WorkerThread::wait_until
             at /home/rubic/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.4.1/src/registry.rs:544
```
