### ISSUE TITLE
Veloren Vram leak after upgrading to Wgpu 0.9 

### ISSUE THREAD

**Issue by YuuriMomo** [gfx-rs/wgpu#1613]
**Description**

Veloren uses more Vram everytime the window is resized after upgrading WGPU to 0.9.

**Repro steps**

https://gitlab.com/veloren/veloren/ 

Latest Master on Vulkan Backend.

**Expected vs observed behavior**

Expected: No increase in VRAM

Observed: Increase in VRAM usage everytime veloren is resized.

**Extra materials**

https://user-images.githubusercontent.com/53386725/124806237-c0d37180-df5c-11eb-94b3-ae4591317bf9.mp4

![obraz](https://user-images.githubusercontent.com/53386725/124806494-0c861b00-df5d-11eb-9656-1c0b4f789c35.png)

**Platform**
OS: Windows 10 Home 

GPU: 1050 TI (Mobile)

Nvidia drivers version: 471.11

**Comment by kvark** [comment]
Interesting. This is a big leak. I wonder if `master` also shows it.

**Comment by zesterer** [comment]
This has been independently reported by another user, this time running with a NVIDIA GeForce 930M on Linux Mint 20 with the Vulkan backend, thereby confirming that it is a cross-platform issue.

```
Panic Payload: "wgpu error (handling all wgpu errors as fatal):\nValidationError { source: ContextError { string: \"Texture::create_view\", cause: OutOfMemory, label_key: \"label\", label: \"Point shadow cubemap face\" }, description: \"Validation Error\\n\\nCaused by:\\n    In Texture::create_view\\n      note: label = `Point shadow cubemap face`\\n    not enough memory left\\n\" }\nAdapterInfo { name: \"NVIDIA GeForce 930M\", vendor: 4318, device: 4934, device_type: DiscreteGpu, backend: Vulkan }"
PanicInfo: panicked at 'wgpu error (handling all wgpu errors as fatal):
ValidationError { source: ContextError { string: "Texture::create_view", cause: OutOfMemory, label_key: "label", label: "Point shadow cubemap face" }, description: "Validation Error\n\nCaused by:\n    In Texture::create_view\n      note: label = `Point shadow cubemap face`\n    not enough memory left\n" }
AdapterInfo { name: "NVIDIA GeForce 930M", vendor: 4318, device: 4934, device_type: DiscreteGpu, backend: Vulkan }', voxygen/src/render/renderer.rs:262:13
Game version: e3876170 [2021-07-07]
```

**Comment by YuuriMomo** [comment]
After testing DX12 backend I managed to reproduce the issue here too. 


```
Panic Payload: "assertion failed: `(left == right)`\n  left: `0`,\n right: `-2005270523`"
PanicInfo: panicked at 'assertion failed: `(left == right)`
  left: `0`,
 right: `-2005270523`', C:\Users\YuriMomo\.cargo\registry\src\github.com-1ecc6299db9ec823\gfx-backend-dx12-0.9.1\src\device.rs:2449:9
Game version: e3876170 [2021-07-07]

Backtrace:
   0: backtrace::backtrace::trace
   1: backtrace::capture::Backtrace::new
   2: quinn_proto::cid_queue::CidQueue::active_seq
   3: std::panicking::rust_panic_with_hook
             at /rustc/3e99439f4dacc8ba0d2ca48d221694362d587927\/library\std\src\panicking.rs:629
   4: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/3e99439f4dacc8ba0d2ca48d221694362d587927\/library\std\src\panicking.rs:519
   5: std::sys_common::backtrace::__rust_end_short_backtrace<closure-0,!>
             at /rustc/3e99439f4dacc8ba0d2ca48d221694362d587927\/library\std\src\sys_common\backtrace.rs:141
   6: std::panicking::begin_panic_handler
             at /rustc/3e99439f4dacc8ba0d2ca48d221694362d587927\/library\std\src\panicking.rs:515
   7: core::panicking::panic_fmt
             at /rustc/3e99439f4dacc8ba0d2ca48d221694362d587927\/library\core\src\panicking.rs:92
   8: core::fmt::Arguments::new_v1
             at /rustc/3e99439f4dacc8ba0d2ca48d221694362d587927\/library\core\src\fmt\mod.rs:316
   9: core::panicking::assert_failed_inner
             at /rustc/3e99439f4dacc8ba0d2ca48d221694362d587927\/library\core\src\panicking.rs:160
  10: core::panicking::assert_failed
  11: gfx_backend_dx12::device::<impl gfx_hal::device::Device<gfx_backend_dx12::Backend> for gfx_backend_dx12::Device>::bind_buffer_memory
  12: wgpu_core::device::queue::<impl wgpu_core::device::Device<B>>::prepare_stage
  13: wgpu_core::device::queue::<impl wgpu_core::hub::Global<G>>::queue_write_texture
  14: <wgpu::backend::direct::Context as wgpu::Context>::queue_write_texture
  15: wgpu::Queue::write_texture
  16: veloren_voxygen::render::texture::Texture::update
  17: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  18: crossbeam_utils::thread::scope
  19: rusttype::gpu_cache::Cache::cache_queued
  20: veloren_voxygen::ui::Ui::maintain
  21: veloren_voxygen::ui::Ui::maintain
  22: veloren_voxygen::hud::Hud::maintain
  23: <veloren_voxygen::session::SessionState as veloren_voxygen::PlayState>::tick
  24: veloren_voxygen::run::handle_main_events_cleared
  25: winit::platform_impl::platform::event_loop::EventLoop<T>::run_return::{{closure}}
  26: std::panic::catch_unwind
  27: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<T>::send_event
  28: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<T>::move_state_to
  29: std::panic::catch_unwind
  30: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<T>::catch_unwind
  31: winit::platform_impl::platform::event_loop::thread_event_target_callback
  32: DefSubclassProc
  33: DefSubclassProc
  34: CallWindowProcW
  35: DispatchMessageW
  36: SendMessageTimeoutW
  37: KiUserCallbackDispatcher
  38: NtUserDispatchMessage
  39: DispatchMessageW
  40: winit::platform_impl::platform::event_loop::update_modifiers
  41: winit::platform_impl::platform::event_loop::update_modifiers
  42: tokio::util::linked_list::LinkedList<L,<L as tokio::util::linked_list::Link>::Target>::remove
  43: veloren_voxygen::run::run
  44: quinn_proto::cid_queue::CidQueue::active_seq
  45: alloc::raw_vec::finish_grow
  46: std::rt::lang_start::{{closure}}
  47: core::ops::function::impls::{{impl}}::call_once
             at /rustc/3e99439f4dacc8ba0d2ca48d221694362d587927\library\core\src\ops\function.rs:280
  48: std::panicking::try::do_call
             at /rustc/3e99439f4dacc8ba0d2ca48d221694362d587927\/library\std\src\panicking.rs:401
  49: std::panicking::try
             at /rustc/3e99439f4dacc8ba0d2ca48d221694362d587927\/library\std\src\panicking.rs:365
  50: std::panic::catch_unwind
             at /rustc/3e99439f4dacc8ba0d2ca48d221694362d587927\/library\std\src\panic.rs:433
  51: std::rt::lang_start_internal
             at /rustc/3e99439f4dacc8ba0d2ca48d221694362d587927\/library\std\src\rt.rs:34
  52: main
  53: post_pgo_initializer
  54: <unknown>

thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `0`,
 right: `-2005270523`', C:\Users\YuriMomo\.cargo\registry\src\github.com-1ecc6299db9ec823\gfx-backend-dx12-0.9.1\src\device.rs:2449:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by YuuriMomo** [comment]
More strange things pop up when testing on dx12 while resizing window 

```
Jul 08 01:01:34.078 ERROR gfx_backend_dx12::window: ResizeBuffers failed with 0x887a0005



Jul 08 01:01:34.407 ERROR veloren_voxygen: VOXYGEN HAS PANICKED

A critical error has occurred and Voxygen has been forced to terminate in an unusual manner. Details about the error can be found below.

> What should I do?

We need your help to fix this! You can help by contacting us and reporting this problem. To do this, open an issue on the Veloren issue tracker:

https://www.gitlab.com/veloren/veloren/issues/new

If you're on the Veloren community Discord server, we'd be grateful if you could also post a message in the #support channel.

> What should I include?

The error information below will be useful in finding and fixing the problem. Please include as much information about your setup and the events that led up to the panic as possible.

Voxygen has logged information about the problem (including this message) to the file C:\veloren\userdata\voxygen\logs\voxygen-<date>.log. Please include the contents of this file in your bug report.

> Error information

The information below is intended for developers and testers.

Panic Payload: "failed to configure swap chain on creation: Window is in use"
PanicInfo: panicked at 'failed to configure swap chain on creation: Window is in use', C:\Users\YuriMomo\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-core-0.9.0\src\device\mod.rs:4547:29
Game version: e3876170 [2021-07-07]

Backtrace:
   0: backtrace::backtrace::dbghelp::trace
             at C:\Users\YuriMomo\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.60\src\backtrace\dbghelp.rs:98
   1: backtrace::backtrace::trace_unsynchronized
             at C:\Users\YuriMomo\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.60\src\backtrace\mod.rs:66
   2: backtrace::backtrace::trace<closure-0>
             at C:\Users\YuriMomo\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.60\src\backtrace\mod.rs:53
   3: backtrace::capture::Backtrace::create
             at C:\Users\YuriMomo\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.60\src\capture.rs:176
   4: backtrace::capture::Backtrace::new
             at C:\Users\YuriMomo\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.60\src\capture.rs:140
   5: veloren_voxygen::main::{{closure}}
             at voxygen\src\main.rs:109
   6: std::panicking::rust_panic_with_hook
             at /rustc/3e99439f4dacc8ba0d2ca48d221694362d587927\/library\std\src\panicking.rs:629
   7: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/3e99439f4dacc8ba0d2ca48d221694362d587927\/library\std\src\panicking.rs:519
   8: std::sys_common::backtrace::__rust_end_short_backtrace<closure-0,!>
             at /rustc/3e99439f4dacc8ba0d2ca48d221694362d587927\/library\std\src\sys_common\backtrace.rs:141
   9: std::panicking::begin_panic_handler
             at /rustc/3e99439f4dacc8ba0d2ca48d221694362d587927\/library\std\src\panicking.rs:515
  10: std::panicking::begin_panic_fmt
             at /rustc/3e99439f4dacc8ba0d2ca48d221694362d587927\/library\std\src\panicking.rs:457
  11: wgpu_core::hub::Storage<wgpu_core::swap_chain::SwapChain<gfx_backend_dx12::Backend>, wgpu_core::id::Id<wgpu_core::swap_chain::SwapChain<gfx_backend_empty::Backend>>>::insert_impl
             at C:\Users\YuriMomo\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-core-0.9.0\src\hub.rs:169
  12: wgpu_core::hub::Storage<wgpu_core::swap_chain::SwapChain<gfx_backend_dx12::Backend>, wgpu_core::id::Id<wgpu_core::swap_chain::SwapChain<gfx_backend_empty::Backend>>>::insert
             at C:\Users\YuriMomo\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-core-0.9.0\src\hub.rs:175
  13: wgpu_core::hub::Global<wgpu_core::hub::IdentityManagerFactory>::device_create_swap_chain<wgpu_core::hub::IdentityManagerFactory,gfx_backend_dx12::Backend>
             at C:\Users\YuriMomo\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-core-0.9.0\src\device\mod.rs:4547
  14: wgpu::backend::direct::{{impl}}::device_create_swap_chain
             at C:\Users\YuriMomo\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.9.0\src\backend\direct.rs:794
  15: wgpu::Device::create_swap_chain
             at C:\Users\YuriMomo\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.9.0\src\lib.rs:1672
  16: veloren_voxygen::render::renderer::Renderer::on_resize
             at voxygen\src\render\renderer.rs:546
  17: veloren_voxygen::window::Window::handle_window_event
             at voxygen\src\window.rs:990
  18: veloren_voxygen::run::run::{{closure}}
             at voxygen\src\run.rs:76
  19: winit::platform_impl::platform::event_loop::{{impl}}::run_return::{{closure}}<tuple<>,closure-1>
             at C:\Users\YuriMomo\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.25.0\src\platform_impl\windows\event_loop.rs:206
  20: winit::platform_impl::platform::event_loop::runner::{{impl}}::call_event_handler::{{closure}}
             at C:\Users\YuriMomo\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.25.0\src\platform_impl\windows\event_loop\runner.rs:250
  21: std::panic::{{impl}}::call_once<tuple<>,closure-0>
             at /rustc/3e99439f4dacc8ba0d2ca48d221694362d587927\library\std\src\panic.rs:346
  22: std::panicking::try::do_call
             at /rustc/3e99439f4dacc8ba0d2ca48d221694362d587927\library\std\src\panicking.rs:401
  23: std::panicking::try
             at /rustc/3e99439f4dacc8ba0d2ca48d221694362d587927\library\std\src\panicking.rs:365
  24: std::panic::catch_unwind
             at /rustc/3e99439f4dacc8ba0d2ca48d221694362d587927\library\std\src\panic.rs:433
  25: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<tuple<>>::catch_unwind
             at C:\Users\YuriMomo\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.25.0\src\platform_impl\windows\event_loop\runner.rs:152
  26: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<tuple<>>::call_event_handler<tuple<>>
             at C:\Users\YuriMomo\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.25.0\src\platform_impl\windows\event_loop\runner.rs:239
  27: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<tuple<>>::send_event<tuple<>>
             at C:\Users\YuriMomo\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.25.0\src\platform_impl\windows\event_loop\runner.rs:220
  28: winit::platform_impl::platform::event_loop::public_window_callback_inner::{{closure}}<tuple<>>
             at C:\Users\YuriMomo\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.25.0\src\platform_impl\windows\event_loop.rs:1384
  29: core::ops::function::FnOnce::call_once
             at /rustc/3e99439f4dacc8ba0d2ca48d221694362d587927\library\core\src\ops\function.rs:227
  30: std::panic::{{impl}}::call_once
             at /rustc/3e99439f4dacc8ba0d2ca48d221694362d587927\library\std\src\panic.rs:346
  31: std::panicking::try::do_call
             at /rustc/3e99439f4dacc8ba0d2ca48d221694362d587927\library\std\src\panicking.rs:401
  32: std::panicking::try
             at /rustc/3e99439f4dacc8ba0d2ca48d221694362d587927\library\std\src\panicking.rs:365
  33: std::panic::catch_unwind
             at /rustc/3e99439f4dacc8ba0d2ca48d221694362d587927\library\std\src\panic.rs:433
  34: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<tuple<>>::catch_unwind<tuple<>,isize,closure-0>
             at C:\Users\YuriMomo\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.25.0\src\platform_impl\windows\event_loop\runner.rs:152
  35: winit::platform_impl::platform::event_loop::public_window_callback_inner
             at C:\Users\YuriMomo\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.25.0\src\platform_impl\windows\event_loop.rs:1980
  36: winit::platform_impl::platform::event_loop::public_window_callback<tuple<>>
             at C:\Users\YuriMomo\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.25.0\src\platform_impl\windows\event_loop.rs:791
  37: DefSubclassProc
  38: DefSubclassProc
  39: CallWindowProcW
  40: SendMessageW
  41: GetWindowTextW
  42: IsIconic
  43: IsCompositionActive
  44: IsCompositionActive
  45: GetWindowTextW
  46: CallWindowProcW
  47: CallWindowProcW
  48: DefSubclassProc
  49: DefSubclassProc
  50: core::ops::function::FnOnce::call_once
             at /rustc/3e99439f4dacc8ba0d2ca48d221694362d587927\library\core\src\ops\function.rs:227
  51: std::panic::{{impl}}::call_once
             at /rustc/3e99439f4dacc8ba0d2ca48d221694362d587927\library\std\src\panic.rs:346
  52: std::panicking::try::do_call
             at /rustc/3e99439f4dacc8ba0d2ca48d221694362d587927\library\std\src\panicking.rs:401
  53: std::panicking::try
             at /rustc/3e99439f4dacc8ba0d2ca48d221694362d587927\library\std\src\panicking.rs:365
  54: std::panic::catch_unwind
             at /rustc/3e99439f4dacc8ba0d2ca48d221694362d587927\library\std\src\panic.rs:433
  55: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<tuple<>>::catch_unwind<tuple<>,isize,closure-0>
             at C:\Users\YuriMomo\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.25.0\src\platform_impl\windows\event_loop\runner.rs:152
  56: winit::platform_impl::platform::event_loop::public_window_callback_inner
             at C:\Users\YuriMomo\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.25.0\src\platform_impl\windows\event_loop.rs:1980
  57: winit::platform_impl::platform::event_loop::public_window_callback<tuple<>>
             at C:\Users\YuriMomo\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.25.0\src\platform_impl\windows\event_loop.rs:791
  58: DefSubclassProc
  59: DefSubclassProc
  60: CallWindowProcW
  61: DispatchMessageW
  62: LookupIconIdFromDirectoryEx
  63: KiUserCallbackDispatcher
  64: NtUserMessageCall
  65: GetWindowTextW
  66: IsIconic
  67: GetUserColorPreference
  68: Ordinal96
  69: IsCompositionActive
  70: IsCompositionActive
  71: GetWindowTextW
  72: core::ops::function::FnOnce::call_once
             at /rustc/3e99439f4dacc8ba0d2ca48d221694362d587927\library\core\src\ops\function.rs:227
  73: std::panic::{{impl}}::call_once
             at /rustc/3e99439f4dacc8ba0d2ca48d221694362d587927\library\std\src\panic.rs:346
  74: std::panicking::try::do_call
             at /rustc/3e99439f4dacc8ba0d2ca48d221694362d587927\library\std\src\panicking.rs:401
  75: std::panicking::try
             at /rustc/3e99439f4dacc8ba0d2ca48d221694362d587927\library\std\src\panicking.rs:365
  76: std::panic::catch_unwind
             at /rustc/3e99439f4dacc8ba0d2ca48d221694362d587927\library\std\src\panic.rs:433
  77: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<tuple<>>::catch_unwind<tuple<>,isize,closure-0>
             at C:\Users\YuriMomo\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.25.0\src\platform_impl\windows\event_loop\runner.rs:152
  78: winit::platform_impl::platform::event_loop::public_window_callback_inner
             at C:\Users\YuriMomo\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.25.0\src\platform_impl\windows\event_loop.rs:1980
  79: winit::platform_impl::platform::event_loop::public_window_callback<tuple<>>
             at C:\Users\YuriMomo\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.25.0\src\platform_impl\windows\event_loop.rs:791
  80: DefSubclassProc
  81: DefSubclassProc
  82: CallWindowProcW
  83: DispatchMessageW
  84: SendMessageTimeoutW
  85: KiUserCallbackDispatcher
  86: NtUserMessageCall
  87: GetWindowTextW
  88: IsIconic
  89: GetUserColorPreference
  90: IsCompositionActive
  91: IsCompositionActive
  92: GetWindowTextW
  93: CallWindowProcW
  94: CallWindowProcW
  95: DefSubclassProc
  96: DefSubclassProc
  97: core::ops::function::FnOnce::call_once
             at /rustc/3e99439f4dacc8ba0d2ca48d221694362d587927\library\core\src\ops\function.rs:227
  98: std::panic::{{impl}}::call_once
             at /rustc/3e99439f4dacc8ba0d2ca48d221694362d587927\library\std\src\panic.rs:346
  99: std::panicking::try::do_call
             at /rustc/3e99439f4dacc8ba0d2ca48d221694362d587927\library\std\src\panicking.rs:401
 100: std::panicking::try
             at /rustc/3e99439f4dacc8ba0d2ca48d221694362d587927\library\std\src\panicking.rs:365
 101: std::panic::catch_unwind
             at /rustc/3e99439f4dacc8ba0d2ca48d221694362d587927\library\std\src\panic.rs:433
 102: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<tuple<>>::catch_unwind<tuple<>,isize,closure-0>
             at C:\Users\YuriMomo\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.25.0\src\platform_impl\windows\event_loop\runner.rs:152
 103: winit::platform_impl::platform::event_loop::public_window_callback_inner
             at C:\Users\YuriMomo\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.25.0\src\platform_impl\windows\event_loop.rs:1980
 104: winit::platform_impl::platform::event_loop::public_window_callback<tuple<>>
             at C:\Users\YuriMomo\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.25.0\src\platform_impl\windows\event_loop.rs:791
 105: DefSubclassProc
 106: DefSubclassProc
 107: CallWindowProcW
 108: DispatchMessageW
 109: winit::platform_impl::platform::event_loop::EventLoop<tuple<>>::run_return<tuple<>,closure-1>
             at C:\Users\YuriMomo\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.25.0\src\platform_impl\windows\event_loop.rs:221
 110: winit::platform_impl::platform::event_loop::EventLoop<tuple<>>::run<tuple<>,closure-1>
             at C:\Users\YuriMomo\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.25.0\src\platform_impl\windows\event_loop.rs:191
 111: winit::event_loop::EventLoop<tuple<>>::run<tuple<>,closure-1>
             at C:\Users\YuriMomo\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.25.0\src\event_loop.rs:154
 112: veloren_voxygen::run::run
             at voxygen\src\run.rs:30
 113: veloren_voxygen::main
             at voxygen\src\main.rs:220
 114: core::ops::function::FnOnce::call_once
             at /rustc/3e99439f4dacc8ba0d2ca48d221694362d587927\library\core\src\ops\function.rs:227
 115: std::sys_common::backtrace::__rust_begin_short_backtrace<fn(),tuple<>>
             at /rustc/3e99439f4dacc8ba0d2ca48d221694362d587927\library\std\src\sys_common\backtrace.rs:125
 116: std::rt::lang_start::{{closure}}<tuple<>>
             at /rustc/3e99439f4dacc8ba0d2ca48d221694362d587927\library\std\src\rt.rs:49
 117: core::ops::function::impls::{{impl}}::call_once
             at /rustc/3e99439f4dacc8ba0d2ca48d221694362d587927\library\core\src\ops\function.rs:280
 118: std::panicking::try::do_call
             at /rustc/3e99439f4dacc8ba0d2ca48d221694362d587927\/library\std\src\panicking.rs:401
 119: std::panicking::try
             at /rustc/3e99439f4dacc8ba0d2ca48d221694362d587927\/library\std\src\panicking.rs:365
 120: std::panic::catch_unwind
             at /rustc/3e99439f4dacc8ba0d2ca48d221694362d587927\/library\std\src\panic.rs:433
 121: std::rt::lang_start_internal
             at /rustc/3e99439f4dacc8ba0d2ca48d221694362d587927\/library\std\src\rt.rs:34
 122: main
 123: post_pgo_initializer
 124: <unknown>

thread 'main' panicked at 'failed to configure swap chain on creation: Window is in use', C:\Users\YuriMomo\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-core-0.9.0\src\device\mod.rs:4547:29
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `target\debug\veloren-voxygen.exe` (exit code: 0xc0000409, STATUS_STACK_BUFFER_OVERRUN)
```

**Comment by YuuriMomo** [comment]
![obraz](https://user-images.githubusercontent.com/53386725/124839474-289fb180-df89-11eb-8cbb-934b9b085d90.png)

**Comment by cwfitzgerald** [comment]
Closing as out-of-date due to hal rewrite
