### ISSUE TITLE
hello_triangle_c panics with OutOfMemory(OutOfHostMemory)

### ISSUE THREAD

**Issue by rukai** [gfx-rs/wgpu#166]
OS: Arch Linux
GPU: GTX 960
Driver: Nvidia proprietary driver, version 418

No frames are ever rendered.
I can prevent the panic by adding a sleep(1) to the main loop, but it still never renders a frame.
```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: OutOfMemory(OutOfHostMemory)', src/libcore/result.rs:997:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:70
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:58
             at src/libstd/panicking.rs:200
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:215
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:478
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:385
   6: rust_begin_unwind
             at src/libstd/panicking.rs:312
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   8: core::result::unwrap_failed
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libcore/macros.rs:17
   9: <core::result::Result<T, E>>::unwrap
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libcore/result.rs:798
  10: wgpu_native::device::device_create_swap_chain
             at wgpu-native/src/device.rs:1741
  11: wgpu_swap_chain_get_next_texture
             at wgpu-native/src/swap_chain.rs:130
  12: main
  13: __libc_start_main
  14: _start
fatal runtime error: failed to initiate panic, error 5
Aborted (core dumped)
```

**Comment by kvark** [comment]
@rukai weird. I double checked on my NVidia, and it works fine. We need to get the debug output off your run to see what's going wrong. Could you hack in a small change into wgpu-native to hook up and initialize `env_logger::init()` when the user creates an instance? This should give us a clue.

**Comment by rukai** [comment]
Sure thing.
```
2019-05-13T10:30:07Z ERROR gfx_backend_vulkan] [Validation]  [ VUID-VkSwapchainCreateInfoKHR-imageExtent-01274 ] Object: 0x55ebb793f510 (Type = 3) | vkCreateSwapchainKHR() called with imageExtent = (640,480), which is outside the bounds returned by vkGetPhysicalDeviceSurfaceCapabilitiesKHR(): currentExtent = (1024,610), minImageExtent = (1024,610), maxImageExtent = (1024,610). The Vulkan spec states: imageExtent must be between minImageExtent and maxImageExtent, inclusive, where minImageExtent and maxImageExtent are members of the VkSurfaceCapabilitiesKHR structure returned by vkGetPhysicalDeviceSurfaceCapabilitiesKHR for the surface (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkSwapchainCreateInfoKHR-imageExtent-01274)
[2019-05-13T10:30:07Z ERROR gfx_backend_vulkan] [Validation]  [ UNASSIGNED-CoreValidation-DrawState-SwapchainTooManyImages ] Object: 0xd (Type = 27) | vkAcquireNextImageKHR: Application has already acquired the maximum number of images (0x1)
```
