### ISSUE TITLE
Tests Fail (Master)

### ISSUE THREAD

**Issue by johannesvollmer** [gfx-rs/wgpu#1727]
Hi! I ran the tests using these commands: 
- `git clone www.github.com/gfx-rs/wgpu` 
- `cd wgpu` 
- `cargo run --bin wgpu-info -- cargo test --no-fail-fast` 

There are some failing tests on my machine. I have an `HP OMEN 15dc` Laptop, unmodified, about 3 years old, the device is `NVIDIA GeForce GTX 1060 on Vulkan` and also I have an `Intel CORE i7 8th Gen`, Window 10.

Condensed:
- `skybox stdout: 0 outliers over max difference 0`
- `process didn't exit successfully (exit code: 0xc0000005, STATUS_ACCESS_VIOLATION)`

### Full Error Log
First failed test:
```
Running unittests (target\debug\examples\skybox-13445620ea830473.exe)

running 4 tests
test skybox_etc2 ... ok
test skybox_astc ... ok
test skybox_bc1 ... ok
test skybox ... FAILED

failures:

---- skybox stdout ----
0 outliers over max difference 0
thread 'skybox' panicked at 'UNEXPECTED TEST PASS: BACKEND', wgpu\examples\skybox\..\..\tests\common\mod.rs:299:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    skybox

test result: FAILED. 3 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 1.57s
```

Second failed test:
```
Doc-tests player

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

error: test failed.

Caused by:
  process didn't exit successfully: `C:\Users\Johannes\Documents\GitHub\wgpu-test-shader-compile\wgpu\target\debug\deps\test-a63410f1b07f0d61.exe` (exit code: 0xc0000005, STATUS_ACCESS_VIOLATION)
  process didn't exit successfully: `C:\Users\Johannes\Documents\GitHub\wgpu-test-shader-compile\wgpu\target\debug\examples\skybox-13445620ea830473.exe` (exit code: 101)
=========== FAILED! NVIDIA GeForce GTX 1060 on Vulkan (1 of 3) in 92.331s ===========
error: process didn't exit successfully: `target\debug\wgpu-info.exe cargo test --no-fail-fast` (exit code: 1)
```

I might continue investigation when I find the time

**Comment by cwfitzgerald** [comment]
The skybox failure looks quite suspicious as "0 outliers over max difference 0" sounds like it should pass. Maybe we're doing the wrong equality.

**Comment by kvark** [comment]
Please grab the stack trace if you can!

**Comment by cwfitzgerald** [comment]
So the first half of this is fixed by #1731.

**Comment by johannesvollmer** [comment]
I pulled master again a minute ago. The second error seems to have disappeared.

Here's the new std output of running the tests, with backtraces activated:
```
[...]

failures:

---- skybox stdout ----
0 outliers over max difference 0
thread 'skybox' panicked at 'UNEXPECTED TEST PASS: BACKEND', wgpu\examples\skybox\..\..\tests\common\mod.rs:299:9
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b\/library\std\src\panicking.rs:493
   1: std::panicking::begin_panic_fmt
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b\/library\std\src\panicking.rs:435
   2: skybox::framework::test_common::initialize_test<closure-0>
             at .\tests\common\mod.rs:299
   3: skybox::framework::test<skybox::Skybox>
             at .\examples\framework.rs:402
   4: skybox::skybox
             at .\examples\skybox\main.rs:469
   5: skybox::skybox::{{closure}}
             at .\examples\skybox\main.rs:468
   6: core::ops::function::FnOnce::call_once<closure-0,tuple<>>
             at C:\Users\Johannes\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\ops\function.rs:227
   7: core::ops::function::FnOnce::call_once
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b\library\core\src\ops\function.rs:227

[...]

Doc-tests wgpu-hal

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

error: test failed, to rerun pass '-p wgpu --example skybox
=========== FAILED! NVIDIA GeForce GTX 1060 on Vulkan (1 of 3) in 17.944s ===========
error: process didn't exit successfully: `target\debug\wgpu-info.exe cargo test --no-fail-fast` (exit code: 1)
[end of std output]
```

I assume the two last lines reference the first failure, and do not contain another second failure, right?.

**Comment by kvark** [comment]
the unexpected pass is also now fixed

**Comment by johannesvollmer** [comment]
Pulled master, ran tests. The previous error seems to have disappeared :)

However, a different error is surfacing now. This test might not even have been executed on my previous attempts, maybe due to other errors ending the whole test suite.

```
test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 1.43s

     Running unittests (target\debug\examples\shadow-63b3ca90a8dd87fb.exe)

running 1 test
[2021-07-27T14:06:28Z ERROR wgpu_hal::dx12::instance] ID3D12CommandAllocator::Reset: The command allocator cannot be reset because a command list is currently being recorded with the allocator. [ EXECUTION ERROR #543: COMMAND_ALLOCATOR_CANNOT_RESET]
```
`[..]`
```
error: test failed, to rerun pass '-p wgpu --example shadow
=========== FAILED! NVIDIA GeForce GTX 1060 on Dx12 (2 of 3) in 20.323s ===========
error: process didn't exit successfully: `target\debug\wgpu-info.exe cargo test --no-fail-fast` (exit code: 1)
```

There seems to be no stacktrace

**Comment by kvark** [comment]
you'd need to run `target\debug\wgpu-info.exe cargo test --no-fail-fast` in a debugger (e.g. visual studio) to get the stack trace
The `ID3D12CommandAllocator` allocator error seems new, I haven't seen it yesterday

**Comment by cwfitzgerald** [comment]
I'm not confident it will show child processes in the debugger, so you should run `target\debug\examples\shadow-63b3ca90a8dd87fb.exe` with environment `WGPU_BACKEND=dx12` and `WGPU_ADAPTER_NAME=1060`. That will make sure you actually get the debug messages.

**Comment by johannesvollmer** [comment]
I did that, but unfortunately, the std output is no different.

Commands:

1. `cd wgpu`
2. `$Env:WGPU_BACKEND="dx12"` (PowerShell set environment variable)
3. `$Env:WGPU_ADAPTER_NAME="1060"`
4. `.\target\debug\examples\shadow-63b3ca90a8dd87fb.exe`

Output:
```
running 1 test
[2021-07-27T16:11:42Z ERROR wgpu_hal::dx12::instance] ID3D12CommandAllocator::Reset: The command allocator cannot be reset because a command list is currently being recorded with the allocator. [ EXECUTION ERROR #543: COMMAND_ALLOCATOR_CANNOT_RESET]
```

The environment variables seemed to have worked, as dx12 is the instance where the error occured. But I can't see any more debug messages. Maybe with a debugger?

**Comment by johannesvollmer** [comment]
I ran that executable with those environment variables in VSCode with the Windows debugger, and (presumably a different error) appeared. The error is about unwrapping an empty option. There is no command allocator mentioned anywhere. It has quite an extended stacktrace:
```
running 1 test
test shadow ... FAILED

failures:

---- shadow stdout ----
thread 'shadow' panicked at 'called `Option::unwrap()` on a `None` value', wgpu-hal\src\dx12\command.rs:672:62
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b\/library\std\src\panicking.rs:493
   1: core::panicking::panic_fmt
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b\/library\core\src\panicking.rs:92
   2: core::panicking::panic
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b\/library\core\src\panicking.rs:50
   3: core::option::Option<wgpu_hal::dx12::descriptor::DualHandle>::unwrap<wgpu_hal::dx12::descriptor::DualHandle>
             at C:\Users\Johannes\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\option.rs:386
   4: wgpu_hal::dx12::command::{{impl}}::set_bind_group
             at .\wgpu\wgpu-hal\src\dx12\command.rs:672
   5: wgpu_core::hub::Global<wgpu_core::hub::IdentityManagerFactory>::command_encoder_run_render_pass_impl<wgpu_core::hub::IdentityManagerFactory,wgpu_hal::dx12::Api>
             at .\wgpu\wgpu-core\src\command\render.rs:974
   6: wgpu_core::hub::Global<wgpu_core::hub::IdentityManagerFactory>::command_encoder_run_render_pass<wgpu_core::hub::IdentityManagerFactory,wgpu_hal::dx12::Api>
             at .\wgpu\wgpu-core\src\command\render.rs:811
   7: wgpu::backend::direct::{{impl}}::command_encoder_end_render_pass
             at .\wgpu\wgpu\src\backend\direct.rs:1866
   8: wgpu::{{impl}}::drop
             at .\wgpu\wgpu\src\lib.rs:2759
   9: core::ptr::drop_in_place<wgpu::RenderPass>
             at C:\Users\Johannes\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\ptr\mod.rs:192
  10: shadow::{{impl}}::render
             at .\wgpu\wgpu\examples\shadow\main.rs:772
  11: shadow::framework::test::{{closure}}<shadow::Example>
             at .\wgpu\wgpu\examples\framework.rs:445
  12: shadow::framework::test_common::initialize_test::{{closure}}<closure-0>
             at .\wgpu\wgpu\tests\common\mod.rs:287
  13: std::panic::{{impl}}::call_once<tuple<>,closure-1>
             at C:\Users\Johannes\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\panic.rs:344
  14: std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure-1>,tuple<>>
             at C:\Users\Johannes\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\panicking.rs:379
  15: deflate::compress::compress_data_dynamic_n<alloc::vec::Vec<u8, alloc::alloc::Global>>
  16: std::panicking::try<tuple<>,std::panic::AssertUnwindSafe<closure-1>>
             at C:\Users\Johannes\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\panicking.rs:343
  17: std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure-1>,tuple<>>
             at C:\Users\Johannes\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\panic.rs:431
  18: shadow::framework::test_common::initialize_test<closure-0>
             at .\wgpu\wgpu\tests\common\mod.rs:287
  19: shadow::framework::test<shadow::Example>
             at .\wgpu\wgpu\examples\framework.rs:402
  20: shadow::shadow
             at .\wgpu\wgpu\examples\shadow\main.rs:827
  21: shadow::shadow::{{closure}}
             at .\wgpu\wgpu\examples\shadow\main.rs:826
  22: core::ops::function::FnOnce::call_once<closure-0,tuple<>>
             at C:\Users\Johannes\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\ops\function.rs:227
  23: core::ops::function::FnOnce::call_once
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b\library\core\src\ops\function.rs:227
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'shadow' panicked at 'UNEXPECTED TEST FAILURE', wgpu\examples\shadow\..\..\tests\common\mod.rs:301:9
stack backtrace:
   0: std::panicking::begin_panic<str>
             at C:\Users\Johannes\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\panicking.rs:519
   1: shadow::framework::test_common::initialize_test<closure-0>
             at .\wgpu\wgpu\tests\common\mod.rs:301
   2: shadow::framework::test<shadow::Example>
             at .\wgpu\wgpu\examples\framework.rs:402
   3: shadow::shadow
             at .\wgpu\wgpu\examples\shadow\main.rs:827
   4: shadow::shadow::{{closure}}
             at .\wgpu\wgpu\examples\shadow\main.rs:826
   5: core::ops::function::FnOnce::call_once<closure-0,tuple<>>
             at C:\Users\Johannes\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\ops\function.rs:227
   6: core::ops::function::FnOnce::call_once
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b\library\core\src\ops\function.rs:227
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    shadow

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.59s

Press any key to continue . . .
```

**Comment by kvark** [comment]
I'm very confused. The code in question is unwrapping an `Option` that is a part of the bind group. There is nothing about this code that would be platform-dependent. I.e. I should be seeing either the `unwrap` failing, or that DX12 error on my side. But I'm not seeing either.

**Comment by johannesvollmer** [comment]
Note that I didn't run `target\debug\wgpu-info.exe cargo test --no-fail-fast` in a debugger, but instead directly debugged the executable for that test, which is `target/debug/examples/shadow-63b3ca90a8dd87fb.exe` in my case. 

Is it even advisable to execute such a generated test binary? When I use cargo to run the test (`target\debug\wgpu-info.exe cargo test --no-fail-fast -p wgpu --example shadow`), the command allocator appears again

**Comment by johannesvollmer** [comment]
All tests pass on my machine now :)
