### ISSUE TITLE
Missing validations

### ISSUE THREAD

**Issue by scoopr** [gfx-rs/wgpu#1756]
By the scientific method of changing random things in the examples, I noticed few missing validations.

* Setting texture descriptor `sample_count` to `3` causes a metal assert 
```Using Intel(R) UHD Graphics 630 (Metal)
-[MTLTextureDescriptorInternal validateWithDevice:]:1248: failed assertion `Texture Descriptor Validation
MTLTextureDescriptor sampleCount (3) is not supported by device.
```

* Removing `RENDER_ATTACHMENT` usage from depth texture that requires it causes a metal assert
```
validateRenderPassDescriptor:783: failed assertion `Texture at depthAttachment has usage (0x01) which doesn't specify MTLTextureUsageRenderTarget (0x04)'
```
* Removing `COPY_DST` usage from uniform buffer causes a panic
```
thread 'main' panicked at 'Error in Queue::write_buffer: destination buffer/texture is missing the `COPY_DST` usage flag', wgpu/src/backend/direct.rs:186:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
* Setting `mapped_at_creation` to true, causing extra mapping that the code didn't expect causes a panic
```
thread 'main' panicked at 'Buffer Valid((4, 1, Metal)) is still mapped', /Users/scoopr/Code/ext/wgpu/wgpu-core/src/device/queue.rs:604:42
```
* Queue.write_buffer with unaligned offset causes a panic
```
thread 'main' panicked at 'Error in Queue::write_buffer: buffer offset 251 is not aligned to block size or `COPY_BUFFER_ALIGNMENT`', wgpu/src/backend/direct.rs:186:9
```
* Queue.write_buffer with too big offset causes a panic
```
thread 'main' panicked at 'Error in Queue::write_buffer: copy of 384..392 would end up overrunning the bounds of the Destination buffer of size 160', wgpu/src/backend/direct.rs:186:9
```
* Queue.write_texture with unaligned offset causes a panic
```
thread 'main' panicked at 'Error in Queue::write_texture: buffer offset 3 is not aligned to block size or `COPY_BUFFER_ALIGNMENT`', wgpu/src/backend/direct.rs:186:9
```
* Queue.write_texture with too little data causes panic
```
thread 'main' panicked at 'Error in Queue::write_texture: number of bytes per row is less than the number of bytes in a complete row', wgpu/src/backend/direct.rs:186:9
```

**Comment by jimblandy** [comment]
Some of these are fixed, and some of these are vague. We're going to close this for now, and let the CTS point out what we're missing.
