### ISSUE TITLE
wgpu examples don't work under Wayland when using OpenGL backend

### ISSUE THREAD

**Issue by treeco123** [gfx-rs/wgpu#1787]
**Description**
As title. They work under X11. This occurred both pre- and post- wgpu-hal.

**Repro steps**
`WGPU_BACKEND=gl cargo run --example cube`

**Observed behavior**
wgpu master, on Wayland:
```
[treeco@treeco-ms7b86 wgpu]$ WGPU_BACKEND=gl cargo run --example cube
    Finished dev [unoptimized + debuginfo] target(s) in 0.05s
     Running `target/debug/examples/cube`
[2021-08-10T18:50:34Z ERROR wgpu_hal::gles::egl] EGL 'eglCreatePlatformWindowSurface' code 0x3009: Unsupported surfacetype/colorspace configuration
Using AMD Radeon (TM) R5 340 (OLAND, DRM 3.41.0, 5.13.8-1-MANJARO, LLVM 12.0.1) (Gl)
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', wgpu-core/src/hub.rs:1037:29
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
wgpu master, on X11:
```
[treeco@treeco-ms7b86 wgpu]$ WGPU_BACKEND=gl cargo run --example cube
    Finished dev [unoptimized + debuginfo] target(s) in 0.06s
     Running `target/debug/examples/cube`
Using AMD Radeon (TM) R5 340 (OLAND, DRM 3.41.0, 5.13.8-1-MANJARO, LLVM 12.0.1) (Gl)
Avg frame time 16.510405ms
Avg frame time 16.676777ms
```
wgpu v0.9 branch, on Wayland:
```
[treeco@treeco-ms7b86 wgpu]$ WGPU_BACKEND=gl cargo run --example cube
    Finished dev [unoptimized + debuginfo] target(s) in 0.06s
     Running `target/debug/examples/cube`
Using AMD Radeon (TM) R5 340 (OLAND, DRM 3.41.0, 5.13.8-1-MANJARO, LLVM 12.0.1) (Gl)
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', wgpu-core/src/hub.rs:878:29
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
**Platform**
Manjaro Linux, Plasma desktop environment, R5 340 GPU

**Comment by kvark** [comment]
According to EGL docs:
>EGL_BAD_MATCH is generated if the pixel format of native_window does not correspond to the format, type, and size of the color buffers required by config. EGL_BAD_MATCH is generated if the pixel

>EGL_BAD_MATCH is generated if config does not support rendering to windows (the EGL_SURFACE_TYPE attribute does not contain EGL_WINDOW_BIT).

>EGL_BAD_MATCH is generated if config does not support the specified OpenVG alpha format attribute (the value of EGL_VG_ALPHA_FORMAT is EGL_VG_ALPHA_FORMAT_PRE and the EGL_VG_ALPHA_FORMAT_PRE_BIT is not set in the EGL_SURFACE_TYPE attribute of config) or colorspace attribute (the value of EGL_VG_COLORSPACE is EGL_VG_COLORSPACE_LINEAR and the EGL_VG_COLORSPACE_LINEAR_IT is not set in the EGL_SURFACE_TYPE attribute of config).

**Comment by niklaskorz** [comment]
For what it's worth, neither OpenGL or Vulkan work for Nvidia on Wayland (with the latest drivers that have improved Wayland support), but I think that's an issue on Nvidia's side... See also the [issue on gluting](https://github.com/rust-windowing/glutin/issues/1188).
I'm not sure if it's worth opening an issue for that on wgpu as it likely can't be fixed easily here. On the other hand, there are OpenGL applications using EGL that run fine on Wayland with Nvidia, so maybe it could be investigated after all. As for Vulkan, wgpu simply reports that the surface capabilities are empty.

**Comment by PolyMeilex** [comment]
I'm running nouveau drivers, and it's the same here. Examples from Glutin repo work fine in my case.
So it seems that it's the same issue on 3 different drivers, radeon ones, nvidia ones, and nouveau

**Comment by niklaskorz** [comment]
So the issue on proprietary Nvidia is actually unrelated as it turns out: https://github.com/NVIDIA/egl-wayland/issues/34

As for the error reported here on AMD and Nouveau ("Unsupported surfacetype/colorspace") I'm able to reproduce it for Zink as well (OpenGL on Vulkan driver of Mesa), where glutin runs just fine.

**Comment by VitalyAnkh** [comment]
@kvark  Hi! This PR doesn't fix #1787 in my system with Nvidia 495.29.05 beta driver and Gnome on Wayland. I pull the latest code and run
```
RUST_LOG=info WINIT_UNIX_BACKEND=wayland WGPU_BACKEND=gl cargo run --example shadow
```
Then I got this:
```
RUST_LOG=info WINIT_UNIX_BACKEND=wayland WGPU_BACKEND=gl cargo run --example shadow
   Compiling wgpu v0.11.0 (/home/vitalyr/projects/contribute/rust-projects/wgpu/wgpu)
    Finished dev [unoptimized + debuginfo] target(s) in 18.61s
     Running `target/debug/examples/shadow`
[2021-10-16T00:26:48Z ERROR smithay_client_toolkit::window::concept_frame] No font could be found
[2021-10-16T00:26:48Z INFO  shadow::framework] Initializing the surface...
[2021-10-16T00:26:48Z INFO  wgpu_hal::gles::egl] Loading Wayland library to get the current display
[2021-10-16T00:26:48Z INFO  wgpu_hal::gles::egl] Loading X11 library to get the current display
[2021-10-16T00:26:48Z INFO  wgpu_hal::gles::egl] Using Wayland platform
[2021-10-16T00:26:48Z INFO  wgpu_hal::gles::egl] Enabling EGL debug output
[2021-10-16T00:26:48Z INFO  wgpu_hal::gles::egl] Display vendor "NVIDIA", version (1, 5)
[2021-10-16T00:26:48Z INFO  wgpu_hal::gles::egl] 	EGL surface: +srgb
[2021-10-16T00:26:48Z INFO  wgpu_hal::gles::egl] 	Trying native-render
[2021-10-16T00:26:48Z WARN  wgpu_hal::gles::egl] No config found!
[2021-10-16T00:26:48Z INFO  wgpu_hal::gles::egl] 	Trying presentation
[2021-10-16T00:26:48Z WARN  wgpu_hal::gles::egl] EGL says it can present to the window but not natively. This has been confirmed to malfunction on Intel+NV laptops. Therefore, we disable presentation entirely for this platform
[2021-10-16T00:26:48Z INFO  wgpu_hal::gles::egl] 	EGL context: +debug
[2021-10-16T00:26:48Z INFO  wgpu_hal::gles::egl] 	EGL context: +robust access
[2021-10-16T00:26:48Z INFO  wgpu_hal::gles::egl] 	EGL context: +surfaceless
[2021-10-16T00:26:48Z WARN  wgpu_hal::gles::egl] Re-initializing Gles context due to Wayland window
[2021-10-16T00:26:49Z INFO  wgpu_hal::gles::egl] Display vendor "NVIDIA", version (1, 5)
[2021-10-16T00:26:49Z INFO  wgpu_hal::gles::egl] 	EGL surface: +srgb
[2021-10-16T00:26:49Z INFO  wgpu_hal::gles::egl] 	Trying native-render
[2021-10-16T00:26:49Z WARN  wgpu_hal::gles::egl] No config found!
[2021-10-16T00:26:49Z INFO  wgpu_hal::gles::egl] 	Trying presentation
[2021-10-16T00:26:49Z WARN  wgpu_hal::gles::egl] EGL says it can present to the window but not natively. This has been confirmed to malfunction on Intel+NV laptops. Therefore, we disable presentation entirely for this platform
[2021-10-16T00:26:49Z INFO  wgpu_hal::gles::egl] 	EGL context: +debug
[2021-10-16T00:26:49Z INFO  wgpu_hal::gles::egl] 	EGL context: +robust access
[2021-10-16T00:26:49Z INFO  wgpu_hal::gles::egl] 	EGL context: +surfaceless
[2021-10-16T00:26:49Z INFO  wgpu_hal::gles::egl] Max label length: 256
[2021-10-16T00:26:49Z INFO  wgpu_hal::gles::egl] Enabling GLES debug output
[2021-10-16T00:26:49Z INFO  wgpu_hal::gles::adapter] Vendor: NVIDIA Corporation
[2021-10-16T00:26:49Z INFO  wgpu_hal::gles::adapter] Renderer: NVIDIA GeForce GTX 1060/PCIe/SSE2
[2021-10-16T00:26:49Z INFO  wgpu_hal::gles::adapter] Version: OpenGL ES 3.2 NVIDIA 495.29.05
[2021-10-16T00:26:49Z INFO  wgpu_hal::gles::adapter] SL version: OpenGL ES GLSL ES 3.20
thread 'main' panicked at 'No suitable GPU adapters found on the system!', wgpu/examples/shadow/../framework.rs:136:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[2021-10-16T00:26:49Z INFO  wgpu_core::hub] Dropping Global
```
I still can't run wgpu with Nvidia driver and Wayland...

**Comment by VitalyAnkh** [comment]
Sorry, now I know I should let this example use wgpu's latest code, not 0.11.0.

**Comment by kvark** [comment]
The wayland fix is included in wgpu-hal-0.11.3

**Comment by kvark** [comment]
That's quite sad. Thank you for investigating so far!
I tested the examples on Intel with and without Wayland, and made sure this worked. So what you are seeing may be some weirdness with NVidia that we need to figure out.

**Comment by PolyMeilex** [comment]
I can confirm that for nouveau it's fixed, there is something wrong with resize events but that's probably unrelated I will check winit for that. The rendering itself runs really well
