### ISSUE TITLE
Dropping SurfaceTexture-derived TextureView After SurfaceTexture Causes a Crash

### ISSUE THREAD

**Issue by cwfitzgerald** [gfx-rs/wgpu#1797]
**Description**

If you drop a texture view derived from a SurfaceTexture after you drop the SurfaceTexture, wgpu panics.

**Repro steps**

```
git clone https://github.com/BVE-Reborn/rend3.git
git checkout e1a4c702c0affba4c3d1e3fafc01eb2d88290320
```

Flip the order of this enum https://github.com/BVE-Reborn/rend3/blob/render-list-removal/rend3/src/util/output.rs#L8-L9 and there will be a crash when you run

```
cargo run --bin scene-viewer -- -m cpu -b vulkan
```

**Expected vs observed behavior**

Expected: Happiness and World Peace
Observed:

<details>
<summary>Backtrace</summary>

```
thread 'main' panicked at 'Texture[13] does not exist', C:\Users\conno\.cargo\git\checkouts\wgpu-53e70f8674b08dd4\1e7d86b\wgpu-core\src\hub.rs:129:32
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b\/library\std\src\panicking.rs:493
   1: std::panicking::begin_panic_fmt
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b\/library\std\src\panicking.rs:435
   2: wgpu_core::hub::Storage<wgpu_core::resource::Texture<wgpu_hal::vulkan::Api>, wgpu_core::id::Id<wgpu_core::resource::Texture<wgpu_hal::empty::Api>>>::get<wgpu_core::resource::Texture<wgpu_hal::vulkan::Api>,wgpu_core::id::Id<wgpu_core::resource::Texture<wgp
             at C:\Users\conno\.cargo\git\checkouts\wgpu-53e70f8674b08dd4\1e7d86b\wgpu-core\src\hub.rs:129
   3: wgpu_core::hub::{{impl}}::index<wgpu_core::resource::Texture<wgpu_hal::vulkan::Api>,wgpu_core::id::Id<wgpu_core::resource::Texture<wgpu_hal::empty::Api>>>
             at C:\Users\conno\.cargo\git\checkouts\wgpu-53e70f8674b08dd4\1e7d86b\wgpu-core\src\hub.rs:102
   4: wgpu_core::hub::Global<wgpu_core::hub::IdentityManagerFactory>::texture_view_drop<wgpu_core::hub::IdentityManagerFactory,wgpu_hal::vulkan::Api>
             at C:\Users\conno\.cargo\git\checkouts\wgpu-53e70f8674b08dd4\1e7d86b\wgpu-core\src\device\mod.rs:3262
   5: wgpu::backend::direct::{{impl}}::texture_view_drop
             at C:\Users\conno\.cargo\git\checkouts\wgpu-53e70f8674b08dd4\1e7d86b\wgpu\src\backend\direct.rs:1629
   6: wgpu::{{impl}}::drop
             at C:\Users\conno\.cargo\git\checkouts\wgpu-53e70f8674b08dd4\1e7d86b\wgpu\src\lib.rs:2113
   7: core::ptr::drop_in_place<wgpu::TextureView>
             at C:\Users\conno\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\ptr\mod.rs:192
   8: core::ptr::drop_in_place<rend3::util::output::OutputFrame>
             at C:\Users\conno\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\ptr\mod.rs:192
   9: rend3::renderer::render::render_loop
             at .\rend3\src\renderer\render.rs:208
  10: rend3::renderer::Renderer::render
             at .\rend3\src\renderer\mod.rs:238
  11: scene_viewer::main::{{closure}}
             at .\examples\scene-viewer\src\main.rs:293
  12: winit::platform_impl::platform::event_loop::{{impl}}::run_return::{{closure}}<tuple<>,closure-2>
             at C:\Users\conno\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.25.0\src\platform_impl\windows\event_loop.rs:206
  13: alloc::boxed::{{impl}}::call_mut<tuple<winit::event::Event<tuple<>>, mut winit::event_loop::ControlFlow*>,FnMut<tuple<winit::event::Event<tuple<>>, mut winit::event_loop::ControlFlow*>>,alloc::alloc::Global>   
             at C:\Users\conno\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\alloc\src\boxed.rs:1553
  14: winit::platform_impl::platform::event_loop::runner::{{impl}}::call_event_handler::{{closure}}<tuple<>>
             at C:\Users\conno\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.25.0\src\platform_impl\windows\event_loop\runner.rs:245
  15: std::panic::{{impl}}::call_once<tuple<>,closure-0>
             at C:\Users\conno\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\panic.rs:344
  16: std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure-0>,tuple<>>
             at C:\Users\conno\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\panicking.rs:379
  17: winit::platform_impl::platform::drop_handler::{{impl}}::drop
  18: std::panicking::try<tuple<>,std::panic::AssertUnwindSafe<closure-0>>
             at C:\Users\conno\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\panicking.rs:343
  19: std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure-0>,tuple<>>
             at C:\Users\conno\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\panic.rs:431
  20: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<tuple<>>::catch_unwind<tuple<>,tuple<>,closure-0>
             at C:\Users\conno\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.25.0\src\platform_impl\windows\event_loop\runner.rs:152
  21: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<tuple<>>::call_event_handler<tuple<>>
             at C:\Users\conno\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.25.0\src\platform_impl\windows\event_loop\runner.rs:239
  22: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<tuple<>>::send_event<tuple<>>
             at C:\Users\conno\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.25.0\src\platform_impl\windows\event_loop\runner.rs:210
  23: winit::platform_impl::platform::event_loop::SubclassInput<tuple<>>::send_event<tuple<>>
             at C:\Users\conno\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.25.0\src\platform_impl\windows\event_loop.rs:96
  24: winit::platform_impl::platform::event_loop::public_window_callback_inner::{{closure}}<tuple<>>
             at C:\Users\conno\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.25.0\src\platform_impl\windows\event_loop.rs:892
  25: core::ops::function::FnOnce::call_once<closure-0,tuple<>>
             at C:\Users\conno\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\ops\function.rs:227
  26: std::panic::{{impl}}::call_once<isize,closure-0>
             at C:\Users\conno\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\panic.rs:344
  27: std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure-0>,isize>
             at C:\Users\conno\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\panicking.rs:379
  28: hashbrown::set::HashSet<mut winapi::shared::windef::HWND__*, std::collections::hash::map::RandomState, alloc::alloc::Global>::remove<mut winapi::shared::windef::HWND__*,std::collections::hash::map::RandomState,alloc::alloc::Global,mut winapi::shared::wind
  29: std::panicking::try<isize,std::panic::AssertUnwindSafe<closure-0>>
             at C:\Users\conno\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\panicking.rs:343
  30: std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure-0>,isize>
             at C:\Users\conno\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\panic.rs:431
  31: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<tuple<>>::catch_unwind<tuple<>,isize,closure-0>
             at C:\Users\conno\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.25.0\src\platform_impl\windows\event_loop\runner.rs:152
  32: winit::platform_impl::platform::event_loop::public_window_callback_inner<tuple<>>
             at C:\Users\conno\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.25.0\src\platform_impl\windows\event_loop.rs:1980
  33: winit::platform_impl::platform::event_loop::public_window_callback<tuple<>>
             at C:\Users\conno\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.25.0\src\platform_impl\windows\event_loop.rs:791
  34: DefSubclassProc
  35: DefSubclassProc
  36: CallWindowProcW
  37: CallWindowProcW
  38: glPushClientAttrib
  39: CallWindowProcW
  40: DispatchMessageW
  41: SendMessageTimeoutW
  42: KiUserCallbackDispatcher
  43: NtUserDispatchMessage
  44: DispatchMessageW
  45: winit::platform_impl::platform::event_loop::EventLoop<tuple<>>::run_return<tuple<>,closure-2>
             at C:\Users\conno\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.25.0\src\platform_impl\windows\event_loop.rs:221
  46: winit::platform_impl::platform::event_loop::EventLoop<tuple<>>::run<tuple<>,closure-2>
             at C:\Users\conno\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.25.0\src\platform_impl\windows\event_loop.rs:191
  47: winit::event_loop::EventLoop<tuple<>>::run<tuple<>,closure-2>
             at C:\Users\conno\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.25.0\src\event_loop.rs:154
  48: scene_viewer::main
             at .\examples\scene-viewer\src\main.rs:172
  49: core::ops::function::FnOnce::call_once<fn(),tuple<>>
             at C:\Users\conno\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\ops\function.rs:227
```

</details>

**Extra materials**

This panic actually causes a double-panic as it tries to delete the texture twice.

**Comment by kvark** [comment]
I think there is a general thing missing here. If a view from a surface texture is dropped, we don't need to do anything about the parent texture. Currently, there is no special logic to make this exclusion.

> Expected: Happiness and World Peace

some day!

**Comment by hannobraun** [comment]
FYI, I've had a workaround for this bug in my code which I've just now removed (after upgrading to wgpu 0.11), without any adverse effect.

**Comment by cwfitzgerald** [comment]
Oh yeah, we just forgot to close this.
