### ISSUE TITLE
No protection against calling Device::create_buffer_init with empty contents

### ISSUE THREAD

**Issue by rukai** [gfx-rs/wgpu#1801]
**Description**
No protection against calling Device::create_buffer_init with empty contents

**Repro steps**
Changing any example as following will trigger the issue:
```
         let index_buf = device.create_buffer_init(&wgpu::util::BufferInitDescriptor {
             label: Some("Index Buffer"),
-            contents: bytemuck::cast_slice(&index_data),
+            contents: bytemuck::cast_slice(&index_data[0..0]),
             usage: wgpu::BufferUsages::INDEX,
         });
```

**Expected vs observed behavior**
We should maintain previous behavior in 0.9 by triggering a wgpu error.
Currently we are hitting vulkan validation layer errors which is no good.

If I run in debug I get:
```
rukai@memes examples$ cargo run --example cube
   Compiling wgpu v0.9.0 (/home/rukai2/Projects/Crates/wgpu/wgpu/wgpu)
    Finished dev [unoptimized + debuginfo] target(s) in 2.57s
     Running `/home/rukai2/Projects/Crates/wgpu/wgpu/target/debug/examples/cube`
Using NVIDIA GeForce GTX 960 (Vulkan)
[2021-08-14T05:13:29Z ERROR wgpu_hal::vulkan::instance] VALIDATION [VUID-VkBufferCreateInfo-size-00912 (0x7c54445e)]
    	Validation Error: [ VUID-VkBufferCreateInfo-size-00912 ] Object 0: handle = 0x5622477e2e58, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x7c54445e | vkCreateBuffer: parameter pCreateInfo->size (= 0) is not greater than 0 The Vulkan spec states: size must be greater than 0 (https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VUID-VkBufferCreateInfo-size-00912)
[2021-08-14T05:13:29Z ERROR wgpu_hal::vulkan::instance] 	objects: (type: DEVICE, hndl: 0x5622477e2e58, name: ?)
thread 'main' panicked at 'attempt to subtract with overflow', /home/rukai/.cargo/registry/src/github.com-1ecc6299db9ec823/gpu-alloc-0.4.7/src/buddy.rs:333:26
stack backtrace:
```
If I run in release I get:
```
rukai@memes examples$ cargo run --example cube --release
   Compiling wgpu v0.9.0 (/home/rukai2/Projects/Crates/wgpu/wgpu/wgpu)
    Finished release [optimized] target(s) in 1.51s
     Running `/home/rukai2/Projects/Crates/wgpu/wgpu/target/release/examples/cube`
Using NVIDIA GeForce GTX 960 (Vulkan)
Killed
```

On wgpu 0.9 it was handled with an error.
```
Using NVIDIA GeForce GTX 960 (Vulkan)
[2021-08-14T12:08:08Z ERROR wgpu::backend::direct] wgpu error: Validation Error
    
    Caused by:
        In a RenderPass
          note: encoder = `<CommandBuffer-(0, 1, Vulkan)>`
        In a draw command, indexed:true indirect:false
          note: render pipeline = `<RenderPipeline-(0, 1, Vulkan)>`
        index 36 extends beyond limit 0. Did you bind the correct index buffer?
    
    
thread 'main' panicked at 'Handling wgpu errors as fatal by default', wgpu/src/backend/direct.rs:1978:5
stack backtrace:
   0: std::panicking::begin_panic
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:541:12
   1: wgpu::backend::direct::default_error_handler
             at ./wgpu/src/backend/direct.rs:1978:5
   2: core::ops::function::Fn::call
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/ops/function.rs:70:5
   3: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/alloc/src/boxed.rs:1589:9
   4: wgpu::backend::direct::ErrorSinkRaw::handle_error
             at ./wgpu/src/backend/direct.rs:1965:9
   5: wgpu::backend::direct::Context::handle_error
             at ./wgpu/src/backend/direct.rs:93:9
   6: <wgpu::backend::direct::Context as wgpu::Context>::command_encoder_end_render_pass
             at ./wgpu/src/backend/direct.rs:1764:13
   7: <wgpu::RenderPass as core::ops::drop::Drop>::drop
             at ./wgpu/src/lib.rs:2629:13
   8: core::ptr::drop_in_place<wgpu::RenderPass>
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/ptr/mod.rs:192:1
   9: <cube::Example as cube::framework::Example>::render
             at ./wgpu/examples/cube/main.rs:385:9
  10: cube::framework::start::{{closure}}
             at ./wgpu/examples/cube/../framework.rs:307:17
  11: winit::platform_impl::platform::sticky_exit_callback
             at /home/rukai/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/platform_impl/linux/mod.rs:736:5
  12: winit::platform_impl::platform::x11::EventLoop<T>::run_return
             at /home/rukai/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/platform_impl/linux/x11/mod.rs:320:21
  13: winit::platform_impl::platform::x11::EventLoop<T>::run
             at /home/rukai/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/platform_impl/linux/x11/mod.rs:398:9
  14: winit::platform_impl::platform::EventLoop<T>::run
             at /home/rukai/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/platform_impl/linux/mod.rs:652:56
  15: winit::event_loop::EventLoop<T>::run
             at /home/rukai/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/event_loop.rs:154:9
  16: cube::framework::start
             at ./wgpu/examples/cube/../framework.rs:220:5
  17: cube::framework::run
             at ./wgpu/examples/cube/../framework.rs:355:5
  18: cube::main
             at ./wgpu/examples/cube/main.rs:392:5
  19: core::ops::function::FnOnce::call_once
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/ops/function.rs:227:5
```
Although this error seems really weird, maybe we can have a better error than this?

**Platform**
wgpu master, linux, vulkan, Nvidia GTX 960 with proprietary driver

**Comment by kvark** [comment]
Would be great to see new contributors (or returning contributors) helping with this. I don't think it needs to block our release.

**Comment by rukai** [comment]
I did hit this when porting my project to master, I guess the error was being silently ignored in certain cases. So fixing this could help others in the upgrade process. Up to you if that's important or not.

**Comment by cwfitzgerald** [comment]
I'll see if I can patch it tonight
