### ISSUE TITLE
create_bind_group OutOfMemory

### ISSUE THREAD

**Issue by rukai** [gfx-rs/wgpu#181]
OS: Arch Linux
GPU: GTX 960
Driver: Nvidia proprietary driver, version 418

repro: https://github.com/rukai/wgpu-rs/blob/85b131378a693e163b3c9d2ba7f21dd57bb02faa/examples/repro/main.rs
Setting any of the loops to only happen once, seems to prevent the issue for me.

validation layers:
```
[2019-05-19T01:53:52Z ERROR gfx_backend_vulkan]
VALIDATION [VUID-VkDescriptorSetAllocateInfo-descriptorSetCount-00306 (0)] : Unable to allocate 1 descriptorSets from pool 0x2. This pool only has 0 descriptorSets remaining. The Vulkan spec states: descriptorSetCount must not be greater than the number of sets that are currently available for allocation in descriptorPool (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkDescriptorSetAllocateInfo-descriptorSetCount-00306)
```

panic:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: OutOfDeviceMemory', src/libcore/result.rs:997:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:70
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:58
             at src/libstd/panicking.rs:200
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:215
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:478
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:385
   6: rust_begin_unwind
             at src/libstd/panicking.rs:312
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   8: core::result::unwrap_failed
   9: wgpu_native::device::device_create_bind_group
  10: wgpu_device_create_bind_group
  11: wgpu::Device::create_bind_group
  12: repro::main
  13: std::rt::lang_start::{{closure}}
  14: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:297
  15: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:87
  16: std::rt::lang_start_internal
             at src/libstd/panicking.rs:276
             at src/libstd/panic.rs:388
             at src/libstd/rt.rs:48
  17: main
  18: __libc_start_main
  19: _start
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', src/libcore/result.rs:997:5
stack backtrace:
   0:     0x556ce046fa63 - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::hd71462e61ec5c76e
                               at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1:     0x556ce046b80b - std::sys_common::backtrace::_print::hae2106692f421f30
                               at src/libstd/sys_common/backtrace.rs:70
   2:     0x556ce046e7a6 - std::panicking::default_hook::{{closure}}::h4e372307f318ae92
                               at src/libstd/sys_common/backtrace.rs:58
                               at src/libstd/panicking.rs:200
   3:     0x556ce046e524 - std::panicking::default_hook::hb6f777c87029e950
                               at src/libstd/panicking.rs:215
   4:     0x556ce046ee4f - std::panicking::rust_panic_with_hook::h49d43efebcb63d45
                               at src/libstd/panicking.rs:478
   5:     0x556ce046e9d1 - std::panicking::continue_panic_fmt::h87cb4de2c26b0fa7
                               at src/libstd/panicking.rs:385
   6:     0x556ce046e8b5 - rust_begin_unwind
                               at src/libstd/panicking.rs:312
   7:     0x556ce0483ccc - core::panicking::panic_fmt::h472d766e4dff71a2
                               at src/libcore/panicking.rs:85
   8:     0x556ce037290d - core::result::unwrap_failed::hd2115df372c3da86
   9:     0x556ce036e2f2 - repro::main::{{closure}}::h3ae5630e504b926a
  10:     0x556ce036e08e - wgpu::Buffer::map_read_async::buffer_map_read_callback_wrapper::ha94371afff65eb33
  11:     0x556ce0387005 - <wgpu_native::device::Device<gfx_backend_vulkan::Backend>>::fire_map_callbacks::he02c64ffdaa3cc34
  12:     0x556ce0390878 - wgpu_device_poll
  13:     0x556ce036b24c - core::ptr::real_drop_in_place::h167f1be1b22f55b6
  14:     0x556ce036c395 - repro::main::h4c083233dcc411b0
  15:     0x556ce0370792 - std::rt::lang_start::{{closure}}::ha5b3cde100852259
  16:     0x556ce046e852 - std::panicking::try::do_call::hf75bca0b71ecc6e0
                               at src/libstd/rt.rs:49
                               at src/libstd/panicking.rs:297
  17:     0x556ce0471809 - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:87
  18:     0x556ce046f35c - std::rt::lang_start_internal::h5a74da15a365d5aa
                               at src/libstd/panicking.rs:276
                               at src/libstd/panic.rs:388
                               at src/libstd/rt.rs:48
  19:     0x556ce036c3d1 - main
  20:     0x7feb7bc73ce2 - __libc_start_main
  21:     0x556ce036b15d - _start
  22:                0x0 - <unknown>
```

**Comment by kvark** [comment]
This is quite possible with the current way descriptor pools are managed. This issue could be seen as a custom case (or dupe) of #111

**Comment by grovesNL** [comment]
Does this still occur after integration of rendy?

**Comment by rukai** [comment]
It no longer occurs after rendy integration
