### ISSUE TITLE
Swapchain creation errors on Vulkan

### ISSUE THREAD

**Issue by cpg314** [gfx-rs/wgpu#1948]
**Description**

I'm using wgpu through [bevy](https://github.com/bevyengine/bevy) , but this seems related to the former rather than the latter. 

Sporadically, the swap chain creation/configuration will fail and trigger a panic. This can be reproduced easily by leaving one of the bevy examples running for some time (10-20min on my machine), see below.

From the trace below, it seems that https://github.com/gfx-rs/wgpu/blob/v0.9/wgpu-core/src/device/mod.rs#L4550 calls https://github.com/gfx-rs/gfx/blob/hal-0.9/src/backend/vulkan/src/window.rs#L387 which calls https://github.com/gfx-rs/gfx/blob/hal-0.9/src/backend/vulkan/src/device.rs#L3076 where the `functor.create_swapchain`triggers an `UNKNOWN` error  https://github.com/gfx-rs/gfx/blob/hal-0.9/src/backend/vulkan/src/device.rs#L3127

```
[2021-09-12][19:17:15][gfx_backend_vulkan::device][ERROR] Unexpected result - driver bug? ERROR_UNKNOWN
thread 'main' panicked at 'failed to configure swap chain on creation: Swapchain can't be created for an unknown reason', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-core-0.9.2/src/device/mod.rs:4556:29
stack backtrace:
   0: rust_begin_unwind
             at /build/rust/src/rustc-1.53.0-src/library/std/src/panicking.rs:493:5
   1: std::panicking::begin_panic_fmt
             at /build/rust/src/rustc-1.53.0-src/library/std/src/panicking.rs:435:5
   2: wgpu_core::device::<impl wgpu_core::hub::Global<G>>::device_create_swap_chain
   3: <wgpu::backend::direct::Context as wgpu::Context>::device_create_swap_chain
   4: wgpu::Device::create_swap_chain
   5: <bevy_wgpu::renderer::wgpu_render_resource_context::WgpuRenderResourceContext as bevy_render::renderer::render_resource_context::RenderResourceContext>::create_swap_chain
   6: <bevy_wgpu::renderer::wgpu_render_resource_context::WgpuRenderResourceContext as bevy_render::renderer::render_resource_context::RenderResourceContext>::next_swap_chain_texture
   7: <bevy_render::render_graph::nodes::window_swapchain_node::WindowSwapChainNode as bevy_render::render_graph::node::Node>::update
   8: bevy_wgpu::renderer::wgpu_render_graph_executor::WgpuRenderGraphExecutor::execute
   9: bevy_ecs::world::World::resource_scope
  10: bevy_wgpu::get_wgpu_render_system::{{closure}}
  11: <bevy_ecs::system::exclusive_system::ExclusiveSystemFn as bevy_ecs::system::exclusive_system::ExclusiveSystem>::run
  12: <bevy_ecs::schedule::stage::SystemStage as bevy_ecs::schedule::stage::Stage>::run
  13: <bevy_ecs::schedule::Schedule as bevy_ecs::schedule::stage::Stage>::run
  14: bevy_winit::winit_runner_with::{{closure}}
  15: winit::platform_impl::platform::x11::EventLoop<T>::run_return
  16: winit::platform_impl::platform::x11::EventLoop<T>::run
  17: winit::platform_impl::platform::EventLoop<T>::run
  18: winit::event_loop::EventLoop<T>::run
  19: bevy_winit::run
  20: bevy_winit::winit_runner_with
  21: core::ops::function::Fn::call
  22: bevy_app::app::App::run
  23: sprite::main
```
That was on bevy `main` branch (wgpu 0.9). On the current release, branch `release-0.5.1` (wgpu 0.7), I get a slightly different error, also after at most ~20min:
```
thread 'main' panicked at 'internal error: entered unreachable code: Unexpected result - driver bug? Err(ERROR_INITIALIZATION_FAILED)', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx-backend-vulkan-0.7.0/src/device.rs:1953:18
stack backtrace:
   0: rust_begin_unwind
             at /build/rust/src/rustc-1.53.0-src/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /build/rust/src/rustc-1.53.0-src/library/core/src/panicking.rs:92:14
   2: gfx_backend_vulkan::device::<impl gfx_backend_vulkan::Device>::create_swapchain
   3: <gfx_backend_vulkan::window::Surface as gfx_hal::window::PresentationSurface<gfx_backend_vulkan::Backend>>::configure_swapchain
   4: wgpu_core::device::<impl wgpu_core::hub::Global<G>>::device_create_swap_chain
   5: <wgpu::backend::direct::Context as wgpu::Context>::device_create_swap_chain
   6: wgpu::Device::create_swap_chain
Sep 12 20:32:25.193 ERROR gpu_descriptor::allocator: `DescriptorAllocator` is dropped while some descriptor sets were not deallocated
[1]    601985 segmentation fault (core dumped)  cargo run --release --example sprite
```

**Repro steps**

- Get bevy on `release-0.5.1` or `main` branch.
- Run https://github.com/bevyengine/bevy/blob/latest/examples/2d/sprite.rs or one of the other examples:
`cargo run --release --example sprite`
- Wait 10-20min.
- Get a panic as above.

**Expected vs observed behavior**
Swapchain is created/configured correctly, or creation is retried so that a panic doesn't occur.

**Platform**
Archlinux x86_64
Kernel 5.12.13
AMD Ryzen 7 3700U with Radeon Vega Mobile Gfx, `amdgpu` driver
wgpu 0.7 on bevy 0.5 and wgpu 0.9 on bevy `main`

**Comment by cwfitzgerald** [comment]
Closing as this was before the wgpu-hal rewrite.
