### ISSUE TITLE
Create ```BindGroup```  with ```get_bind_group_layout``` of the pipeline occurs validation error.

### ISSUE THREAD

**Issue by jinleili** [gfx-rs/wgpu#1976]
It is convenient to create ```BindGroup```  with the ```get_bind_group_layout``` of the pipeline. 

However, if the var ```binding(index)``` within the shader is not used within the ```fn main()```, a validation error occurs during```device.create_bind_group```. Rigorous validation is good for writing good code, but inconvenient during the development phase.

wgsl shader:
```
[[group(0), binding(0)]] var<uniform> fluid: FluidUniform; 
[[group(0), binding(1)]] var dissolve_texture: texture_2d<f32>;
[[group(0), binding(2)]] var bg_texture: texture_2d<f32>;
[[group(0), binding(3)]] var sampler0: sampler;
[[group(0), binding(4)]] var sampler1: sampler;

[[stage(fragment)]]
fn main(in : VertexOutput) -> [[location(0)]] vec4<f32> {
  // trick wgpu validation
  // let trick = fluid.rho_factor;

  let dessolve: vec4<f32> = textureSample(dissolve_texture, sampler0, in.uv);
  var color: vec4<f32> = textureSample(bg_texture, sampler1, in.uv);
  if (dessolve.r > 0.005) {
    color.a = 0.0;
  }
  return color;
}
```

error log:
```
[2021-09-18T08:00:49Z ERROR wgpu::backend::direct] wgpu error: Validation Error
    
    Caused by:
        In Device::create_bind_group
        number of bindings in bind group descriptor (5) does not match the number of bindings defined in the bind group layout (4)
    
    
thread 'main' panicked at 'Handling wgpu errors as fatal by default', /Users/LiJinlei/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/e8c236c/wgpu/src/backend/direct.rs:2170:5
stack backtrace:
   0:        0x10373bff4 - std::backtrace_rs::backtrace::libunwind::trace::hd9b9204470182ffc
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:        0x10373bff4 - std::backtrace_rs::backtrace::trace_unsynchronized::hdc48b9180be04761
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x10373bff4 - std::sys_common::backtrace::_print_fmt::h8824de041faf4112
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:67:5
   3:        0x10373bff4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h8d168763f08a78b9
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:46:22
   4:        0x10375a1cc - core::fmt::write::h0fa46d4891ed63f1
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/fmt/mod.rs:1115:17
   5:        0x10373966a - std::io::Write::write_fmt::hacbf9e10e17149ce
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/io/mod.rs:1665:15
   6:        0x10373dcff - std::sys_common::backtrace::_print::h26213154a400cfbe
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:49:5
   7:        0x10373dcff - std::sys_common::backtrace::print::h0f4ab60f53d1f93b
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:36:9
   8:        0x10373dcff - std::panicking::default_hook::{{closure}}::hee7cf38dedfa76fc
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:208:50
   9:        0x10373d7fd - std::panicking::default_hook::hd12252412832a45f
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:225:9
  10:        0x10373e400 - std::panicking::rust_panic_with_hook::h521fd09e07057893
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:622:17
  11:        0x103723327 - std::panicking::begin_panic::{{closure}}::h7842ada718dd9b6b
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:542:9
  12:        0x103723278 - std::sys_common::backtrace::__rust_end_short_backtrace::heebc1daa0a718742
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:141:18
  13:        0x10376c8a5 - std::panicking::begin_panic::h2a64603b9c345f73
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:541:12
  14:        0x10329be6b - wgpu::backend::direct::default_error_handler::h7f514867ce89f40f
                               at /Users/LiJinlei/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/e8c236c/wgpu/src/backend/direct.rs:2170:5
  15:        0x10334c49b - core::ops::function::Fn::call::h711e5b7b97b330e5
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/ops/function.rs:70:5
  16:        0x10338d5f8 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h62bb8a2deea3cd52
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/alloc/src/boxed.rs:1586:9
  17:        0x10329bcdd - wgpu::backend::direct::ErrorSinkRaw::handle_error::h21cc513e86bc453c
                               at /Users/LiJinlei/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/e8c236c/wgpu/src/backend/direct.rs:2157:9
  18:        0x103291434 - wgpu::backend::direct::Context::handle_error::hb92b3ad9b80cd7ce
                               at /Users/LiJinlei/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/e8c236c/wgpu/src/backend/direct.rs:177:9
  19:        0x103296875 - <wgpu::backend::direct::Context as wgpu::Context>::device_create_bind_group::h8fcc678c89262fb1
                               at /Users/LiJinlei/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/e8c236c/wgpu/src/backend/direct.rs:1138:13
  20:        0x103345848 - wgpu::Device::create_bind_group::h781a8162fbb8be33
                               at /Users/LiJinlei/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/e8c236c/wgpu/src/lib.rs:1719:17
```

**Comment by jinleili** [comment]
[WGPU_TRACE.zip](https://github.com/gfx-rs/wgpu/files/7189555/WGPU_TRACE.zip)

**Comment by kvark** [comment]
Welcome to the world of pain with implicit bind group layouts!
The current behavior is by design. The topic was heavily discussed in https://github.com/gpuweb/gpuweb/issues/1806.
This isn't about how rigorous the validation is. If we don't validate it, we'll generate invalid API commands down the road, which is UB.
