### ISSUE TITLE
OutOfMemory error after awhile on 0.11

### ISSUE THREAD

**Issue by sotrh** [gfx-rs/wgpu#2042]
**Description**
I've started migrating to 0.11 and I've run into a snag where my code fails with an OutOfMemory error after waiting for a bit. All I'm doing is clearing the screen. My code is using winit and I'm polling for input. If there are no events the code will request a redraw. I'm using Fifo as well, but I think the code isn't actually waiting for vsync.

**Repro steps**
I have a branch with all the code [here](https://github.com/sotrh/learn-wgpu/tree/0.11). If you run `cargo run --bin tutorial2-surface` it should fail after waiting for a minute or two.

**Expected vs observed behavior**
Using Fifo should have the code block until the surface is ready to render.

**Extra materials**
Logs:
```
2021-10-09T01:01:56Z INFO  winit::platform_impl::platform::x11::window] Guessed window scale factor: 1
[2021-10-09T01:02:03Z INFO  wgpu_hal::gles::egl] Loading Wayland library to get the current display
[2021-10-09T01:02:03Z INFO  wgpu_hal::gles::egl] Loading X11 library to get the current display
[2021-10-09T01:02:03Z INFO  wgpu_hal::gles::egl] Using X11 platform
[2021-10-09T01:02:03Z INFO  wgpu_hal::gles::egl] Enabling EGL debug output
[2021-10-09T01:02:03Z INFO  wgpu_hal::gles::egl] Display vendor "Mesa Project", version (1, 4)
[2021-10-09T01:02:03Z INFO  wgpu_hal::gles::egl] 	Trying native-render
[2021-10-09T01:02:03Z INFO  wgpu_hal::gles::egl] 	EGL context: +debug KHR
[2021-10-09T01:02:03Z INFO  wgpu_hal::gles::egl] 	EGL context: +robust access EXT
[2021-10-09T01:02:03Z INFO  wgpu_hal::gles::egl] 	EGL context: +surfaceless
[2021-10-09T01:02:03Z INFO  wgpu_hal::gles::egl] 	EGL surface: +srgb khr
[2021-10-09T01:02:03Z INFO  wgpu_hal::gles::egl] Max label length: 256
[2021-10-09T01:02:03Z INFO  wgpu_hal::gles::egl] Enabling GLES debug output
[2021-10-09T01:02:03Z INFO  wgpu_hal::gles::adapter] Vendor: Intel Open Source Technology Center
[2021-10-09T01:02:03Z INFO  wgpu_hal::gles::adapter] Renderer: Mesa DRI Intel(R) HD Graphics 520 (SKL GT2)
[2021-10-09T01:02:03Z INFO  wgpu_hal::gles::adapter] Version: OpenGL ES 3.2 Mesa 20.0.8
[2021-10-09T01:02:03Z INFO  wgpu_hal::gles::adapter] SL version: OpenGL ES GLSL ES 3.20
[2021-10-09T01:02:03Z WARN  wgpu_hal::gles::adapter] Detected skylake derivative running on mesa i915. Clears to srgb textures will use manual shader clears.
[2021-10-09T01:02:03Z INFO  wgpu_core::instance] Adapter Vulkan AdapterInfo { name: "Intel(R) HD Graphics 520 (SKL GT2)", vendor: 32902, device: 6422, device_type: IntegratedGpu, backend: Vulkan }
[2021-10-09T01:02:03Z INFO  wgpu_hal::vulkan::instance] GENERAL [Loader Message (0x0)]
    	Loading layer library libVkLayer_khronos_validation.so
[2021-10-09T01:02:03Z INFO  wgpu_hal::vulkan::instance] 	objects: (type: INSTANCE, hndl: 0x5650a39e2cf0, name: ?)
[2021-10-09T01:02:03Z INFO  wgpu_hal::vulkan::instance] GENERAL [Loader Message (0x0)]
    	Inserted device layer VK_LAYER_KHRONOS_validation (libVkLayer_khronos_validation.so)
[2021-10-09T01:02:03Z INFO  wgpu_hal::vulkan::instance] 	objects: (type: INSTANCE, hndl: 0x5650a39e2cf0, name: ?)
[2021-10-09T01:02:04Z INFO  wgpu_hal::vulkan::adapter] Private capabilities: PrivateCapabilities { flip_y_requires_shift: true, imageless_framebuffers: true, image_view_usage: true, timeline_semaphores: true, texture_d24: true, texture_d24_s8: true, can_present: true, non_coherent_map_mask: 63, robust_buffer_access: true, robust_image_access: false }
[2021-10-09T01:02:04Z INFO  wgpu_core::device] configuring surface with SurfaceConfiguration { usage: RENDER_ATTACHMENT, format: Bgra8UnormSrgb, width: 800, height: 600, present_mode: Fifo }
[2021-10-09T01:02:04Z INFO  wgpu_core::device] configuring surface with SurfaceConfiguration { usage: RENDER_ATTACHMENT, format: Bgra8UnormSrgb, width: 800, height: 600, present_mode: Fifo }
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: OutOfMemory', /home/benjamin/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-core-0.11.0/src/command/render.rs:810:64
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[2021-10-09T01:04:26Z INFO  wgpu_core::hub] Dropping Global
memory allocation of 40960 bytes failed
Aborted (core dumped)
```

**Platform**
wgpu 0.11
Linux Mint

**Comment by kvark** [comment]
Running this on both a MacBook Pro and Linux (NV), I'm not able to reproduce the issue. Also, not able to see any memory growth. Do you see memory growing? Do you do anything with the app to trigger this?

**Comment by sotrh** [comment]
Let me check

**Comment by sotrh** [comment]
So the difference that I'm seeing is that "hello-triangle" doesn't call `window.request_redraw()`. The `framework.rs` module is using it, but it's using a `Spawner` struct that I'm not familiar with, as well as some manual frame rate limiting.

I wanted to test some of the other examples to see if they have the same problem I'm having, but I keep getting a "No such file or directory" error. I'm not sure what file it's referring to. Here's the command I'm running:

```bash
RUST_BACKTRACE=1 cargo r +nightly --example hello-cube
```

**Comment by sotrh** [comment]
```
RUST_BACKTRACE=1 cargo r +nightly --example cube
    Finished dev [unoptimized + debuginfo] target(s) in 0.07s
     Running `target/debug/wgpu-info +nightly --example cube`
=========== TESTING Intel(R) HD Graphics 520 (SKL GT2) on Vulkan (1 of 2) ===========
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', wgpu-info/src/main.rs:131:18
stack backtrace:
   0: rust_begin_unwind
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/panicking.rs:92:14
   2: core::option::expect_none_failed
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/option.rs:1300:5
   3: core::result::Result<T,E>::unwrap
             at /home/benjamin/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/result.rs:1037:23
   4: wgpu_info::main
             at ./wgpu-info/src/main.rs:115:31
   5: core::ops::function::FnOnce::call_once
             at /home/benjamin/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by sotrh** [comment]
This is the commit I'm on:
```
commit 47fb0efb2cba2adfc7472d0fbdbf37732afdbd99 (HEAD -> master, origin/master, origin/HEAD)
Author: Dzmitry Malyshau <kvarkus@gmail.com>
Date:   Wed Oct 13 13:42:44 2021 -0400

    ETC2 texture format refactor (#2064)
```

**Comment by sotrh** [comment]
Ok it seems like the issue is with version of wgpu that's currently on crates.io. Switching to using git fixed the issue.
