### ISSUE TITLE
Vulkan validation error on a trivial loop

### ISSUE THREAD

**Issue by terrence2** [gfx-rs/wgpu#2134]
**Description**
I am attempting to upgrade a game engine (~2000 lines glsl) from wgpu-0.7 to wgpu-0.11. Eventually I will rewrite everything into wgsl, but given the size and complexity, I was hoping to port incrementally and continue using glsl in the meantime by continuing to ship spirv in the binary.

The offending pattern appears to be writes in a loop to variables defined outside the loop body. This is almost certainly caused by some bug in naga, but the reproduction requires wgpu, so I am filing here. Please let me know if there's some better place to put this.

**Repro steps**
Cargo.toml:
```
[package]
name = "naga_spirv_loop_test"
version = "0.0.0"
edition = "2021"

[dependencies]
wgpu = { version = "^ 0.11", features = ["spirv"] }
#wgpu = { version = "^ 0.7" } # working
naga = { version = "^ 0.7", features = ["spv-in"] }
shaderc = "^ 0.7"
env_logger = "^ 0.8"
pollster = "0.2"
```

src/main.rs:
```
// Reduced from the following shader that works on wgpu-0.7:
// https://gitlab.com/terrence_too/nitrogen/-/blob/3eac23025e047fc71e4c1a0c73981e49e67764e3/libs/wgpu-buffer/atmosphere/shaders/build_scattering_density_lut.comp.glsl
const SHADER: &'static str = r"
#version 450
layout(local_size_x = 8, local_size_y = 8, local_size_z = 8) in;
layout(binding = 0, rgba32f) uniform writeonly image3D delta_scattering_density_texture;
void main() {
    vec4 tmp = vec4(0);
    for (int i = 0; i < 3; ++i) {
        tmp += vec4(1);
    }
    // The usage here keeps the compiler from deleting the body entirely.
    imageStore(
        delta_scattering_density_texture,
        ivec3(gl_GlobalInvocationID.xyz),
        tmp
    );
}
";

fn main() {
    env_logger::init();

    // Shaderc accepts the script
    let spirv_artifact = {
        use shaderc::{CompileOptions, Compiler, OptimizationLevel, ShaderKind};
        let mut options = CompileOptions::new().unwrap();
        options.set_warnings_as_errors();
        options.set_optimization_level(OptimizationLevel::Performance);
        // If we disable optimizations, the error does not occur in this test, but it does in the
        // several thousand lines of actual code linked above.
        // options.set_optimization_level(OptimizationLevel::Zero);
        let mut compiler = Compiler::new().unwrap();
        compiler
            .compile_into_spirv(
                SHADER,
                ShaderKind::Compute,
                "<input>",
                "main",
                Some(&options),
            )
            .unwrap()
    };

    // Naga can parse the generated spirv
    {
        let options = naga::front::spv::Options {
            adjust_coordinate_space: false, // we require NDC_Y_UP feature
            strict_capabilities: true,
            block_ctx_dump_prefix: None,
        };
        let parser =
            naga::front::spv::Parser::new(spirv_artifact.as_binary().iter().cloned(), &options);
        parser.parse().unwrap();
    }

    // When we use wgpu-0.11 to create a shader module with it, however...
    pollster::block_on(test_wgpu(wgpu::ShaderSource::SpirV(
        std::borrow::Cow::from(spirv_artifact.as_binary()),
    )));
}

async fn test_wgpu(source: wgpu::ShaderSource<'_>) {
    // I have only tested against the vulkan backend, in linux, on the proprietary nVidia drivers.
    let instance = wgpu::Instance::new(wgpu::Backends::VULKAN);
    let adapter = instance
        .request_adapter(&wgpu::RequestAdapterOptions::default())
        .await
        .unwrap();
    let (device, _queue) = adapter
        .request_device(
            &wgpu::DeviceDescriptor {
                label: None,
                features: wgpu::Features::empty(),
                limits: wgpu::Limits::default(),
            },
            None,
        )
        .await
        .unwrap();
    device.create_shader_module(&wgpu::ShaderModuleDescriptor {
        label: Some("naga_spirv_loop_test"),
        source,
        // flags: wgpu::ShaderFlags::empty()
    });
}
```

**Expected vs observed behavior**
Expected: no output, successful return code.
Observed:
```
╰➤ RUST_BACKTRACE=1 cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.02s
     Running `target/debug/naga_spirv_loop_test`
[2021-10-30T15:34:06Z ERROR wgpu::backend::direct] Handling wgpu errors as fatal by default
thread 'main' panicked at 'wgpu error: Validation Error

Caused by:
    In Device::create_shader_module
      note: label = `naga_spirv_loop_test`
    Function [1] '' is invalid
    Expression [17] is invalid
    Used by a statement before it was introduced into the scope by any of the dominating blocks

', /home/terrence/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.11.0/src/backend/direct.rs:2195:5
stack backtrace:
   0: rust_begin_unwind
             at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:517:5
   1: std::panicking::begin_panic_fmt
             at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:460:5
   2: wgpu::backend::direct::default_error_handler
             at /home/terrence/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.11.0/src/backend/direct.rs:2195:5
   3: core::ops::function::Fn::call
             at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/ops/function.rs:70:5
   4: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/alloc/src/boxed.rs:1650:9
   5: wgpu::backend::direct::ErrorSinkRaw::handle_error
             at /home/terrence/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.11.0/src/backend/direct.rs:2183:9
   6: wgpu::backend::direct::Context::handle_error
             at /home/terrence/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.11.0/src/backend/direct.rs:184:9
   7: <wgpu::backend::direct::Context as wgpu::Context>::device_create_shader_module
             at /home/terrence/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.11.0/src/backend/direct.rs:1020:13
   8: wgpu::Device::create_shader_module
             at /home/terrence/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.11.0/src/lib.rs:1665:17
   9: naga_spirv_loop_test::test_wgpu::{{closure}}
             at ./src/main.rs:81:5
  10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/future/mod.rs:80:19
  11: pollster::block_on
             at /home/terrence/.cargo/registry/src/github.com-1ecc6299db9ec823/pollster-0.2.4/src/lib.rs:132:15
  12: naga_spirv_loop_test::main
             at ./src/main.rs:58:5
  13: core::ops::function::FnOnce::call_once
             at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Extra materials**

**Platform**
```
╰➤ cat /etc/redhat-release 
Fedora release 34 (Thirty Four)
```

```
╰➤ lsmod | grep nvidia
nvidia_drm             69632  21
nvidia_modeset       1200128  34 nvidia_drm
nvidia              35319808  1865 nvidia_modeset
drm_kms_helper        303104  1 nvidia_drm
drm                   630784  25 drm_kms_helper,nvidia,nvidia_drm
i2c_nvidia_gpu         16384  0
```

```
╰➤ cat /proc/version 
Linux version 5.14.11-200.fc34.x86_64 (mockbuild@bkernel02.iad2.fedoraproject.org) (gcc (GCC) 11.2.1 20210728 (Red Hat 11.2.1-1), GNU ld version 2.35.2-6.fc34) #1 SMP Sun Oct 10 14:39:31 UTC 2021
```

```
╰➤ nvidia-smi 
Sat Oct 30 08:51:09 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.63.01    Driver Version: 470.63.01    CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0  On |                  N/A |
|  0%   30C    P8    21W / 250W |   1239MiB /  7979MiB |      9%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A     25313      G   /usr/libexec/Xorg                 565MiB |
|    0   N/A  N/A     25877      G   /usr/lib64/firefox/firefox        267MiB |
|    0   N/A  N/A     26026      G   /usr/lib64/firefox/firefox         71MiB |
|    0   N/A  N/A     26072      G   /usr/lib64/firefox/firefox          2MiB |
|    0   N/A  N/A     26085      G   /usr/lib64/firefox/firefox          2MiB |
|    0   N/A  N/A     28619      G   .../debug.log --shared-files       31MiB |
|    0   N/A  N/A     29578      G   ..._29458.log --shared-files       78MiB |
|    0   N/A  N/A     37999      G   ...AAAAAAAAA= --shared-files       33MiB |
|    0   N/A  N/A     77147      G   /usr/lib64/firefox/firefox        113MiB |
|    0   N/A  N/A     77270      G   /usr/lib64/firefox/firefox          2MiB |
|    0   N/A  N/A     84718      G   /usr/lib64/firefox/firefox          2MiB |
|    0   N/A  N/A     94002      G   /usr/lib64/firefox/firefox          2MiB |
|    0   N/A  N/A     94089      G   /usr/lib64/firefox/firefox          2MiB |
|    0   N/A  N/A     94501      G   /usr/lib64/firefox/firefox          2MiB |
|    0   N/A  N/A    700823      G   ...AAAAAAAAA= --shared-files       48MiB |
+-----------------------------------------------------------------------------+
```

**Comment by kvark** [comment]
Thank you for filing this detailed issue!
Generating SPIR-V from your GLSL and feeding it to Naga master seems to pass validation. What is the Naga version in your lockfile?

**Comment by terrence2** [comment]
Exactly! That's what so weird about it and why I filed it here.

When I failed to upgrade to wgpu-0.9 -- naga-0.5 couldn't quite parse all of my shaders -- I installed a canary in my build program. I just copied over the code wgpu was using. (It's actually included above under the comment `// Naga can parse the generated spirv`)

This canary went from red to green when naga-0.7.0 came out, so when I saw that the wgpu-0.11 release was using naga-0.7, I figured I was good to go. Plot twist: it was not.

The indirection where the generic backtrace re-throws means we don't have a stack to point us to the actual issue without getting a debugger involved, and I haven't set up a dev environment with the new code organization. Not that that would necessarily helps -- if I had to bet, I'd say that it's probably breaking _under_ the call to `vk::PipelineShaderStageCreateInfo::builder()...build()`.

So that's why I thought it was interesting enough to share with others. Regardless, thanks for taking a look, @kvark! I really appreciate all the work you do in this ecosystem: my modest side project wouldn't even be possible without it.

**Comment by kvark** [comment]
It would help to have the exact SPIR-V by hand that causes the failure, since you aren't feeding GLSL into Naga.
Perhaps, my incantation of `glslValidator` is doing a different kind of optimization, which seems to be important here:
>// If we disable optimizations, the error does not occur in this test, but it does in the
        // several thousand lines of actual code linked above.

A heavier weapon would be uploading an [API trace](https://github.com/gfx-rs/wgpu/wiki/Debugging-wgpu-Applications#tracing-infrastructure) here as a ZIP attachment.

Finally, if this doesn't work, sharing an example that we (or at least I) can run would be needed.

**Comment by terrence2** [comment]
Sorry, I assumed shaderrc would emit the same SPIRV everywhere. If I add a line to dump the spirv as text to the test case above I get:
```
; SPIR-V
; Version: 1.0
; Generator: Google Shaderc over Glslang; 10
; Bound: 48
; Schema: 0
               OpCapability Shader
          %1 = OpExtInstImport "GLSL.std.450"
               OpMemoryModel Logical GLSL450
               OpEntryPoint GLCompute %4 "main" %gl_GlobalInvocationID
               OpExecutionMode %4 LocalSize 8 8 8
               OpDecorate %34 DescriptorSet 0
               OpDecorate %34 Binding 0
               OpDecorate %34 NonReadable
               OpDecorate %gl_GlobalInvocationID BuiltIn GlobalInvocationId
               OpDecorate %gl_WorkGroupSize BuiltIn WorkgroupSize
       %void = OpTypeVoid
          %3 = OpTypeFunction %void
      %float = OpTypeFloat 32
    %v4float = OpTypeVector %float 4
    %float_0 = OpConstant %float 0
         %11 = OpConstantComposite %v4float %float_0 %float_0 %float_0 %float_0
        %int = OpTypeInt 32 1
      %int_0 = OpConstant %int 0
      %int_3 = OpConstant %int 3
       %bool = OpTypeBool
    %float_1 = OpConstant %float 1
         %26 = OpConstantComposite %v4float %float_1 %float_1 %float_1 %float_1
      %int_1 = OpConstant %int 1
         %32 = OpTypeImage %float 3D 0 0 0 2 Rgba32f
%_ptr_UniformConstant_32 = OpTypePointer UniformConstant %32
         %34 = OpVariable %_ptr_UniformConstant_32 UniformConstant
       %uint = OpTypeInt 32 0
     %v3uint = OpTypeVector %uint 3
%_ptr_Input_v3uint = OpTypePointer Input %v3uint
%gl_GlobalInvocationID = OpVariable %_ptr_Input_v3uint Input
      %v3int = OpTypeVector %int 3
     %uint_8 = OpConstant %uint 8
%gl_WorkGroupSize = OpConstantComposite %v3uint %uint_8 %uint_8 %uint_8
          %4 = OpFunction %void None %3
          %5 = OpLabel
               OpBranch %16
         %16 = OpLabel
         %47 = OpPhi %v4float %11 %5 %28 %17
         %46 = OpPhi %int %int_0 %5 %31 %17
         %24 = OpSLessThan %bool %46 %int_3
               OpLoopMerge %18 %17 None
               OpBranchConditional %24 %17 %18
         %17 = OpLabel
         %28 = OpFAdd %v4float %47 %26
         %31 = OpIAdd %int %46 %int_1
               OpBranch %16
         %18 = OpLabel
         %35 = OpLoad %32 %34
         %40 = OpLoad %v3uint %gl_GlobalInvocationID
         %42 = OpBitcast %v3int %40
               OpImageWrite %35 %42 %47
               OpReturn
               OpFunctionEnd
```

I'll try to set up tracing tonight, if I have some time.

**Comment by kvark** [comment]
Thank you! This allows us to see the problem now.
Calling our SPIR-V experts @jimblandy and @JCapucho . Looks like the `Emit` happens inside a loop body but used after the loop:
```
Loop {
                        body: Block {
                            body: [
                                Emit(
                                    [17..17], // <---------------------
                                ),
                                Emit(
                                    [19..20],
                                ),
                                If {
                                    condition: [20],
                                    accept: Block {
                                        body: [
                                            Continue,
                                        ],
                                        span_info: [
                                            Span {
                                                start: 0,
                                                end: 0,
                                            },
                                        ],
                                    },
                                    reject: Block {
                                        body: [
                                            Break,
                                        ],
                                        span_info: [
                                            Span {
                                                start: 0,
                                                end: 0,
                                            },
                                        ],
                                    },
                                },
                            ],
                            span_info: [
                                Span {
                                    start: 612,
                                    end: 640,
                                },
                                Span {
                                    start: 640,
                                    end: 688,
                                },
                                Span {
                                    start: 0,
                                    end: 0,
                                },
                            ],
                        },
                        continuing: Block {
                            body: [
                                Emit(
                                    [21..22],
                                ),
                                Store {
                                    pointer: [25],
                                    value: [21],
                                },
                                Store {
                                    pointer: [26],
                                    value: [22],
                                },
                            ],
                            span_info: [
                                Span {
                                    start: 728,
                                    end: 768,
                                },
                                Span {
                                    start: 0,
                                    end: 0,
                                },
                                Span {
                                    start: 0,
                                    end: 0,
                                },
                            ],
                        },
                    },
                    Emit(
                        [23..24],
                    ),
                    ImageStore {
                        image: [1],
                        coordinate: [24],
                        array_index: None,
                        value: [17], // <---------------------
                    },
                    Return {
                        value: None,
                    },
                ],
```
