### ISSUE TITLE
Remove dependency on condvar for wasm32-unknown-unknown

### ISSUE THREAD

**Issue by caiiiycuk** [gfx-rs/wgpu#2197]
I am trying to build [vanger-rs](https://github.com/kvark/vange-rs) for web. It requires to building against `wasm32-unknown-unknown`. You know that this target have many features not supported. In my wgpu even can't create context, this error happens on initialization (both in FF and chrome):
```
road.js:879 panicked at 'condvar wait not supported', library/std/src/sys/wasm/../unsupported/condvar.rs:23:9

Stack:

Error
    at imports.wbg.__wbg_new_693216e109162396 (http://127.0.0.1:8080/road.js:885:19)
    at console_error_panic_hook::Error::new::h38cd73c14ad8ceb8 (wasm://wasm/0cb2723e:wasm-function[12437]:0x366c14)
    at console_error_panic_hook::hook_impl::h447f30d6e3c844d9 (wasm://wasm/0cb2723e:wasm-function[1616]:0x1eb4de)
    at console_error_panic_hook::hook::hbe3eff4fa303ec62 (wasm://wasm/0cb2723e:wasm-function[14178]:0x37e34d)
    at core::ops::function::Fn::call::h4e6ac1b157783bd7 (wasm://wasm/0cb2723e:wasm-function[11421]:0x35714c)
    at std::panicking::rust_panic_with_hook::hf5929c1b5a08f3d9 (wasm://wasm/0cb2723e:wasm-function[2421]:0x230ad5)
    at std::panicking::begin_panic::{{closure}}::h8ff4589c5cfea805 (wasm://wasm/0cb2723e:wasm-function[15062]:0x3885b0)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h19734fc13c53f35e (wasm://wasm/0cb2723e:wasm-function[14604]:0x3837a8)
    at std::panicking::begin_panic::hf455a3f076787df0 (wasm://wasm/0cb2723e:wasm-function[15063]:0x3885dd)
    at std::sys::wasm::condvar::Condvar::wait::hc77410a0ccc911f4 (wasm://wasm/0cb2723e:wasm-function[16413]:0x3927f7)

RuntimeError: unreachable
    at __rust_start_panic (0cb2723e:0x392eb4)
    at rust_panic (0cb2723e:0x3189ee)
    at std::panicking::rust_panic_with_hook::hf5929c1b5a08f3d9 (0cb2723e:0x230afb)
    at std::panicking::begin_panic::{{closure}}::h8ff4589c5cfea805 (0cb2723e:0x3885b0)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h19734fc13c53f35e (0cb2723e:0x3837a8)
    at std::panicking::begin_panic::hf455a3f076787df0 (0cb2723e:0x3885dd)
    at std::sys::wasm::condvar::Condvar::wait::hc77410a0ccc911f4 (0cb2723e:0x3927f7)
    at std::sync::condvar::Condvar::wait::h0cd3236db5d1477a (0cb2723e:0x392aab)
    at std::sys_common::thread_parker::generic::Parker::park::hbc9ac8301fd905e0 (0cb2723e:0x1af9b3)
    at std::thread::park::hf101e8b4b1b8b456 (0cb2723e:0x31bc35)
road.js:879 panicked at 'assertion failed: `(left == right)`
  left: `true`,
 right: `false`: cannot recursively acquire mutex', library/std/src/sys/wasm/../unsupported/mutex.rs:23:9

Stack:

Error
    at imports.wbg.__wbg_new_693216e109162396 (http://127.0.0.1:8080/road.js:885:19)
    at console_error_panic_hook::Error::new::h38cd73c14ad8ceb8 (wasm://wasm/0cb2723e:wasm-function[12437]:0x366c14)
    at console_error_panic_hook::hook_impl::h447f30d6e3c844d9 (wasm://wasm/0cb2723e:wasm-function[1616]:0x1eb4de)
    at console_error_panic_hook::hook::hbe3eff4fa303ec62 (wasm://wasm/0cb2723e:wasm-function[14178]:0x37e34d)
    at core::ops::function::Fn::call::h4e6ac1b157783bd7 (wasm://wasm/0cb2723e:wasm-function[11421]:0x35714c)
    at std::panicking::rust_panic_with_hook::hf5929c1b5a08f3d9 (wasm://wasm/0cb2723e:wasm-function[2421]:0x230ad5)
    at std::panicking::begin_panic_handler::{{closure}}::h357d41682ce6f65f (wasm://wasm/0cb2723e:wasm-function[5364]:0x2c87bf)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h78451e1dd249a6ac (wasm://wasm/0cb2723e:wasm-function[14605]:0x3837d6)
    at rust_begin_unwind (wasm://wasm/0cb2723e:wasm-function[13544]:0x3761c5)
    at core::panicking::panic_fmt::h927a4041e210fb24 (wasm://wasm/0cb2723e:wasm-function[14607]:0x383844)

0cb2723e:0x230b8e Uncaught (in promise) RuntimeError: unreachable
    at std::panicking::rust_panic_with_hook::hf5929c1b5a08f3d9 (0cb2723e:0x230b8e)
    at std::panicking::begin_panic_handler::{{closure}}::h357d41682ce6f65f (0cb2723e:0x2c87bf)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h78451e1dd249a6ac (0cb2723e:0x3837d6)
    at rust_begin_unwind (0cb2723e:0x3761c5)
    at core::panicking::panic_fmt::h927a4041e210fb24 (0cb2723e:0x383844)
    at core::panicking::assert_failed::inner::ha2abe019449a2679 (0cb2723e:0x207d23)
    at core::panicking::assert_failed::h5e64d2192048a6a7 (0cb2723e:0x3039d9)
    at std::sys_common::thread_parker::generic::Parker::unpark::ha2761215bcf1f7ba (0cb2723e:0x2327ed)
    at std::thread::Thread::unpark::h0e4a13d0e9d21c15 (0cb2723e:0x348738)
    at <futures_executor::local_pool::ThreadNotify as futures_task::arc_wake::ArcWake>::wake_by_ref::h40463823281fe520 (0cb2723e:0x29a41a)
``` 

I believe this problem is somehow related to webgpu backend, because if I build project with webgl feature it initialize device successfully.

**Comment by caiiiycuk** [comment]
This happens in this code block:
```
        let adapter = task_pool
            .run_until(instance.request_adapter(&wgpu::RequestAdapterOptions {
                power_preference: wgpu::PowerPreference::HighPerformance,
                compatible_surface: Some(&surface),
                force_fallback_adapter: false,
            }))
            .expect("Unable to initialize GPU via the selected backend.");
```

**Comment by cwfitzgerald** [comment]
So the problem here is that `run_until` will block on the future completing iff there is no more work in the pool. This is when you hit the condvar. The reason it works with webgl is that webgl initialization is fully synchronous (any direct backend is "async" but it just returns a future which is `ready(adapter)`). So this is an issue of how vange-rs deals with initialization on the web, not a problem in wgpu itself.
