### ISSUE TITLE
Window temporarily hangs when resizing continuously, eventually panics

### ISSUE THREAD

**Issue by nyanpasu64** [gfx-rs/wgpu#2301]
**Description**
When I run a wgpu example program on Xfce 4 or Openbox (X11), then resize it continuously, I get validation errors, eventually followed by a panic at "Error in Surface::configure: parent device is lost".

**Repro steps**

- Clone wgpu at master (ec1d022a75898a3bc4e03589471d0ba7facc066c).
- Run an example (eg. `cargo run --example skybox`). This prints "Using NVIDIA GeForce GT 730 (Vulkan)".
- Continually resize the window, eg. drag the bottom-right corner of the window in a circle. This bug is much easier to trigger with a 1000 Hz gaming mouse than a 125 Hz office mouse.

**Expected vs observed behavior**

On Xfce and Openbox X11, while I resize, the window stops redrawing, and I get Vulkan validation errors in the terminal. On KDE X11, the window slows down drawing, but prints very few validation errors.

On Xfce and Openbox (not KWin), the window remains hung after I finish resizing, since resize events are queued up. With an office mouse, the extra time hung is around 20% of the time spent resizing. With a gaming mouse, it's around 200% of the time.

When I look in htop, while resizing, Xorg burns half a core of CPU and xfwm4/skybox burns less. When I stop resizing and leave the app hung, Xorg and skybox each burn half a CPU core.

After spending a long time continually resizing with a gaming mouse, the app panics. On Openbox, you can resize for 2 seconds, and wait >5 seconds while the app continually processes resize events before panicking. On Xfce, I got a crash after around 40 seconds of resizing (IIRC).

```
[2021-12-18T04:36:40Z ERROR wgpu_hal::vulkan::instance] VALIDATION [VUID-VkSwapchainCreateInfoKHR-imageExtent-01274 (0x7cd0911d)]
        Validation Error: [ VUID-VkSwapchainCreateInfoKHR-imageExtent-01274 ] Object 0: handle = 0x559c38b3dd98, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x7cd0911d | vkCreateSwapchainKHR() called with imageExtent = (1507,751), which is outside the bounds returned by vkGetPhysicalDeviceSurfaceCapabilitiesKHR(): currentExtent = (1230,481), minImageExtent = (1230,481), maxImageExtent = (1230,481). The Vulkan spec states: imageExtent must be between minImageExtent and maxImageExtent, inclusive, where minImageExtent and maxImageExtent are members of the VkSurfaceCapabilitiesKHR structure returned by vkGetPhysicalDeviceSurfaceCapabilitiesKHR for the surface (https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VUID-VkSwapchainCreateInfoKHR-imageExtent-01274)
[2021-12-18T04:36:40Z ERROR wgpu_hal::vulkan::instance]         objects: (type: DEVICE, hndl: 0x559c38b3dd98, name: ?)
[2021-12-18T04:36:40Z ERROR wgpu_hal::vulkan::instance] VALIDATION [VUID-VkSwapchainCreateInfoKHR-imageExtent-01274 (0x7cd0911d)]
        Validation Error: [ VUID-VkSwapchainCreateInfoKHR-imageExtent-01274 ] Object 0: handle = 0x559c38b3dd98, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x7cd0911d | vkCreateSwapchainKHR() called with imageExtent = (1471,772), which is outside the bounds returned by vkGetPhysicalDeviceSurfaceCapabilitiesKHR(): currentExtent = (1198,641), minImageExtent = (1198,641), maxImageExtent = (1198,641). The Vulkan spec states: imageExtent must be between minImageExtent and maxImageExtent, inclusive, where minImageExtent and maxImageExtent are members of the VkSurfaceCapabilitiesKHR structure returned by vkGetPhysicalDeviceSurfaceCapabilitiesKHR for the surface (https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VUID-VkSwapchainCreateInfoKHR-imageExtent-01274)
[2021-12-18T04:36:40Z ERROR wgpu_hal::vulkan::instance]         objects: (type: DEVICE, hndl: 0x559c38b3dd98, name: ?)
thread 'main' panicked at 'Error in Surface::configure: parent device is lost', wgpu/src/backend/direct.rs:214:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:517:5
   1: std::panicking::begin_panic_fmt
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:460:5
   2: wgpu::backend::direct::Context::handle_error_fatal
             at ./wgpu/src/backend/direct.rs:214:9
   3: <wgpu::backend::direct::Context as wgpu::Context>::surface_configure
             at ./wgpu/src/backend/direct.rs:921:13
   4: wgpu::Surface::configure
             at ./wgpu/src/lib.rs:3267:9
   5: skybox::framework::start::{{closure}}
             at ./wgpu/examples/skybox/../framework.rs:276:17
   6: winit::platform_impl::platform::x11::EventLoop<T>::drain_events::{{closure}}::{{closure}}
             at /home/nyanpasu64/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.26.0/src/platform_impl/linux/x11/mod.rs:419:29
   7: winit::platform_impl::platform::sticky_exit_callback
             at /home/nyanpasu64/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.26.0/src/platform_impl/linux/mod.rs:753:5
   8: winit::platform_impl::platform::x11::EventLoop<T>::drain_events::{{closure}}
             at /home/nyanpasu64/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.26.0/src/platform_impl/linux/x11/mod.rs:407:17
   9: winit::platform_impl::platform::x11::event_processor::EventProcessor<T>::process_event
             at /home/nyanpasu64/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.26.0/src/platform_impl/linux/x11/event_processor.rs:481:25
  10: winit::platform_impl::platform::x11::EventLoop<T>::drain_events
             at /home/nyanpasu64/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.26.0/src/platform_impl/linux/x11/mod.rs:406:13
  11: winit::platform_impl::platform::x11::EventLoop<T>::run_return
             at /home/nyanpasu64/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.26.0/src/platform_impl/linux/x11/mod.rs:278:13
  12: winit::platform_impl::platform::x11::EventLoop<T>::run
             at /home/nyanpasu64/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.26.0/src/platform_impl/linux/x11/mod.rs:392:9
  13: winit::platform_impl::platform::EventLoop<T>::run
             at /home/nyanpasu64/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.26.0/src/platform_impl/linux/mod.rs:669:56
  14: winit::event_loop::EventLoop<T>::run
             at /home/nyanpasu64/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.26.0/src/event_loop.rs:154:9
  15: skybox::framework::start
             at ./wgpu/examples/skybox/../framework.rs:229:5
  16: skybox::framework::run
             at ./wgpu/examples/skybox/../framework.rs:386:5
  17: skybox::main
             at ./wgpu/examples/skybox/main.rs:463:5
  18: core::ops::function::FnOnce::call_once
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

What's the issue here? Is my GPU bad and unsuited for Vulkan? Should Openbox and xfwm4 throttle the window resize events to one a frame, or discard redundant resize events while the app is backed up? Why does KWin not cause the wgpu app to hang? (I'm currently investigating and will post a comment with more info.)

Is this a wgpu or winit bug? Should wgpu or winit or etc. discard resize events when backed up? What causes the "parent device is lost" error?

**Extra materials**
Screenshots to help explain your problem.
Validation logs can be attached in case there are warnings and errors.
Zip-compressed API traces and GPU captures can also land here.

Related: https://github.com/gfx-rs/wgpu/issues/1971, https://github.com/gfx-rs/wgpu/issues/2286, https://github.com/sotrh/learn-wgpu/issues/230

**Platform**
Information about your OS, version of `wgpu`, your tech stack, etc.

Operating System: Arch Linux
Xfce Version: 4.16
Kernel Version: 5.15.7-zen1-1-zen (64-bit)
Graphics Platform: X11
Processors: 12 × AMD Ryzen 5 5600X 6-Core Processor
Memory: 15.6 GiB of RAM
Graphics Processor: NVIDIA GeForce GT 730/PCIe/SSE2
Graphics Driver: Proprietary 470.74

**Comment by nyanpasu64** [comment]
Why does KWin not cause the wgpu app to hang, and Xfce takes longer to hang than Openbox. I think it's because KWin delivers 1 or less resize event per frame, not because it discards resize events while wgpu is backed up.

## Sleeping during resizing causes events to build up even on KDE

If I edit `wgpu/examples/skybox/main.rs` and add `std::thread::sleep(std::time::Duration::from_millis(100));` to `fn resize(...)`, then after I resize the window continuously, the window remains hung (stuck sleeping) for many seconds, meaning KDE doesn't (immediately) stop sending resize events. (I'm not sure if KDE avoids sending resize events entirely, or only sends resize events if the queue size is below a limit. Given that other WMs don't seem to have any backpressure at all, my guess is that KDE has none.)

## Different window managers produce different rates of resize() calls

I modified the example to count the number of resize() calls, then tested similar mouse motions on different X11 window managers.

When I resized the app continuously for 10 seconds on kwin_x11, it counted 263 calls (<30 resizes per second). Maybe KDE is just bad on my GPU, drops frames, and/or runs at a low framerate.

On xfce, 5 seconds produced 502 resizes with a wide circle (so 100 resizes per second, though the window was quite stuttery). If I drew a smaller circle so the window was smaller during resizing, I got >760 resizes (>150 resizes per second), since Xorg/xfwm4/the app spent less time redrawing a large window, and more time picking up mouse movements.

On openbox, 1 second of continuous resizing produced 872 resizes followed by a panic, and another attempt at 1 second of continuous resizing produced 985 resizes with no panic. This indicates that Openbox passes through my mouse's 1000 Hz refresh rate as up to 1000 resize events per second.

## xtruss

I wondered if the resize messages were seen by the app immediately, or buffered on the X server. When I ran `xtruss -e events=Expose -e requests=none ./target/debug/examples/skybox 2>&1 | rg Expose`, I saw that `Expose` messages with new sizes were sent during the resize, but not afterwards while the app processes these messages.

**Comment by VarLad** [comment]
@nyanpasu64 Are you getting the same issue on the latest master?

**Comment by nyanpasu64** [comment]
I still get this issue on master 39a0256bcb98876d9138fd01f25b48fc0d62a3c0. On Linux X11 Openbox, I get endless validation errors and a panic, as before:

```
[2022-01-25T00:21:41Z ERROR wgpu_hal::vulkan::instance] VALIDATION [VUID-VkSwapchainCreateInfoKHR-imageExtent-01274 (0x7cd0911d)]
        Validation Error: [ VUID-VkSwapchainCreateInfoKHR-imageExtent-01274 ] Object 0: handle = 0x56213095a398, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x7cd0911d | vkCreateSwapchainKHR() called with imageExtent = (1455,847), which is outside the bounds returned by vkGetPhysicalDeviceSurfaceCapabilitiesKHR(): currentExtent = (1076,615), minImageExtent = (1076,615), maxImageExtent = (1076,615). The Vulkan spec states: imageExtent must be between minImageExtent and maxImageExtent, inclusive, where minImageExtent and maxImageExtent are members of the VkSurfaceCapabilitiesKHR structure returned by vkGetPhysicalDeviceSurfaceCapabilitiesKHR for the surface (https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VUID-VkSwapchainCreateInfoKHR-imageExtent-01274)
[2022-01-25T00:21:41Z ERROR wgpu_hal::vulkan::instance]         objects: (type: DEVICE, hndl: 0x56213095a398, name: ?)
[2022-01-25T00:21:41Z ERROR wgpu_hal::vulkan::instance] VALIDATION [VUID-VkSwapchainCreateInfoKHR-imageExtent-01274 (0x7cd0911d)]
        Validation Error: [ VUID-VkSwapchainCreateInfoKHR-imageExtent-01274 ] Object 0: handle = 0x56213095a398, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x7cd0911d | vkCreateSwapchainKHR() called with imageExtent = (1445,847), which is outside the bounds returned by vkGetPhysicalDeviceSurfaceCapabilitiesKHR(): currentExtent = (1076,615), minImageExtent = (1076,615), maxImageExtent = (1076,615). The Vulkan spec states: imageExtent must be between minImageExtent and maxImageExtent, inclusive, where minImageExtent and maxImageExtent are members of the VkSurfaceCapabilitiesKHR structure returned by vkGetPhysicalDeviceSurfaceCapabilitiesKHR for the surface (https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VUID-VkSwapchainCreateInfoKHR-imageExtent-01274)
[2022-01-25T00:21:41Z ERROR wgpu_hal::vulkan::instance]         objects: (type: DEVICE, hndl: 0x56213095a398, name: ?)
thread 'main' panicked at 'Error in Surface::configure: parent device is lost', wgpu/src/backend/direct.rs:214:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/core/src/panicking.rs:107:14
   2: wgpu::backend::direct::Context::handle_error_fatal
             at ./wgpu/src/backend/direct.rs:214:9
   3: <wgpu::backend::direct::Context as wgpu::Context>::surface_configure
             at ./wgpu/src/backend/direct.rs:921:13
   4: wgpu::Surface::configure
             at ./wgpu/src/lib.rs:3171:9
   5: skybox::framework::start::{{closure}}
             at ./wgpu/examples/skybox/../framework.rs:276:17
   6: winit::platform_impl::platform::x11::EventLoop<T>::drain_events::{{closure}}::{{closure}}
             at /home/nyanpasu64/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.26.0/src/platform_impl/linux/x11/mod.rs:419:29
   7: winit::platform_impl::platform::sticky_exit_callback
             at /home/nyanpasu64/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.26.0/src/platform_impl/linux/mod.rs:753:5
   8: winit::platform_impl::platform::x11::EventLoop<T>::drain_events::{{closure}}
             at /home/nyanpasu64/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.26.0/src/platform_impl/linux/x11/mod.rs:407:17
   9: winit::platform_impl::platform::x11::event_processor::EventProcessor<T>::process_event
             at /home/nyanpasu64/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.26.0/src/platform_impl/linux/x11/event_processor.rs:481:25
  10: winit::platform_impl::platform::x11::EventLoop<T>::drain_events
             at /home/nyanpasu64/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.26.0/src/platform_impl/linux/x11/mod.rs:406:13
  11: winit::platform_impl::platform::x11::EventLoop<T>::run_return
             at /home/nyanpasu64/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.26.0/src/platform_impl/linux/x11/mod.rs:278:13
  12: winit::platform_impl::platform::x11::EventLoop<T>::run
             at /home/nyanpasu64/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.26.0/src/platform_impl/linux/x11/mod.rs:392:9
  13: winit::platform_impl::platform::EventLoop<T>::run
             at /home/nyanpasu64/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.26.0/src/platform_impl/linux/mod.rs:669:56
  14: winit::event_loop::EventLoop<T>::run
             at /home/nyanpasu64/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.26.0/src/event_loop.rs:154:9
  15: skybox::framework::start
             at ./wgpu/examples/skybox/../framework.rs:229:5
  16: skybox::framework::run
             at ./wgpu/examples/skybox/../framework.rs:386:5
  17: skybox::main
             at ./wgpu/examples/skybox/main.rs:463:5
  18: core::ops::function::FnOnce::call_once
             at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

On Windows 10, 39a0256bcb98876d9138fd01f25b48fc0d62a3c0, `cargo run --example skybox`, I noticed some oddities with a 1 second sleep added in `resize()`:

When resizing the window corner, the window size updates based on the mouse position once per second, but with an extra second of latency (so 1-2 seconds of latency). **Discarding all but one mouse cursor position each second avoids the unbounded buffering** causing this crash on Linux.

- The extra second (1 frame) of latency feels undesirable to me. Can this be resolved? Is it worth fixing or not? (Possibly related: https://raphlinus.github.io/ui/graphics/2020/09/13/compositor-is-evil.html)

Interestingly, when I drag the corner to the top/bottom of my screen, Windows 10's "maximize window vertically" updates position once per second with no extra latency.

The window size updates in lockstep with the window being rerendered at the new size. I don't think this happens on X11, and I suspect it's not possible.

**Comment by inner-daemons** [comment]
I'm curious if this is still a problem.

**Comment by dimtpap** [comment]
It is. With Xwayland: 

https://github.com/user-attachments/assets/4caf0bc9-a021-4b52-ba73-4ddbb3a5126d

(It's not terminal output lag, happens with `hello_triangle` too which outputs nothing)

With Wayland I sort of ran into this here https://github.com/emilk/egui/pull/8089
