### ISSUE TITLE
Invalid uniforms in wgsl

### ISSUE THREAD

**Issue by dsmtE** [gfx-rs/wgpu#2334]
Hello everyone,

I've some trouble with running my learning test about uniforms and wgsl.

I'm learning rust by following [this](https://sotrh.github.io/learn-wgpu/beginner/tutorial6-uniforms/#uniform-buffers-and-bind-groups) tutorial and I'm trying to pass new uniforms (a vec2) .
I'm trying to use uniforms buffer to pass pixel_size to my Frament Shader, unfortunately my shader in wgsl doesn't compile, and it gave my this error and backtrace:

```shell
    Finished dev [unoptimized + debuginfo] target(s) in 1.66s
     Running `target\debug\wgpu_test.exe`
[2021-12-30T10:18:02Z ERROR wgpu::backend::direct] Handling wgpu errors as fatal by default
thread 'main' panicked at 'wgpu error: Validation Error

Caused by:
    In Device::create_shader_module
      note: label = `Simulation Shader`
    Global variable [3] 'simulation_uniforms' is invalid
    Type flags DATA | SIZED | COPY | INTERFACE | HOST_SHARED | ARGUMENT do not meet the required DATA | SIZED | COPY | HOST_SHARED | TOP_LEVEL

', C:\Users\admin\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.11.1\src\backend\direct.rs:2195:5
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c\/library\std\src\panicking.rs:517
   1: std::panicking::begin_panic_fmt
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c\/library\std\src\panicking.rs:460
   2: wgpu::backend::direct::default_error_handler
             at C:\Users\admin\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.11.1\src\backend\direct.rs:2195
   3: core::ops::function::Fn::call<void (*)(enum$<wgpu::Error>),tuple$<enum$<wgpu::Error> > >
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c\library\core\src\ops\function.rs:70
   4: alloc::boxed::impl$46::call<tuple$<enum$<wgpu::Error> >,dyn$<wgpu::UncapturedErrorHandler,assoc$<Output,tuple$<> > > >,alloc::alloc::Global>       
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c\library\alloc\src\boxed.rs:1705
   5: wgpu::backend::direct::ErrorSinkRaw::handle_error
             at C:\Users\admin\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.11.1\src\backend\direct.rs:2183
   6: wgpu::backend::direct::Context::handle_error<enum$<wgpu_core::pipeline::CreateShaderModuleError> >
             at C:\Users\admin\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.11.1\src\backend\direct.rs:184
   7: wgpu::backend::direct::impl$3::device_create_shader_module
             at C:\Users\admin\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.11.1\src\backend\direct.rs:1020
   8: wgpu::Device::create_shader_module
             at C:\Users\admin\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.11.1\src\lib.rs:1665
   9: wgpu_test::utils::state::impl$0::new::generator$0
             at .\src\utils\state.rs:86
  10: core::future::from_generator::impl$1::poll<wgpu_test::utils::state::impl$0::new::generator$0>
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c\library\core\src\future\mod.rs:80
  11: pollster::block_on<core::future::from_generator::GenFuture<wgpu_test::utils::state::impl$0::new::generator$0> >
             at C:\Users\admin\.cargo\registry\src\github.com-1ecc6299db9ec823\pollster-0.2.4\src\lib.rs:132
  12: wgpu_test::main
             at .\src\main.rs:17
  13: core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c\library\core\src\ops\function.rs:227
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: process didn't exit successfully: `target\debug\wgpu_test.exe` (exit code: 101)
```

After some research, I am unable to find why and how to solve this error. Can you help me ?

My shader : 
```glsl
struct VertexOutput {
    [[builtin(position)]] clip_position: vec4<f32>;
    [[location(0)]] uv: vec2<f32>;
};

var<private> positions: array<vec2<f32>, 3> = array<vec2<f32>, 3>(
    vec2<f32>(-1.0, -1.0),
    vec2<f32>(3.0, -1.0),
    vec2<f32>(-1.0, 3.0)
);

[[stage(vertex)]]
fn vs_main([[builtin(vertex_index)]] in_vertex_index: u32) -> VertexOutput {
    var out: VertexOutput;
    out.clip_position = vec4<f32>(positions[in_vertex_index], 0.0, 1.0);
    out.uv = (out.clip_position.xy+vec2<f32>(1.0))/vec2<f32>(2.0);
    return out;
}

struct SimulationUniforms {
    // pixel_size: vec2<f32>;
    pixel_width: f32;
    pixel_height: f32;
};

[[group(0), binding(0)]] var simulation_texture: texture_2d<f32>;
[[group(0), binding(1)]] var simulation_tex_sampler: sampler;

[[group(1), binding(0)]]
var<uniform> simulation_uniforms: SimulationUniforms;

[[stage(fragment)]]
fn fs_main(in: VertexOutput) -> [[location(0)]] vec4<f32> {
    var val: f32 = textureSample(simulation_texture, simulation_tex_sampler, in.uv ).x;
    val = val + 0.01;
    
    if (val > 1.0) { val = 0.0; }
    return vec4<f32>(val, val, val, 1.0);
}
```

And my buffer struct and initialization:
```rust
use wgpu::util::DeviceExt;

#[repr(C)]
#[derive(Debug, Copy, Clone, bytemuck::Pod, bytemuck::Zeroable)]
struct SimulationUniforms {
    // pixel_size: [f32; 2],
    pixel_width: f32,
    pixel_height: f32,
}

impl SimulationUniforms {
    pub fn new(simulation_size : &[u32; 2]) -> Self {
        Self {
            // pixel_size: simulation_size.map(|x| 1.0 / x as f32),
            pixel_width: 1.0,
            pixel_height: 1.0,
        }
    }
}

pub struct SimulationData {
    uniform: SimulationUniforms,
    buffer: wgpu::Buffer,
    pub bind_group_layout: wgpu::BindGroupLayout,
    pub bind_group: wgpu::BindGroup,
}

impl SimulationData {

    pub fn new(device: &wgpu::Device, simulation_size : &[u32; 2]) -> Self {
        
        let uniform = SimulationUniforms::new(&simulation_size);

        let buffer = device.create_buffer_init(&wgpu::util::BufferInitDescriptor {
            label: Some("Simulation uniforms Buffer"),
            contents: bytemuck::cast_slice(&[uniform]),
            usage: wgpu::BufferUsages::UNIFORM,
        });

        let bind_group_layout = device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {
            entries: &[
                wgpu::BindGroupLayoutEntry {
                    binding: 0,
                    visibility: wgpu::ShaderStages::FRAGMENT,
                    ty: wgpu::BindingType::Buffer {
                        ty: wgpu::BufferBindingType::Uniform,
                        has_dynamic_offset: false,
                        min_binding_size: None,
                    },
                    count: None,
                }
            ],
            label: Some("simulation uniforms bind group layout"),
        });

        let bind_group = device.create_bind_group(&wgpu::BindGroupDescriptor {
        layout: &bind_group_layout,
        entries: &[
            wgpu::BindGroupEntry {
                binding: 0,
                resource: buffer.as_entire_binding(),
            }
        ],
        label: Some("Simulation uniforms bind group"),
        });

        Self {
            uniform,
            buffer,
            bind_group_layout,
            bind_group,
        }
    }
}
```

and usage:
```rust
let simulation_render_pipeline = device.create_render_pipeline(&wgpu::RenderPipelineDescriptor {
            label: Some("Simulation Render Pipeline"),
            layout: Some(&device.create_pipeline_layout(&wgpu::PipelineLayoutDescriptor {
                label: Some("Simulation Pipeline Layout"),
                bind_group_layouts: &[&simulation_textures.bind_group_layout, &simulation_uniforms.bind_group_layout],
                push_constant_ranges: &[],
            })),
            vertex: wgpu::VertexState {
                module: &screen_shader,
                entry_point: "vs_main",
                buffers: &[],
            },
            fragment: Some(wgpu::FragmentState {
                module: &simulation_shader,
                entry_point: "fs_main",
                targets: &[wgpu::ColorTargetState {
                    format: config.format,
                    blend: Some(wgpu::BlendState::REPLACE),
                    write_mask: wgpu::ColorWrites::ALL,
                }],
            }),
            primitive: primitive_state,
            depth_stencil: None,
            multisample: multisample_state
});
       
(...)

{
            let mut simulation_render_pass = encoder.begin_render_pass(&wgpu::RenderPassDescriptor {
                label: Some("Simulation Render Pass"),
                color_attachments: &[
                    wgpu::RenderPassColorAttachment {
                    view: self.simulation_textures.get_target_texture_view(),
                    resolve_target: None,
                    ops: wgpu::Operations {
                        load: wgpu::LoadOp::Clear(self.clear_color),
                        store: true,
                    },
                }],
                depth_stencil_attachment: None,
            });
            
            simulation_render_pass.set_pipeline(&self.simulation_render_pipeline);
            simulation_render_pass.set_bind_group(0, self.simulation_textures.get_rendered_bind_group(), &[]);
            simulation_render_pass.set_bind_group(1, &self.simulation_uniforms.bind_group, &[]);
            simulation_render_pass.draw(0..3, 0..1);
        }
```

I can share my whole test and project to reproduce my uniform error if needed.
I'm on Windows 10.

Thanks in advance.

**Comment by kvark** [comment]
You are using wgpu-0.11 perhaps? And with the new WGSL syntax (lack of `[[block]]`) that didn't exist in 0.11.
So just update to wgpu-0.12 and you should be good.

**Comment by dsmtE** [comment]
Thanks so much @kvark.

I am a beginner and still learning rust. Sorry, I had the wrong version (wgpu-0.11) and was looking at a tutorial and documentation that was not the right one.

 I'm a bit confusing about cargo and version management, but I finally make it work after update to wgpu-0.12.
