### ISSUE TITLE
halmark example panics when I maximize the window

### ISSUE THREAD

**Issue by stephengtuggy** [gfx-rs/wgpu#2349]
**Description**
When I run the `halmark` example and try to maximize the window, the example application crashes.

**Repro steps**
Follow the instructions from the README for running the examples; run `halmark` specifically, with `cargo run --example halmark`, and try maximizing the window.

**Expected vs observed behavior**
The example application should keep running. Instead, it crashes, with a message that the main thread panicked.

**Extra materials**
Stack backtrace:
```
    Finished dev [unoptimized + debuginfo] target(s) in 0.06s
     Running `target/debug/examples/halmark`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Outdated', wgpu-hal/examples/halmark/main.rs:710:64
stack backtrace:
   0: rust_begin_unwind
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:517:5
   1: core::panicking::panic_fmt
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:100:14
   2: core::result::unwrap_failed
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/result.rs:1616:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/result.rs:1298:23
   4: halmark::Example<A>::render
             at ./wgpu-hal/examples/halmark/main.rs:710:13
   5: halmark::main::{{closure}}
             at ./wgpu-hal/examples/halmark/main.rs:819:17
   6: winit::platform_impl::platform::sticky_exit_callback
             at /home/stephengt/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.26.0/src/platform_impl/linux/mod.rs:753:5
   7: winit::platform_impl::platform::x11::EventLoop<T>::run_return
             at /home/stephengt/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.26.0/src/platform_impl/linux/x11/mod.rs:310:21
   8: winit::platform_impl::platform::x11::EventLoop<T>::run
             at /home/stephengt/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.26.0/src/platform_impl/linux/x11/mod.rs:392:9
   9: winit::platform_impl::platform::EventLoop<T>::run
             at /home/stephengt/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.26.0/src/platform_impl/linux/mod.rs:669:56
  10: winit::event_loop::EventLoop<T>::run
             at /home/stephengt/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.26.0/src/event_loop.rs:154:9
  11: halmark::main
             at ./wgpu-hal/examples/halmark/main.rs:780:5
  12: core::ops::function::FnOnce::call_once
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Platform**
OS: Manjaro Linux XFCE, fully updated as of this morning
wgpu version: latest (just checked out today)
Graphics card: NVidia GeForce GTX 1050Ti
Graphics back end: Vulkan
CPU: Intel Core i5 8th-generation, 6 cores x 3.0 GHz
Motherboard: Gigabyte H370M-DS3H
64 GB RAM

**Comment by cwfitzgerald** [comment]
Halmark intentionally does not deal with resizing properly. I'm going to close this as wontfix, as halmark likely won't see major improvements.
