### ISSUE TITLE
panicked at 'Error in Surface::get_preferred_format: no suitable format found' with llvmpipe

### ISSUE THREAD

**Issue by parasyte** [gfx-rs/wgpu#2397]
**Description**

I'm using `wgpu` in Windows 11 + WSL2 + Ubuntu 20.04. `wgpu` prefers Vulkan over GL (but WSL only has hardware acceleration with GL). When I run my app with Vulkan (i.e., the default backend) I get this panic:

```
[2022-01-16T23:01:53Z INFO  wgpu_core::instance] Adapter Vulkan AdapterInfo { name: "llvmpipe (LLVM 13.0.0, 256 bits)", vendor: 65541, device: 0, device_type: Cpu, backend: Vulkan }
WARNING: lavapipe is not a conformant vulkan implementation, testing use only.
thread 'main' panicked at 'Error in Surface::get_preferred_format: no suitable format found', /home/jay/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.12.0/src/backend/direct.rs:214:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/207c80f105282245d93024c95ac408c622f70114/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/207c80f105282245d93024c95ac408c622f70114/library/core/src/panicking.rs:107:14
   2: wgpu::backend::direct::Context::handle_error_fatal
             at /home/jay/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.12.0/src/backend/direct.rs:214:9
   3: <wgpu::backend::direct::Context as wgpu::Context>::surface_get_preferred_format
             at /home/jay/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.12.0/src/backend/direct.rs:907:25
   4: wgpu::Surface::get_preferred_format
             at /home/jay/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.12.0/src/lib.rs:3257:9
   5: pixels::builder::PixelsBuilder<W>::build_impl::{{closure}}::{{closure}}
             at ./src/builder.rs:271:13
   6: core::option::Option<T>::unwrap_or_else
             at /rustc/207c80f105282245d93024c95ac408c622f70114/library/core/src/option.rs:787:21
   7: pixels::builder::PixelsBuilder<W>::build_impl::{{closure}}
             at ./src/builder.rs:270:38
   8: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/207c80f105282245d93024c95ac408c622f70114/library/core/src/future/mod.rs:80:19
   9: pollster::block_on
             at /home/jay/.cargo/registry/src/github.com-1ecc6299db9ec823/pollster-0.2.4/src/lib.rs:132:15
  10: pixels::builder::PixelsBuilder<W>::build
             at ./src/builder.rs:333:9
  11: pixels::Pixels::new
             at ./src/lib.rs:200:9
  12: minimal_winit::main
             at ./examples/minimal-winit/src/main.rs:41:9
  13: core::ops::function::FnOnce::call_once
             at /rustc/207c80f105282245d93024c95ac408c622f70114/library/core/src/ops/function.rs:227:5
```

**Repro steps**

Repro with [`pixels`](https://github.com/parasyte/pixels) in WSL2 (Windows 11 and Ubuntu 20.04 with updated Mesa. See https://github.com/gfx-rs/wgpu/issues/2213#issuecomment-1013965380):

```bash
$ RUST_BACKTRACE=1 RUST_LOG='wgpu_core::instance=info' cargo run --package minimal-winit
```

**Expected vs observed behavior**

`Surface::get_preferred_format` returns `Option<_>`. I would like to get `None` in this environment instead of a panic:

https://github.com/gfx-rs/wgpu/blob/f345628a9a2690f9cefe07d713d36bd3e7d7c1e5/wgpu/src/backend/direct.rs#L907

Unfortunately, patching this just results in another error:

```
Error in Surface::configure: requested format Bgra8UnormSrgb is not in list of supported formats: []
```

**Extra materials**

 I can work around this issue by using X11, e.g. setting the env var `WINIT_UNIX_BACKEND=x11`.

<details><summary><code>wgpu-info</code> output</summary>

```
Adapter 0:
        Backend:   Vulkan
        Name:      "llvmpipe (LLVM 13.0.0, 256 bits)"
        VendorID:  65541
        DeviceID:  0
        Type:      Cpu
        Compliant: true
        Features:
                DEPTH_CLIP_CONTROL:                                             true
                TEXTURE_COMPRESSION_BC:                                         true
                INDIRECT_FIRST_INSTANCE:                                        true
                TIMESTAMP_QUERY:                                                true
                PIPELINE_STATISTICS_QUERY:                                      true
                MAPPABLE_PRIMARY_BUFFERS:                                       true
                TEXTURE_BINDING_ARRAY:                                          false
                BUFFER_BINDING_ARRAY:                                           true
                STORAGE_RESOURCE_BINDING_ARRAY:                                 true
                SAMPLED_TEXTURE_AND_STORAGE_BUFFER_ARRAY_NON_UNIFORM_INDEXING:  false
                UNIFORM_BUFFER_AND_STORAGE_TEXTURE_ARRAY_NON_UNIFORM_INDEXING:  false
                PARTIALLY_BOUND_BINDING_ARRAY:                                  false
                UNSIZED_BINDING_ARRAY:                                          false
                MULTI_DRAW_INDIRECT:                                            true
                MULTI_DRAW_INDIRECT_COUNT:                                      true
                PUSH_CONSTANTS:                                                 true
                ADDRESS_MODE_CLAMP_TO_BORDER:                                   true
                POLYGON_MODE_LINE:                                              true
                POLYGON_MODE_POINT:                                             true
                TEXTURE_COMPRESSION_ETC2:                                       false
                TEXTURE_COMPRESSION_ASTC_LDR:                                   false
                TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES:                       true
                SHADER_FLOAT64:                                                 true
                VERTEX_ATTRIBUTE_64BIT:                                         false
                CONSERVATIVE_RASTERIZATION:                                     false
                VERTEX_WRITABLE_STORAGE:                                        true
                CLEAR_TEXTURE:                                                  true
                SPIRV_SHADER_PASSTHROUGH:                                       true
                SHADER_PRIMITIVE_INDEX:                                         true
                MULTIVIEW:                                                      true
                TEXTURE_FORMAT_16BIT_NORM:                                      true
                ADDRESS_MODE_CLAMP_TO_ZERO:                                     true
        Limits:
                Max Texture Dimension 1d:                        16384
                Max Texture Dimension 2d:                        16384
                Max Texture Dimension 3d:                        4096
                Max Texture Array Layers:                        2048
                Max Bind Groups:                                 8
                Max Dynamic Uniform Buffers Per Pipeline Layout: 256
                Max Dynamic Storage Buffers Per Pipeline Layout: 256
                Max Sampled Textures Per Shader Stage:           128
                Max Samplers Per Shader Stage:                   32
                Max Storage Buffers Per Shader Stage:            16
                Max Storage Textures Per Shader Stage:           16
                Max Uniform Buffers Per Shader Stage:            15
                Max Uniform Buffer Binding Size:                 65536
                Max Storage Buffer Binding Size:                 134217728
                Max Vertex Buffers:                              16
                Max Vertex Attributes:                           32
                Max Vertex Buffer Array Stride:                  2048
                Max Push Constant Size:                          128
                Min Uniform Buffer Offset Alignment:             16
                Min Storage Buffer Offset Alignment:             16
                Max Inter-Stage Shader Component:                128
                Max Compute Workgroup Storage Size:              32768
                Max Compute Invocations Per Workgroup:           1024
                Max Compute Workgroup Size X:                    1024
                Max Compute Workgroup Size Y:                    1024
                Max Compute Workgroup Size Z:                    1024
                Max Compute Workgroups Per Dimension:            65535
        Downlevel Properties:
                Shader Model:                        Sm5
                COMPUTE_SHADERS:                     true
                FRAGMENT_WRITABLE_STORAGE:           true
                INDIRECT_EXECUTION:                  true
                BASE_VERTEX:                         true
                READ_ONLY_DEPTH_STENCIL:             true
                DEVICE_LOCAL_IMAGE_COPIES:           true
                NON_POWER_OF_TWO_MIPMAPPED_TEXTURES: true
                CUBE_ARRAY_TEXTURES:                 true
                COMPARISON_SAMPLERS:                 true
                INDEPENDENT_BLENDING:                true
                VERTEX_STORAGE:                      true
                ANISOTROPIC_FILTERING:               true
                FRAGMENT_STORAGE:                    true
Adapter 1:
        Backend:   Gl
        Name:      "D3D12 (NVIDIA GeForce RTX 3090)"
        VendorID:  0
        DeviceID:  0
        Type:      DiscreteGpu
        Compliant: false
        Features:
                DEPTH_CLIP_CONTROL:                                             true
                TEXTURE_COMPRESSION_BC:                                         false
                INDIRECT_FIRST_INSTANCE:                                        false
                TIMESTAMP_QUERY:                                                false
                PIPELINE_STATISTICS_QUERY:                                      false
                MAPPABLE_PRIMARY_BUFFERS:                                       false
                TEXTURE_BINDING_ARRAY:                                          false
                BUFFER_BINDING_ARRAY:                                           false
                STORAGE_RESOURCE_BINDING_ARRAY:                                 false
                SAMPLED_TEXTURE_AND_STORAGE_BUFFER_ARRAY_NON_UNIFORM_INDEXING:  false
                UNIFORM_BUFFER_AND_STORAGE_TEXTURE_ARRAY_NON_UNIFORM_INDEXING:  false
                PARTIALLY_BOUND_BINDING_ARRAY:                                  false
                UNSIZED_BINDING_ARRAY:                                          false
                MULTI_DRAW_INDIRECT:                                            false
                MULTI_DRAW_INDIRECT_COUNT:                                      false
                PUSH_CONSTANTS:                                                 false
                ADDRESS_MODE_CLAMP_TO_BORDER:                                   true
                POLYGON_MODE_LINE:                                              false
                POLYGON_MODE_POINT:                                             false
                TEXTURE_COMPRESSION_ETC2:                                       true
                TEXTURE_COMPRESSION_ASTC_LDR:                                   true
                TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES:                       true
                SHADER_FLOAT64:                                                 false
                VERTEX_ATTRIBUTE_64BIT:                                         false
                CONSERVATIVE_RASTERIZATION:                                     false
                VERTEX_WRITABLE_STORAGE:                                        false
                CLEAR_TEXTURE:                                                  true
                SPIRV_SHADER_PASSTHROUGH:                                       false
                SHADER_PRIMITIVE_INDEX:                                         false
                MULTIVIEW:                                                      false
                TEXTURE_FORMAT_16BIT_NORM:                                      false
                ADDRESS_MODE_CLAMP_TO_ZERO:                                     true
        Limits:
                Max Texture Dimension 1d:                        16384
                Max Texture Dimension 2d:                        16384
                Max Texture Dimension 3d:                        1024
                Max Texture Array Layers:                        16384
                Max Bind Groups:                                 8
                Max Dynamic Uniform Buffers Per Pipeline Layout: 12
                Max Dynamic Storage Buffers Per Pipeline Layout: 0
                Max Sampled Textures Per Shader Stage:           16
                Max Samplers Per Shader Stage:                   16
                Max Storage Buffers Per Shader Stage:            0
                Max Storage Textures Per Shader Stage:           0
                Max Uniform Buffers Per Shader Stage:            12
                Max Uniform Buffer Binding Size:                 65536
                Max Storage Buffer Binding Size:                 0
                Max Vertex Buffers:                              16
                Max Vertex Attributes:                           16
                Max Vertex Buffer Array Stride:                  4294967295
                Max Push Constant Size:                          0
                Min Uniform Buffer Offset Alignment:             256
                Min Storage Buffer Offset Alignment:             256
                Max Inter-Stage Shader Component:                128
                Max Compute Workgroup Storage Size:              0
                Max Compute Invocations Per Workgroup:           0
                Max Compute Workgroup Size X:                    0
                Max Compute Workgroup Size Y:                    0
                Max Compute Workgroup Size Z:                    0
                Max Compute Workgroups Per Dimension:            0
        Downlevel Properties:
                Shader Model:                        Sm5
                COMPUTE_SHADERS:                     false
                FRAGMENT_WRITABLE_STORAGE:           false
                INDIRECT_EXECUTION:                  false
                BASE_VERTEX:                         false
                READ_ONLY_DEPTH_STENCIL:             false
                DEVICE_LOCAL_IMAGE_COPIES:           true
                NON_POWER_OF_TWO_MIPMAPPED_TEXTURES: true
                CUBE_ARRAY_TEXTURES:                 true
                COMPARISON_SAMPLERS:                 true
                INDEPENDENT_BLENDING:                true
                VERTEX_STORAGE:                      false
                ANISOTROPIC_FILTERING:               false
                FRAGMENT_STORAGE:                    false
```
</details>

**Platform**

- Host OS: Windows 11
- VM: WSL2
- Guest OS: Ubuntu 20.04

**Comment by kvark** [comment]
Interesting! So lavapipe doesn't support any of the formats WebGPU spec considers mandatory:
```rust
let preferred_formats = [
            wgt::TextureFormat::Bgra8UnormSrgb,
            wgt::TextureFormat::Rgba8UnormSrgb,
            wgt::TextureFormat::Bgra8Unorm,
            wgt::TextureFormat::Rgba8Unorm,
        ];
```

**Comment by kvark** [comment]
It would be interesting to see what this code returns on lavapipe:
```rust
adapter
                .raw
                .adapter
                .surface_capabilities(&suf.raw)
```
It's ran inside `get_preferred_format()`

**Comment by parasyte** [comment]
That returns:

```
[/home/jay/other-projects/wgpu/wgpu-core/src/instance.rs:205] adapter.raw.adapter.surface_capabilities(&suf.raw) = Some(
    SurfaceCapabilities {
        formats: [],
        swap_chain_sizes: 4..=4294967295,
        current_extent: None,
        extents: Extent3d {
            width: 1,
            height: 1,
            depth_or_array_layers: 1,
        }..=Extent3d {
            width: 16384,
            height: 16384,
            depth_or_array_layers: 1,
        },
        usage: COPY_SRC | COPY_DST | RESOURCE | COLOR_TARGET | STORAGE_READ | STORAGE_WRITE,
        present_modes: [
            Mailbox,
            Fifo,
        ],
        composite_alpha_modes: [
            Opaque,
            PreMultiplied,
        ],
    },
)
```

Empty formats. 🤷

**Comment by parasyte** [comment]
And when forcing X11:

```
[/home/jay/other-projects/wgpu/wgpu-core/src/instance.rs:205] adapter.raw.adapter.surface_capabilities(&suf.raw) = Some(
    SurfaceCapabilities {
        formats: [
            Bgra8Unorm,
            Bgra8UnormSrgb,
        ],
        swap_chain_sizes: 3..=4294967295,
        current_extent: Some(
            Extent3d {
                width: 347,
                height: 260,
                depth_or_array_layers: 1,
            },
        ),
        extents: Extent3d {
            width: 347,
            height: 260,
            depth_or_array_layers: 1,
        }..=Extent3d {
            width: 347,
            height: 260,
            depth_or_array_layers: 1,
        },
        usage: COPY_SRC | COPY_DST | RESOURCE | COLOR_TARGET | STORAGE_READ | STORAGE_WRITE,
        present_modes: [
            Immediate,
            Mailbox,
            Fifo,
        ],
        composite_alpha_modes: [
            Opaque,
        ],
    },
)
```

**Comment by parasyte** [comment]
I dug into Mesa, and this is clearly their bug.

- The formats are added here with the `opaque` flag set to false (why?): https://gitlab.freedesktop.org/mesa/mesa/-/blob/mesa-21.3.4/src/vulkan/wsi/wsi_common_wayland.c#L360-367
- When formats are queried, they skip ones which are not capable of both alpha and opaque rendering: https://gitlab.freedesktop.org/mesa/mesa/-/blob/mesa-21.3.4/src/vulkan/wsi/wsi_common_wayland.c#L776-781

Patching Mesa to enable the `opaque` flag on these formats makes it work:

```
[/home/jay/other-projects/wgpu/wgpu-core/src/instance.rs:205] adapter.raw.adapter.surface_capabilities(&suf.raw) = Some(
    SurfaceCapabilities {
        formats: [
            Bgra8Unorm,
            Bgra8UnormSrgb,
        ],
        swap_chain_sizes: 4..=4294967295,
        current_extent: None,
        extents: Extent3d {
            width: 1,
            height: 1,
            depth_or_array_layers: 1,
        }..=Extent3d {
            width: 16384,
            height: 16384,
            depth_or_array_layers: 1,
        },
        usage: COPY_SRC | COPY_DST | RESOURCE | COLOR_TARGET | STORAGE_READ | STORAGE_WRITE,
        present_modes: [
            Mailbox,
            Fifo,
        ],
        composite_alpha_modes: [
            Opaque,
            PreMultiplied,
        ],
    },
)
```

**Comment by kvark** [comment]
That's a very high quality investigation, kudos for pushing this forward!
For my reference, the relevant spec text is:
> The number of format pairs supported must be greater than or equal to 1. pSurfaceFormats must not contain an entry whose value for format is VK_FORMAT_UNDEFINED.

**Comment by parasyte** [comment]
This should be fixed in the next Mesa release. https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/14588 was merged 🎉
