### ISSUE TITLE
Cannot run examples with RenderDoc on Linux

### ISSUE THREAD

**Issue by KeKsBoTer** [gfx-rs/wgpu#2486]
**Description**
Running the cube example (and also other examples) with RenderDoc on Linux (amdgpu) raises an exception.

**Repro steps**
Build the cube example and run the executable with RenderDoc.

**Expected vs observed behavior**
Expected: The example runs.
But error is thrown:
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', wgpu-core/src/hub.rs:996:33
stack backtrace:
   0: rust_begin_unwind
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panicking.rs:107:14
   2: core::panicking::panic
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panicking.rs:48:5
   3: core::option::Option<T>::unwrap
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/option.rs:746:21
   4: <wgpu_hal::vulkan::Api as wgpu_core::hub::HalApi>::get_surface
             at /home/simon/Projects/wgpu/wgpu-core/src/hub.rs:996:9
   5: wgpu_core::instance::<impl wgpu_core::hub::Global<G>>::request_adapter::gather
             at /home/simon/Projects/wgpu/wgpu-core/src/instance.rs:665:40
   6: wgpu_core::instance::<impl wgpu_core::hub::Global<G>>::request_adapter
             at /home/simon/Projects/wgpu/wgpu-core/src/instance.rs:690:40
   7: <wgpu::backend::direct::Context as wgpu::Context>::instance_request_adapter
             at /home/simon/Projects/wgpu/wgpu/src/backend/direct.rs:812:18
   8: wgpu::Instance::request_adapter
             at /home/simon/Projects/wgpu/wgpu/src/lib.rs:1468:23
   9: cube::framework::setup::{{closure}}
             at /home/simon/Projects/wgpu/wgpu/examples/cube/../framework.rs:137:19
  10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/future/mod.rs:80:19
  11: pollster::block_on
             at /home/simon/.cargo/registry/src/github.com-1ecc6299db9ec823/pollster-0.2.4/src/lib.rs:132:15
  12: cube::framework::run
             at /home/simon/Projects/wgpu/wgpu/examples/cube/../framework.rs:393:17
  13: cube::main
             at /home/simon/Projects/wgpu/wgpu/examples/cube/main.rs:400:5
  14: core::ops::function::FnOnce::call_once
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Platform**
Linux (Ubuntu 21.10)
wgpu (0.12.0)
RenderDoc 1.18

**Comment by kvark** [comment]
This isn't really wgpu-0.12, is it? https://github.com/gfx-rs/wgpu/blob/v0.12/wgpu-core/src/hub.rs#L996 doesn't have this panic.

**Comment by kvark** [comment]
Ok, in wgpu master this is accessing the Vulkan surface, which isn't there.

**Comment by KeKsBoTer** [comment]
Oh sorry, I checked out master.
Here is the trace for v.0.12 (almost the same):
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', wgpu-core/src/hub.rs:960:33
stack backtrace:
   0: rust_begin_unwind
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panicking.rs:107:14
   2: core::panicking::panic
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panicking.rs:48:5
   3: core::option::Option<T>::unwrap
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/option.rs:746:21
   4: <wgpu_hal::vulkan::Api as wgpu_core::hub::HalApi>::get_surface
             at /home/simon/Projects/wgpu/wgpu-core/src/hub.rs:960:9
   5: wgpu_core::instance::<impl wgpu_core::hub::Global<G>>::request_adapter::gather
             at /home/simon/Projects/wgpu/wgpu-core/src/instance.rs:630:40
   6: wgpu_core::instance::<impl wgpu_core::hub::Global<G>>::request_adapter
             at /home/simon/Projects/wgpu/wgpu-core/src/instance.rs:655:40
   7: <wgpu::backend::direct::Context as wgpu::Context>::instance_request_adapter
             at /home/simon/Projects/wgpu/wgpu/src/backend/direct.rs:795:18
   8: wgpu::Instance::request_adapter
             at /home/simon/Projects/wgpu/wgpu/src/lib.rs:1473:23
   9: cube::framework::setup::{{closure}}
             at /home/simon/Projects/wgpu/wgpu/examples/cube/../framework.rs:137:19
  10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/future/mod.rs:80:19
  11: pollster::block_on
             at /home/simon/.cargo/registry/src/github.com-1ecc6299db9ec823/pollster-0.2.4/src/lib.rs:132:15
  12: cube::framework::run
             at /home/simon/Projects/wgpu/wgpu/examples/cube/../framework.rs:393:17
  13: cube::main
             at /home/simon/Projects/wgpu/wgpu/examples/cube/main.rs:400:5
  14: core::ops::function::FnOnce::call_once
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```

**Comment by kvark** [comment]
Does renderdoc log contain anything interesting? FWIW, we've been actively using RenderDoc without seeing anything like this.

**Comment by fintelia** [comment]
The problem might be that RenderDoc [doesn't support Wayland](https://github.com/baldurk/renderdoc/issues/853). I've found that I have to set the `WINIT_UNIX_BACKEND` environment variable to `x11` to work around it. Does that fix things?

**Comment by KeKsBoTer** [comment]
@fintelia It solved the problem. Thank you very much!
