### ISSUE TITLE
Entered unreachable code by use of booleans in shader code

### ISSUE THREAD

**Issue by Denis-Pe** [gfx-rs/wgpu#2798]
**Description**
I am trying to use a boolean in a fragment shader, but I end up entering unreachable code.

The error says
thread 'main' panicked at 'internal error: entered unreachable code', .cargo\registry\src\github.com-1ecc6299db9ec823\naga-0.8.5\src\back\hlsl\conv.rs:9:27

The unreachable code being this guy inside the impl ScalarKind block
```rust
    pub(super) fn to_hlsl_cast(self) -> &'static str {
        match self {
            Self::Float => "asfloat",
            Self::Sint => "asint",
            Self::Uint => "asuint",
            Self::Bool => unreachable!(),
        }
    }
```

**Repro steps**
What I am doing in my shader looks like this:

```rust
struct Foo {
    bar: array<bool>;
};

[[group(x), binding(y)]]
var<storage, read_write> foo: Foo;

[[stage(fragment)]]
fn fragment_shader(stuff) -> [[location(0)]] vec4<f32> {
    let boolean = foo.bar[any index];
    // etc...
}
```

**Expected vs observed behavior**
The behavior I am expecting is to be able to assign a member of this array of booleans to a variable so that I could go on with my fragment shader business, but the program simply starts up and panics.

**Extra materials**
The output from RUST_BACKTRACE=1
```
thread 'main' panicked at 'internal error: entered unreachable code', .cargo\registry\src\github.com-1ecc6299db9ec823\naga-0.8.5\src\back\hlsl\conv.rs:9:27
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\panicking.rs:584
   1: core::panicking::panic_fmt
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\core\src\panicking.rs:143
   2: core::panicking::panic
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\core\src\panicking.rs:48
   3: naga::ScalarKind::to_hlsl_cast
             at .cargo\registry\src\github.com-1ecc6299db9ec823\naga-0.8.5\src\back\hlsl\conv.rs:9
   4: naga::back::hlsl::Writer<ref_mut$<alloc::string::String> >::write_storage_load<ref_mut$<alloc::string::String> >
             at .cargo\registry\src\github.com-1ecc6299db9ec823\naga-0.8.5\src\back\hlsl\storage.rs:94
   5: naga::back::hlsl::Writer<ref_mut$<alloc::string::String> >::write_expr<ref_mut$<alloc::string::String> 
>
             at .cargo\registry\src\github.com-1ecc6299db9ec823\naga-0.8.5\src\back\hlsl\writer.rs:1755
   6: naga::back::hlsl::Writer<ref_mut$<alloc::string::String> >::write_named_expr<ref_mut$<alloc::string::String> >
             at .cargo\registry\src\github.com-1ecc6299db9ec823\naga-0.8.5\src\back\hlsl\writer.rs:2130
   7: naga::back::hlsl::Writer<ref_mut$<alloc::string::String> >::write_stmt<ref_mut$<alloc::string::String> 
>
             at .cargo\registry\src\github.com-1ecc6299db9ec823\naga-0.8.5\src\back\hlsl\writer.rs:1054
   8: naga::back::hlsl::Writer<ref_mut$<alloc::string::String> >::write_function<ref_mut$<alloc::string::String> >
             at .cargo\registry\src\github.com-1ecc6299db9ec823\naga-0.8.5\src\back\hlsl\writer.rs:1004
   9: naga::back::hlsl::Writer<ref_mut$<alloc::string::String> >::write<ref_mut$<alloc::string::String> >    
             at .cargo\registry\src\github.com-1ecc6299db9ec823\naga-0.8.5\src\back\hlsl\writer.rs:292
  10: wgpu_hal::dx12::Device::load_shader
             at .cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-hal-0.12.4\src\dx12\device.rs:191
  11: wgpu_hal::dx12::device::impl$1::create_render_pipeline
             at .cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-hal-0.12.4\src\dx12\device.rs:1217
  12: wgpu_core::device::Device<wgpu_hal::dx12::Api>::create_render_pipeline<wgpu_hal::dx12::Api,wgpu_core::hub::IdentityManagerFactory>
             at .cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-core-0.12.2\src\device\mod.rs:2623
  13: wgpu_core::hub::Global<wgpu_core::hub::IdentityManagerFactory>::device_create_render_pipeline<wgpu_core::hub::IdentityManagerFactory,wgpu_hal::dx12::Api>
             at .cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-core-0.12.2\src\device\mod.rs:4415
  14: wgpu::backend::direct::impl$3::device_create_render_pipeline
             at .cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.12.0\src\backend\direct.rs:1303
  15: wgpu::Device::create_render_pipeline
             at .cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.12.0\src\lib.rs:1810
  16: my stuff
```

**Platform**
I am running Windows 10 with DX12 on an Intel HD Graphics 4000 that is about a decade old. Rust version is 1.61.0 and I am using wgpu 0.12

Thank you very much.

**Comment by cwfitzgerald** [comment]
Can you check with one of the examples on wgpu master if this is still a problem?

**Comment by Denis-Pe** [comment]
I apologize for the late reply, but I've ran all examples and everything works fine no panicking.
The water example looks a bit odd though, I don't know if it's supposed to be like that:
![image](https://user-images.githubusercontent.com/96642256/178390466-55258ca4-d3a2-4b9b-9a45-df72d8f353a0.png)

**Comment by Denis-Pe** [comment]
To anyone that encounters the same issue, updating to 0.13 showed me that I can't really achieve this because a dynamic array of booleans does not meet the HOST_SHAREABLE flag, which is needed for a global variable. My solution was to use u32s that can be either 0 or 1 since u32s are host shareable and therefore an array of them is also host shareable
For more information, look at this:
https://gpuweb.github.io/gpuweb/wgsl/#host-shareable-types
