### ISSUE TITLE
wgpu examples don't work under ubuntu 22.04, x11

### ISSUE THREAD

**Issue by naturalfreak** [gfx-rs/wgpu#2914]
**System:**
Ubuntu 22.04
GPU:  NVIDIA GTX 560

**Repro steps**
`cargo run --example shadow`

**Observed behavior**
wgpu master, on x11:
`
thread 'main' panicked at 'No suitable GPU adapters found on the system!', wgpu/examples/shadow/../framework.rs:184:14
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace
`

**RUST_LOG=info WINIT_UNIX_BACKEND=x11 WGPU_BACKEND=vulkan cargo run --example shadow**

```
    Finished dev [unoptimized + debuginfo] target(s) in 0.10s
     Running `target/debug/examples/shadow`
[2022-07-25T21:11:11Z INFO  winit::platform_impl::platform::x11::window] Guessed window scale factor: 1
[2022-07-25T21:11:11Z INFO  shadow::framework] Initializing the surface...
[2022-07-25T21:11:11Z INFO  wgpu_hal::vulkan::instance] Unable to find extension: VK_EXT_swapchain_colorspace
[2022-07-25T21:11:11Z INFO  wgpu_hal::vulkan::instance] Instance version: 0x4030cc
[2022-07-25T21:11:11Z INFO  wgpu_hal::vulkan::instance] Enabling debug utils
[2022-07-25T21:11:11Z INFO  wgpu_hal::vulkan::instance] Enabling device properties2
[2022-07-25T21:11:11Z INFO  wgpu_hal::vulkan::instance] GENERAL [Loader Message (0x0)]
    	loader_add_implicit_layer: Disabling implicit layer VK_LAYER_MESA_device_select for using an old API version 1.2 versus application requested 1.3
[2022-07-25T21:11:11Z INFO  wgpu_hal::vulkan::instance] 	objects: (type: INSTANCE, hndl: 0x5639ce25da00, name: ?)
[2022-07-25T21:11:11Z INFO  wgpu_hal::vulkan::instance] GENERAL [Loader Message (0x0)]
    	loader_add_implicit_layer: Disabling implicit layer VK_LAYER_MESA_device_select for using an old API version 1.2 versus application requested 1.3
[2022-07-25T21:11:11Z INFO  wgpu_hal::vulkan::instance] 	objects: (type: INSTANCE, hndl: 0x5639ce25da00, name: ?)
[2022-07-25T21:11:11Z INFO  wgpu_hal::vulkan::instance] GENERAL [Loader Message (0x0)]
    	loader_add_implicit_layer: Disabling implicit layer VK_LAYER_MESA_device_select for using an old API version 1.2 versus application requested 1.3
[2022-07-25T21:11:11Z INFO  wgpu_hal::vulkan::instance] 	objects: (type: INSTANCE, hndl: 0x5639ce25da00, name: ?)
[2022-07-25T21:11:11Z INFO  wgpu_hal::vulkan::instance] GENERAL [Loader Message (0x0)]
    	loader_add_implicit_layer: Disabling implicit layer VK_LAYER_MESA_device_select for using an old API version 1.2 versus application requested 1.3
[2022-07-25T21:11:11Z INFO  wgpu_hal::vulkan::instance] 	objects: (type: INSTANCE, hndl: 0x5639ce25da00, name: ?)
[2022-07-25T21:11:11Z INFO  wgpu_hal::vulkan::instance] GENERAL [Loader Message (0x0)]
    	loader_add_implicit_layer: Disabling implicit layer VK_LAYER_MESA_device_select for using an old API version 1.2 versus application requested 1.3
[2022-07-25T21:11:11Z INFO  wgpu_hal::vulkan::instance] 	objects: (type: INSTANCE, hndl: 0x5639ce25da00, name: ?)
[2022-07-25T21:11:11Z INFO  wgpu_hal::vulkan::instance] GENERAL [Loader Message (0x0)]
    	loader_add_implicit_layer: Disabling implicit layer VK_LAYER_MESA_device_select for using an old API version 1.2 versus application requested 1.3
[2022-07-25T21:11:11Z INFO  wgpu_hal::vulkan::instance] 	objects: (type: INSTANCE, hndl: 0x5639ce25da00, name: ?)
[2022-07-25T21:11:11Z INFO  wgpu_hal::vulkan::instance] GENERAL [Loader Message (0x0)]
    	loader_add_implicit_layer: Disabling implicit layer VK_LAYER_MESA_device_select for using an old API version 1.2 versus application requested 1.3
[2022-07-25T21:11:11Z INFO  wgpu_hal::vulkan::instance] 	objects: (type: INSTANCE, hndl: 0x5639ce25da00, name: ?)
[2022-07-25T21:11:11Z INFO  wgpu_hal::vulkan::instance] GENERAL [Loader Message (0x0)]
    	loader_add_implicit_layer: Disabling implicit layer VK_LAYER_MESA_device_select for using an old API version 1.2 versus application requested 1.3
[2022-07-25T21:11:11Z INFO  wgpu_hal::vulkan::instance] 	objects: (type: INSTANCE, hndl: 0x5639ce25da00, name: ?)
thread 'main' panicked at 'No suitable GPU adapters found on the system!', wgpu/examples/shadow/../framework.rs:184:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by cwfitzgerald** [comment]
Closing as stale.
