### ISSUE TITLE
No appropiate adapter found with `WGPU_BACKEND=vulkan` on Linux

### ISSUE THREAD

**Issue by AlexandruIca** [gfx-rs/wgpu#3033]
I'm using Nix to create an environment where I have vulkan available (I can run `vkcube` and `vulkaninfo` shows me the 2 devices that I have - the Intel integrated GPU and the AMD dedicated GPU). I'm trying to render a simple triangle (the code is based on the "Learn WGPU" tutorial, so I'm also using winit). When I run:
```
WINIT_UNIX_BACKEND=x11 WGPU_BACKEND=vulkan cargo run
```
The app fails at:
```rs
let size = window.inner_size();
let instance = wgpu::Instance::new(wgpu::Backends::all());
let surface = unsafe { instance.create_surface(&window) };
let adapter = instance
    .request_adapter(&wgpu::RequestAdapterOptions {
        power_preference: wgpu::PowerPreference::default(),
        force_fallback_adapter: false,
        compatible_surface: Some(&surface),
    })
    .await
    .expect("Failed to find an appropriate adapter"); // <-- here
```

I'm not sure whether I should enable a certain feature in `Cargo.toml` for `wgpu` (I'm using version `0.13.1`), or if the problem is somewhere else (for example in my Nix environment). I couldn't find info on how to build with the vulkan backend on Linux, sorry if I've missed the corresponding docs.
<details>
  <summary>The full backtrace</summary>

```sh
thread 'main' panicked at 'Failed to find an appropriate adapter', src/main.rs:88:14
stack backtrace:
   0:     0x55c982287bfc - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf9a1e5015c7372de
   1:     0x55c9822b8d0e - core::fmt::write::h9fe85dc123605e26
   2:     0x55c982293ad8 - std::io::Write::write_fmt::hb015af194a783782
   3:     0x55c98229b2f6 - std::panicking::default_hook::{{closure}}::h5be0c3f8bc5f82d3
   4:     0x55c98229af8c - std::panicking::default_hook::h26c625e8da3d12e5
   5:     0x55c98229b939 - std::panicking::rust_panic_with_hook::h9e5373efea59497b
   6:     0x55c9822889e7 - std::panicking::begin_panic_handler::{{closure}}::h6675d1d897d2268b
   7:     0x55c982287d24 - std::sys_common::backtrace::__rust_end_short_backtrace::h2eebb466dcccf8e7
   8:     0x55c98229b432 - rust_begin_unwind
   9:     0x55c981433f73 - core::panicking::panic_fmt::h388cf0442c96c658
  10:     0x55c9822b3961 - core::panicking::panic_display::h9cab5c963364b008
  11:     0x55c9822b390b - core::panicking::panic_str::h1e463a0b78fe617a
  12:     0x55c9814339a6 - core::option::expect_failed::h977089c48194ce61
  13:     0x55c981ce4993 - core::option::Option<T>::expect::h868c68612eaa3a41
                               at /build/rustc-1.60.0-src/library/core/src/option.rs:715:21
  14:     0x55c9814de2b6 - rust_wgpu_practice::State::new::{{closure}}::h861b8b4088b7ab36
                               at /hdd/devel/rust-wgpu-practice/src/main.rs:81:23
  15:     0x55c981484d67 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hf86e4be73ba4bdfa
                               at /build/rustc-1.60.0-src/library/core/src/future/mod.rs:84:19
  16:     0x55c9814df4a9 - rust_wgpu_practice::run::{{closure}}::hcae3935a4048eb7e
                               at /hdd/devel/rust-wgpu-practice/src/main.rs:243:40
  17:     0x55c981484b99 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h150018b676ba21c9
                               at /build/rustc-1.60.0-src/library/core/src/future/mod.rs:84:19
  18:     0x55c981466f5d - pollster::block_on::ha6b6f3b432934e8a
                               at /home/std-bless/.cargo/registry/src/github.com-1ecc6299db9ec823/pollster-0.2.5/src/lib.rs:125:15
  19:     0x55c981485f27 - rust_wgpu_practice::main::h69d02b01a73eb617
                               at /hdd/devel/rust-wgpu-practice/src/main.rs:286:9
  20:     0x55c98143a4eb - core::ops::function::FnOnce::call_once::h25ab19a9523be9ba
                               at /build/rustc-1.60.0-src/library/core/src/ops/function.rs:227:5
  21:     0x55c981491e3e - std::sys_common::backtrace::__rust_begin_short_backtrace::hd12ecfe3c0195373
                               at /build/rustc-1.60.0-src/library/std/src/sys_common/backtrace.rs:122:18
  22:     0x55c9814b75b1 - std::rt::lang_start::{{closure}}::hbd8d043f6b87e03c
                               at /build/rustc-1.60.0-src/library/std/src/rt.rs:145:18
  23:     0x55c98228f1b1 - std::rt::lang_start_internal::hf41d970dc65153b4
  24:     0x55c9814b7580 - std::rt::lang_start::hb61825479af3b430
                               at /build/rustc-1.60.0-src/library/std/src/rt.rs:144:17
  25:     0x55c981485f8c - main
  26:     0x7f5af368f237 - __libc_start_call_main
  27:     0x7f5af368f2f5 - __libc_start_main_impl
  28:     0x55c981434321 - _start
                               at /build/glibc-2.34/csu/../sysdeps/x86_64/start.S:116
  29:                0x0 - <unknown>
```

</details>
<details>
  <summary>Source code</summary>

```rs
use std::iter;
use wgpu::util::DeviceExt;
use winit::{
    event::{Event, WindowEvent},
    event_loop::{ControlFlow, EventLoop},
    window::Window,
};

#[repr(C)]
struct Vertex {
    position: [f32; 3],
    color: [f32; 3],
}

impl Vertex {
    fn desc<'a>() -> wgpu::VertexBufferLayout<'a> {
        wgpu::VertexBufferLayout {
            array_stride: std::mem::size_of::<Vertex>() as wgpu::BufferAddress,
            step_mode: wgpu::VertexStepMode::Vertex,
            attributes: &[
                wgpu::VertexAttribute {
                    offset: 0,
                    shader_location: 0,
                    format: wgpu::VertexFormat::Float32x3,
                },
                wgpu::VertexAttribute {
                    offset: std::mem::size_of::<[f32; 3]>() as wgpu::BufferAddress,
                    shader_location: 1,
                    format: wgpu::VertexFormat::Float32x3,
                },
            ],
        }
    }
}

const VERTICES: &[Vertex] = &[
    Vertex {
        position: [-1.0, 1.0, 0.0],
        color: [0.5, 0.0, 0.5],
    }, // Top left
    Vertex {
        position: [-1.0, -1.0, 0.0],
        color: [0.5, 0.0, 1.0],
    }, // Bottom left
    Vertex {
        position: [1.0, -1.0, 0.0],
        color: [0.8, 0.3, 0.2],
    }, // Bottom right
    Vertex {
        position: [1.0, 1.0, 0.0],
        color: [0.6, 0.7, 0.1],
    }, // Top right
];

const INDICES: &[u16] = &[0, 1, 2, 2, 3, 0];

unsafe fn slice_to_bytes<T>(input: &[T]) -> &[u8] {
    core::slice::from_raw_parts(
        input.as_ptr() as *const u8,
        input.len() * std::mem::size_of::<T>(),
    )
}

struct State {
    surface: wgpu::Surface,
    device: wgpu::Device,
    queue: wgpu::Queue,
    config: wgpu::SurfaceConfiguration,
    size: winit::dpi::PhysicalSize<u32>,
    render_pipeline: wgpu::RenderPipeline,
    vertex_buffer: wgpu::Buffer,
    index_buffer: wgpu::Buffer,
    num_indices: u32,
}

impl State {
    async fn new(window: &Window) -> Self {
        let size = window.inner_size();
        let instance = wgpu::Instance::new(wgpu::Backends::all());
        let surface = unsafe { instance.create_surface(&window) };
        let adapter = instance
            .request_adapter(&wgpu::RequestAdapterOptions {
                power_preference: wgpu::PowerPreference::default(),
                force_fallback_adapter: false,
                compatible_surface: Some(&surface),
            })
            .await
            .expect("Failed to find an appropriate adapter");

        let (device, queue) = adapter
            .request_device(
                &wgpu::DeviceDescriptor {
                    label: None,
                    features: wgpu::Features::empty(),
                    limits: if cfg!(target_arch = "wasm32") {
                        wgpu::Limits::downlevel_webgl2_defaults()
                    } else {
                        wgpu::Limits::default()
                    },
                },
                None,
            )
            .await
            .expect("Failed to create device");

        let config = wgpu::SurfaceConfiguration {
            usage: wgpu::TextureUsages::RENDER_ATTACHMENT,
            format: surface.get_supported_formats(&adapter)[0],
            width: size.width,
            height: size.height,
            present_mode: wgpu::PresentMode::Fifo,
        };

        surface.configure(&device, &config);

        let shader = device.create_shader_module(wgpu::ShaderModuleDescriptor {
            label: Some("Background rendering shader"),
            source: wgpu::ShaderSource::Wgsl(include_str!("shader.wgsl").into()),
        });

        let render_pipeline_layout =
            device.create_pipeline_layout(&wgpu::PipelineLayoutDescriptor {
                label: Some("Renderer pipeline layout descriptor"),
                bind_group_layouts: &[],
                push_constant_ranges: &[],
            });

        let render_pipeline = device.create_render_pipeline(&wgpu::RenderPipelineDescriptor {
            label: Some("Render pipeline"),
            layout: Some(&render_pipeline_layout),
            vertex: wgpu::VertexState {
                module: &shader,
                entry_point: "vs_main",
                buffers: &[Vertex::desc()],
            },
            fragment: Some(wgpu::FragmentState {
                module: &shader,
                entry_point: "fs_main",
                targets: &[Some(wgpu::ColorTargetState {
                    format: config.format,
                    blend: Some(wgpu::BlendState {
                        color: wgpu::BlendComponent::REPLACE,
                        alpha: wgpu::BlendComponent::REPLACE,
                    }),
                    write_mask: wgpu::ColorWrites::ALL,
                })],
            }),
            primitive: wgpu::PrimitiveState {
                topology: wgpu::PrimitiveTopology::TriangleList,
                strip_index_format: None,
                front_face: wgpu::FrontFace::Ccw,
                cull_mode: Some(wgpu::Face::Back),
                polygon_mode: wgpu::PolygonMode::Fill,
                unclipped_depth: false,
                conservative: false,
            },
            depth_stencil: None,
            multisample: wgpu::MultisampleState {
                count: 1,
                mask: !0,
                alpha_to_coverage_enabled: false,
            },
            multiview: None,
        });

        let vertex_buffer = device.create_buffer_init(&wgpu::util::BufferInitDescriptor {
            label: Some("Vertex buffer"),
            contents: unsafe { slice_to_bytes(VERTICES) },
            usage: wgpu::BufferUsages::VERTEX,
        });
        let index_buffer = device.create_buffer_init(&wgpu::util::BufferInitDescriptor {
            label: Some("Index buffer"),
            contents: unsafe { slice_to_bytes(INDICES) },
            usage: wgpu::BufferUsages::INDEX,
        });
        let num_indices = INDICES.len() as u32;

        Self {
            surface,
            device,
            queue,
            config,
            size,
            render_pipeline,
            vertex_buffer,
            index_buffer,
            num_indices,
        }
    }

    fn resize(&mut self, new_size: winit::dpi::PhysicalSize<u32>) {
        self.size = new_size;
        self.config.width = new_size.width;
        self.config.height = new_size.height;
        self.surface.configure(&self.device, &self.config);
    }

    fn render(&mut self) -> Result<(), wgpu::SurfaceError> {
        let output = self.surface.get_current_texture()?;
        let view = output
            .texture
            .create_view(&wgpu::TextureViewDescriptor::default());

        let mut encoder = self
            .device
            .create_command_encoder(&wgpu::CommandEncoderDescriptor {
                label: Some("Render Encoder"),
            });

        {
            let mut render_pass = encoder.begin_render_pass(&wgpu::RenderPassDescriptor {
                label: Some("Render pass"),
                color_attachments: &[Some(wgpu::RenderPassColorAttachment {
                    view: &view,
                    resolve_target: None,
                    ops: wgpu::Operations {
                        load: wgpu::LoadOp::Clear(wgpu::Color {
                            r: 0.0,
                            g: 0.0,
                            b: 0.0,
                            a: 1.0,
                        }),
                        store: true,
                    },
                })],
                depth_stencil_attachment: None,
            });

            render_pass.set_pipeline(&self.render_pipeline);
            render_pass.set_vertex_buffer(0, self.vertex_buffer.slice(..));
            render_pass.set_index_buffer(self.index_buffer.slice(..), wgpu::IndexFormat::Uint16);
            render_pass.draw_indexed(0..self.num_indices, 0, 0..1);
        }

        self.queue.submit(iter::once(encoder.finish()));
        output.present();

        Ok(())
    }
}

async fn run(event_loop: EventLoop<()>, window: Window) {
    let mut state = State::new(&window).await;

    event_loop.run(move |event, _, control_flow| {
        *control_flow = ControlFlow::Wait;
        match event {
            Event::WindowEvent {
                event: WindowEvent::Resized(size),
                ..
            } => {
                state.resize(size);
            }
            Event::WindowEvent {
                event: WindowEvent::ScaleFactorChanged { new_inner_size, .. },
                ..
            } => {
                state.resize(*new_inner_size);
            }
            Event::RedrawRequested(_) => match state.render() {
                Ok(_) => {}
                Err(wgpu::SurfaceError::Lost | wgpu::SurfaceError::Outdated) => {
                    state.resize(state.size)
                }
                Err(wgpu::SurfaceError::OutOfMemory) => *control_flow = ControlFlow::Exit,
                Err(wgpu::SurfaceError::Timeout) => eprintln!("Surface timeout!"),
            },
            Event::MainEventsCleared => {
                window.request_redraw();
            }
            Event::WindowEvent {
                event: WindowEvent::CloseRequested,
                ..
            } => *control_flow = ControlFlow::Exit,
            _ => {}
        }
    });
}

fn main() {
    let event_loop = EventLoop::new();
    let window = winit::window::Window::new(&event_loop).unwrap();
    #[cfg(not(target_arch = "wasm32"))]
    {
        env_logger::init();
        pollster::block_on(run(event_loop, window));
    }
    #[cfg(target_arch = "wasm32")]
    {
        std::panic::set_hook(Box::new(console_error_panic_hook::hook));
        console_log::init().expect("could not initialize logger");
        use winit::platform::web::WindowExtWebSys;
        web_sys::window()
            .and_then(|win| win.document())
            .and_then(|doc| doc.body())
            .and_then(|body| {
                body.append_child(&web_sys::Element::from(window.canvas()))
                    .ok()
            })
            .expect("couldn't append canvas to document body");
        wasm_bindgen_futures::spawn_local(run(event_loop, window));
    }
}
```

</details>
<details>
  <summary>My flake.nix</summary>

```nix
{
  description = "WebGPU environment";

  inputs.nixpkgs.url = "nixpkgs/nixos-22.05";

  outputs = { self, nixpkgs }:
    let
      supportedSystems = ["x86_64-linux"];
      forAllSystems = nixpkgs.lib.genAttrs supportedSystems;
      nixpkgsFor = forAllSystems (system: import nixpkgs { inherit system; });
    in {
        devShells = forAllSystems (system:
          let
            pkgs = nixpkgsFor.${system};
          in {
            default = pkgs.mkShell rec {
              buildInputs = with pkgs; [
                cargo
                rust-analyzer
                rustfmt

                # needed by some dependencies
                cmake
                pkg-config
                fontconfig

                # WINIT_UNIX_BACKEND=x11
                xorg.libxcb
                xorg.libXcursor
                xorg.libXrandr
                xorg.libXi
                xorg.libX11

                # WGPU_BACKEND=vulkan
                glslang
                vulkan-headers
                vulkan-loader
                vulkan-validation-layers
              ];
              LD_LIBRARY_PATH = "${nixpkgs.lib.makeLibraryPath buildInputs}";
              VULKAN_SDK = "${pkgs.vulkan-validation-layers}/share/vulkan/explicit_layer.d"; # don't know if it's needed
            };
          });
    };
}
```

</details>

**Comment by cwfitzgerald** [comment]
Random idea: try without the compatible surface

**Comment by AlexandruIca** [comment]
@cwfitzgerald I've tried with `compatible_surface: None` and it gave the same error.

**Comment by expenses** [comment]
I've encountered some issues with using wgpu, multiple GPUs and Vulkan on Linux. I think the easiest solution to set `VK_ICD_FILENAMES` to the driver ICD you want to use, e.g. `VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/intel_icd.x86_64.json cargo run ...`.

**Comment by AlexandruIca** [comment]
@expenses Thanks for the suggestion. It didn't work, but I've managed to succesfully run the app by just not using Nix. I'm not sure what the issue with the Nix environment was (I'm not too experienced with Nix, probably I should have set up more things in `flake.nix`), but it doesn't matter, the issue doesn't seem to be with wgpu. Thanks for the help, I'll close the issue.

**Comment by jonringer** [comment]
Ran into this same issue with NixOS + iced (which uses wgpu). My findings are that NixOS distributes suffixed libraries (e.g. `libvulkan_radeon.so.1`, while ash (which wgpu uses) asks specifically for `libvulkan.so.1`.  Since there's no complicated loading logic like with the lunarg vulkan bindings. The search ends very quickly to find a corresponding libvulkan.so.

**Comment by SeanOMik** [comment]
@jonringer I'm running into the same issue on nixos. Were you able to fix it?

**Comment by musjj** [comment]
@SeanOMik
I had the same problem and I solved it by simply adding `vulkan-loader` to my `LD_LIBRARY_PATH`.
This is roughly what my `shell.nix` looks like:

```nix
pkgs.mkShell {
  ...
  shellHook = ''
    LD_LIBRARY_PATH="''${LD_LIBRARY_PATH:+$LD_LIBRARY_PATH:}${
      with pkgs;
        lib.makeLibraryPath [
          vulkan-loader
          xorg.libX11
          xorg.libXcursor
          xorg.libXi
          xorg.libXrandr
        ]
    }"
    export LD_LIBRARY_PATH
  '';
};
```

**Comment by gretchenfrage** [comment]
Previous comment worked for me but I had to add libxkbcommon to the packages as per [this blog post](https://eu90h.com/wgpu-winit-and-nixos.html). So my shell.nix file ended up being:

```nix
{ pkgs ? import <nixpkgs> {} }:
pkgs.mkShell {
  shellHook = ''
    LD_LIBRARY_PATH="''${LD_LIBRARY_PATH:+$LD_LIBRARY_PATH:}${
      with pkgs;
        lib.makeLibraryPath [
          vulkan-loader
          xorg.libX11
          xorg.libXcursor
          xorg.libXi
          xorg.libXrandr
          libxkbcommon
        ]
    }"
    export LD_LIBRARY_PATH
  '';
}
```
