### ISSUE TITLE
`cts_runner::integration hello_compute_example` fails

### ISSUE THREAD

**Issue by jimblandy** [gfx-rs/wgpu#3164]
Running `cargo test -p cts_runner --test integration` fails.

```
$ cargo test -p cts_runner --test integration
    Finished test [unoptimized + debuginfo] target(s) in 0.07s
     Running tests/integration.rs (target/debug/deps/integration-3ec71e982bffcb5b)

running 1 test
error: TypeError: core.ops is not a function
    at bootstrapRuntime (deno:cts_runner/bootstrap.js:222:10)
    at [deno:cts_runner/src/main.rs:53:29]:1:12
test hello_compute_example ... FAILED

failures:

---- hello_compute_example stdout ----
thread 'hello_compute_example' panicked at 'assertion failed: output.status.success()', cts_runner/tests/integration.rs:26:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    hello_compute_example

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.03s

error: test failed, to rerun pass '-p cts_runner --test integration'
```

I'm running Fedora 36.

**Comment by cwfitzgerald** [comment]
This is fixed by #3068 which I need to rebase on top of the latest CI work.

**Comment by andyleiserson** [comment]
This test is passing now.
