### ISSUE TITLE
Intermittent panic getting adapter when running Bevy example

### ISSUE THREAD

**Issue by LegNeato** [gfx-rs/wgpu#3556]
**Description**
Running `RUST_BACKTRACE=1 cargo run --release --example window_fallthrough` on [latest bevy](https://github.com/bevyengine/bevy/commit/2ea00610188dce1eba1172a3ded8244570189230) panics intermittently. **I am not sure if this is a `wgpu` or `bevy` bug.**

**Repro steps**
On an M1 Pro:

* `git clone https://github.com/bevyengine/bevy.git`
* `cd bevy`
* `RUST_BACKTRACE=1 cargo run --release --example window_fallthrough`

**Expected vs observed behavior**
Sometimes it works fine, sometimes it panics with the following:

```rust
❯ RUST_BACKTRACE=1 cargo run --release --example window_fallthrough
    Finished release [optimized] target(s) in 0.15s
     Running `target/release/examples/window_fallthrough`
thread 'main' panicked at '', /Users/x/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-hal-0.15.2/src/metal/adapter.rs:473:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/2d14db321b043ffc579a7461464c88d7e3f54f83/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/2d14db321b043ffc579a7461464c88d7e3f54f83/library/core/src/panicking.rs:64:14
   2: core::panicking::panic_display
   3: wgpu_hal::metal::AdapterShared::new
   4: <wgpu_hal::metal::Instance as wgpu_hal::Instance<wgpu_hal::metal::Api>>::enumerate_adapters::{{closure}}
   5: alloc::vec::in_place_collect::<impl alloc::vec::spec_from_iter::SpecFromIter<T,I> for alloc::vec::Vec<T>>::from_iter
   6: <wgpu_hal::metal::Instance as wgpu_hal::Instance<wgpu_hal::metal::Api>>::enumerate_adapters
   7: wgpu_core::instance::<impl wgpu_core::hub::Global<G>>::request_adapter::gather
   8: wgpu_core::instance::<impl wgpu_core::hub::Global<G>>::request_adapter
   9: <T as wgpu::context::DynContext>::instance_request_adapter
  10: wgpu::Instance::request_adapter
  11: bevy_render::renderer::initialize_renderer::{{closure}}
  12: std::thread::local::LocalKey<T>::with
  13: <bevy_render::RenderPlugin as bevy_app::plugin::Plugin>::build
  14: bevy_app::app::App::add_boxed_plugin
  15: bevy_app::plugin_group::PluginGroupBuilder::finish
  16: window_fallthrough::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
window_fallthrough(32940,0x102988580) malloc: *** error for object 0x6: pointer being freed was not allocated
window_fallthrough(32940,0x102988580) malloc: *** set a breakpoint in malloc_error_break to debug
```

**Platform**
<img width="214" alt="Screen Shot 2023-03-03 at 10 35 14 PM" src="https://user-images.githubusercontent.com/368904/222871455-b950fc1d-aa1b-44bb-93b8-1a0fba6d1054.png">

**Comment by grovesNL** [comment]
Hi! :wave: Thank you for creating this issue, it looks like a problem in wgpu's macOS version checking (#3557)

**Comment by LegNeato** [comment]
Wow, that was quick! ❤️
