### ISSUE TITLE
compute pipelines are broken with bad slice panics

### ISSUE THREAD

**Issue by m4b** [gfx-rs/wgpu#364]
on wgpu-rs  master ed2c67f762970d0099c1e6c6e078fb645afbf964
with wgpu-native 78fbbba

```
cargo run --example hello-compute -- 0 1
    Finished dev [unoptimized + debuginfo] target(s) in 0.07s
     Running `target/debug/examples/hello-compute 0 1`
thread 'main' panicked at 'slice index starts at 1 but ends at 0', src/libcore/slice/mod.rs:2589:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```
Called from here:
```
        pass.binder
            .reset_expectations(pipeline_layout.bind_group_layout_ids.len());
        let mut is_compatible = true;
...
    pub(crate) fn reset_expectations(&mut self, length: usize) {
        for entry in self.entries[length ..].iter_mut() {
            entry.expected_layout_id = None;
        }
    }
```

Backtrace:
```
  10: core::slice::slice_index_order_fail
             at src/libcore/slice/mod.rs:2589
  11: <core::ops::range::Range<usize> as core::slice::SliceIndex<[T]>>::index_mut
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libcore/slice/mod.rs:2776
  12: <core::ops::range::RangeFrom<usize> as core::slice::SliceIndex<[T]>>::index_mut
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libcore/slice/mod.rs:2852
  13: core::slice::<impl core::ops::index::IndexMut<I> for [T]>::index_mut
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libcore/slice/mod.rs:2576
  14: <smallvec::SmallVec<A> as core::ops::index::IndexMut<core::ops::range::RangeFrom<usize>>>::index_mut
             at /home/m4b/.cargo/registry/src/github.com-1ecc6299db9ec823/smallvec-0.6.10/lib.rs:1313
  15: wgpu_native::command::bind::Binder::reset_expectations
             at /home/m4b/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/78fbbba/wgpu-native/src/command/bind.rs:156
  16: wgpu_native::command::compute::compute_pass_set_pipeline
             at /home/m4b/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/78fbbba/wgpu-native/src/command/compute.rs:261
  17: wgpu_compute_pass_set_pipeline
             at /home/m4b/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/78fbbba/wgpu-native/src/command/compute.rs:299
  18: wgpu::ComputePass::set_pipeline
             at src/lib.rs:1301
  19: hello_compute::main
             at examples/hello-compute/main.rs:85
```

**Comment by kvark** [comment]
I'll have a look, unless somebody wants to help. It should be easy.

**Comment by m4b** [comment]
I don't still understand what's the issue, but i'd like to help. I can debug any patch you push, but it might be faster for you to fix it if you know what's going on?

**Comment by m4b** [comment]
This problem doesn't exist in wgpu-native c3609d71c95dc5be1672c737ee4010e6a9408748

**Comment by kvark** [comment]
https://github.com/gfx-rs/wgpu/pull/348 is most likely the one that broke it. I already followed up with one compute fix, a bit surprising more fixes are needed.

**Comment by kvark** [comment]
Actually, I think you are just seeing #348 since the wgpu-native version you are using doesn't include https://github.com/gfx-rs/wgpu/pull/352 . This issue is fixed, we just need to update wgpu-rs to use the latest wgpu-native
