### ISSUE TITLE
panic in hello-triangle example: `eglInitialize` fails with `EGL_BAD_ACCESS` -- backend failed to allocate context

### ISSUE THREAD

**Issue by bluenote10** [gfx-rs/wgpu#3655]
**Description**

Checking out the `wgpu` repo and running `cargo run --example hello-triangle` panics (details below).

**Repro steps**

- Checkout `wgpu`
- Run `cargo run --example hello-triangle`

**Expected vs observed behavior**

The example fails with (adding `RUST_BACKTRACE=1 RUST_LOG=info` for details):

```
[2023-04-07T07:33:28Z INFO  wgpu_hal::vulkan::instance] Unable to find extension: VK_EXT_swapchain_colorspace
[2023-04-07T07:33:28Z WARN  wgpu_hal::vulkan::instance] Unable to find layer: VK_LAYER_KHRONOS_validation
[2023-04-07T07:33:28Z INFO  wgpu_hal::vulkan::instance] Instance version: 0x4030cc
[2023-04-07T07:33:28Z INFO  wgpu_hal::vulkan::instance] Enabling debug utils
[2023-04-07T07:33:28Z INFO  wgpu_hal::vulkan::instance] Enabling device properties2
[2023-04-07T07:33:28Z INFO  wgpu_hal::gles::egl] Loading Wayland library to get the current display
[2023-04-07T07:33:28Z INFO  wgpu_hal::gles::egl] Loading X11 library to get the current display
[2023-04-07T07:33:28Z INFO  wgpu_hal::gles::egl] Using X11 platform
[2023-04-07T07:33:28Z INFO  wgpu_hal::gles::egl] Enabling EGL debug output
[2023-04-07T07:33:28Z ERROR wgpu_hal::gles::egl] EGL 'eglInitialize' code 0x3002: EGL_BAD_ACCESS error: In eglInitialize: EGLDisplay (0x55a209c39300): Backend failed to allocate context
    
thread 'main' panicked at 'Failed to find an appropriate adapter', wgpu/examples/hello-triangle/main.rs:22:10
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:142:14
   2: core::panicking::panic_display
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:72:5
   3: core::panicking::panic_str
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:56:5
   4: core::option::expect_failed
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/option.rs:1874:5
   5: core::option::Option<T>::expect
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/option.rs:738:21
   6: hello_triangle::run::{{closure}}
             at ./wgpu/examples/hello-triangle/main.rs:14:19
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/future/mod.rs:91:19
   8: pollster::block_on
             at /home/fabian/.cargo/registry/src/github.com-1ecc6299db9ec823/pollster-0.2.5/src/lib.rs:125:15
   9: hello_triangle::main
             at ./wgpu/examples/hello-triangle/main.rs:149:9
  10: core::ops::function::FnOnce::call_once
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[2023-04-07T07:33:28Z INFO  wgpu_core::hub] Dropping Global
```

**Platform**

OS: Ubuntu 22.04
GPU: NVIDIA GeForce GTX 980
NVidia driver version: 470.161.03
wgpu: Just the `trunk` branch as of today

**Comment by bluenote10** [comment]
It looks like this was some kind of hiccup with my graphics card / driver / system. I noticed that `nvidia-smi` was in a broken state, reporting `Failed to initialize NVML: Driver/library version mismatch`. Rebooting actually resolved the issue.
