### ISSUE TITLE
mipmap example does not work in v0.16

### ISSUE THREAD

**Issue by im-0** [gfx-rs/wgpu#3736]
**Description**
`mipmap` example panics on start:

```
$ RUST_BACKTRACE=1 cargo run --example mipmap 
    Finished dev [unoptimized + debuginfo] target(s) in 0.13s
     Running `target/debug/examples/mipmap`
warning: queue 0x562dc83f1140 destroyed while proxies still attached:
  wl_display@1 still attached
Using AMD Radeon RX 6900 XT (RADV NAVI21) (Vulkan)
[2023-04-29T04:13:24Z ERROR wgpu::backend::direct] Handling wgpu errors as fatal by default
thread 'main' panicked at 'wgpu error: Validation Error

Caused by:
    In Device::create_buffer
      note: label = `query buffer`
    `MAP` usage can only be combined with the opposite `COPY`, requested BufferUsages(MAP_READ | QUERY_RESOLVE)

', wgpu/src/backend/direct.rs:3019:5
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: wgpu::backend::direct::default_error_handler
             at ./wgpu/src/backend/direct.rs:3019:5
   3: core::ops::function::Fn::call
             at /builddir/build/BUILD/rustc-1.69.0-src/library/core/src/ops/function.rs:79:5
   4: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /builddir/build/BUILD/rustc-1.69.0-src/library/alloc/src/boxed.rs:2001:9
   5: wgpu::backend::direct::ErrorSinkRaw::handle_error
             at ./wgpu/src/backend/direct.rs:3005:17
   6: wgpu::backend::direct::Context::handle_error
             at ./wgpu/src/backend/direct.rs:287:9
   7: <wgpu::backend::direct::Context as wgpu::context::Context>::device_create_buffer
             at ./wgpu/src/backend/direct.rs:1250:13
   8: <T as wgpu::context::DynContext>::device_create_buffer
             at ./wgpu/src/context.rs:2219:30
   9: wgpu::Device::create_buffer
             at ./wgpu/src/lib.rs:2123:13
  10: <mipmap::Example as mipmap::framework::Example>::init
             at ./wgpu/examples/mipmap/main.rs:359:31
  11: mipmap::framework::start
             at ./wgpu/examples/mipmap/../framework.rs:284:23
  12: mipmap::framework::run
             at ./wgpu/examples/mipmap/../framework.rs:445:5
  13: mipmap::main
             at ./wgpu/examples/mipmap/main.rs:488:5
  14: core::ops::function::FnOnce::call_once
             at /builddir/build/BUILD/rustc-1.69.0-src/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
warning: queue 0x562dc8aae3f0 destroyed while proxies still attached:
  zwp_linux_dmabuf_feedback_v1@41 still attached
warning: queue 0x562dc85ddbc0 destroyed while proxies still attached:
  wl_display@1 still attached
warning: queue 0x562dc79ba840 destroyed while proxies still attached:
  xdg_wm_base@20 still attached
  zwp_text_input_manager_v3@13 still attached
  wl_output@12 still attached
  xdg_activation_v1@11 still attached
  wl_subcompositor@10 still attached
  zwp_relative_pointer_manager_v1@9 still attached
  zwp_pointer_constraints_v1@8 still attached
  wl_seat@7 still attached
  wl_shm@6 still attached
  zxdg_decoration_manager_v1@5 still attached
  wl_compositor@4 still attached
  wl_registry@2 still attached
  ```

**Repro steps**
Just try to run it as a native application (not WASM/WebGPU in browser).

**Expected vs observed behavior**
It should work.

**Extra materials**
This seems to be broken because of a https://github.com/gfx-rs/wgpu/pull/3489. I do not see any fixes or implementation for `QUERY_RESOLVE` for native backends in that pull request.

**Platform**
Linux, Mesa, wgpu v0.16.

**Comment by valaphee** [comment]
Also noticed this, and addressed it in #3402 while I was working on occlusion queries, by using a staging buffer.

Seems unnecessary, because most backends saves it client-side anyway.
