### ISSUE TITLE
wgpu.rs examples not working on chrome 113 windows 10

### ISSUE THREAD

**Issue by lesleyrs** [gfx-rs/wgpu#3745]
**Description**
Chrome added webgpu support in 113, but they error out.

**Repro steps**
https://wgpu.rs/examples-gpu/?example=hello-triangle

**Expected vs observed behavior**
```
Uncaught (in promise) TypeError: getObject(...).requestDevice is not a function
    at imports.wbg.__wbg_requestDevice_7dbb93ae9dc5edc1 (hello-triangle.js:465:37)
    at web_sys::features::gen_GpuAdapter::GpuAdapter::request_device_with_descriptor::h5ba22dc545c9a335 (hello-triangle_bg.wasm:0x3bb7f)
    at <wgpu::backend::web::Context as wgpu::context::Context>::adapter_request_device::h48b9ca110c43c4f4 (hello-triangle_bg.wasm:0x19338)
    at <T as wgpu::context::DynContext>::adapter_request_device::h8802e6ea7a136b98 (hello-triangle_bg.wasm:0x2f0d3)
    at wgpu::Adapter::request_device::hd987f184958be88f (hello-triangle_bg.wasm:0x2e381)
    at hello_triangle::run::{{closure}}::h505ace009edd29b5 (hello-triangle_bg.wasm:0x9341)
    at wasm_bindgen_futures::task::singlethread::Task::run::hc370dcf952beab62 (hello-triangle_bg.wasm:0x286ff)
    at wasm_bindgen_futures::queue::Queue::new::{{closure}}::h2c947084f815b722 (hello-triangle_bg.wasm:0x1d2a5)
    at <dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::hc3229f73f18334a4 (hello-triangle_bg.wasm:0x3b0f7)
    at __wbg_adapter_49 (hello-triangle.js:229:10)
```

**Comment by cwfitzgerald** [comment]
This is https://github.com/gfx-rs/wgpu/issues/3684
