### ISSUE TITLE
Just fetched latest, now dx12 panics in "surface.configure(...)"

### ISSUE THREAD

**Issue by apessino** [gfx-rs/wgpu#3938]
I am sure it is related to the recent `d3d12 0.7 with ownership` merge, but nothing has changed on my side and now I get the following panic:

```
    Finished dev [unoptimized + debuginfo] target(s) in 22.06s
     Running `target\debug\rre_play.exe`
Adapter: NVIDIA GeForce RTX 4090 (Dx12)
thread 'main' panicked at 'assertion failed: !self.is_null()', C:\Users\andre\.cargo\registry\src\index.crates.io-6f17d22bba15001f\d3d12-0.7.0\src\com.rs:67:9
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library\std\src\panicking.rs:593
   1: core::panicking::panic_fmt
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library\core\src\panicking.rs:67
   2: core::panicking::panic
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library\core\src\panicking.rs:117
   3: d3d12::com::impl$2::clone<winapi::um::d3d12::ID3D12Resource>
             at C:\Users\andre\.cargo\registry\src\index.crates.io-6f17d22bba15001f\d3d12-0.7.0\src\com.rs:67
   4: alloc::vec::impl$4::next<d3d12::com::ComPtr<winapi::um::d3d12::ID3D12Resource> >
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225\library\alloc\src\vec\mod.rs:2481
   5: alloc::vec::Vec<d3d12::com::ComPtr<winapi::um::d3d12::ID3D12Resource>,alloc::alloc::Global>::extend_with<d3d12::com::ComPtr<winapi::um::d3d12::ID3D12Resource>,alloc::alloc::Global,alloc::vec::ExtendElement<d3d12::com::ComPtr<winapi::um::d3d12::ID3D12Resou
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225\library\alloc\src\vec\mod.rs:2503
   6: alloc::vec::spec_from_elem::impl$0::from_elem<d3d12::com::ComPtr<winapi::um::d3d12::ID3D12Resource>,alloc::alloc::Global>
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225\library\alloc\src\vec\spec_from_elem.rs:16
   7: alloc::vec::from_elem<d3d12::com::ComPtr<winapi::um::d3d12::ID3D12Resource> >
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225\library\alloc\src\vec\mod.rs:2550
   8: wgpu_hal::dx12::impl$41::configure
             at D:\projects\rust\wgpu\wgpu-hal\src\dx12\mod.rs:749
   9: wgpu_core::global::Global<wgpu_core::identity::IdentityManagerFactory>::surface_configure<wgpu_core::identity::IdentityManagerFactory,wgpu_hal::dx12::Api>
             at D:\projects\rust\wgpu\wgpu-core\src\device\global.rs:2184
  10: wgpu::backend::direct::impl$7::surface_configure
             at D:\projects\rust\wgpu\wgpu\src\backend\direct.rs:769
  11: wgpu::context::impl$5::surface_configure<wgpu::backend::direct::Context>
             at D:\projects\rust\wgpu\wgpu\src\context.rs:2154
  12: wgpu::Surface::configure
             at D:\projects\rust\wgpu\wgpu\src\lib.rs:4581
...
```

My code is unchanged - the odd thing is that the examples still run fine, but so far I have failed to see anything that I am doing differently during initialization, other than my init is mostly synchronous. If I use Vulkan everything is still OK.

Any hints? Thanks...

A=

**Comment by cwfitzgerald** [comment]
Yeah this appears to be an issue with the new ComPtr type, I can work around the problem in the mean time.

**Comment by apessino** [comment]
Got your work around, works for now, and I appreciate your help! 

A=
