### ISSUE TITLE
thread 'main' panicked at 'assertion failed: prev.is_none()', src/front/spv/mod.rs:2903:25

### ISSUE THREAD

**Issue by Jack-Clark** [gfx-rs/wgpu#4388]
Running:
```
target/debug/naga break-error.spv break-error.comp
```
Gives:
```
thread 'main' panicked at 'assertion failed: prev.is_none()', src/front/spv/mod.rs:2903:25
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted (core dumped)
```
If I run a release build, then I get:
```
Function [1] '' is invalid: 
	The `break` is used outside of a `loop` or `switch` context
Generating glsl output requires validation to succeed, and it failed in a previous step
```

I can also produce a slightly different error in both debug and release mode using a different example:
```
target/release/naga continue-error.spv continue-error.comp
```
Outputs:
```
Function [1] '' is invalid: 
	The `continue` is used outside of a `loop` context
Generating glsl output requires validation to succeed, and it failed in a previous step
```
I've tried `.comp` `.metal` and `.hlsl` as translation targets and I get the same result regardless. I reproduced this on main (commit b3d5e6d807560310fa514c0920c91c7f2cac974b). [Here is an archive with the code examples](https://github.com/gfx-rs/naga/files/8662473/errors.tar.gz)

**Comment by eddyb** [comment]
I suspect this is a duplicate of:
* gfx-rs/naga#1977

I have a fix open for that, can you try it out on your input?
* gfx-rs/naga#2290
