### ISSUE TITLE
Shader translation error: Size of declared private variable exceeds implementation-defined limit  

### ISSUE THREAD

**Issue by tmvkrpxl0** [gfx-rs/wgpu#4430]
```wgsl
struct BlitContents {
    map: array<vec4<u32>, 129600> // 1920 * 1080 / 16 = 129600
}
@group(0) @binding(0)
var<uniform> contents: BlitContents;

@vertex
fn vs_main(@location(0) vertices: vec3<f32>) -> @builtin(position) vec4<f32> {
    return vec4<f32>(vertices, 1.0);
}

@fragment
fn fs_main(@builtin(position) in: vec4<f32>) -> @location(0) vec4<f32> {
    let x = u32(floor(in.x));
    let y = u32(floor(in.y));

    let index = (1920u * y + x);
    let page = contents.map[index/16u];

    let offset = index % 16u;

    var subpage = 0u;
    let suboffset = offset / 4u;
    if (suboffset == 0u) {
        subpage = page.x;
    } else if (suboffset == 1u) {
        subpage = page.y;
    } else if (suboffset == 2u) {
        subpage = page.z;
    } else if (suboffset == 3u) {
        subpage = page.w;
    }

    let to_shift = (offset % 4u) * 8u;
    let data = subpage & (0xFFu << to_shift);
    let byte = data >> to_shift;
    let value = f32(byte) / 255.0;

    return vec4<f32>(value, value, value, 1.0);
}
```
This is my shader.wgsl file. It looks very weird, but it was to work around alignment 16 restriction. What it does is, cpu sends unsigned byte array with size 1920*1080, and divide that byte by 255.0, and use it as rgb. Because of the said restriction I had to use vec<u32> instead.
This indeed work on native hardware but it crashes on browser with this error:
```
Vendor: Google Inc. (AMD)
nfractal.js:1498 Renderer: ANGLE (AMD, RENOIR (renoir LLVM 15.0.3), OpenGL 4.6)
nfractal.js:1498 Version: WebGL 2.0 (OpenGL ES 3.0 Chromium)
nfractal.js:1501 Extensions: {
    "OVR_multiview2",
    "OES_texture_float_linear",
    "OES_draw_buffers_indexed",
    "WEBGL_provoking_vertex",
    "EXT_disjoint_timer_query_webgl2",
    "WEBGL_draw_instanced_base_vertex_base_instance",
    "EXT_float_blend",
    "EXT_texture_compression_rgtc",
    "WEBGL_debug_renderer_info",
    "KHR_parallel_shader_compile",
    "WEBGL_debug_shaders",
    "WEBGL_multi_draw_instanced_base_vertex_base_instance",
    "EXT_color_buffer_float",
    "EXT_color_buffer_half_float",
    "WEBGL_compressed_texture_s3tc_srgb",
    "EXT_texture_compression_bptc",
    "WEBGL_lose_context",
    "WEBGL_compressed_texture_s3tc",
    "WEBGL_multi_draw",
    "WEBGL_clip_cull_distance",
    "WEBGL_video_texture",
    "EXT_texture_filter_anisotropic",
    "EXT_texture_norm16",
}
nfractal.js:1498 SL version: WebGL GLSL ES 3.00 (OpenGL ES GLSL ES 3.0 Chromium)
nfractal.js:1498 Adapter Gl AdapterInfo { name: "ANGLE (AMD, RENOIR (renoir LLVM 15.0.3), OpenGL 4.6)", vendor: 4098, device: 0, device_type: Other, driver: "", driver_info: "", backend: Gl }
nfractal.js:1498 configuring surface with SurfaceConfiguration { usage: RENDER_ATTACHMENT, format: Rgba8UnormSrgb, width: 450, height: 400, present_mode: Fifo, alpha_mode: Opaque, view_formats: [] }
nfractal.js:1501 Resolving [1] = FunctionArgument(0) : Handle([4])
nfractal.js:1501 Resolving [2] = Constant([2]) : Value(Scalar { kind: Float, width: 4 })
nfractal.js:1501 Resolving [1] = FunctionArgument(0) : Handle([5])
nfractal.js:1501 Resolving [2] = AccessIndex { base: [1], index: 0 } : Value(Scalar { kind: Float, width: 4 })
nfractal.js:1501 Resolving [3] = Math { fun: Floor, arg: [2], arg1: None, arg2: None, arg3: None } : Value(Scalar { kind: Float, width: 4 })
nfractal.js:1501 Resolving [4] = As { expr: [3], kind: Uint, convert: Some(4) } : Value(Scalar { kind: Uint, width: 4 })
nfractal.js:1501 Resolving [5] = AccessIndex { base: [1], index: 1 } : Value(Scalar { kind: Float, width: 4 })
nfractal.js:1501 Resolving [6] = Math { fun: Floor, arg: [5], arg1: None, arg2: None, arg3: None } : Value(Scalar { kind: Float, width: 4 })
nfractal.js:1501 Resolving [7] = As { expr: [6], kind: Uint, convert: Some(4) } : Value(Scalar { kind: Uint, width: 4 })
nfractal.js:1501 Resolving [8] = Constant([3]) : Value(Scalar { kind: Uint, width: 4 })
nfractal.js:1501 Resolving [9] = Binary { op: Multiply, left: [8], right: [7] } : Value(Scalar { kind: Uint, width: 4 })
nfractal.js:1501 Resolving [10] = Binary { op: Add, left: [9], right: [4] } : Value(Scalar { kind: Uint, width: 4 })
nfractal.js:1501 Resolving [11] = GlobalVariable([1]) : Value(Pointer { base: [3], space: Uniform })
nfractal.js:1501 Resolving [12] = AccessIndex { base: [11], index: 0 } : Value(Pointer { base: [2], space: Uniform })
nfractal.js:1501 Resolving [13] = Constant([4]) : Value(Scalar { kind: Uint, width: 4 })
nfractal.js:1501 Resolving [14] = Binary { op: Divide, left: [10], right: [13] } : Value(Scalar { kind: Uint, width: 4 })
nfractal.js:1501 Resolving [15] = Access { base: [12], index: [14] } : Value(Pointer { base: [1], space: Uniform })
nfractal.js:1501 Resolving [16] = Load { pointer: [15] } : Handle([1])
nfractal.js:1501 Resolving [17] = Constant([4]) : Value(Scalar { kind: Uint, width: 4 })
nfractal.js:1501 Resolving [18] = Binary { op: Modulo, left: [10], right: [17] } : Value(Scalar { kind: Uint, width: 4 })
nfractal.js:1501 Resolving [19] = Constant([5]) : Value(Scalar { kind: Uint, width: 4 })
nfractal.js:1501 Resolving [20] = LocalVariable([1]) : Value(Pointer { base: [6], space: Function })
nfractal.js:1501 Resolving [21] = Constant([6]) : Value(Scalar { kind: Uint, width: 4 })
nfractal.js:1501 Resolving [22] = Binary { op: Divide, left: [18], right: [21] } : Value(Scalar { kind: Uint, width: 4 })
nfractal.js:1501 Resolving [23] = Constant([5]) : Value(Scalar { kind: Uint, width: 4 })
nfractal.js:1501 Resolving [24] = Binary { op: Equal, left: [22], right: [23] } : Value(Scalar { kind: Bool, width: 1 })
nfractal.js:1501 Resolving [25] = AccessIndex { base: [16], index: 0 } : Value(Scalar { kind: Uint, width: 4 })
nfractal.js:1501 Resolving [26] = Constant([7]) : Value(Scalar { kind: Uint, width: 4 })
nfractal.js:1501 Resolving [27] = Binary { op: Equal, left: [22], right: [26] } : Value(Scalar { kind: Bool, width: 1 })
nfractal.js:1501 Resolving [28] = AccessIndex { base: [16], index: 1 } : Value(Scalar { kind: Uint, width: 4 })
nfractal.js:1501 Resolving [29] = Constant([8]) : Value(Scalar { kind: Uint, width: 4 })
nfractal.js:1501 Resolving [30] = Binary { op: Equal, left: [22], right: [29] } : Value(Scalar { kind: Bool, width: 1 })
nfractal.js:1501 Resolving [31] = AccessIndex { base: [16], index: 2 } : Value(Scalar { kind: Uint, width: 4 })
nfractal.js:1501 Resolving [32] = Constant([9]) : Value(Scalar { kind: Uint, width: 4 })
nfractal.js:1501 Resolving [33] = Binary { op: Equal, left: [22], right: [32] } : Value(Scalar { kind: Bool, width: 1 })
nfractal.js:1501 Resolving [34] = AccessIndex { base: [16], index: 3 } : Value(Scalar { kind: Uint, width: 4 })
nfractal.js:1501 Resolving [35] = Constant([6]) : Value(Scalar { kind: Uint, width: 4 })
nfractal.js:1501 Resolving [36] = Binary { op: Modulo, left: [18], right: [35] } : Value(Scalar { kind: Uint, width: 4 })
nfractal.js:1501 Resolving [37] = Constant([10]) : Value(Scalar { kind: Uint, width: 4 })
nfractal.js:1501 Resolving [38] = Binary { op: Multiply, left: [36], right: [37] } : Value(Scalar { kind: Uint, width: 4 })
nfractal.js:1501 Resolving [39] = Load { pointer: [20] } : Handle([6])
nfractal.js:1501 Resolving [40] = Constant([11]) : Value(Scalar { kind: Uint, width: 4 })
nfractal.js:1501 Resolving [41] = Binary { op: ShiftLeft, left: [40], right: [38] } : Value(Scalar { kind: Uint, width: 4 })
nfractal.js:1501 Resolving [42] = Binary { op: And, left: [39], right: [41] } : Handle([6])
nfractal.js:1501 Resolving [43] = Binary { op: ShiftRight, left: [42], right: [38] } : Handle([6])
nfractal.js:1501 Resolving [44] = As { expr: [43], kind: Float, convert: Some(4) } : Value(Scalar { kind: Float, width: 4 })
nfractal.js:1501 Resolving [45] = Constant([12]) : Value(Scalar { kind: Float, width: 4 })
nfractal.js:1501 Resolving [46] = Binary { op: Divide, left: [44], right: [45] } : Value(Scalar { kind: Float, width: 4 })
nfractal.js:1501 Resolving [47] = Constant([2]) : Value(Scalar { kind: Float, width: 4 })
nfractal.js:1501 var GlobalVariable { name: Some("contents"), space: Uniform, binding: Some(ResourceBinding { group: 0, binding: 0 }), ty: [3], init: None }
nfractal.js:1501 var LocalVariable { name: Some("subpage"), ty: [6], init: None }
nfractal.js:1498 Created buffer Valid((0, 1, Gl)) with BufferDescriptor { label: Some("Blit contents"), size: 2073600, usage: COPY_DST | UNIFORM, mapped_at_creation: true }
nfractal.js:1501 Buffer (0, 1, Gl) map state -> Idle
nfractal.js:1501 Bind group Valid((0, 1, Gl))
nfractal.js:1501 Naga generated shader:
#version 300 es

precision highp float;
precision highp int;

struct BlitContents {
    uvec4 map[129600];
};
layout(location = 0) in vec3 _p2vs_location0;

void main() {
    vec3 vertices = _p2vs_location0;
    gl_Position = vec4(vertices, 1.0);
    gl_Position.yz = vec2(-gl_Position.y, gl_Position.z * 2.0 - gl_Position.w);
    return;
}


nfractal.js:1498 	Compiled shader WebShaderKey(1v5)
nfractal.js:1492 Shader translation error for stage VERTEX: ERROR: 0:6: 's15e6' : Size of declared private variable exceeds implementation-defined limit
�
(익명) @ nfractal.js:1492
logError @ nfractal.js:232
imports.wbg.__wbg_error_fe807da27c4a4ced @ nfractal.js:1491
$web_sys::features::gen_console::console::error_1::hc5be3088129fb498 @ nfractal_bg.wasm:0xc7a65e
$console_log::log::h7b04f26b718bced6 @ nfractal_bg.wasm:0x7d3a56
$<console_log::WebConsoleLogger as log::Log>::log::hc58b59d1cf3a8a19 @ nfractal_bg.wasm:0xbb22e6
$log::__private_api_log::h7f2b864e3bcb252a @ nfractal_bg.wasm:0x710789
$<wgpu::backend::direct::Context as wgpu::context::Context>::device_create_render_pipeline::h694b24a7aa47de8f @ nfractal_bg.wasm:0x2a1d4d
$<T as wgpu::context::DynContext>::device_create_render_pipeline::hc8ca1b69a95eb9e1 @ nfractal_bg.wasm:0xab23eb
$wgpu::Device::create_render_pipeline::ha66693dac43e110f @ nfractal_bg.wasm:0x96130b
$nfractal::State::new::{{closure}}::h169c21f01fd09b99 @ nfractal_bg.wasm:0x18b5c9
$nfractal::run::{{closure}}::h511f51b826ce0d94 @ nfractal_bg.wasm:0x4c75b8
$nfractal::_::__wasm_bindgen_generated_run::{{closure}}::h496007ac35a631ad @ nfractal_bg.wasm:0x7a7ac6
$wasm_bindgen_futures::task::singlethread::Task::run::h9d510a8982286b5c @ nfractal_bg.wasm:0x77660d
$wasm_bindgen_futures::queue::QueueState::run_all::h2b9d6b5d84f478b2 @ nfractal_bg.wasm:0x6c3954
$wasm_bindgen_futures::queue::Queue::new::{{closure}}::h4c5def4a14e9e452 @ nfractal_bg.wasm:0xb7f6fd
$<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h9e6aab68686581d7 @ nfractal_bg.wasm:0xa6a1af
__wbg_adapter_59 @ nfractal.js:302
real @ nfractal.js:215
Promise.then(비동기)
(익명) @ nfractal.js:1637
logError @ nfractal.js:232
imports.wbg.__wbg_then_ec5db6d509eb475f @ nfractal.js:1636
$js_sys::Promise::then::hc7ae769e748e5ea9 @ nfractal_bg.wasm:0xbc2a95
$wasm_bindgen_futures::queue::Queue::schedule_task::h37dcd492172d59f5 @ nfractal_bg.wasm:0x88e2fd
$wasm_bindgen_futures::task::singlethread::Task::spawn::{{closure}}::h4e553affddc1636b @ nfractal_bg.wasm:0xc88c7b
$std::thread::local::LocalKey<T>::try_with::h7dab32bed3203156 @ nfractal_bg.wasm:0x8a9807
$std::thread::local::LocalKey<T>::with::h91d90af7b2f43891 @ nfractal_bg.wasm:0xab1d17
$wasm_bindgen_futures::task::singlethread::Task::spawn::ha556ab0b9b3cf8da @ nfractal_bg.wasm:0x6bbdfa
$wasm_bindgen_futures::spawn_local::h350e93b17c3392d0 @ nfractal_bg.wasm:0xcab575
$run @ nfractal_bg.wasm:0xb85e17
finalizeInit @ nfractal.js:1793
init @ nfractal.js:1825
await in init(비동기)
(익명) @ (색인):19
nfractal.js:1492 Please report it to https://github.com/gfx-rs/naga
(익명) @ nfractal.js:1492
logError @ nfractal.js:232
imports.wbg.__wbg_error_fe807da27c4a4ced @ nfractal.js:1491
$web_sys::features::gen_console::console::error_1::hc5be3088129fb498 @ nfractal_bg.wasm:0xc7a65e
$console_log::log::h7b04f26b718bced6 @ nfractal_bg.wasm:0x7d3a56
$<console_log::WebConsoleLogger as log::Log>::log::hc58b59d1cf3a8a19 @ nfractal_bg.wasm:0xbb22e6
$log::__private_api_log::h7f2b864e3bcb252a @ nfractal_bg.wasm:0x710789
$<wgpu::backend::direct::Context as wgpu::context::Context>::device_create_render_pipeline::h694b24a7aa47de8f @ nfractal_bg.wasm:0x2a1eeb
$<T as wgpu::context::DynContext>::device_create_render_pipeline::hc8ca1b69a95eb9e1 @ nfractal_bg.wasm:0xab23eb
$wgpu::Device::create_render_pipeline::ha66693dac43e110f @ nfractal_bg.wasm:0x96130b
$nfractal::State::new::{{closure}}::h169c21f01fd09b99 @ nfractal_bg.wasm:0x18b5c9
$nfractal::run::{{closure}}::h511f51b826ce0d94 @ nfractal_bg.wasm:0x4c75b8
$nfractal::_::__wasm_bindgen_generated_run::{{closure}}::h496007ac35a631ad @ nfractal_bg.wasm:0x7a7ac6
$wasm_bindgen_futures::task::singlethread::Task::run::h9d510a8982286b5c @ nfractal_bg.wasm:0x77660d
$wasm_bindgen_futures::queue::QueueState::run_all::h2b9d6b5d84f478b2 @ nfractal_bg.wasm:0x6c3954
$wasm_bindgen_futures::queue::Queue::new::{{closure}}::h4c5def4a14e9e452 @ nfractal_bg.wasm:0xb7f6fd
$<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h9e6aab68686581d7 @ nfractal_bg.wasm:0xa6a1af
__wbg_adapter_59 @ nfractal.js:302
real @ nfractal.js:215
Promise.then(비동기)
(익명) @ nfractal.js:1637
logError @ nfractal.js:232
imports.wbg.__wbg_then_ec5db6d509eb475f @ nfractal.js:1636
$js_sys::Promise::then::hc7ae769e748e5ea9 @ nfractal_bg.wasm:0xbc2a95
$wasm_bindgen_futures::queue::Queue::schedule_task::h37dcd492172d59f5 @ nfractal_bg.wasm:0x88e2fd
$wasm_bindgen_futures::task::singlethread::Task::spawn::{{closure}}::h4e553affddc1636b @ nfractal_bg.wasm:0xc88c7b
$std::thread::local::LocalKey<T>::try_with::h7dab32bed3203156 @ nfractal_bg.wasm:0x8a9807
$std::thread::local::LocalKey<T>::with::h91d90af7b2f43891 @ nfractal_bg.wasm:0xab1d17
$wasm_bindgen_futures::task::singlethread::Task::spawn::ha556ab0b9b3cf8da @ nfractal_bg.wasm:0x6bbdfa
$wasm_bindgen_futures::spawn_local::h350e93b17c3392d0 @ nfractal_bg.wasm:0xcab575
$run @ nfractal_bg.wasm:0xb85e17
finalizeInit @ nfractal.js:1793
init @ nfractal.js:1825
await in init(비동기)
(익명) @ (색인):19
nfractal.js:1492 Handling wgpu errors as fatal by default
(익명) @ nfractal.js:1492
logError @ nfractal.js:232
imports.wbg.__wbg_error_fe807da27c4a4ced @ nfractal.js:1491
$web_sys::features::gen_console::console::error_1::hc5be3088129fb498 @ nfractal_bg.wasm:0xc7a65e
$console_log::log::h7b04f26b718bced6 @ nfractal_bg.wasm:0x7d3a56
$<console_log::WebConsoleLogger as log::Log>::log::hc58b59d1cf3a8a19 @ nfractal_bg.wasm:0xbb22e6
$log::__private_api_log::h7f2b864e3bcb252a @ nfractal_bg.wasm:0x710789
$wgpu::backend::direct::default_error_handler::h1c4986ae9c9112ba @ nfractal_bg.wasm:0x7e4923
$core::ops::function::Fn::call::h38cb2d07c965dc35 @ nfractal_bg.wasm:0xabc30f
$<alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h151740a64db76834 @ nfractal_bg.wasm:0xa748b8
$wgpu::backend::direct::ErrorSinkRaw::handle_error::hfcdd0d7b8b147842 @ nfractal_bg.wasm:0x594e28
$wgpu::backend::direct::Context::handle_error::h5dfcc9a5febd06e9 @ nfractal_bg.wasm:0x45fa90
$<wgpu::backend::direct::Context as wgpu::context::Context>::device_create_render_pipeline::h694b24a7aa47de8f @ nfractal_bg.wasm:0x2a1f60
$<T as wgpu::context::DynContext>::device_create_render_pipeline::hc8ca1b69a95eb9e1 @ nfractal_bg.wasm:0xab23eb
$wgpu::Device::create_render_pipeline::ha66693dac43e110f @ nfractal_bg.wasm:0x96130b
$nfractal::State::new::{{closure}}::h169c21f01fd09b99 @ nfractal_bg.wasm:0x18b5c9
$nfractal::run::{{closure}}::h511f51b826ce0d94 @ nfractal_bg.wasm:0x4c75b8
$nfractal::_::__wasm_bindgen_generated_run::{{closure}}::h496007ac35a631ad @ nfractal_bg.wasm:0x7a7ac6
$wasm_bindgen_futures::task::singlethread::Task::run::h9d510a8982286b5c @ nfractal_bg.wasm:0x77660d
$wasm_bindgen_futures::queue::QueueState::run_all::h2b9d6b5d84f478b2 @ nfractal_bg.wasm:0x6c3954
$wasm_bindgen_futures::queue::Queue::new::{{closure}}::h4c5def4a14e9e452 @ nfractal_bg.wasm:0xb7f6fd
$<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h9e6aab68686581d7 @ nfractal_bg.wasm:0xa6a1af
__wbg_adapter_59 @ nfractal.js:302
real @ nfractal.js:215
Promise.then(비동기)
(익명) @ nfractal.js:1637
logError @ nfractal.js:232
imports.wbg.__wbg_then_ec5db6d509eb475f @ nfractal.js:1636
$js_sys::Promise::then::hc7ae769e748e5ea9 @ nfractal_bg.wasm:0xbc2a95
$wasm_bindgen_futures::queue::Queue::schedule_task::h37dcd492172d59f5 @ nfractal_bg.wasm:0x88e2fd
$wasm_bindgen_futures::task::singlethread::Task::spawn::{{closure}}::h4e553affddc1636b @ nfractal_bg.wasm:0xc88c7b
$std::thread::local::LocalKey<T>::try_with::h7dab32bed3203156 @ nfractal_bg.wasm:0x8a9807
$std::thread::local::LocalKey<T>::with::h91d90af7b2f43891 @ nfractal_bg.wasm:0xab1d17
$wasm_bindgen_futures::task::singlethread::Task::spawn::ha556ab0b9b3cf8da @ nfractal_bg.wasm:0x6bbdfa
$wasm_bindgen_futures::spawn_local::h350e93b17c3392d0 @ nfractal_bg.wasm:0xcab575
$run @ nfractal_bg.wasm:0xb85e17
finalizeInit @ nfractal.js:1793
init @ nfractal.js:1825
await in init(비동기)
(익명) @ (색인):19
nfractal.js:407 panicked at 'wgpu error: Validation Error

Caused by:
    In Device::create_render_pipeline
      note: label = `nfractal pipeline`
    Internal error in VERTEX shader: ERROR: 0:6: 's15e6' : Size of declared private variable exceeds implementation-defined limit
�

', /home/tmvkrpxl0/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.15.1/src/backend/direct.rs:3024:5

Stack:

Error
    at http://localhost:8000/pkg/nfractal.js:413:21
    at logError (http://localhost:8000/pkg/nfractal.js:232:18)
    at imports.wbg.__wbg_new_abda76e883ba8a5f (http://localhost:8000/pkg/nfractal.js:412:66)
    at console_error_panic_hook::Error::new::h56359eebdd9dc412 (http://localhost:8000/pkg/nfractal_bg.wasm:wasm-function[33430]:0xc8827c)
    at console_error_panic_hook::hook_impl::h62aace64f8929d10 (http://localhost:8000/pkg/nfractal_bg.wasm:wasm-function[6885]:0x867f6f)
    at console_error_panic_hook::hook::h9ff032677ba2646c (http://localhost:8000/pkg/nfractal_bg.wasm:wasm-function[35920]:0xcab7e4)
    at core::ops::function::Fn::call::hb334f0da77f85a2f (http://localhost:8000/pkg/nfractal_bg.wasm:wasm-function[32100]:0xc7311e)
    at std::panicking::rust_panic_with_hook::h7f7102b82d51338f (http://localhost:8000/pkg/nfractal_bg.wasm:wasm-function[13896]:0xa59e68)
    at std::panicking::begin_panic_handler::{{closure}}::hfa40135feb109919 (http://localhost:8000/pkg/nfractal_bg.wasm:wasm-function[17702]:0xb072dd)
    at std::sys_common::backtrace::__rust_end_short_backtrace::haf21bfec9a028e09 (http://localhost:8000/pkg/nfractal_bg.wasm:wasm-function[42353]:0xcec2a4)


(익명) @ nfractal.js:407
logError @ nfractal.js:232
imports.wbg.__wbg_error_f851667af71bcfc6 @ nfractal.js:405
$console_error_panic_hook::error::hd29b8a11067ff17b @ nfractal_bg.wasm:0xbed5f0
$console_error_panic_hook::hook_impl::h62aace64f8929d10 @ nfractal_bg.wasm:0x868060
$console_error_panic_hook::hook::h9ff032677ba2646c @ nfractal_bg.wasm:0xcab7e4
$core::ops::function::Fn::call::hb334f0da77f85a2f @ nfractal_bg.wasm:0xc7311e
$std::panicking::rust_panic_with_hook::h7f7102b82d51338f @ nfractal_bg.wasm:0xa59e68
$std::panicking::begin_panic_handler::{{closure}}::hfa40135feb109919 @ nfractal_bg.wasm:0xb072dd
$std::sys_common::backtrace::__rust_end_short_backtrace::haf21bfec9a028e09 @ nfractal_bg.wasm:0xcec2a4
$rust_begin_unwind @ nfractal_bg.wasm:0xc25890
$core::panicking::panic_fmt::he4489d678d6570d5 @ nfractal_bg.wasm:0xca9e7b
$wgpu::backend::direct::default_error_handler::h1c4986ae9c9112ba @ nfractal_bg.wasm:0x7e49a0
$core::ops::function::Fn::call::h38cb2d07c965dc35 @ nfractal_bg.wasm:0xabc30f
$<alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h151740a64db76834 @ nfractal_bg.wasm:0xa748b8
$wgpu::backend::direct::ErrorSinkRaw::handle_error::hfcdd0d7b8b147842 @ nfractal_bg.wasm:0x594e28
$wgpu::backend::direct::Context::handle_error::h5dfcc9a5febd06e9 @ nfractal_bg.wasm:0x45fa90
$<wgpu::backend::direct::Context as wgpu::context::Context>::device_create_render_pipeline::h694b24a7aa47de8f @ nfractal_bg.wasm:0x2a1f60
$<T as wgpu::context::DynContext>::device_create_render_pipeline::hc8ca1b69a95eb9e1 @ nfractal_bg.wasm:0xab23eb
$wgpu::Device::create_render_pipeline::ha66693dac43e110f @ nfractal_bg.wasm:0x96130b
$nfractal::State::new::{{closure}}::h169c21f01fd09b99 @ nfractal_bg.wasm:0x18b5c9
$nfractal::run::{{closure}}::h511f51b826ce0d94 @ nfractal_bg.wasm:0x4c75b8
$nfractal::_::__wasm_bindgen_generated_run::{{closure}}::h496007ac35a631ad @ nfractal_bg.wasm:0x7a7ac6
$wasm_bindgen_futures::task::singlethread::Task::run::h9d510a8982286b5c @ nfractal_bg.wasm:0x77660d
$wasm_bindgen_futures::queue::QueueState::run_all::h2b9d6b5d84f478b2 @ nfractal_bg.wasm:0x6c3954
$wasm_bindgen_futures::queue::Queue::new::{{closure}}::h4c5def4a14e9e452 @ nfractal_bg.wasm:0xb7f6fd
$<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h9e6aab68686581d7 @ nfractal_bg.wasm:0xa6a1af
__wbg_adapter_59 @ nfractal.js:302
real @ nfractal.js:215
Promise.then(비동기)
(익명) @ nfractal.js:1637
logError @ nfractal.js:232
imports.wbg.__wbg_then_ec5db6d509eb475f @ nfractal.js:1636
$js_sys::Promise::then::hc7ae769e748e5ea9 @ nfractal_bg.wasm:0xbc2a95
$wasm_bindgen_futures::queue::Queue::schedule_task::h37dcd492172d59f5 @ nfractal_bg.wasm:0x88e2fd
$wasm_bindgen_futures::task::singlethread::Task::spawn::{{closure}}::h4e553affddc1636b @ nfractal_bg.wasm:0xc88c7b
$std::thread::local::LocalKey<T>::try_with::h7dab32bed3203156 @ nfractal_bg.wasm:0x8a9807
$std::thread::local::LocalKey<T>::with::h91d90af7b2f43891 @ nfractal_bg.wasm:0xab1d17
$wasm_bindgen_futures::task::singlethread::Task::spawn::ha556ab0b9b3cf8da @ nfractal_bg.wasm:0x6bbdfa
$wasm_bindgen_futures::spawn_local::h350e93b17c3392d0 @ nfractal_bg.wasm:0xcab575
$run @ nfractal_bg.wasm:0xb85e17
finalizeInit @ nfractal.js:1793
init @ nfractal.js:1825
await in init(비동기)
(익명) @ (색인):19
(색인):20 WASM Loaded
nfractal_bg.wasm:0xcec4ea Uncaught (in promise) RuntimeError: unreachable
    at __rust_start_panic (nfractal_bg.wasm:0xcec4ea)
    at rust_panic (nfractal_bg.wasm:0xcdcc20)
    at std::panicking::rust_panic_with_hook::h7f7102b82d51338f (nfractal_bg.wasm:0xa59e95)
    at std::panicking::begin_panic_handler::{{closure}}::hfa40135feb109919 (nfractal_bg.wasm:0xb072dd)
    at std::sys_common::backtrace::__rust_end_short_backtrace::haf21bfec9a028e09 (nfractal_bg.wasm:0xcec2a4)
    at rust_begin_unwind (nfractal_bg.wasm:0xc25890)
    at core::panicking::panic_fmt::he4489d678d6570d5 (nfractal_bg.wasm:0xca9e7b)
    at wgpu::backend::direct::default_error_handler::h1c4986ae9c9112ba (nfractal_bg.wasm:0x7e49a0)
    at core::ops::function::Fn::call::h38cb2d07c965dc35 (nfractal_bg.wasm:0xabc30f)
    at <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h151740a64db76834 (nfractal_bg.wasm:0xa748b8)
$
```
Or here's part of the error in image:
![image](https://user-images.githubusercontent.com/41675181/236985679-33f6bbe6-744b-45c1-9161-8f82fdabc69d.png)

**Comment by teoxoy** [comment]
Private variables are indeed limited to (at a minimum) 65535 bytes (see https://gpuweb.github.io/gpuweb/wgsl/#limits) but I don't see any private variable in your shader. We also don't even have this limit yet.

Considering this works on native but not on WebGL via ANGLE, this might be an issue with Angle but I can't seem to find anyone else getting the "Size of declared private variable exceeds implementation-defined limit" error.

**Comment by tmvkrpxl0** [comment]
Should I use other buffers such as texture instead?

**Comment by teoxoy** [comment]
Instead of `var<uniform> contents: BlitContents;`? Yeah, you can try to use a Texture instead.

**Comment by tmvkrpxl0** [comment]
Yeah ive already reimplemented with it
