### ISSUE TITLE
Internal error: entered unreachable code: metal requires all arrays be constant sized

### ISSUE THREAD

**Issue by wgslfuzz** [gfx-rs/wgpu#4512]
On git commit 33b75a27 naga panics with the following backtrace when executing `naga input.wgsl output.metal`

```
thread 'main' panicked at src/back/msl/writer.rs:229:21:
internal error: entered unreachable code: metal requires all arrays be constant sized
stack backtrace:
   0: rust_begin_unwind
             at /rustc/030e4d382f1df30240408540f25cd1ccc8dbbf50/library/std/src/panicking.rs:619:5
   1: core::panicking::panic_fmt
             at /rustc/030e4d382f1df30240408540f25cd1ccc8dbbf50/library/core/src/panicking.rs:72:14
   2: <naga::back::msl::writer::TypeContext as core::fmt::Display>::fmt
   3: core::fmt::rt::Argument::fmt
             at /rustc/030e4d382f1df30240408540f25cd1ccc8dbbf50/library/core/src/fmt/rt.rs:138:9
   4: core::fmt::write
             at /rustc/030e4d382f1df30240408540f25cd1ccc8dbbf50/library/core/src/fmt/mod.rs:1094:21
   5: naga::back::msl::writer::TypedGlobalVariable::try_fmt
   6: naga::back::msl::writer::Writer<W>::write_functions
   7: naga::back::msl::writer::Writer<W>::write
   8: naga::back::msl::write_string
   9: naga::write_output
  10: naga::main
```

```wgsl
@group(0) @binding(0) 
var g: binding_array<texture_2d<f32>>;

@group(0) @binding(1)
var g_1: binding_array<texture_2d<f32>, 5>; 

@group(0) @binding(6)
var g_6: binding_array<sampler, 5>; 

@fragment
fn main() {
    let uv = vec2<f32>(0.0);
    textureDimensions(g[0]);
    textureSampleGrad(g_1[0], g_6[0], uv, uv, uv);
}
```

**Comment by Jefffrey** [comment]
This can probably be closed. Testing on latest trunk 48904f8e769a9b1ef146032a4fc94c53a1e02e00 on M4 Macbook, if I try the raw file I'll get some errors (but not `unreachable!()` panics), e.g.

```sh
wgpu (trunk)$ cargo run --bin naga -- input.wgsl output.metal
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.08s
     Running `/Users/jeffrey/.cargo_target_cache/debug/naga input.wgsl output.metal`
Could not parse WGSL:
error: the `wgpu_binding_array` enable extension is not enabled
  ┌─ input.wgsl:2:8
  │
2 │ var g: binding_array<texture_2d<f32>>;
  │        ^^^^^^^^^^^^^ the `wgpu_binding_array` "Enable Extension" is needed for this functionality, but it is not currently enabled.
  │
  = note: You can enable this extension by adding `enable wgpu_binding_array;` at the top of the shader, before any other items.
```

But if I fix them up as such:

```diff
+ enable wgpu_binding_array;
+
@group(0) @binding(0)
var g: binding_array<texture_2d<f32>>;

@group(0) @binding(1)
var g_1: binding_array<texture_2d<f32>, 5>;

@group(0) @binding(6)
var g_6: binding_array<sampler, 5>;

@fragment
fn main() {
    let uv = vec2<f32>(0.0);
-   textureDimensions(g[0]);
-   textureSampleGrad(g_1[0], g_6[0], uv, uv, uv);
+   let a = textureDimensions(g[0]);
+   let b = textureSampleGrad(g_1[0], g_6[0], uv, uv, uv);
}
```

And run with supported Metal version (2.0 and above) then it succeeds:

```sh
wgpu (trunk)$ cargo run --bin naga -- --metal-version 2.0 input.wgsl output.metal
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.09s
     Running `/Users/jeffrey/.cargo_target_cache/debug/naga --metal-version 2.0 input.wgsl output.metal`
```

**Comment by ErichDonGubler** [comment]
@Jefffrey: Are you saying that you were able to reproduce the problem before? If so, I agree, we can close this.

**Comment by Jefffrey** [comment]
yes, i checked out the commit above and ran with the exact input:

```sh
wgpu ((33b75a27))$ cargo run --bin naga -- input.wgsl output.metal
...(bunch of clippy warnings)...
thread 'main' (31381852) panicked at src/back/msl/writer.rs:229:21:
internal error: entered unreachable code: metal requires all arrays be constant sized
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fish: Job 1, 'cargo run --bin naga -- input.w…' terminated by signal SIGABRT (Abort)
wgpu ((33b75a27))$ git show
commit 33b75a27d93c6574b11b4dd4492b85b5783d6c52 (HEAD)
Author: Nicolas Silva <nical@fastmail.com>
Date:   Tue Oct 10 18:13:19 2023 +0200

    [wgsl-in] Parse the bgra8unorm storage format (#2550)


Δ src/front/wgsl/parse/conv.rs
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

───────────────────────────────────────────────────────────────────────────────────────┐
• 98: pub fn map_storage_format(word: &str, span: Span) -> Result<crate::StorageFormat │
───────────────────────────────────────────────────────────────────────────────────────┘
 98 ⋮ 98 │        "rgba32uint" => Sf::Rgba32Uint,
 99 ⋮ 99 │        "rgba32sint" => Sf::Rgba32Sint,
 100⋮ 100│        "rgba32float" => Sf::Rgba32Float,
    ⋮ 101│        "bgra8unorm" => Sf::Bgra8Unorm,
 101⋮ 102│        _ => return Err(Error::UnknownStorageFormat(span)),
 102⋮ 103│    })
 103⋮ 104│}
wgpu ((33b75a27))$ cat input.wgsl
@group(0) @binding(0)
var g: binding_array<texture_2d<f32>>;

@group(0) @binding(1)
var g_1: binding_array<texture_2d<f32>, 5>;

@group(0) @binding(6)
var g_6: binding_array<sampler, 5>;

@fragment
fn main() {
    let uv = vec2<f32>(0.0);
    textureDimensions(g[0]);
    textureSampleGrad(g_1[0], g_6[0], uv, uv, uv);
}
```
