### ISSUE TITLE
No bind target was defined for the push constants block

### ISSUE THREAD

**Issue by wgslfuzz** [gfx-rs/wgpu#4513]
On git commit 33b75a2 naga panics with the following backtrace when executing `naga input.wgsl output.hlsl`

```
thread 'main' panicked at src/back/hlsl/writer.rs:740:18:
No bind target was defined for the push constants block
stack backtrace:
   0: rust_begin_unwind
             at /rustc/030e4d382f1df30240408540f25cd1ccc8dbbf50/library/std/src/panicking.rs:619:5
   1: core::panicking::panic_fmt
             at /rustc/030e4d382f1df30240408540f25cd1ccc8dbbf50/library/core/src/panicking.rs:72:14
   2: core::panicking::panic_display
             at /rustc/030e4d382f1df30240408540f25cd1ccc8dbbf50/library/core/src/panicking.rs:168:5
   3: core::panicking::panic_str
             at /rustc/030e4d382f1df30240408540f25cd1ccc8dbbf50/library/core/src/panicking.rs:152:5
   4: core::option::expect_failed
             at /rustc/030e4d382f1df30240408540f25cd1ccc8dbbf50/library/core/src/option.rs:1988:5
   5: naga::back::hlsl::writer::<impl naga::back::hlsl::Writer<W>>::write
   6: naga::write_output
   7: naga::main
```

```wgsl
struct t { 
    m: f32,
}

struct s { 
    @location(0) m: vec4<f32>,
}

var<push_constant> g: t;

@fragment
fn main(l: s) -> @location(0) vec4<f32> {
    return (l.m * g.m);
}
```

**Comment by teoxoy** [comment]
There are instances like these where the cli doesn't have enough information to generate valid code.

https://github.com/gfx-rs/naga/blob/c5d884fca8b56ac957530c7184ee050cc5fd67ec/src/back/hlsl/writer.rs#L733-L746

I'm not sure what we can do here, allow users to somehow specify the mapping via the cli?
