### ISSUE TITLE
 Index out of bounds in valid/analyzer.rs

### ISSUE THREAD

**Issue by wgslfuzz** [gfx-rs/wgpu#4547]
On git commit https://github.com/gfx-rs/naga/commit/5b65f11e3cb491707f9cdbb78388972367feb52d naga panics with the following backtrace when executing `naga input.wgsl output.msl`

```
thread 'main' panicked at src/valid/analyzer.rs:372:34:
index out of bounds: the len is 1 but the index is 1
stack backtrace:
   0: rust_begin_unwind
             at /rustc/030e4d382f1df30240408540f25cd1ccc8dbbf50/library/std/src/panicking.rs:619:5
   1: core::panicking::panic_fmt
             at /rustc/030e4d382f1df30240408540f25cd1ccc8dbbf50/library/core/src/panicking.rs:72:14
   2: core::panicking::panic_bounds_check
             at /rustc/030e4d382f1df30240408540f25cd1ccc8dbbf50/library/core/src/panicking.rs:180:5
   3: naga::valid::analyzer::FunctionInfo::process_block
   4: naga::valid::function::<impl naga::valid::Validator>::validate_function
   5: naga::valid::Validator::validate
   6: naga::main
```

```wgsl
@group(0) @binding(0)
var g: texture_2d<f32>;

fn f(s: sampler, t: texture_2d<f32>) {
    textureSample(t, s, vec2<f32>(0.0, 0.0));
}

fn main() {
    f(g);
}
```

**Comment by jamienicol** [comment]
This was fixed by 601f235b345baf907a8478d37d6756948fab9639. It now gives this error message rather than a panic:

```
error: Function [1] 'main' is invalid
  ┌─ in.wgsl:8:1
  │
8 │ ╭ fn main() {
9 │ │     f(g);
  │ │     ^^^^ invalid function call
  │ ╰─────────^ naga::Function [1]
  │
  = Call to [0] is invalid
  = Requires 2 arguments, but 1 are provided
```
