### ISSUE TITLE
Unwrap crash on wgpu_render_pass_end_pass

### ISSUE THREAD

**Issue by LaylConway** [gfx-rs/wgpu#455]
Not entirely sure where the unwrap in question is happening, I looked through the stack trace and couldn't find it.

Trimmed stack trace:

```
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', src\libcore\option.rs:378:21
stack backtrace:
   0: backtrace::backtrace::trace_unsynchronized
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.40\src\backtrace\mod.rs:66
   1: std::sys_common::backtrace::_print_fmt
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\sys_common\backtrace.rs:77
   2: std::sys_common::backtrace::_print::{{impl}}::fmt
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\sys_common\backtrace.rs:61
   3: core::fmt::write
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libcore\fmt\mod.rs:1028
   4: std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\io\mod.rs:1412
   5: std::sys_common::backtrace::_print
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\sys_common\backtrace.rs:65
   6: std::sys_common::backtrace::print
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\sys_common\backtrace.rs:50
   7: std::panicking::default_hook::{{closure}}
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\panicking.rs:188
   8: std::panicking::default_hook
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\panicking.rs:205
   9: std::panicking::rust_panic_with_hook
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\panicking.rs:464
  10: std::panicking::continue_panic_fmt
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\panicking.rs:373
  11: std::panicking::rust_begin_panic
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libstd\panicking.rs:302
  12: core::panicking::panic_fmt
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libcore\panicking.rs:139
  13: core::panicking::panic
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libcore\panicking.rs:70
  14: core::option::Option<wgpu_core::RefCount*>::unwrap<wgpu_core::RefCount*>
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\src\libcore\macros.rs:41
  15: wgpu_core::track::ResourceTracker<wgpu_core::track::Unit<wgpu_core::resource::BufferUsage>>::use_extend<wgpu_core::track::Unit<wgpu_core::resource::BufferUsage>,wgpu_core::resource::Buffer<gfx_backend_vulkan::Backend>>
             at C:\Users\Layl\Desktop\wgpu\wgpu-core\src\track\mod.rs:402
  16: wgpu_core::command::render::{{impl}}::command_encoder_run_render_pass::{{closure}}<lock_api::mutex::Mutex<parking_lot::raw_mutex::RawMutex, wgpu_core::hub::IdentityManager>,gfx_backend_vulkan::Backend>
             at C:\Users\Layl\Desktop\wgpu\wgpu-core\src\command\render.rs:963
  17: core::iter::adapters::map_fold::{{closure}}<(mut wgpu_core::command::render::VertexBufferState*, (wgpu_core::id::Id<wgpu_core::resource::Buffer<gfx_backend_empty::Backend>>*, u64*)),(gfx_backend_vulkan::native::Buffer*, u64),(),closure-19,closure-0>
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\src\libcore\iter\adapters\mod.rs:694
  18: core::iter::traits::iterator::Iterator::fold::ok::{{closure}}<(),(mut wgpu_core::command::render::VertexBufferState*, (wgpu_core::id::Id<wgpu_core::resource::Buffer<gfx_backend_empty::Backend>>*, u64*)),closure-0>
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\src\libcore\iter\traits\iterator.rs:1828
  19: core::iter::traits::iterator::Iterator::try_fold<core::iter::adapters::zip::Zip<core::slice::IterMut<wgpu_core::command::render::VertexBufferState>, core::iter::adapters::zip::Zip<core::slice::Iter<wgpu_core::id::Id<wgpu_core::resource::Buffer<gfx_backend
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\src\libcore\iter\traits\iterator.rs:1709
  20: core::iter::traits::iterator::Iterator::fold<core::iter::adapters::zip::Zip<core::slice::IterMut<wgpu_core::command::render::VertexBufferState>, core::iter::adapters::zip::Zip<core::slice::Iter<wgpu_core::id::Id<wgpu_core::resource::Buffer<gfx_backend_emp
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\src\libcore\iter\traits\iterator.rs:1831
  21: core::iter::adapters::{{impl}}::fold<(gfx_backend_vulkan::native::Buffer*, u64),core::iter::adapters::zip::Zip<core::slice::IterMut<wgpu_core::command::render::VertexBufferState>, core::iter::adapters::zip::Zip<core::slice::Iter<wgpu_core::id::Id<wgpu_cor
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\src\libcore\iter\adapters\mod.rs:727
  22: core::iter::adapters::{{impl}}::fold<(ash::vk::Buffer, u64),core::iter::adapters::Map<core::iter::adapters::zip::Zip<core::slice::IterMut<wgpu_core::command::render::VertexBufferState>, core::iter::adapters::zip::Zip<core::slice::Iter<wgpu_core::id::Id<wg
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\src\libcore\iter\adapters\mod.rs:727
  23: core::iter::traits::iterator::Iterator::for_each<core::iter::adapters::Map<core::iter::adapters::Map<core::iter::adapters::zip::Zip<core::slice::IterMut<wgpu_core::command::render::VertexBufferState>, core::iter::adapters::zip::Zip<core::slice::Iter<wgpu_
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\src\libcore\iter\traits\iterator.rs:631
  24: core::iter::traits::iterator::Iterator::unzip<core::iter::adapters::Map<core::iter::adapters::Map<core::iter::adapters::zip::Zip<core::slice::IterMut<wgpu_core::command::render::VertexBufferState>, core::iter::adapters::zip::Zip<core::slice::Iter<wgpu_cor
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\src\libcore\iter\traits\iterator.rs:2409
  25: gfx_backend_vulkan::command::{{impl}}::bind_vertex_buffers<core::iter::adapters::Map<core::iter::adapters::zip::Zip<core::slice::IterMut<wgpu_core::command::render::VertexBufferState>, core::iter::adapters::zip::Zip<core::slice::Iter<wgpu_core::id::Id<wgp
             at C:\Users\Layl\.cargo\registry\src\github.com-1ecc6299db9ec823\gfx-backend-vulkan-0.4.0\src\command.rs:527
  26: wgpu_core::hub::Global<lock_api::mutex::Mutex<parking_lot::raw_mutex::RawMutex, wgpu_core::hub::IdentityManager>>::command_encoder_run_render_pass<lock_api::mutex::Mutex<parking_lot::raw_mutex::RawMutex, wgpu_core::hub::IdentityManager>,gfx_backend_vulkan
             at C:\Users\Layl\Desktop\wgpu\wgpu-core\src\command\render.rs:974
  27: wgpu_native::command::wgpu_render_pass_end_pass
             at C:\Users\Layl\Desktop\wgpu\wgpu-native\src\command.rs:114
  28: kinematic_rendering::surface::render_world
             at .\crates\rendering\src\surface.rs:193
  29: kinematic_rendering::surface::SurfaceRenderer::render_frame
             at .\crates\rendering\src\surface.rs:77
  30: kinematic_pc::rendering::surface::surface_render_worker::{{closure}}
             at .\binaries\kinematic-pc\src\rendering\surface.rs:80
```

**Comment by kvark** [comment]
Figured it's an expected panic, because a resource does no longer exist by the time we finish the pass. We could have a better error message, for this I'm leaving the issue open.
Note: for Rust, wgpu-rs enforces this at compile time.

**Comment by cwfitzgerald** [comment]
The error message issue should have been solved by various error refactors.
