### ISSUE TITLE
Window surface exceeding max_texture_dimension_2d

### ISSUE THREAD

**Issue by dhardy** [gfx-rs/wgpu#4576]
According to the documentation, usage `Limits` may not exceed those requested for an adapter, and the default value of `max_texture_dimension_2d` is 8192.

My device claims to support a `max_texture_dimension_2d` of 16384.

Using the default limits, I can create and use a draw surface of size 16384x16384 without error. If I understand correctly, this should result in a validation error due to the lower (default) limit being requested?

Attempting to configure a surface where one side has size 16385 results in a panic:
```
Error in Surface::configure: Validation Error

Caused by:
    Not enough memory left.
```
The error message *could* be better.

---

Question: to support a UI framework with freely resizable windows should I always request the maximum supported `max_texture_dimension_2d`?

**Comment by cwfitzgerald** [comment]
> Question: to support a UI framework with freely resizable windows should I always request the maximum supported max_texture_dimension_2d?

Yes, there's even a helper to help you do this. See the example here: https://github.com/gfx-rs/wgpu/blob/trunk/examples/common/src/framework.rs#L224

Seems we are just flat out missing size checks on this, so the OOM is coming directly from the driver.

**Comment by wez** [comment]
FWIW: I found this issue because I just got hit by a panic when resizing my window in 0.19. In 0.18 I could freely resize my window. I consider this to be a somewhat scary change in behavior as part of this upgrade; I don't know what else might also panic in this version that worked previously!

For reference, the relevant portions of the panic stack trace are:

```
   6: wgpu::backend::wgpu_core::ContextWgpuCore::handle_error_fatal
             at /home/wez/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.19.0/src/backend/wgpu_core.rs:283:9
   7: <wgpu::backend::wgpu_core::ContextWgpuCore as wgpu::context::Context>::surface_configure
             at /home/wez/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.19.0/src/backend/wgpu_core.rs:724:13
   8: <T as wgpu::context::DynContext>::surface_configure
             at /home/wez/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.19.0/src/context.rs:2124:9
   9: wgpu::Surface::configure
             at /home/wez/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.19.0/src/lib.rs:4811:9
  10: wezterm_gui::termwindow::webgpu::WebGpuState::resize
             at wezterm-gui/src/termwindow/webgpu.rs:553:13
  11: wezterm_gui::termwindow::resize::<impl wezterm_gui::termwindow::TermWindow>::resize
```

with:

```
thread 'main' panicked at /home/wez/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.19.0/src/backend/wgpu_core.rs:724:18:
Error in Surface::configure: Validation Error

Caused by:
    `Surface` width and height must be within the maximum supported texture size. Requested was (2063, 1458), maximum extent is 2048.
```

Also: the link to framework.rs is no longer valid (got moved), the code at the time of writing the comment above was:

https://github.com/gfx-rs/wgpu/blob/daedf03f0617aab6b3ab7380132dc9cb07f62d32/examples/common/src/framework.rs#L223-L224

Applying the adapter limits as shown in the linked example does resolve the panic I encountered, so that's good!

I think what I'm experiencing is actually the opposite of the behavior in the OP, so I guess this is an example of how you can't please everyone :)
