### ISSUE TITLE
Always "Not enough memory left."

### ISSUE THREAD

**Issue by torsteingrindvik** [gfx-rs/wgpu#4810]
**Description**

 I get `Not enough memory left.` everywhere, even `hello_triangle`.

First noticed while running a Bevy app, then I tried a simple Bevy example, then I tried `wgpu` on trunk a9c582166dd478483b6e61123ddb32934d9a88cd 

since Bevy `main` is on an older version of `wgpu` things seem even more uncertain.

I'm on arch linux and did a system update, perhaps issues because of a very recent version of NVIDIA drivers?

No clue how to debug.

**Extra materials**

```
➜  wgpu git:(trunk) c rrb wgpu-examples hello_triangle
    Finished release [optimized] target(s) in 0.08s
     Running `target/release/wgpu-examples hello_triangle`
thread 'main' panicked at 'Error in Surface::configure: Validation Error

Caused by:
    Not enough memory left.
', wgpu/src/backend/direct.rs:782:18
stack backtrace:
   0:     0x563b433ce5ca - std::backtrace_rs::backtrace::libunwind::trace::h9a6b80bbf328ba5d
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x563b433ce5ca - std::backtrace_rs::backtrace::trace_unsynchronized::hd162ec543a11886b
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x563b433ce5ca - std::sys_common::backtrace::_print_fmt::h78a5099be12f51a6
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x563b433ce5ca - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::ha1c5390454d74f71
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x563b433f5d6f - core::fmt::write::h9ffde816c577717b
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/fmt/mod.rs:1254:17
   5:     0x563b433ca9f5 - std::io::Write::write_fmt::h88186074961638e4
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/io/mod.rs:1698:15
   6:     0x563b433ce395 - std::sys_common::backtrace::_print::h184198273ed08d59
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x563b433ce395 - std::sys_common::backtrace::print::h1b4d8e7add699453
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x563b433cf91e - std::panicking::default_hook::{{closure}}::h393bcea75423915a
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:269:22
   9:     0x563b433cf6c5 - std::panicking::default_hook::h48c64f31d8b3fd03
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:288:9
  10:     0x563b433cfede - std::panicking::rust_panic_with_hook::hafdc493a79370062
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:691:13
  11:     0x563b433cfdd9 - std::panicking::begin_panic_handler::{{closure}}::h0a64bc82e36bedc7
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:582:13
  12:     0x563b433cea36 - std::sys_common::backtrace::__rust_end_short_backtrace::hc203444fb7416a16
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:150:18
  13:     0x563b433cfb32 - rust_begin_unwind
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:578:5
  14:     0x563b433f3653 - core::panicking::panic_fmt::h0f6ef0178afce4f2
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:67:14
  15:     0x563b430b3c06 - wgpu::backend::direct::Context::handle_error_fatal::h4a18f74a5b8bd2cf
  16:     0x563b430b6b87 - <wgpu::backend::direct::Context as wgpu::context::Context>::surface_configure::ha160cfd08259ce95
  17:     0x563b430c4f9c - <T as wgpu::context::DynContext>::surface_configure::h51ad0a61f8002917
  18:     0x563b43186712 - wgpu::Surface::configure::ha8833c95f0b23d62
  19:     0x563b42d76612 - pollster::block_on::h8f8e7059e678ec87
  20:     0x563b42d1b161 - wgpu_examples::hello_triangle::main::hed8b9283bb041f76
  21:     0x563b42bfb092 - wgpu_examples::main::h0a5a5353ec0d0fdc
  22:     0x563b42bfa263 - std::sys_common::backtrace::__rust_begin_short_backtrace::h2df7be810924b26b
  23:     0x563b42bfb119 - std::rt::lang_start::{{closure}}::h7346ff0ca9cf7ea2
  24:     0x563b433c596e - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hb1327dc2ef3fecdf
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/ops/function.rs:287:13
  25:     0x563b433c596e - std::panicking::try::do_call::h4044173225fe83dd
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:485:40
  26:     0x563b433c596e - std::panicking::try::hd8a722c09d156a53
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:449:19
  27:     0x563b433c596e - std::panic::catch_unwind::hd2ca07971cf0119b
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panic.rs:140:14
  28:     0x563b433c596e - std::rt::lang_start_internal::{{closure}}::h26d89d595cf47b70
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/rt.rs:148:48
  29:     0x563b433c596e - std::panicking::try::do_call::hf47aa1aa005e5f1a
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:485:40
  30:     0x563b433c596e - std::panicking::try::h73d246b2423eaf4e
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:449:19
  31:     0x563b433c596e - std::panic::catch_unwind::hbaaeae8f1b2f9915
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panic.rs:140:14
  32:     0x563b433c596e - std::rt::lang_start_internal::h76f3e81e6b8f13f9
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/rt.rs:148:20
  33:     0x563b42bfb105 - main
  34:     0x7fa3ca680cd0 - <unknown>
  35:     0x7fa3ca680d8a - __libc_start_main
  36:     0x563b42bfa185 - _start
  37:                0x0 - <unknown>
```

**Platform**

```
2023-11-30T14:05:28.754448Z  INFO wgpu_core::instance: Adapter Vulkan AdapterInfo { name: "NVIDIA GeForce RTX 4080 Laptop GPU", vendor: 4318, device: 10144, device_type: DiscreteGpu, driver: "NVIDIA", driver_info: "545.29.06", backend: Vulkan }    
```

**Comment by torsteingrindvik** [comment]
After a _second_ reboot- it works :slightly_frowning_face:
