### ISSUE TITLE
Android Exception

### ISSUE THREAD

**Issue by dt665m** [gfx-rs/wgpu#4942]
**Description**
Bevy example panics on android on apple silicon sonoma device.  I think this is a platform specific issue.  The android emulator could be funky on apple silicon.

**Repro steps**
OSX Sonoma Apple Silicon + [bevy v0.12.1](https://github.com/bevyengine/bevy/tree/v0.12.1)'s android example `cargo apk run -p bevy_mobile_example` using the SDK 33 and 31 both fail for me.  Someone else also mentioned this in #3972 

**Expected vs observed behavior**
Example should run instead of panic

**Extra materials**
```
12-28 22:08:15.114  4386  4432 I RustStdoutStderr: thread 'Compute Task Pool (1)' panicked at /Users/denistsai/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.17.2/src/backend/direct.rs:3056:5:
12-28 22:08:15.115  4386  4432 I RustStdoutStderr: wgpu error: Validation Error
12-28 22:08:15.115  4386  4432 I RustStdoutStderr:
12-28 22:08:15.115  4386  4432 I RustStdoutStderr: Caused by:
12-28 22:08:15.115  4386  4432 I RustStdoutStderr:     In Device::create_render_pipeline
12-28 22:08:15.115  4386  4432 I RustStdoutStderr:       note: label = `copy_deferred_lighting_id_pipeline`
12-28 22:08:15.115  4386  4432 I RustStdoutStderr:     Error matching ShaderStages(VERTEX) shader requirements against the pipeline
12-28 22:08:15.115  4386  4432 I RustStdoutStderr:     Shader uses 2 inter-stage components above the limit of 0
12-28 22:08:15.115  4386  4432 I RustStdoutStderr:
12-28 22:08:15.115  4386  4432 I RustStdoutStderr:
12-28 22:08:15.115  4386  4432 I RustStdoutStderr: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
12-28 22:08:15.139  4386  4432 I RustStdoutStderr: Encountered a panic in system `bevy_render::render_resource::pipeline_cache::PipelineCache::process_pipeline_queue_system`!
12-28 22:08:15.160  4386  4432 I RustStdoutStderr: thread 'Compute Task Pool (1)' panicked at /Users/denistsai/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_render-0.12.1/src/pipelined_rendering.rs:145:45:
12-28 22:08:15.160  4386  4432 I RustStdoutStderr: called `Result::unwrap()` on an `Err` value: RecvError
12-28 22:08:15.185  4386  4433 E RustPanic: called `Result::unwrap()` on an `Err` value: RecvError
12-28 22:08:15.510  4386  4432 I RustStdoutStderr: thread '<unnamed>' panicked at /Users/denistsai/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ndk-context-0.1.1/src/lib.rs:72:30:
12-28 22:08:15.510  4386  4432 I RustStdoutStderr: android context was not initialized
```

```
INFO    | Android emulator version 33.1.23.0 (build_id 11150993) (CL:N/A)
INFO    | Found systemPath /Users/denistsai/Library/Android/sdk/system-images/android-33/google_apis_playstore/arm64-v8a/
INFO    | Storing crashdata in: , detection is enabled for process: 3722
INFO    | Duplicate loglines will be removed, if you wish to see each individual line launch with the -log-nofilter flag.
INFO    | Warning: QMetaObject::connectSlotsByName: No matching signal for on_new_posture_requested(int) ((null):0, (null))
INFO    | Warning: QMetaObject::connectSlotsByName: No matching signal for on_dismiss_posture_selection_dialog() ((null):0, (null))
INFO    | Warning: QMetaObject::connectSlotsByName: No matching signal for on_new_resizable_requested(PresetEmulatorSizeType) ((null):0, (null))
INFO    | Warning: QMetaObject::connectSlotsByName: No matching signal for on_dismiss_resizable_dialog() ((null):0, (null))
library_mode host gpu mode host
I1228 22:07:34.534507 5915300 HealthMonitor.cpp:279] HealthMonitor disabled.
cannot add library /Users/denistsai/Library/Android/sdk/emulator/qemu/darwin-aarch64/lib64/vulkan/libvulkan.dylib: failed
added library /Users/denistsai/Library/Android/sdk/emulator/lib64/vulkan/libvulkan.dylib
createGlobalVkEmulation:963 Selecting Vulkan device: SwiftShader Device (LLVM 10.0.0)
initialize: Supports id properties, got a vulkan device UUID
I1228 22:07:34.579367 5915300 VkCommonOperations.cpp:1225] Initializing VkEmulation features:
I1228 22:07:34.579381 5915300 VkCommonOperations.cpp:1226]     glInteropSupported: false
I1228 22:07:34.579384 5915300 VkCommonOperations.cpp:1227]     useDeferredCommands: true
I1228 22:07:34.579386 5915300 VkCommonOperations.cpp:1229]     createResourceWithRequirements: true
I1228 22:07:34.579389 5915300 VkCommonOperations.cpp:1230]     useVulkanComposition: false
I1228 22:07:34.579391 5915300 VkCommonOperations.cpp:1231]     useVulkanNativeSwapchain: false
I1228 22:07:34.579393 5915300 VkCommonOperations.cpp:1232]     enable guestRenderDoc: false
I1228 22:07:34.579395 5915300 VkCommonOperations.cpp:1233]     ASTC LDR emulation mode: 2
I1228 22:07:34.579397 5915300 VkCommonOperations.cpp:1234]     enable ETC2 emulation: true
I1228 22:07:34.579400 5915300 VkCommonOperations.cpp:1235]     enable Ycbcr emulation: false
I1228 22:07:34.579402 5915300 VkCommonOperations.cpp:1236]     guestUsesAngle: false
I1228 22:07:34.579404 5915300 VkCommonOperations.cpp:1237]     useDedicatedAllocations: false
I1228 22:07:34.579667 5915300 FrameBuffer.cpp:486] Graphics Adapter Vendor Google (Apple)
I1228 22:07:34.579674 5915300 FrameBuffer.cpp:487] Graphics Adapter Android Emulator OpenGL ES Translator (Apple M1 Max)
I1228 22:07:34.579676 5915300 FrameBuffer.cpp:488] Graphics API Version OpenGL ES 3.0 (4.1 Metal - 86)
I1228 22:07:34.579679 5915300 FrameBuffer.cpp:489] Graphics API Extensions GL_OES_EGL_sync GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_depth24 GL_OES_depth32 GL_OES_element_index_uint GL_OES_texture_float GL_OES_texture_float_linear GL_OES_compressed_paletted_texture GL_OES_compressed_ETC1_RGB8_texture GL_OES_depth_texture GL_OES_texture_npot GL_OES_rgb8_rgba8 GL_EXT_color_buffer_float GL_EXT_color_buffer_half_float GL_EXT_texture_format_BGRA8888 GL_APPLE_texture_format_BGRA8888
I1228 22:07:34.579682 5915300 FrameBuffer.cpp:490] Graphics Device Extensions N/A
INFO    | Sending adb public key [QAAAABWDWlzDS8utzEj0f52GiUWaUs/LfUelkM0adGyLWUEoOIKUunvdx4jZGPjaHQ7TGoQCTJWIFgh29KDlwv5MCI8c2mLWQOZ6FHvpI87hxS1XHSd1NL/cGdmZhOHEcGq0XosV0o8aYKtcmxxqMhBF7A6Cuikrr8lqcgkZ0+C2F8ac730zQFdc4yGkATT6pJnVrOJ/gStxJVf7xmUzFgqOu9ZTiGtn0ggvb5iDcxq+UGvLnjiVF8Jmnyce56i1MHXioJucJNH4rBd90r/gk2ejdS8p2FIYcZljToMa7pRuyo7GyeVkkiZ0UvBfEvFWtnSvLvaTRS9LK1uDl0p92tswfL3apT/BbRypn1ZuL5EsfGXi3mNP7MbVyRO+HOAtPKdjS1Dcfd1ShIfPRWZ1RZ+X55ecuOCE1HfG+ZuVWusXbd/HpR3BpOhhnxxKHChyywlcx8NFs1aFN844YNnzl6H8l0r8v0YSjchxQ/+Tyel3wxsKJ9+84I+xcaghwtA/tE3fBhIhcywgeK6Yyc3Ji0a/Xl7KEh62yyAWqXNMmAeTOYq0aSax0NbbVJyO7c1kSx5U4v9Ysg5kdh/zskJCsxDnymplPBQcmFSBGnbILV3Jfb0T1K3VGxfa3KHoeK9gQwdyirGrsGnMV+IMhYfGaafMo5y+m5u2T/n/7f3oLPDSnZbRQRK7kAEAAQA= denistsai@unknown]
WARNING | The emulator now requires a signed jwt token for gRPC access! Use the -grpc flag if you really want an open unprotected grpc port
INFO    | Using security allow list from: /Users/denistsai/Library/Android/sdk/emulator/lib/emulator_access.json
WARNING | *** Basic token auth should only be used by android-studio ***
INFO    | The active JSON Web Key Sets can be found here: /Users/denistsai/Library/Caches/TemporaryItems/avd/running/3722/jwks/b3c652a6-f807-4066-872b-82c67fd68579/active.jwk
INFO    | Scanning /Users/denistsai/Library/Caches/TemporaryItems/avd/running/3722/jwks/b3c652a6-f807-4066-872b-82c67fd68579 for jwk keys.
INFO    | Started GRPC server at 127.0.0.1:8554, security: Local, auth: +token
INFO    | Advertising in: /Users/denistsai/Library/Caches/TemporaryItems/avd/running/pid_3722.ini
I1228 22:07:35.710470 ce5f000 FrameBuffer.cpp:3682] setDisplayConfigs w 1080 h 2400 dpiX 420 dpiY 420
I1228 22:07:35.710524 ce5f000 FrameBuffer.cpp:3695] setDisplayActiveConfig 0
INFO    | Loading snapshot 'default_boot'...
WARNING | Device 'encrypt' does not have the requested snapshot 'default_boot'
WARNING | Failed to load snapshot 'default_boot'
INFO    | Activated packet streamer for bluetooth emulation
INFO    | Boot completed in 23169 ms
INFO    | Increasing screen off timeout, logcat buffer size to 2M.
I1228 22:08:13.857483 7f7f000 VkDecoderGlobalState.cpp:444] Creating Vulkan instance for app: wgpu
I1228 22:08:13.857505 7f7f000 VkDecoderGlobalState.cpp:447] Creating Vulkan instance for engine: wgpu-hal
```

**Platform**
Bevy 0.12.1 
wgpu 0.17.2 
Android SDK 33 and 31
NDK 26.1
Rust 1.74.0
MacOS Sonoma, Apple Silicon

**Comment by dt665m** [comment]
This might be a bevy issue on initialization.  I found a solution and posted it here: https://github.com/bevyengine/bevy/issues/10945
