### ISSUE TITLE
WebGPU support detection doesn't handle failure at `getContext()`

### ISSUE THREAD

**Issue by kpreid** [gfx-rs/wgpu#5332]
**Description**
Enabling the "webgpu" backend can cause WebGL support to be lost.

**Repro steps**
1. Use Firefox 123.0 on macOS.
2. Set `dom.webgpu.enabled` to true.
3. Visit https://wgpu.rs/examples/?backend=webgl2&example=bunnymark

**Expected vs observed behavior**
Expected: The demo should display, using either webgpu or webgl2.
Observed: it fails to initialize:
`CreateSurfaceError { inner: Web("canvas.getContext() returned null; webgpu not available or canvas already in use") }`

WebGPU detection is presumably concluding WebGPU is supported [because `navigator.gpu` exists](https://github.com/gfx-rs/wgpu/blob/2d8d045453855f6594c42a6988692253da195323/wgpu/src/lib.rs#L1795-L1796), but that is evidently not sufficient.

(Note that it is also possible for a canvas to return null for the context simply because it was _previously used_ as `"webgl2"` rather than `"webgpu"`. That would be nice to support too, but since it would require a simultaneous WebGPU-or-WebGL2 backend, understandable to skip.)

**Platform**
* Firefox 123.0
* macOS
* wgpu 0.19.3

**Comment by Wumpf** [comment]
As I understand `navigator.gpu` existence is _supposed_ to signify webgpu support, but I ran into the same issue and had to do an [elaborate workaround](https://github.com/emilk/egui/pull/3895).
The whole situation is surprisingly hard to solve with the way things are set up right now: In order to check whether the `Instance` should be a WebGPU instance, we have to first instantiate the adapter and if that fails turn around and create a different instance. So fixing this likely needs us to step back a bit and rethink how all of this works.

**Comment by Wumpf** [comment]
Related to:
* #5142

**Comment by kpreid** [comment]
> In order to check whether the Instance should be a WebGPU instance, we have to first instantiate the adapter and if that fails turn around and create a different instance. So fixing this likely needs us to step back a bit and rethink how all of this works.

Oh, this is actually a feasible _workaround_ in applications which create the instance and adapter together, since it can be done purely using the wgpu API! I'll have to try that. Would be nice to have it mentioned in wgpu's docs until this bug can be fixed (or Firefox can be ?more conformant?).

**Comment by kpreid** [comment]
I tried implementing the workaround: creating an instance, surface, and adapter first with `Backends::BROWSER_WEBGPU`, and then `wgpu::Backends::GL` if that fails. But, I got a panic when WebGPU isn't supported/enabled in the browser at all:

> panicked at /Users/kpreid/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-core-0.19.3/src/instance.rs:521:39:
called `Option::unwrap()` on a `None` value

This appears to be the bug already fixed by <https://github.com/gfx-rs/wgpu/pull/5166>. But it can be avoided by using `Backends::all()` in the first attempt, and then initialization succeeds in all cases I've tested.

**Comment by dv29** [comment]
I'm getting this as well. Tried running it locally and https://wgpu.rs/examples/?backend=webgpu&example=bunnymark both give the same error. I'm going to investigate it unless a fix is already in the works

```
panicked at examples/src/framework.rs:148:65:
called `Result::unwrap()` on an `Err` value: CreateSurfaceError { inner: Web("canvas.getContext() returned null; webgpu not available or canvas already in use") }
```

**Comment by cwfitzgerald** [comment]
There is not, go ahead :)

**Comment by dv29** [comment]
So it seems that firefox only supports [WebGPU API on Nightly](https://developer.mozilla.org/en-US/docs/Web/API/WebGPU_API#browser_compatibility), I tried it with nightly and its works.
I'm not sure why `dom.webgpu.enabled` did not work though, i'm guessing that it only affects on Nightly builds.
I'm going to try to fall back on WebGL as you suggested on #5142 (btw this is my first time with this project)

**Comment by Wumpf** [comment]
I for one observed that issue on Linux Chrome where they (afaik as of writing) still don't support WebGPU. wgpu incorrectly picks webgpu over webgl there

**Comment by Wumpf** [comment]
There's now proper webgpu supprot via new utilities:
* https://github.com/gfx-rs/wgpu/pull/6371

But I think we still have to use that in the samples correctly!
