### ISSUE TITLE
Seg fault with Wayland + Nvidia 535 drivers

### ISSUE THREAD

**Issue by acarl005** [gfx-rs/wgpu#5487]
**Description**

If I run any of the examples with `WGPU_POWER_PREF=high`, I get a seg fault.

**Repro steps**

```sh
WGPU_POWER_PREF=high cargo run --bin wgpu-examples -- mipmap
```
```
    Finished dev [unoptimized + debuginfo] target(s) in 0.10s
     Running `target/debug/wgpu-examples mipmap`
[2024-04-03T19:55:50Z WARN  sctk_adwaita::buttons] Ignoring unknown button type: icon
[2024-04-03T19:55:50Z INFO  wgpu_examples::framework] Initializing wgpu...
[2024-04-03T19:55:52Z INFO  wgpu_core::instance] Adapter Vulkan AdapterInfo { name: "NVIDIA GeForce RTX 3050 4GB Laptop GPU", vendor: 4318, device: 9643, device_type: DiscreteGpu, driver: "NVIDIA", driver_info: "535.161.07", backend: Vulkan }
[2024-04-03T19:55:52Z INFO  wgpu_examples::framework] Using NVIDIA GeForce RTX 3050 4GB Laptop GPU (Vulkan)
[2024-04-03T19:55:52Z INFO  wgpu_examples::framework] Entering event loop...
[2024-04-03T19:55:52Z INFO  wgpu_examples::framework] Surface resume PhysicalSize { width: 800, height: 600 }
[1]    97446 segmentation fault (core dumped)  WGPU_POWER_PREF=high cargo run --bin wgpu-examples -- mipmap
```

Interestingly, if I force winit to use X11, via `WAYLAND_DISPLAY=""` then it _doesn't_ crash and runs just fine.

**Expected vs observed behavior**

I expect no crash with Wayland and high power pref.

**Platform**

Current `trunk` branch of wgpu, commit `ed843f802974eae9d708d3b3895264e9efb01dc6`.

```
uname -a
```
```
Linux queenie 6.5.0-21-generic #21~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Feb  9 13:32:52 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
```
```
nvidia-smi
```
```
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.161.07             Driver Version: 535.161.07   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3050 ...    Off | 00000000:01:00.0 Off |                  N/A |
| N/A   45C    P0              N/A /  25W |      3MiB /  4096MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      2055      G   /usr/bin/gnome-shell                          1MiB |
+---------------------------------------------------------------------------------------+
```

**Comment by cwfitzgerald** [comment]
If you run the program in a debugger, so you get a good backtrace for the crash?

**Comment by acarl005** [comment]
```sh
cargo build
WGPU_POWER_PREF=high gdb --args target/debug/wgpu-examples mipmap
```
```
GNU gdb (Ubuntu 12.1-0ubuntu1~22.04) 12.1
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from target/debug/wgpu-examples...
warning: Missing auto-load script at offset 0 in section .debug_gdb_scripts
of file /home/andy/src/wgpu/target/debug/wgpu-examples.
Use `info auto-load python-scripts [REGEXP]' to list them.
(gdb) r
Starting program: /home/andy/src/wgpu/target/debug/wgpu-examples mipmap
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[Detaching after vfork from child process 10422]
[Detaching after vfork from child process 10424]
[Detaching after vfork from child process 10429]
[Detaching after vfork from child process 10430]
[2024-04-09T14:31:37Z WARN  sctk_adwaita::buttons] Ignoring unknown button type: icon
[2024-04-09T14:31:37Z INFO  wgpu_examples::framework] Initializing wgpu...
[New Thread 0x7fffe03ff640 (LWP 10432)]
[New Thread 0x7fffdfbfe640 (LWP 10433)]
[New Thread 0x7fffdf3fd640 (LWP 10434)]
[New Thread 0x7fffdebfc640 (LWP 10435)]
[New Thread 0x7fffde3fb640 (LWP 10436)]
[New Thread 0x7fffddbfa640 (LWP 10437)]
[New Thread 0x7fffdd3f9640 (LWP 10438)]
[New Thread 0x7fffdcbf8640 (LWP 10439)]
[New Thread 0x7fffb7fff640 (LWP 10440)]
[New Thread 0x7fffbffff640 (LWP 10441)]
[New Thread 0x7fffbf7fe640 (LWP 10442)]
[New Thread 0x7fffbeffd640 (LWP 10443)]
[New Thread 0x7fffbe7fc640 (LWP 10444)]
[New Thread 0x7fffbdffb640 (LWP 10445)]
[New Thread 0x7fffbd7fa640 (LWP 10446)]
[New Thread 0x7fffbcff9640 (LWP 10447)]
[New Thread 0x7fffb77fe640 (LWP 10448)]
[New Thread 0x7fffb6ffd640 (LWP 10449)]
[New Thread 0x7fffb67fc640 (LWP 10450)]
[2024-04-09T14:31:37Z INFO  wgpu_core::instance] Adapter Vulkan AdapterInfo { name: "NVIDIA GeForce RTX 3050 4GB Laptop GPU", vendor: 4318, device: 9643, device_type: DiscreteGpu, driver: "NVIDIA", driver_info: "535.161.07", backend: Vulkan }
[2024-04-09T14:31:37Z INFO  wgpu_examples::framework] Using NVIDIA GeForce RTX 3050 4GB Laptop GPU (Vulkan)
[New Thread 0x7fffb5ffb640 (LWP 10451)]
[New Thread 0x7fffb57fa640 (LWP 10452)]
[New Thread 0x7fffb4ff9640 (LWP 10453)]
[New Thread 0x7fff7ffff640 (LWP 10454)]
[2024-04-09T14:31:37Z INFO  wgpu_examples::framework] Entering event loop...
[2024-04-09T14:31:37Z INFO  wgpu_examples::framework] Surface resume PhysicalSize { width: 800, height: 600 }

Thread 1 "wgpu-examples" received signal SIGSEGV, Segmentation fault.
_dl_close (_map=0x0) at ./elf/dl-close.c:795
795	./elf/dl-close.c: No such file or directory.
```

**Comment by acarl005** [comment]
Sorry, I just learned how to get a full stacktrace from `gdb`. Here's the full stacktrace for the case above:

```
#0  _dl_close (_map=0x0) at ./elf/dl-close.c:795
#1  0x00007ffff7d74a98 in __GI__dl_catch_exception (exception=exception@entry=0x7fffffff6f70, operate=<optimized out>, args=<optimized out>) at ./elf/dl-error-skeleton.c:208
#2  0x00007ffff7d74b63 in __GI__dl_catch_error (objname=0x7fffffff6fc8, errstring=0x7fffffff6fd0, mallocedp=0x7fffffff6fc7, operate=<optimized out>, args=<optimized out>)
    at ./elf/dl-error-skeleton.c:227
#3  0x00007ffff7c9012e in _dlerror_run (operate=<optimized out>, args=<optimized out>) at ./dlfcn/dlerror.c:138
#4  0x00007ffff7c8fe58 in __dlclose (handle=<optimized out>) at ./dlfcn/dlclose.c:31
#5  0x00007fffac401e0d in ProducerCleanup () from /lib/x86_64-linux-gnu/libnvidia-vulkan-producer.so
#6  0x00007fffac4020db in ProducerInit () from /lib/x86_64-linux-gnu/libnvidia-vulkan-producer.so
#7  0x00007fffea41a0e2 in ?? () from /lib/x86_64-linux-gnu/libnvidia-glcore.so.535.171.04
#8  0x00007fffea44442f in ?? () from /lib/x86_64-linux-gnu/libnvidia-glcore.so.535.171.04
#9  0x00007fffea46844d in ?? () from /lib/x86_64-linux-gnu/libnvidia-glcore.so.535.171.04
#10 0x00007fffebd75b50 in ?? () from /lib/x86_64-linux-gnu/libGLX_nvidia.so.0
#11 0x00007ffff7b74c4e in ?? () from /lib/x86_64-linux-gnu/libvulkan.so.1
#12 0x00005555568d0990 in ash::extensions::khr::swapchain::Swapchain::create_swapchain (self=0x7fffffff7610, create_info=0x7fffffff7800, allocation_callbacks=...)
    at /home/andy/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ash-0.37.3+1.3.251/src/extensions/khr/swapchain.rs:54
#13 0x000055555678ce36 in wgpu_hal::vulkan::Device::create_swapchain (self=0x55555816ffa0, surface=0x5555576a81a0, config=0x7fffffff90b0, provided_old_swapchain=...)
    at wgpu-hal/src/vulkan/device.rs:606
#14 0x000055555679d916 in wgpu_hal::vulkan::instance::{impl#6}::configure (self=0x5555576a81a0, device=0x55555816ffa0, config=0x7fffffff90b0)
    at wgpu-hal/src/vulkan/instance.rs:898
#15 0x000055555664e66c in wgpu_core::global::Global<wgpu_core::identity::IdentityManagerFactory>::surface_configure<wgpu_core::identity::IdentityManagerFactory, wgpu_hal::vulkan::Api> (self=0x555557bddbd0, surface_id=..., device_id=..., config=0x7fffffff9dd0) at wgpu-core/src/device/global.rs:2039
#16 0x00005555565a61bd in wgpu::backend::wgpu_core::{impl#7}::surface_configure (self=0x555557bddbd0, surface=0x7fffffff99b0, surface_data=0x555558173530,
    device=0x7fffffff99b8, _device_data=0x5555581730d0, config=0x7fffffff9dd0) at wgpu/src/backend/wgpu_core.rs:722
#17 0x00005555565d16dc in wgpu::context::{impl#5}::surface_configure<wgpu::backend::wgpu_core::ContextWgpuCore> (self=0x555557bddbd0, surface=0x7fffffffd6d0,
    surface_data=..., device=0x7fffffffd568, device_data=..., config=0x7fffffff9dd0) at wgpu/src/context.rs:2124
#18 0x000055555638f910 in wgpu::Surface::configure (self=0x7fffffffd6a0, device=0x7fffffffd548, config=0x7fffffff9dd0) at wgpu/src/lib.rs:4818
#19 0x0000555555a4c8bc in wgpu_examples::framework::SurfaceWrapper::resume (self=0x7fffffffd6a0, context=0x7fffffffd508, window=..., srgb=true)
    at examples/src/framework.rs:200
#20 0x00005555559eea9a in wgpu_examples::framework::start::{async_fn#0}::{closure#0}<wgpu_examples::mipmap::Example> (event=..., target=0x555557695130)
    at examples/src/framework.rs:395
#21 0x00005555559cca0f in core::ops::function::impls::{impl#3}::call_mut<(winit::event::Event<()>, &winit::event_loop::EventLoopWindowTarget<()>), wgpu_examples::framework::start::{async_fn#0}::{closure_env#0}<wgpu_examples::mipmap::Example>> (self=0x7fffffffc608, args=...)
    at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/ops/function.rs:294
#22 0x000055555594c95e in winit::platform_impl::platform::wayland::event_loop::EventLoop<()>::single_iteration<(), &mut wgpu_examples::framework::start::{async_fn#0}::{closure_env#0}<wgpu_examples::mipmap::Example>> (self=0x555557695080, callback=0x7fffffffc608, cause=...)
    at /home/andy/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.9/src/platform_impl/linux/wayland/event_loop/mod.rs:340
#23 0x0000555555930131 in winit::platform_impl::platform::wayland::event_loop::EventLoop<()>::pump_events<(), &mut wgpu_examples::framework::start::{async_fn#0}::{closure_env#0}<wgpu_examples::mipmap::Example>> (self=0x555557695080, timeout=..., callback=0x7fffffffd508)
    at /home/andy/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.9/src/platform_impl/linux/wayland/event_loop/mod.rs:231
#24 0x0000555555931319 in winit::platform_impl::platform::wayland::event_loop::EventLoop<()>::run_on_demand<(), wgpu_examples::framework::start::{async_fn#0}::{closure_env#0}--Type <RET> for more, q to quit, c to continue without paging--
<wgpu_examples::mipmap::Example>> (self=0x555557695080, event_handler=...)
    at /home/andy/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.9/src/platform_impl/linux/wayland/event_loop/mod.rs:201
#25 0x0000555555a13486 in winit::platform_impl::platform::EventLoop<()>::run_on_demand<(), wgpu_examples::framework::start::{async_fn#0}::{closure_env#0}<wgpu_examples::mipmap::Example>> (self=0x7fffffffc9a8, callback=...) at /home/andy/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.9/src/platform_impl/linux/mod.rs:821
#26 0x0000555555a1443a in winit::platform_impl::platform::EventLoop<()>::run<(), wgpu_examples::framework::start::{async_fn#0}::{closure_env#0}<wgpu_examples::mipmap::Example>> (self=<error reading variable: Cannot access memory at address 0x0>, callback=<error reading variable: Cannot access memory at address 0x199>)
    at /home/andy/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.9/src/platform_impl/linux/mod.rs:814
#27 0x00005555556ffd88 in winit::event_loop::EventLoop<()>::run<(), wgpu_examples::framework::start::{async_fn#0}::{closure_env#0}<wgpu_examples::mipmap::Example>> (
    self=..., event_handler=...) at /home/andy/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.9/src/event_loop.rs:249
#28 0x00005555559e410b in wgpu_examples::framework::start::{async_fn#0}<wgpu_examples::mipmap::Example> () at examples/src/framework.rs:390
#29 0x00005555558a13d5 in pollster::block_on<wgpu_examples::framework::start::{async_fn_env#0}<wgpu_examples::mipmap::Example>> (fut=...)
    at /home/andy/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pollster-0.3.0/src/lib.rs:128
#30 0x00005555559f157f in wgpu_examples::framework::run<wgpu_examples::mipmap::Example> (title=...) at examples/src/framework.rs:482
#31 0x0000555555916b83 in wgpu_examples::mipmap::main () at examples/src/mipmap/mod.rs:504
#32 0x00005555556ff28b in wgpu_examples::main () at examples/src/main.rs:229
```

**Comment by Oliver-makes-code** [comment]
Confirming this crash on Arch Linux with Nvidia driver version 570.124.04-S

Backtrace:
```
#0  0x00007ffff7fb388c in ?? () from /usr/lib/libwayland-client.so.0
#1  0x00007ffff7fb3a01 in ?? () from /usr/lib/libwayland-client.so.0
#2  0x00007ffff7fb3b30 in wl_proxy_destroy () from /usr/lib/libwayland-client.so.0
#3  0x00007fffe7939029 in ?? () from /usr/lib/libnvidia-glcore.so.570.124.04
#4  0x00007fffe7923055 in ?? () from /usr/lib/libnvidia-glcore.so.570.124.04
#5  0x00007fffe79316e3 in ?? () from /usr/lib/libnvidia-glcore.so.570.124.04
#6  0x00007fffe79700d6 in ?? () from /usr/lib/libnvidia-glcore.so.570.124.04
#7  0x00007fffe16a95e5 in ?? () from /usr/lib/libVkLayer_khronos_validation.so
#8  0x00007fffe1a06dbb in ?? () from /usr/lib/libVkLayer_khronos_validation.so
#9  0x000055555676f8f9 in ash::extensions_generated::khr::swapchain::Device::destroy_swapchain (self=0x7fffffffba08, swapchain=..., allocation_callbacks=...)
    at /home/octal/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ash-0.38.0+1.3.281/src/extensions/khr/swapchain.rs:36
#10 0x0000555556754dbb in wgpu_hal::vulkan::instance::{impl#7}::unconfigure (self=0x55555702bc20, device=0x5555576b77b0) at src/vulkan/instance.rs:987
#11 0x00005555564ec7b9 in wgpu_hal::dynamic::surface::{impl#0}::unconfigure<wgpu_hal::vulkan::Surface> (self=0x55555702bc20, device=...)
    at /home/octal/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-24.0.2/src/dynamic/surface.rs:47
#12 0x00005555565e9ab2 in wgpu_core::instance::{impl#4}::drop (self=0x55555778c540) at src/instance.rs:466
#13 0x000055555652aee7 in core::ptr::drop_in_place<wgpu_core::instance::Surface> ()
--Type <RET> for more, q to quit, c to continue without paging--
    at /home/octal/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:521
#14 0x00005555564ad232 in alloc::sync::Arc<wgpu_core::instance::Surface, alloc::alloc::Global>::drop_slow<wgpu_core::instance::Surface, alloc::alloc::Global> (
    self=0x7fffffffbf28) at /home/octal/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/sync.rs:1888
#15 0x00005555564b247a in alloc::sync::{impl#37}::drop<wgpu_core::instance::Surface, alloc::alloc::Global> (self=0x7fffffffbf28)
    at /home/octal/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/sync.rs:2575
#16 0x000055555653168b in core::ptr::drop_in_place<alloc::sync::Arc<wgpu_core::instance::Surface, alloc::alloc::Global>> ()
    at /home/octal/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:521
#17 0x000055555657733f in wgpu_core::global::Global::surface_drop (self=0x5555571c7380, id=...) at src/instance.rs:832
#18 0x000055555637ac06 in wgpu::backend::wgpu_core::{impl#56}::drop (self=0x55555778e120) at src/backend/wgpu_core.rs:3486
#19 0x0000555556391cc7 in core::ptr::drop_in_place<wgpu::backend::wgpu_core::CoreSurface> ()
    at /home/octal/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:521
#20 0x000055555637d362 in alloc::sync::Arc<wgpu::backend::wgpu_core::CoreSurface, alloc::alloc::Global>::drop_slow<wgpu::backend::wgpu_core::CoreSurface, alloc::alloc::Global>
    (self=0x7fffffffd148) at /home/octal/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/sync.rs:1888
#21 0x000055555637d5ca in alloc::sync::{impl#37}::drop<wgpu::backend::wgpu_core::CoreSurface, alloc::alloc::Global> (self=0x7fffffffd148)
    at /home/octal/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/sync.rs:2575
#22 0x0000555556393deb in core::ptr::drop_in_place<alloc::sync::Arc<wgpu::backend::wgpu_core::CoreSurface, alloc::alloc::Global>> ()
--Type <RET> for more, q to quit, c to continue without paging--
    at /home/octal/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:521
#23 0x000055555639168b in core::ptr::drop_in_place<wgpu::dispatch::DispatchSurface> ()
    at /home/octal/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:521
#24 0x0000555555bf3aeb in core::ptr::drop_in_place<wgpu::api::surface::Surface> ()
    at /home/octal/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:521
#25 0x0000555555bf3a43 in core::ptr::drop_in_place<pawprint::runtime::Runtime> ()
    at /home/octal/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:521
#26 0x0000555555bf4945 in core::ptr::drop_in_place<core::option::Option<pawprint::runtime::Runtime>> ()
    at /home/octal/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:521
#27 0x0000555555bf397a in core::ptr::drop_in_place<pawprint::runtime::App> ()
    at /home/octal/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:521
#28 0x0000555555be3bf6 in pawprint::main () at src/main.rs:33
```

**Comment by cwfitzgerald** [comment]
This may be https://github.com/gfx-rs/wgpu/issues/5781, try keeping your window alive longer than your surface.

**Comment by Heraclito-Q-Saldanha** [comment]
I have the exact same behavior on an AMD video card

WM: sway
GPU: RX6600

reproduction steps: run the 02_hello_window example

running with WAYLAND_DISPLAY="" makes everything run fine

the error only occurs when closing the window

![Image](https://github.com/user-attachments/assets/5ff24576-5b61-4d5d-913c-b9e551d32e53)
