### ISSUE TITLE
    Internal error in ShaderStages(VERTEX | FRAGMENT) shader: new_render_pipeline_state: "Compiler encountered an internal error"

### ISSUE THREAD

**Issue by ekalosak** [gfx-rs/wgpu#5788]
On macOS 12.x, I get this error:
```
thread 'Compute Task Pool (2)' panicked at /Users/eric/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.19.4/src/backend/wgpu_core.rs:3006:5:
wgpu error: Validation Error

Caused by:
    In Device::create_render_pipeline
      note: label = `pbr_opaque_mesh_pipeline`
    Internal error in ShaderStages(VERTEX | FRAGMENT) shader: new_render_pipeline_state: "Compiler encountered an internal error"

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Encountered a panic in system `bevy_core_pipeline::upscaling::prepare_view_upscaling_pipelines`!
thread 'Compute Task Pool (1)' panicked at /Users/eric/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_render-0.13.2/src/pipelined_rendering.rs:49:67:
called `Result::unwrap()` on an `Err` value: RecvError
thread 'main' panicked at /Users/eric/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.15/src/platform_impl/macos/app_state.rs:387:33:
called `Result::unwrap()` on an `Err` value: PoisonError { .. }
```

As this occurs on legacy hardware (that can't update to latest macOS) I don't suspect there will be high priority for it, but as the error requests I report it here, I have.

Thanks for the incredible tooling, it works great on my Ubuntu system, just not on this ancient mac.

**Comment by ekalosak** [comment]
Duplicates https://github.com/gfx-rs/wgpu/issues/4817 but as that is closed (because I'd found a work-around) and this issue is not resolved, on circling back, seems useful to have it open for others searching.
