### ISSUE TITLE
NotSupported(NotSupportedError) when attempting to run example

### ISSUE THREAD

**Issue by RedPlayer1** [gfx-rs/wgpu#6128]
**Description**
When running any example in the [examples](https://github.com/gfx-rs/wgpu/tree/trunk/examples/src) directory, some form of NotSupportedError is thrown. Looking at the backtrace, it seems this line is the culprit:
```rust
EventLoop::new().unwrap();
```

**Repro steps**
- Clone the repo
- Run ```cargo run --bin wgpu-examples hello_triangle```

**Expected vs observed behavior**
Expected behavior is shown in the [example's README](https://github.com/gfx-rs/wgpu/blob/trunk/examples/src/hello_triangle/README.md), but the following error is emitted instead:
```
thread 'main' panicked at examples/src/hello_triangle/mod.rs:149:39:
called `Result::unwrap()` on an `Err` value: NotSupported(NotSupportedError)
```

**Extra materials**
When run with ```RUST_BACKTRACE=1```
<details>
<br>

```
    Finished dev [unoptimized + debuginfo] target(s) in 0.14s
     Running `target/debug/wgpu-examples hello_triangle`
thread 'main' panicked at examples/src/hello_triangle/mod.rs:149:39:
called `Result::unwrap()` on an `Err` value: NotSupported(NotSupportedError)
stack backtrace:
   0: rust_begin_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/result.rs:1649:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/result.rs:1073:23
   4: wgpu_examples::hello_triangle::main
             at ./examples/src/hello_triangle/mod.rs:149:22
   5: wgpu_examples::main
             at ./examples/src/main.rs:229:5
   6: core::ops::function::FnOnce::call_once
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:250:5
```
</details>

When run with ```RUST_BACKTRACE=full```
<details>
<br>

```
Finished dev [unoptimized + debuginfo] target(s) in 0.14s
     Running `target/debug/wgpu-examples hello_triangle`
thread 'main' panicked at examples/src/hello_triangle/mod.rs:149:39:
called `Result::unwrap()` on an `Err` value: NotSupported(NotSupportedError)
stack backtrace:
   0:     0x7f2f6887fc66 - std::backtrace_rs::backtrace::libunwind::trace::h7d9d6777fb8bb20d
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x7f2f6887fc66 - std::backtrace_rs::backtrace::trace_unsynchronized::h9c973399eff3243c
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f2f6887fc66 - std::sys_common::backtrace::_print_fmt::hcfcb0438b59f41ac
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x7f2f6887fc66 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h12ff509796e7db1f
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f2f688c54a0 - core::fmt::rt::Argument::fmt::h0f89a5eb60e0da5a
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/fmt/rt.rs:142:9
   5:     0x7f2f688c54a0 - core::fmt::write::hd2897b7ab92710d9
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/fmt/mod.rs:1120:17
   6:     0x7f2f6887d1ef - std::io::Write::write_fmt::h7aec362f631668c1
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/io/mod.rs:1810:15
   7:     0x7f2f6887fa44 - std::sys_common::backtrace::_print::h02de5e3a7ec93331
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x7f2f6887fa44 - std::sys_common::backtrace::print::h39dfbda16576800a
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7f2f68880fa7 - std::panicking::default_hook::{{closure}}::h9d3976e3cec30e20
  10:     0x7f2f68880d09 - std::panicking::default_hook::h8f0238c5452f23e8
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:292:9
  11:     0x7f2f68881438 - std::panicking::rust_panic_with_hook::hc412fca92650d4b2
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:779:13
  12:     0x7f2f68881312 - std::panicking::begin_panic_handler::{{closure}}::hf6e9952ead3e2c54
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:657:13
  13:     0x7f2f68880166 - std::sys_common::backtrace::__rust_end_short_backtrace::h1410a9c85ac94b3e
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:171:18
  14:     0x7f2f68881070 - rust_begin_unwind
                             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
  15:     0x7f2f671b50a5 - core::panicking::panic_fmt::h2838d0515af9b2ed
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
  16:     0x7f2f671b56e3 - core::result::unwrap_failed::he2d03f3cb0a94e0c
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/result.rs:1649:5
  17:     0x7f2f671ccd2f - core::result::Result<T,E>::unwrap::he1c40f0404a0bf6f
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/result.rs:1073:23
  18:     0x7f2f672898d8 - wgpu_examples::hello_triangle::main::h8287eb11c5c3dc11
                               at /home/jxr5t/Dev/wgpu/examples/src/hello_triangle/mod.rs:149:22
  19:     0x7f2f671b637f - wgpu_examples::main::h9554d4467fb579ab
                               at /home/jxr5t/Dev/wgpu/examples/src/main.rs:229:5
  20:     0x7f2f671b687b - core::ops::function::FnOnce::call_once::h8efef3aba1e75667
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:250:5
  21:     0x7f2f671b5c2e - std::sys_common::backtrace::__rust_begin_short_backtrace::h647a47a3c2b4d20b
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:155:18
  22:     0x7f2f671b5e41 - std::rt::lang_start::{{closure}}::h28cd3ae0e9f6089d
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/rt.rs:166:18
  23:     0x7f2f68875a58 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hbd70bf23aaabb1f2
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:284:13
  24:     0x7f2f68875a58 - std::panicking::try::do_call::h34a2aa1a42d8b296
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:552:40
  25:     0x7f2f68875a58 - std::panicking::try::ha9060f095dce4b29
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:516:19
  26:     0x7f2f68875a58 - std::panic::catch_unwind::h6bae8dd14d964496
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panic.rs:142:14
  27:     0x7f2f68875a58 - std::rt::lang_start_internal::{{closure}}::h4ced5aadb57c4e33
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/rt.rs:148:48
  28:     0x7f2f68875a58 - std::panicking::try::do_call::hb890e897357f772c
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:552:40
  29:     0x7f2f68875a58 - std::panicking::try::h795efaa1580fa0bb
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:516:19
  30:     0x7f2f68875a58 - std::panic::catch_unwind::hcdb55523e22a6b5f
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panic.rs:142:14
  31:     0x7f2f68875a58 - std::rt::lang_start_internal::h6c2766cc18ac837a
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/rt.rs:148:20
  32:     0x7f2f671b5e1a - std::rt::lang_start::h97fd1831ce37b167
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/rt.rs:165:17
  33:     0x7f2f671b645e - main
```
</details>

**Platform**
OS: ```Linux void 6.6.46_1 #1 SMP PREEMPT_DYNAMIC x86_64 GNU/Linux```
Display: ```X.Org X Server 1.21.1.13  X Protocol Version 11, Revision 0```
wgpu version: ```22.1.0 (most current version as of August 18, 2024)```

I've found one other instance of this occurring (https://github.com/rust-windowing/winit/issues/3603) and I have all the libraries installed that were mentioned in [notgull's comment](https://github.com/rust-windowing/winit/issues/3603#issuecomment-2016581170)

**Comment by teoxoy** [comment]
You should report this to winit.
