### ISSUE TITLE
Panic at unreachable

### ISSUE THREAD

**Issue by edwloef** [gfx-rs/wgpu#6159]
**Description**
Panic at an unreachable in wgpu-core/src/device/global.rs, line 1859:
`unreachable!("Fallback system failed to choose present mode. This is a bug. Mode: {:?}, Options: {:?}", config.present_mode, &caps.present_modes);`

**Repro steps**
Run an iced application, e.g. https://github.com/edwloef/iced-text-editor, in a wayland compositor that supports explicit sync with an nvidia gpu.

**Expected vs observed behavior**
Expected: no crash
Observed: crash

**Extra materials**
backtrace: https://pastebin.com/N77ge13a
This may be an oopsie on nvidia's part, but maybe an issue to document the bug could be useful?

**Platform**
linux 6.10.6, nvidia-open 560.35.03, wgpu-core 0.19.4

**Comment by RuofengX** [comment]
same issue.
I am running ggez engine demo, so I think it is a hardware releated issue.

- System: Fedora41  
- GraphicCard: Advanced Micro Devices, Inc. [AMD/ATI] Phoenix3 (rev 01) 
_(which from Ryzen R7840U Intergrated Graphic chipset)_  
- Driver: amd-gpu-firmware.noarch 20241017-2.fc41  
 
```
wl_surface#25: error 2: Buffer size (553x45) must be an integer multiple of the buffer_scale (2).
thread 'main' panicked at /home/ruofeng/.cargo/registry/src/rsproxy.cn-0dccff568467c15b/wgpu-core-0.16.1/src/device/mod.rs:5384:21:
internal error: entered unreachable code: Fallback system failed to choose present mode. This is a bug. Mode: AutoVsync, Options: []
```

**Comment by LuanVSO** [comment]
i have an nvidia gpu and an amd igpu, if i blacklist amdgpu kernel module the crash doesn't happen, maybe it is trying to open with the wrong gpu

**Comment by cwfitzgerald** [comment]
This is telling us that the options for PresentMode are an empty string, probably because of the wayland issue.

**Comment by user583953** [comment]
This may be related, crash log from running an example from the latest branch of iced:

I am on a PC, monitor connected to Nvidia dGPU, but it selects AMD iGPU.

Fedora 41, KDE, Wayland, proprietary drivers.

Selects AMD iGPU (Vulkan), crashes:
<details><summary>Log (default)</summary>

```
2025-02-16T10:42:49.150690Z  WARN wgpu_hal::vulkan::instance: InstanceFlags::VALIDATION requested, but unable to find layer: VK_LAYER_KHRONOS_validation    
2025-02-16T10:42:49.156351Z  INFO wgpu_hal::vulkan::instance: Debug utils not enabled: debug_utils_user_data not passed to Instance::from_raw    
2025-02-16T10:42:49.164653Z  INFO wgpu_hal::gles::egl: Using Wayland platform    
2025-02-16T10:42:49.167181Z ERROR wgpu_hal::gles::egl: EGL 'eglCreateSyncKHR' code 0x3004: EGL_BAD_ATTRIBUTE error: In eglCreateSyncKHR: EGL_SYNC_NATIVE_FENCE_FD_ANDROID specified valid fd butEGL_SYNC_STATUS is also being set
    
2025-02-16T10:42:49.167548Z  WARN wgpu_hal::gles::egl: No config found!    
2025-02-16T10:42:49.167558Z  WARN wgpu_hal::gles::egl: EGL says it can present to the window but not natively    
2025-02-16T10:42:49.174927Z  INFO iced_wgpu::window::compositor: Settings {
    present_mode: AutoVsync,
    backends: Backends(
        VULKAN | GL | METAL | DX12 | BROWSER_WEBGPU,
    ),
    default_font: Font {
        family: SansSerif,
        weight: Normal,
        stretch: Normal,
        style: Normal,
    },
    default_text_size: Pixels(
        16.0,
    ),
    antialiasing: None,
}    
2025-02-16T10:42:49.189349Z  INFO wgpu_core::instance: Adapter Vulkan AdapterInfo { name: "NVIDIA GeForce GTX 1050", vendor: 4318, device: 7297, device_type: DiscreteGpu, driver: "NVIDIA", driver_info: "565.77", backend: Vulkan }    
2025-02-16T10:42:49.189877Z  INFO wgpu_core::instance: Adapter Vulkan AdapterInfo { name: "AMD Radeon Graphics (RADV RAPHAEL_MENDOCINO)", vendor: 4098, device: 5710, device_type: IntegratedGpu, driver: "radv", driver_info: "Mesa 24.3.4", backend: Vulkan }    
2025-02-16T10:42:49.189887Z  INFO wgpu_core::instance: Adapter Vulkan AdapterInfo { name: "llvmpipe (LLVM 19.1.7, 256 bits)", vendor: 65541, device: 0, device_type: Cpu, driver: "llvmpipe", driver_info: "Mesa 24.3.4 (LLVM 19.1.7)", backend: Vulkan }    
2025-02-16T10:42:49.207077Z  INFO wgpu_core::instance: Adapter Gl AdapterInfo { name: "NVIDIA GeForce GTX 1050/PCIe/SSE2", vendor: 4318, device: 0, device_type: Other, driver: "", driver_info: "", backend: Gl }    
2025-02-16T10:42:49.207678Z  INFO iced_wgpu::window::compositor: Available adapters: [
    AdapterInfo {
        name: "NVIDIA GeForce GTX 1050",
        vendor: 4318,
        device: 7297,
        device_type: DiscreteGpu,
        driver: "NVIDIA",
        driver_info: "565.77",
        backend: Vulkan,
    },
    AdapterInfo {
        name: "AMD Radeon Graphics (RADV RAPHAEL_MENDOCINO)",
        vendor: 4098,
        device: 5710,
        device_type: IntegratedGpu,
        driver: "radv",
        driver_info: "Mesa 24.3.4",
        backend: Vulkan,
    },
    AdapterInfo {
        name: "llvmpipe (LLVM 19.1.7, 256 bits)",
        vendor: 65541,
        device: 0,
        device_type: Cpu,
        driver: "llvmpipe",
        driver_info: "Mesa 24.3.4 (LLVM 19.1.7)",
        backend: Vulkan,
    },
    AdapterInfo {
        name: "NVIDIA GeForce GTX 1050/PCIe/SSE2",
        vendor: 4318,
        device: 0,
        device_type: Other,
        driver: "",
        driver_info: "",
        backend: Gl,
    },
]    
2025-02-16T10:42:49.214600Z  INFO wgpu_core::instance: Adapter Vulkan AdapterInfo { name: "AMD Radeon Graphics (RADV RAPHAEL_MENDOCINO)", vendor: 4098, device: 5710, device_type: IntegratedGpu, driver: "radv", driver_info: "Mesa 24.3.4", backend: Vulkan }    
2025-02-16T10:42:49.214644Z  INFO iced_wgpu::window::compositor: Selected: AdapterInfo {
    name: "AMD Radeon Graphics (RADV RAPHAEL_MENDOCINO)",
    vendor: 4098,
    device: 5710,
    device_type: IntegratedGpu,
    driver: "radv",
    driver_info: "Mesa 24.3.4",
    backend: Vulkan,
}    
2025-02-16T10:42:49.215613Z  INFO iced_wgpu::window::compositor: Available formats: Copied {
    it: Iter(
        [
            Rgba8UnormSrgb,
            Bgra8UnormSrgb,
            Rgba8Unorm,
            Bgra8Unorm,
        ],
    ),
}    
2025-02-16T10:42:49.215629Z  INFO iced_wgpu::window::compositor: Available alpha modes: [
    Opaque,
    PreMultiplied,
]    
2025-02-16T10:42:49.215754Z  INFO iced_wgpu::window::compositor: Selected format: Rgba8UnormSrgb with alpha mode: PreMultiplied    
2025-02-16T10:42:49.265039Z  INFO iced_winit::program: Window attributes for id `Id(
    1,
)`: WindowAttributes {
    inner_size: Some(
        Logical(
            LogicalSize {
                width: 1024.0,
                height: 768.0,
            },
        ),
    ),
    min_inner_size: None,
    max_inner_size: None,
    position: None,
    resizable: true,
    enabled_buttons: WindowButtons(
        CLOSE | MINIMIZE | MAXIMIZE,
    ),
    title: "Welcome - Iced",
    maximized: false,
    visible: false,
    transparent: false,
    blur: false,
    decorations: true,
    window_icon: None,
    preferred_theme: None,
    resize_increments: None,
    content_protected: false,
    window_level: Normal,
    active: true,
    cursor: Icon(
        Default,
    ),
    parent_window: None,
    fullscreen: None,
    platform_specific: PlatformSpecificWindowAttributes {
        name: Some(
            ApplicationName {
                general: "",
                instance: "",
            },
        ),
        activation_token: None,
        x11: X11WindowAttributes {
            visual_id: None,
            screen_id: None,
            base_size: None,
            override_redirect: false,
            x11_window_types: [
                Normal,
            ],
            embed_window: None,
        },
    },
}    
[destroyed object]: error 7: importing the supplied dmabufs failed
Protocol error 7 on object @0: 
2025-02-16T10:42:49.410334Z ERROR wgpu_hal::vulkan::adapter: get_physical_device_surface_present_modes: ERROR_SURFACE_LOST_KHR    
2025-02-16T10:42:49.410358Z ERROR wgpu_hal::vulkan::adapter: get_physical_device_surface_formats: ERROR_SURFACE_LOST_KHR    
thread 'main' panicked at /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-core-0.19.4/src/device/global.rs:1859:21:
internal error: entered unreachable code: Fallback system failed to choose present mode. This is a bug. Mode: AutoVsync, Options: []
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

</details>


Selects Nvidia dGPU (GL), runs fine:
<details><summary>Log (WGPU_BACKEND=gl)</summary>

```
2025-02-16T10:56:18.474110Z  INFO wgpu_hal::gles::egl: Using Wayland platform    
2025-02-16T10:56:18.479545Z ERROR wgpu_hal::gles::egl: EGL 'eglCreateSyncKHR' code 0x3004: EGL_BAD_ATTRIBUTE error: In eglCreateSyncKHR: EGL_SYNC_NATIVE_FENCE_FD_ANDROID specified valid fd butEGL_SYNC_STATUS is also being set
    
2025-02-16T10:56:18.479937Z  WARN wgpu_hal::gles::egl: No config found!    
2025-02-16T10:56:18.479947Z  WARN wgpu_hal::gles::egl: EGL says it can present to the window but not natively    
2025-02-16T10:56:18.484605Z  INFO iced_wgpu::window::compositor: Settings {
    present_mode: AutoVsync,
    backends: Backends(
        GL,
    ),
    default_font: Font {
        family: SansSerif,
        weight: Normal,
        stretch: Normal,
        style: Normal,
    },
    default_text_size: Pixels(
        16.0,
    ),
    antialiasing: None,
}    
2025-02-16T10:56:18.494136Z  INFO wgpu_core::instance: Adapter Gl AdapterInfo { name: "NVIDIA GeForce GTX 1050/PCIe/SSE2", vendor: 4318, device: 0, device_type: Other, driver: "", driver_info: "", backend: Gl }    
2025-02-16T10:56:18.494240Z  INFO iced_wgpu::window::compositor: Available adapters: [
    AdapterInfo {
        name: "NVIDIA GeForce GTX 1050/PCIe/SSE2",
        vendor: 4318,
        device: 0,
        device_type: Other,
        driver: "",
        driver_info: "",
        backend: Gl,
    },
]    
2025-02-16T10:56:18.494273Z  WARN wgpu_hal::gles::egl: Re-initializing Gles context due to Wayland window    
2025-02-16T10:56:18.495166Z ERROR wgpu_hal::gles::egl: EGL 'eglCreateSyncKHR' code 0x3004: EGL_BAD_ATTRIBUTE error: In eglCreateSyncKHR: EGL_SYNC_NATIVE_FENCE_FD_ANDROID specified valid fd butEGL_SYNC_STATUS is also being set
    
2025-02-16T10:56:18.495514Z  WARN wgpu_hal::gles::egl: No config found!    
2025-02-16T10:56:18.495523Z  WARN wgpu_hal::gles::egl: EGL says it can present to the window but not natively    
2025-02-16T10:56:18.497682Z  INFO iced_winit::program: Window attributes for id `Id(
    1,
)`: WindowAttributes {
    inner_size: Some(
        Logical(
            LogicalSize {
                width: 1024.0,
                height: 768.0,
            },
        ),
    ),
    min_inner_size: None,
    max_inner_size: None,
    position: None,
    resizable: true,
    enabled_buttons: WindowButtons(
        CLOSE | MINIMIZE | MAXIMIZE,
    ),
    title: "Welcome - Iced",
    maximized: false,
    visible: false,
    transparent: false,
    blur: false,
    decorations: true,
    window_icon: None,
    preferred_theme: None,
    resize_increments: None,
    content_protected: false,
    window_level: Normal,
    active: true,
    cursor: Icon(
        Default,
    ),
    parent_window: None,
    fullscreen: None,
    platform_specific: PlatformSpecificWindowAttributes {
        name: Some(
            ApplicationName {
                general: "",
                instance: "",
            },
        ),
        activation_token: None,
        x11: X11WindowAttributes {
            visual_id: None,
            screen_id: None,
            base_size: None,
            override_redirect: false,
            x11_window_types: [
                Normal,
            ],
            embed_window: None,
        },
    },
}    
```

</details>


Selects Nvidia dGPU (Vulkan), runs fine:
</details><details><summary>Log (WGPU_POWER_PREF=high)</summary>

```
2025-02-16T11:02:04.681333Z  WARN wgpu_hal::vulkan::instance: InstanceFlags::VALIDATION requested, but unable to find layer: VK_LAYER_KHRONOS_validation    
2025-02-16T11:02:04.686117Z  INFO wgpu_hal::vulkan::instance: Debug utils not enabled: debug_utils_user_data not passed to Instance::from_raw    
2025-02-16T11:02:04.693475Z  INFO wgpu_hal::gles::egl: Using Wayland platform    
2025-02-16T11:02:04.696456Z ERROR wgpu_hal::gles::egl: EGL 'eglCreateSyncKHR' code 0x3004: EGL_BAD_ATTRIBUTE error: In eglCreateSyncKHR: EGL_SYNC_NATIVE_FENCE_FD_ANDROID specified valid fd butEGL_SYNC_STATUS is also being set
    
2025-02-16T11:02:04.696836Z  WARN wgpu_hal::gles::egl: No config found!    
2025-02-16T11:02:04.696847Z  WARN wgpu_hal::gles::egl: EGL says it can present to the window but not natively    
2025-02-16T11:02:04.701226Z  INFO iced_wgpu::window::compositor: Settings {
    present_mode: AutoVsync,
    backends: Backends(
        VULKAN | GL | METAL | DX12 | BROWSER_WEBGPU,
    ),
    default_font: Font {
        family: SansSerif,
        weight: Normal,
        stretch: Normal,
        style: Normal,
    },
    default_text_size: Pixels(
        16.0,
    ),
    antialiasing: None,
}    
2025-02-16T11:02:04.712133Z  INFO wgpu_core::instance: Adapter Vulkan AdapterInfo { name: "NVIDIA GeForce GTX 1050", vendor: 4318, device: 7297, device_type: DiscreteGpu, driver: "NVIDIA", driver_info: "565.77", backend: Vulkan }    
2025-02-16T11:02:04.712196Z  INFO wgpu_core::instance: Adapter Vulkan AdapterInfo { name: "AMD Radeon Graphics (RADV RAPHAEL_MENDOCINO)", vendor: 4098, device: 5710, device_type: IntegratedGpu, driver: "radv", driver_info: "Mesa 24.3.4", backend: Vulkan }    
2025-02-16T11:02:04.712204Z  INFO wgpu_core::instance: Adapter Vulkan AdapterInfo { name: "llvmpipe (LLVM 19.1.7, 256 bits)", vendor: 65541, device: 0, device_type: Cpu, driver: "llvmpipe", driver_info: "Mesa 24.3.4 (LLVM 19.1.7)", backend: Vulkan }    
2025-02-16T11:02:04.727271Z  INFO wgpu_core::instance: Adapter Gl AdapterInfo { name: "NVIDIA GeForce GTX 1050/PCIe/SSE2", vendor: 4318, device: 0, device_type: Other, driver: "", driver_info: "", backend: Gl }    
2025-02-16T11:02:04.727345Z  INFO iced_wgpu::window::compositor: Available adapters: [
    AdapterInfo {
        name: "NVIDIA GeForce GTX 1050",
        vendor: 4318,
        device: 7297,
        device_type: DiscreteGpu,
        driver: "NVIDIA",
        driver_info: "565.77",
        backend: Vulkan,
    },
    AdapterInfo {
        name: "AMD Radeon Graphics (RADV RAPHAEL_MENDOCINO)",
        vendor: 4098,
        device: 5710,
        device_type: IntegratedGpu,
        driver: "radv",
        driver_info: "Mesa 24.3.4",
        backend: Vulkan,
    },
    AdapterInfo {
        name: "llvmpipe (LLVM 19.1.7, 256 bits)",
        vendor: 65541,
        device: 0,
        device_type: Cpu,
        driver: "llvmpipe",
        driver_info: "Mesa 24.3.4 (LLVM 19.1.7)",
        backend: Vulkan,
    },
    AdapterInfo {
        name: "NVIDIA GeForce GTX 1050/PCIe/SSE2",
        vendor: 4318,
        device: 0,
        device_type: Other,
        driver: "",
        driver_info: "",
        backend: Gl,
    },
]    
2025-02-16T11:02:04.732507Z  INFO wgpu_core::instance: Adapter Vulkan AdapterInfo { name: "NVIDIA GeForce GTX 1050", vendor: 4318, device: 7297, device_type: DiscreteGpu, driver: "NVIDIA", driver_info: "565.77", backend: Vulkan }    
2025-02-16T11:02:04.732544Z  INFO iced_wgpu::window::compositor: Selected: AdapterInfo {
    name: "NVIDIA GeForce GTX 1050",
    vendor: 4318,
    device: 7297,
    device_type: DiscreteGpu,
    driver: "NVIDIA",
    driver_info: "565.77",
    backend: Vulkan,
}    
2025-02-16T11:02:04.732574Z  INFO iced_wgpu::window::compositor: Available formats: Copied {
    it: Iter(
        [
            Rgba8UnormSrgb,
            Bgra8UnormSrgb,
            Rgba8Unorm,
            Bgra8Unorm,
        ],
    ),
}    
2025-02-16T11:02:04.732585Z  INFO iced_wgpu::window::compositor: Available alpha modes: [
    Opaque,
    PreMultiplied,
]    
2025-02-16T11:02:04.732595Z  INFO iced_wgpu::window::compositor: Selected format: Rgba8UnormSrgb with alpha mode: PreMultiplied    
2025-02-16T11:02:04.774961Z  INFO iced_winit::program: Window attributes for id `Id(
    1,
)`: WindowAttributes {
    inner_size: Some(
        Logical(
            LogicalSize {
                width: 1024.0,
                height: 768.0,
            },
        ),
    ),
    min_inner_size: None,
    max_inner_size: None,
    position: None,
    resizable: true,
    enabled_buttons: WindowButtons(
        CLOSE | MINIMIZE | MAXIMIZE,
    ),
    title: "Welcome - Iced",
    maximized: false,
    visible: false,
    transparent: false,
    blur: false,
    decorations: true,
    window_icon: None,
    preferred_theme: None,
    resize_increments: None,
    content_protected: false,
    window_level: Normal,
    active: true,
    cursor: Icon(
        Default,
    ),
    parent_window: None,
    fullscreen: None,
    platform_specific: PlatformSpecificWindowAttributes {
        name: Some(
            ApplicationName {
                general: "",
                instance: "",
            },
        ),
        activation_token: None,
        x11: X11WindowAttributes {
            visual_id: None,
            screen_id: None,
            base_size: None,
            override_redirect: false,
            x11_window_types: [
                Normal,
            ],
            embed_window: None,
        },
    },
}    
warning: queue 0x56254bd096f0 destroyed while proxies still attached:
  wl_registry#63 still attached
```

</details>

**Comment by valpackett** [comment]
Saw these errors launching [Airshipper](https://gitlab.com/veloren/airshipper) on freedreno/turnip, with mutter 48.2.

Looks like fractional scaling is the root issue, this kind of thing:

```
wl_surface@21: error 2: Buffer size (1070x45) must be an integer multiple of the buffer_scale (2).
```

is what actually causes the rest of the errors, if you see that one. It works fine with 100% scale. Oddly didn't seem to work with 200% either 0.o

**Comment by dtanzer** [comment]
Having the same problem with a toy project I created using the 2D graphics library ggez - I can confirm the scaling issue. When I set my display to 100% scale, it works, at 200% (which I usually use) it crashes.
It also does **not** crash when I use the docking station, which I think makes the laptop switch to the dedicated graphics card.
