### ISSUE TITLE
Crash when using multiple bind groups in certain ways

### ISSUE THREAD

**Issue by almarklein** [gfx-rs/wgpu#620]
@kvark this is the problem that I was referring to the other day in the chat. I've dug deeper and can now reproduce it more reliably:

I tweaked the `wgpu-rs/examples/cube` example. See the branch [here](https://github.com/almarklein/wgpu-rs/pull/1) as a PR on my own fork. I first made some changes to use two bind groups, the second being empty: https://github.com/almarklein/wgpu-rs/pull/1/commits/dfb9c52a31fd899e35b68442d7ca9afdff17d7b7. Then I moved the texture and sampler bindings to the second group: https://github.com/almarklein/wgpu-rs/pull/1/commits/e42d5281e7f20c96e4027d2387e769731f7bf7c0. This fails. 

This [example with wgpu-py](https://github.com/almarklein/wgpu-py/blob/master/examples/cube_glfw.py) can also demonstrate the problem.

Some observations:
* Depending on the order of the sampler and texture and the fase of the moon, it either produces a black texture or a crashes.
* With wgu-p (which wraps wgpu-native), I get a 0xc0000005 Access Violation, though I have also seen (0xc000041d STATUS_FATAL_USER_CALLBACK_EXCEPTION).
* With the wgpu-rs example I get a lot more info. See below.

<details>
<summary>Rust output (Click to expand)</summary>

```
C:\dev\rust\wgpu-rs (cube-fail -> origin)
λ cargo run --example cube
warning: Patch `js-sys v0.3.38 (https://github.com/rustwasm/wasm-bindgen#7bee6a8c)` was not used in the crate graph.
Patch `wasm-bindgen v0.2.61 (https://github.com/rustwasm/wasm-bindgen#7bee6a8c)` was not used in the crate graph.
Patch `wasm-bindgen-futures v0.4.11 (https://github.com/rustwasm/wasm-bindgen#7bee6a8c)` was not used in the crate graph.
Patch `web-sys v0.3.38 (https://github.com/rustwasm/wasm-bindgen#7bee6a8c)` was not used in the crate graph.
Check that the patched package version and available features are compatible
with the dependency requirements. If the patch has a different version from
what is locked in the Cargo.lock file, run `cargo update` to use the new
version. This may also occur with an optional dependency that is not enabled.
    Finished dev [unoptimized + debuginfo] target(s) in 0.25s
     Running `target\debug\examples\cube.exe`
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `Ok(())`,
 right: `Err(ERROR_DEVICE_LOST)`', C:\Users\Almar\.cargo\registry\src\github.com-1ecc6299db9ec823\gfx-backend-vulkan-0.5.2\src\lib.rs:1346:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `Err(DeviceLost(DeviceLost))`,
 right: `Ok(true)`: GPU got stuck :(', C:\Users\Almar\.cargo\git\checkouts\wgpu-53e70f8674b08dd4\5c172dd\wgpu-core\src\device\life.rs:238:13
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `Err(DeviceLost(DeviceLost))`,
 right: `Ok(true)`: GPU got stuck :(', C:\Users\Almar\.cargo\git\checkouts\wgpu-53e70f8674b08dd4\5c172dd\wgpu-core\src\device\life.rs:238:13
stack backtrace:
   0:     0x7ff6b2e19a09 - backtrace::backtrace::trace_unsynchronized
                               at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.37\src\backtrace\mod.rs:66
   1:     0x7ff6b2e19a09 - std::sys_common::backtrace::_print_fmt
                               at /rustc/10a52c25cad963986cace7a22c167363afca0d74\/src\libstd\sys_common\backtrace.rs:77
   2:     0x7ff6b2e19a09 - std::sys_common::backtrace::_print::{{impl}}::fmt
                               at /rustc/10a52c25cad963986cace7a22c167363afca0d74\/src\libstd\sys_common\backtrace.rs:61
   3:     0x7ff6b2e2f73b - core::fmt::write
                               at /rustc/10a52c25cad963986cace7a22c167363afca0d74\/src\libcore\fmt\mod.rs:1028
   4:     0x7ff6b2e16e24 - std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
                               at /rustc/10a52c25cad963986cace7a22c167363afca0d74\/src\libstd\io\mod.rs:1412
   5:     0x7ff6b2e1c1a9 - std::sys_common::backtrace::_print
                               at /rustc/10a52c25cad963986cace7a22c167363afca0d74\/src\libstd\sys_common\backtrace.rs:65
   6:     0x7ff6b2e1c1a9 - std::sys_common::backtrace::print
                               at /rustc/10a52c25cad963986cace7a22c167363afca0d74\/src\libstd\sys_common\backtrace.rs:50
   7:     0x7ff6b2e1c1a9 - std::panicking::default_hook::{{closure}}
                               at /rustc/10a52c25cad963986cace7a22c167363afca0d74\/src\libstd\panicking.rs:188
   8:     0x7ff6b2e1bdfc - std::panicking::default_hook
                               at /rustc/10a52c25cad963986cace7a22c167363afca0d74\/src\libstd\panicking.rs:205
   9:     0x7ff6b2e1ca08 - std::panicking::rust_panic_with_hook
                               at /rustc/10a52c25cad963986cace7a22c167363afca0d74\/src\libstd\panicking.rs:468
  10:     0x7ff6b2e1c574 - std::panicking::continue_panic_fmt
                               at /rustc/10a52c25cad963986cace7a22c167363afca0d74\/src\libstd\panicking.rs:375
  11:     0x7ff6b2e1c4bf - std::panicking::begin_panic_fmt
                               at /rustc/10a52c25cad963986cace7a22c167363afca0d74\/src\libstd\panicking.rs:330
  12:     0x7ff6b28b6b3f - wgpu_core::device::life::LifetimeTracker<gfx_backend_vulkan::Backend>::wait_idle<gfx_backend_vulkan::Backend>
                               at <::std::macros::panic macros>:9
  13:     0x7ff6b28b248a - wgpu_core::device::life::LifetimeTracker<gfx_backend_vulkan::Backend>::triage_submissions<gfx_backend_vulkan::Backend>
                               at C:\Users\Almar\.cargo\git\checkouts\wgpu-53e70f8674b08dd4\5c172dd\wgpu-core\src\device\life.rs:245
  14:     0x7ff6b2897e53 - wgpu_core::device::Device<gfx_backend_vulkan::Backend>::dispose<gfx_backend_vulkan::Backend>
                               at C:\Users\Almar\.cargo\git\checkouts\wgpu-53e70f8674b08dd4\5c172dd\wgpu-core\src\device\mod.rs:457
  15:     0x7ff6b25b1594 - wgpu_core::hub::{{impl}}::drop<gfx_backend_vulkan::Backend,wgpu_core::hub::IdentityManagerFactory>
                               at C:\Users\Almar\.cargo\git\checkouts\wgpu-53e70f8674b08dd4\5c172dd\wgpu-core\src\hub.rs:495
  16:     0x7ff6b28e0f2f - core::ptr::real_drop_in_place<wgpu_core::hub::Hub<gfx_backend_vulkan::Backend, wgpu_core::hub::IdentityManagerFactory>>
                               at /rustc/10a52c25cad963986cace7a22c167363afca0d74\src\libcore\ptr\mod.rs:175
  17:     0x7ff6b28de4df - core::ptr::real_drop_in_place<wgpu_core::hub::Hubs<wgpu_core::hub::IdentityManagerFactory>>
                               at /rustc/10a52c25cad963986cace7a22c167363afca0d74\src\libcore\ptr\mod.rs:175
  18:     0x7ff6b28e44d3 - core::ptr::real_drop_in_place<wgpu_core::hub::Global<wgpu_core::hub::IdentityManagerFactory>>
                               at /rustc/10a52c25cad963986cace7a22c167363afca0d74\src\libcore\ptr\mod.rs:175
  19:     0x7ff6b25a9382 - core::ptr::drop_in_place
                               at /rustc/10a52c25cad963986cace7a22c167363afca0d74\src\libcore\ptr\mod.rs:165
  20:     0x7ff6b25a9382 - alloc::sync::Arc<wgpu_core::hub::Global<wgpu_core::hub::IdentityManagerFactory>>::drop_slow<wgpu_core::hub::Global<wgpu_core::hub::IdentityManagerFactory>>
                               at /rustc/10a52c25cad963986cace7a22c167363afca0d74\src\liballoc\sync.rs:706
  21:     0x7ff6b25a9b45 - alloc::sync::{{impl}}::drop<wgpu_core::hub::Global<wgpu_core::hub::IdentityManagerFactory>>
                               at /rustc/10a52c25cad963986cace7a22c167363afca0d74\src\liballoc\sync.rs:1234
  22:     0x7ff6b236c023 - core::ptr::real_drop_in_place<alloc::sync::Arc<wgpu_core::hub::Global<wgpu_core::hub::IdentityManagerFactory>>>
                               at /rustc/10a52c25cad963986cace7a22c167363afca0d74\src\libcore\ptr\mod.rs:175
  23:     0x7ff6b23689f3 - core::ptr::real_drop_in_place<wgpu::Instance>
                               at /rustc/10a52c25cad963986cace7a22c167363afca0d74\src\libcore\ptr\mod.rs:175
  24:     0x7ff6b2381e93 - cube::framework::run_async::{{closure}}<cube::Example>
                               at C:\dev\rust\wgpu-rs\examples\framework.rs:149
  25:     0x7fff379ec0b0 - _C_specific_handler
  26:     0x7fff379e1d6e - _TypeMatch
  27:     0x7fff379eb7fb - _unDNameEx
  28:     0x7fff379e23e3 - _BuildCatchObject
  29:     0x7fff379eb882 - _CxxFrameHandler3
  30:     0x7fff4b5e124f - _chkstk
  31:     0x7fff4b55d9b2 - RtlUnwindEx
  32:     0x7fff379ebbd1 - FindAndUnlinkFrame
  33:     0x7fff379e2f61 - _BuildCatchObject
  34:     0x7fff379e2ce9 - _BuildCatchObject
  35:     0x7fff379e24de - _BuildCatchObject
  36:     0x7fff379eb882 - _CxxFrameHandler3
  37:     0x7fff4b5e11cf - _chkstk
  38:     0x7fff4b5aa209 - RtlRaiseException
  39:     0x7fff4b5a9fc3 - RtlRaiseException
  40:     0x7fff490aa799 - RaiseException
  41:     0x7fff379e42cd - CxxThrowException
  42:     0x7ff6b2e1fbd8 - panic_unwind::imp::panic
                               at /rustc/10a52c25cad963986cace7a22c167363afca0d74\/src\libpanic_unwind\seh.rs:281
  43:     0x7ff6b2e1fbd8 - panic_unwind::__rust_start_panic
                               at /rustc/10a52c25cad963986cace7a22c167363afca0d74\/src\libpanic_unwind\lib.rs:96
  44:     0x7ff6b2e1cbe8 - std::panicking::rust_panic
                               at /rustc/10a52c25cad963986cace7a22c167363afca0d74\/src\libstd\panicking.rs:517
  45:     0x7ff6b2e1caba - std::panicking::rust_panic_with_hook
                               at /rustc/10a52c25cad963986cace7a22c167363afca0d74\/src\libstd\panicking.rs:488
  46:     0x7ff6b2e1c574 - std::panicking::continue_panic_fmt
                               at /rustc/10a52c25cad963986cace7a22c167363afca0d74\/src\libstd\panicking.rs:375
  47:     0x7ff6b2e1c4bf - std::panicking::begin_panic_fmt
                               at /rustc/10a52c25cad963986cace7a22c167363afca0d74\/src\libstd\panicking.rs:330
  48:     0x7ff6b28b6b3f - wgpu_core::device::life::LifetimeTracker<gfx_backend_vulkan::Backend>::wait_idle<gfx_backend_vulkan::Backend>
                               at <::std::macros::panic macros>:9
  49:     0x7ff6b28b248a - wgpu_core::device::life::LifetimeTracker<gfx_backend_vulkan::Backend>::triage_submissions<gfx_backend_vulkan::Backend>
                               at C:\Users\Almar\.cargo\git\checkouts\wgpu-53e70f8674b08dd4\5c172dd\wgpu-core\src\device\life.rs:245
  50:     0x7ff6b2898afa - wgpu_core::device::Device<gfx_backend_vulkan::Backend>::maintain<gfx_backend_vulkan::Backend,wgpu_core::hub::IdentityManagerFactory>
                               at C:\Users\Almar\.cargo\git\checkouts\wgpu-53e70f8674b08dd4\5c172dd\wgpu-core\src\device\mod.rs:266
  51:     0x7ff6b25e92ae - wgpu_core::hub::Global<wgpu_core::hub::IdentityManagerFactory>::device_poll<wgpu_core::hub::IdentityManagerFactory,gfx_backend_vulkan::Backend>
                               at C:\Users\Almar\.cargo\git\checkouts\wgpu-53e70f8674b08dd4\5c172dd\wgpu-core\src\device\mod.rs:2069
  52:     0x7ff6b29ec3b6 - wgpu::backend::direct::{{impl}}::device_drop
                               at C:\dev\rust\wgpu-rs\src\backend\direct.rs:657
  53:     0x7ff6b26ce5e3 - wgpu::{{impl}}::drop
                               at C:\dev\rust\wgpu-rs\src\lib.rs:1142
  54:     0x7ff6b236c21f - core::ptr::real_drop_in_place<wgpu::Device>
                               at /rustc/10a52c25cad963986cace7a22c167363afca0d74\src\libcore\ptr\mod.rs:175
  55:     0x7ff6b236a500 - core::ptr::real_drop_in_place<closure-0>
                               at /rustc/10a52c25cad963986cace7a22c167363afca0d74\src\libcore\ptr\mod.rs:175
  56:     0x7ff6b2363ec6 - core::ptr::real_drop_in_place<closure-0>
                               at /rustc/10a52c25cad963986cace7a22c167363afca0d74\src\libcore\ptr\mod.rs:175
  57:     0x7ff6b2368806 - core::ptr::real_drop_in_place<alloc::boxed::Box<FnMut<(winit::event::Event<()>, mut winit::event_loop::ControlFlow*)>>>
                               at /rustc/10a52c25cad963986cace7a22c167363afca0d74\src\libcore\ptr\mod.rs:175
  58:     0x7ff6b236c0e6 - core::ptr::real_drop_in_place<winit::platform_impl::platform::event_loop::runner::EventLoopRunner<()>>
                               at /rustc/10a52c25cad963986cace7a22c167363afca0d74\src\libcore\ptr\mod.rs:175
  59:     0x7ff6b2364311 - core::ptr::real_drop_in_place<core::option::Option<winit::platform_impl::platform::event_loop::runner::EventLoopRunner<()>>>
                               at /rustc/10a52c25cad963986cace7a22c167363afca0d74\src\libcore\ptr\mod.rs:175
  60:     0x7ff6b234909b - winit::platform_impl::platform::event_loop::runner::ELRShared<()>::destroy_runner<()>
                               at C:\Users\Almar\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.1\src\platform_impl\windows\event_loop\runner.rs:93
  61:     0x7ff6b238ab94 - winit::platform_impl::platform::event_loop::EventLoop<()>::run_return<(),closure-0>
                               at C:\Users\Almar\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.1\src\platform_impl\windows\event_loop.rs:216
  62:     0x7ff6b238b0c6 - winit::platform_impl::platform::event_loop::EventLoop<()>::run<(),closure-0>
                               at C:\Users\Almar\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.1\src\platform_impl\windows\event_loop.rs:189
  63:     0x7ff6b236e3cd - winit::event_loop::EventLoop<()>::run<(),closure-0>
                               at C:\Users\Almar\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.1\src\event_loop.rs:149
  64:     0x7ff6b2381c92 - cube::framework::run_async::{{closure}}<cube::Example>
                               at C:\dev\rust\wgpu-rs\examples\framework.rs:101
  65:     0x7ff6b2362fbd - std::future::{{impl}}::poll::{{closure}}<generator-0>
                               at /rustc/10a52c25cad963986cace7a22c167363afca0d74\src\libstd\future.rs:43
  66:     0x7ff6b2362d83 - std::future::set_task_context<closure-1,core::task::poll::Poll<()>>
                               at /rustc/10a52c25cad963986cace7a22c167363afca0d74\src\libstd\future.rs:79
  67:     0x7ff6b2362f66 - std::future::{{impl}}::poll<generator-0>
                               at /rustc/10a52c25cad963986cace7a22c167363afca0d74\src\libstd\future.rs:43
  68:     0x7ff6b23831c0 - futures_executor::local_pool::block_on::{{closure}}<std::future::GenFuture<generator-0>>
                               at C:\Users\Almar\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-executor-0.3.4\src\local_pool.rs:317
  69:     0x7ff6b2382fe1 - futures_executor::local_pool::run_executor::{{closure}}<(),closure-0>
                               at C:\Users\Almar\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-executor-0.3.4\src\local_pool.rs:87
  70:     0x7ff6b237c29f - std::thread::local::LocalKey<alloc::sync::Arc<futures_executor::local_pool::ThreadNotify>>::try_with<alloc::sync::Arc<futures_executor::local_pool::ThreadNotify>,closure-0,()>
                               at /rustc/10a52c25cad963986cace7a22c167363afca0d74\src\libstd\thread\local.rs:262
  71:     0x7ff6b237bd8d - std::thread::local::LocalKey<alloc::sync::Arc<futures_executor::local_pool::ThreadNotify>>::with<alloc::sync::Arc<futures_executor::local_pool::ThreadNotify>,closure-0,()>
                               at /rustc/10a52c25cad963986cace7a22c167363afca0d74\src\libstd\thread\local.rs:239
  72:     0x7ff6b2382f23 - futures_executor::local_pool::run_executor<(),closure-0>
                               at C:\Users\Almar\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-executor-0.3.4\src\local_pool.rs:83
  73:     0x7ff6b238311e - futures_executor::local_pool::block_on<std::future::GenFuture<generator-0>>
                               at C:\Users\Almar\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-executor-0.3.4\src\local_pool.rs:317
  74:     0x7ff6b2382631 - cube::framework::run<cube::Example>
                               at C:\dev\rust\wgpu-rs\examples\framework.rs:165
  75:     0x7ff6b234f998 - cube::main
                               at C:\dev\rust\wgpu-rs\examples\cube\main.rs:382
  76:     0x7ff6b2383920 - std::rt::lang_start::{{closure}}<()>
                               at /rustc/10a52c25cad963986cace7a22c167363afca0d74\src\libstd\rt.rs:61
  77:     0x7ff6b2e1c3b7 - std::rt::lang_start_internal::{{closure}}
                               at /rustc/10a52c25cad963986cace7a22c167363afca0d74\/src\libstd\rt.rs:48
  78:     0x7ff6b2e1c3b7 - std::panicking::try::do_call<closure-0,i32>
                               at /rustc/10a52c25cad963986cace7a22c167363afca0d74\/src\libstd\panicking.rs:287
  79:     0x7ff6b2e1faf2 - panic_unwind::__rust_maybe_catch_panic
                               at /rustc/10a52c25cad963986cace7a22c167363afca0d74\/src\libpanic_unwind\lib.rs:80
  80:     0x7ff6b2e1cd42 - std::panicking::try
                               at /rustc/10a52c25cad963986cace7a22c167363afca0d74\/src\libstd\panicking.rs:265
  81:     0x7ff6b2e1cd42 - std::panic::catch_unwind
                               at /rustc/10a52c25cad963986cace7a22c167363afca0d74\/src\libstd\panic.rs:396
  82:     0x7ff6b2e1cd42 - std::rt::lang_start_internal
                               at /rustc/10a52c25cad963986cace7a22c167363afca0d74\/src\libstd\rt.rs:47
  83:     0x7ff6b23838fb - std::rt::lang_start<()>
                               at /rustc/10a52c25cad963986cace7a22c167363afca0d74\src\libstd\rt.rs:61
  84:     0x7ff6b234f9c0 - main
  85:     0x7ff6b3057494 - invoke_main
                               at d:\agent\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  86:     0x7ff6b3057494 - __scrt_common_main_seh
                               at d:\agent\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  87:     0x7fff4a317bd4 - BaseThreadInitThunk
  88:     0x7fff4b5ace51 - RtlUserThreadStart
thread panicked while panicking. aborting.
error: process didn't exit successfully: `target\debug\examples\cube.exe` (exit code: 0xc000001d, STATUS_ILLEGAL_INSTRUCTION)
C:\dev\rust\wgpu-rs (cube-fail -> origin)
λ
```
</details>

**Comment by kvark** [comment]
I ran your case via Vulkan with validation enabled, and noticed the errors. It turns out, you weren't recompiling the shaders. Since `wgpu-rs` got support for WASM, we unlinked from glsl_to_spirv (cc @grovesNL ), and we started having both GLSL source and compiled SPIR-V for the examples. The latter is not updated automatically (!).

So basically you are hitting a case where the shader needs something, but the pipeline doesn't provide it (because the example still uses the original SPIR-V shaders, not your modified GLSL). This falls under #269 , which is a big red dot on our radar to address.

Please feel free to revive this! Closing as a dupe, for now.

**Comment by almarklein** [comment]
Thanks!

Right ... when I started on this, my clone was still on a version that *did* compile the shaders. 
Then I `git pull`'ed and did not realize that the shader would not longer update.

Anyway, if I compile the shader it does work. Which means the issue is not in wgpu-core. Sorry for the noise!

**Comment by almarklein** [comment]
> I ran your case via Vulkan with validation enabled

How do I do this? I ran `cargo run --example cube`, and I have the Lunar SDK installed on on my PATH, but I don't think I see any validation messages.

**Comment by almarklein** [comment]
Excluding wgpu-core made me realize I had overlooked another potential source. So I just found the problem. The Python-to-spirv compiler did not produce a DescriptorSet-annotation-instruction for samplers ... *sigh*
