### ISSUE TITLE
Misaligned Memory On Nvidia/Windows

### ISSUE THREAD

**Issue by cwfitzgerald** [gfx-rs/wgpu#750]
**Description**

A call to `device.create_texture` panics due to misaligned memory.

**Repro steps**

Grab datafiles here: https://cwfitz.com/lsz3E7.zip

```
git clone https://github.com/BVE-Reborn/bve-reborn --branch buffer-belt
cd bve-reborn
cargo run -p bve-build -- --shaderc
cargo build -p bve-client
```

Copy binary into unzipped data folder.

`./bve-client ./load_list.json`

**Expected vs observed behavior**

Expected: Texture to be created successfully,
Observed: Fire and explosions

**Extra materials**

<details>
<summary>Notable Code</summary>

My code: https://github.com/BVE-Reborn/bve-reborn/blob/buffer-belt/bve-render/src/texture.rs#L45
wgpu: https://github.com/gfx-rs/wgpu/blob/master/wgpu-core/src/device/mod.rs#L928

</details>

<details>
<summary>Backtrace</summary>

```
thread 'async-std/runtime' panicked at 'internal error: entered unreachable code', C:\Users\connor\.cargo\registry\src\github.com-1ecc6299db9ec823\gfx-backend-vulkan-0.5.8\src\device.rs:1477:18
stack backtrace:
   0:     0x7ff7c4435f5e - backtrace::backtrace::trace_unsynchronized
                               at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.46\src\backtrace\mod.rs:66
   1:     0x7ff7c4435f5e - std::sys_common::backtrace::_print_fmt
                               at /rustc/a8cf3991177f30694200002cd9479ffbbe6d9a1a\/src\libstd\sys_common\backtrace.rs:78
   2:     0x7ff7c4435f5e - std::sys_common::backtrace::_print::{{impl}}::fmt
                               at /rustc/a8cf3991177f30694200002cd9479ffbbe6d9a1a\/src\libstd\sys_common\backtrace.rs:59
   3:     0x7ff7c444e8ec - core::fmt::write
                               at /rustc/a8cf3991177f30694200002cd9479ffbbe6d9a1a\/src\libcore\fmt\mod.rs:1076
   4:     0x7ff7c443268c - std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
                               at /rustc/a8cf3991177f30694200002cd9479ffbbe6d9a1a\/src\libstd\io\mod.rs:1537
   5:     0x7ff7c443911b - std::sys_common::backtrace::_print
                               at /rustc/a8cf3991177f30694200002cd9479ffbbe6d9a1a\/src\libstd\sys_common\backtrace.rs:62
   6:     0x7ff7c443911b - std::sys_common::backtrace::print
                               at /rustc/a8cf3991177f30694200002cd9479ffbbe6d9a1a\/src\libstd\sys_common\backtrace.rs:49
   7:     0x7ff7c443911b - std::panicking::default_hook::{{closure}}
                               at /rustc/a8cf3991177f30694200002cd9479ffbbe6d9a1a\/src\libstd\panicking.rs:198
   8:     0x7ff7c4438d68 - std::panicking::default_hook
                               at /rustc/a8cf3991177f30694200002cd9479ffbbe6d9a1a\/src\libstd\panicking.rs:217
   9:     0x7ff7c44398f6 - std::panicking::rust_panic_with_hook
                               at /rustc/a8cf3991177f30694200002cd9479ffbbe6d9a1a\/src\libstd\panicking.rs:473
  10:     0x7ff7c3e46d92 - std::panicking::begin_panic<str*>
                               at C:\Users\connor\.rustup\toolchains\nightly-2020-06-22-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\panicking.rs:403
  11:     0x7ff7c3c965e1 - gfx_backend_vulkan::device::{{impl}}::bind_image_memory
                               at C:\Users\connor\.cargo\registry\src\github.com-1ecc6299db9ec823\gfx-backend-vulkan-0.5.8\src\device.rs:1477
  12:     0x7ff7c39c9556 - wgpu_core::device::Device<gfx_backend_vulkan::Backend>::create_texture<gfx_backend_vulkan::Backend>
                               at C:\Users\connor\.cargo\git\checkouts\wgpu-53e70f8674b08dd4\285b31a\wgpu-core\src\device\mod.rs:532
  13:     0x7ff7c3928d87 - wgpu_core::hub::Global<wgpu_core::hub::IdentityManagerFactory>::device_create_texture<wgpu_core::hub::IdentityManagerFactory,gfx_backend_vulkan::Backend>
                               at C:\Users\connor\.cargo\git\checkouts\wgpu-53e70f8674b08dd4\285b31a\wgpu-core\src\device\mod.rs:928
  14:     0x7ff7c39955b7 - wgpu::backend::direct::{{impl}}::device_create_texture
                               at C:\Users\connor\.cargo\git\checkouts\wgpu-rs-40ea39809c03c5d8\90307b6\src\backend\direct.rs:636
  15:     0x7ff7c36911a0 - wgpu::Device::create_texture
                               at C:\Users\connor\.cargo\git\checkouts\wgpu-rs-40ea39809c03c5d8\90307b6\src\lib.rs:1286
  16:     0x7ff7c346aa1b - bve_render::Renderer::add_texture
                               at C:\Users\connor\Programming\bve-reborn\bve-render\src\texture.rs:45
  17:     0x7ff7c329e6f3 - bve_client::{{impl}}::add_texture
                               at C:\Users\connor\Programming\bve-reborn\bve-client\src\main.rs:135
  18:     0x7ff7c3266ac6 - bve::runtime::cache::texture::{{impl}}::load_texture_impl::{{closure}}<bve_client::Client>
                               at C:\Users\connor\Programming\bve-reborn\bve\src\runtime\cache\texture.rs:35
  19:     0x7ff7c32e19ac - core::future::from_generator::{{impl}}::poll<generator-0>
                               at C:\Users\connor\.rustup\toolchains\nightly-2020-06-22-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libcore\future\mod.rs:74
  20:     0x7ff7c3267c13 - bve::runtime::cache::texture::{{impl}}::load_texture_handle_path::{{closure}}::{{closure}}<bve_client::Client>
                               at C:\Users\connor\Programming\bve-reborn\bve\src\runtime\cache\texture.rs:46
  21:     0x7ff7c32e305c - core::future::from_generator::{{impl}}::poll<generator-0>
                               at C:\Users\connor\.rustup\toolchains\nightly-2020-06-22-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libcore\future\mod.rs:74
  22:     0x7ff7c337b6f5 - bve::runtime::cache::{{impl}}::get_or_insert::{{closure}}<bve_render::texture::TextureHandle,core::future::from_generator::GenFuture<generator-0>>
                               at C:\Users\connor\Programming\bve-reborn\bve\src\runtime\cache\mod.rs:58
  23:     0x7ff7c32e31bc - core::future::from_generator::{{impl}}::poll<generator-0>
                               at C:\Users\connor\.rustup\toolchains\nightly-2020-06-22-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libcore\future\mod.rs:74
  24:     0x7ff7c326785e - bve::runtime::cache::texture::{{impl}}::load_texture_handle_path::{{closure}}<bve_client::Client>
                               at C:\Users\connor\Programming\bve-reborn\bve\src\runtime\cache\texture.rs:44
  25:     0x7ff7c32e0817 - core::future::from_generator::{{impl}}::poll<generator-0>
                               at C:\Users\connor\.rustup\toolchains\nightly-2020-06-22-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libcore\future\mod.rs:74
  26:     0x7ff7c32673a6 - bve::runtime::cache::texture::{{impl}}::load_texture_handle::{{closure}}<bve_client::Client>
                               at C:\Users\connor\Programming\bve-reborn\bve\src\runtime\cache\texture.rs:58
  27:     0x7ff7c32e1347 - core::future::from_generator::{{impl}}::poll<generator-0>
                               at C:\Users\connor\.rustup\toolchains\nightly-2020-06-22-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libcore\future\mod.rs:74
  28:     0x7ff7c32fd765 - bve::runtime::{{impl}}::load_mesh_textures::{{closure}}::{{closure}}<bve_client::Client>
                               at C:\Users\connor\Programming\bve-reborn\bve\src\runtime\mod.rs:151
  29:     0x7ff7c32e3967 - core::future::from_generator::{{impl}}::poll<generator-0>
                               at C:\Users\connor\.rustup\toolchains\nightly-2020-06-22-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libcore\future\mod.rs:74
  30:     0x7ff7c329129e - async_std::task::builder::{{impl}}::poll::{{closure}}<core::future::from_generator::GenFuture<generator-0>>
                               at C:\Users\connor\.cargo\registry\src\github.com-1ecc6299db9ec823\async-std-1.6.2\src\task\builder.rs:198
  31:     0x7ff7c33b81df - async_std::task::task_locals_wrapper::{{impl}}::set_current::{{closure}}<closure-0,core::task::poll::Poll<core::option::Option<bve_render::texture::TextureHandle>>>
                               at C:\Users\connor\.cargo\registry\src\github.com-1ecc6299db9ec823\async-std-1.6.2\src\task\task_locals_wrapper.rs:60
  32:     0x7ff7c32a6363 - std::thread::local::LocalKey<core::cell::Cell<const async_std::task::task_locals_wrapper::TaskLocalsWrapper*>>::try_with<core::cell::Cell<const async_std::task::task_locals_wrapper::TaskLocalsWrapper*>,closure-0,core::task::poll::Poll<core::option::Option
                               at C:\Users\connor\.rustup\toolchains\nightly-2020-06-22-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\thread\local.rs:263
  33:     0x7ff7c32a3912 - std::thread::local::LocalKey<core::cell::Cell<const async_std::task::task_locals_wrapper::TaskLocalsWrapper*>>::with<core::cell::Cell<const async_std::task::task_locals_wrapper::TaskLocalsWrapper*>,closure-0,core::task::poll::Poll<core::option::Option<bve
                               at C:\Users\connor\.rustup\toolchains\nightly-2020-06-22-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\thread\local.rs:239
  34:     0x7ff7c33b78b0 - async_std::task::task_locals_wrapper::TaskLocalsWrapper::set_current<closure-0,core::task::poll::Poll<core::option::Option<bve_render::texture::TextureHandle>>>
                               at C:\Users\connor\.cargo\registry\src\github.com-1ecc6299db9ec823\async-std-1.6.2\src\task\task_locals_wrapper.rs:55
  35:     0x7ff7c329096d - async_std::task::builder::{{impl}}::poll<core::future::from_generator::GenFuture<generator-0>>
                               at C:\Users\connor\.cargo\registry\src\github.com-1ecc6299db9ec823\async-std-1.6.2\src\task\builder.rs:196
  36:     0x7ff7c32c2c62 - async_task::raw::RawTask<async_std::task::builder::SupportTaskLocals<core::future::from_generator::GenFuture<generator-0>>, core::option::Option<bve_render::texture::TextureHandle>, closure-0, ()>::run<async_std::task::builder::SupportTaskLocals<core::fut
                               at C:\Users\connor\.cargo\registry\src\github.com-1ecc6299db9ec823\async-task-3.0.0\src\raw.rs:502
  37:     0x7ff7c43bb35e - async_task::task::Task<()>::run<()>
                               at C:\Users\connor\.cargo\registry\src\github.com-1ecc6299db9ec823\async-task-3.0.0\src\task.rs:265
  38:     0x7ff7c43c24ae - smol::multitask::{{impl}}::tick::{{closure}}
                               at C:\Users\connor\.cargo\registry\src\github.com-1ecc6299db9ec823\smol-0.1.18\src\multitask.rs:333
  39:     0x7ff7c43d2871 - scoped_tls::ScopedKey<smol::multitask::Worker>::set<smol::multitask::Worker,closure-0,bool>
                               at C:\Users\connor\.cargo\registry\src\github.com-1ecc6299db9ec823\scoped-tls-1.0.0\src\lib.rs:137
  40:     0x7ff7c43c212b - smol::multitask::Worker::tick
                               at C:\Users\connor\.cargo\registry\src\github.com-1ecc6299db9ec823\smol-0.1.18\src\multitask.rs:333
  41:     0x7ff7c43a8fd9 - smol::run::run::{{closure}}::{{closure}}<(),async_std::task::builder::SupportTaskLocals<core::future::from_generator::GenFuture<generator-0>>>
                               at C:\Users\connor\.cargo\registry\src\github.com-1ecc6299db9ec823\smol-0.1.18\src\run.rs:124
  42:     0x7ff7c43a7fb4 - scoped_tls::ScopedKey<smol::multitask::Worker>::set<smol::multitask::Worker,closure-0,()>
                               at C:\Users\connor\.cargo\registry\src\github.com-1ecc6299db9ec823\scoped-tls-1.0.0\src\lib.rs:137
  43:     0x7ff7c43a8e9e - smol::run::run::{{closure}}<(),async_std::task::builder::SupportTaskLocals<core::future::from_generator::GenFuture<generator-0>>>
                               at C:\Users\connor\.cargo\registry\src\github.com-1ecc6299db9ec823\smol-0.1.18\src\run.rs:116
  44:     0x7ff7c439ba61 - smol::context::enter<(),closure-2>
                               at C:\Users\connor\.cargo\registry\src\github.com-1ecc6299db9ec823\smol-0.1.18\src\context.rs:8
  45:     0x7ff7c43a8cc7 - smol::run::run<(),async_std::task::builder::SupportTaskLocals<core::future::from_generator::GenFuture<generator-0>>>
                               at C:\Users\connor\.cargo\registry\src\github.com-1ecc6299db9ec823\smol-0.1.18\src\run.rs:115
  46:     0x7ff7c43a9584 - async_std::task::builder::{{impl}}::blocking::{{closure}}::{{closure}}<core::future::from_generator::GenFuture<generator-0>,()>
                               at C:\Users\connor\.cargo\registry\src\github.com-1ecc6299db9ec823\async-std-1.6.2\src\task\builder.rs:170
  47:     0x7ff7c43a00b9 - async_std::task::task_locals_wrapper::{{impl}}::set_current::{{closure}}<closure-0,()>
                               at C:\Users\connor\.cargo\registry\src\github.com-1ecc6299db9ec823\async-std-1.6.2\src\task\task_locals_wrapper.rs:60
  48:     0x7ff7c43a17cc - std::thread::local::LocalKey<core::cell::Cell<const async_std::task::task_locals_wrapper::TaskLocalsWrapper*>>::try_with<core::cell::Cell<const async_std::task::task_locals_wrapper::TaskLocalsWrapper*>,closure-0,()>
                               at C:\Users\connor\.rustup\toolchains\nightly-2020-06-22-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\thread\local.rs:263
  49:     0x7ff7c43a13ae - std::thread::local::LocalKey<core::cell::Cell<const async_std::task::task_locals_wrapper::TaskLocalsWrapper*>>::with<core::cell::Cell<const async_std::task::task_locals_wrapper::TaskLocalsWrapper*>,closure-0,()>
                               at C:\Users\connor\.rustup\toolchains\nightly-2020-06-22-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\thread\local.rs:239
  50:     0x7ff7c439fe93 - async_std::task::task_locals_wrapper::TaskLocalsWrapper::set_current<closure-0,()>
                               at C:\Users\connor\.cargo\registry\src\github.com-1ecc6299db9ec823\async-std-1.6.2\src\task\task_locals_wrapper.rs:55
  51:     0x7ff7c43a96c3 - async_std::task::builder::{{impl}}::blocking::{{closure}}<core::future::from_generator::GenFuture<generator-0>,()>
                               at C:\Users\connor\.cargo\registry\src\github.com-1ecc6299db9ec823\async-std-1.6.2\src\task\builder.rs:167
  52:     0x7ff7c43a1a0c - std::thread::local::LocalKey<core::cell::Cell<usize>>::try_with<core::cell::Cell<usize>,closure-0,()>
                               at C:\Users\connor\.rustup\toolchains\nightly-2020-06-22-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\thread\local.rs:263
  53:     0x7ff7c43a1338 - std::thread::local::LocalKey<core::cell::Cell<usize>>::with<core::cell::Cell<usize>,closure-0,()>
                               at C:\Users\connor\.rustup\toolchains\nightly-2020-06-22-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\thread\local.rs:239
  54:     0x7ff7c43a948e - async_std::task::builder::Builder::blocking<core::future::from_generator::GenFuture<generator-0>,()>
                               at C:\Users\connor\.cargo\registry\src\github.com-1ecc6299db9ec823\async-std-1.6.2\src\task\builder.rs:160
  55:     0x7ff7c439bb34 - async_std::task::block_on::block_on<core::future::from_generator::GenFuture<generator-0>,()>
                               at C:\Users\connor\.cargo\registry\src\github.com-1ecc6299db9ec823\async-std-1.6.2\src\task\block_on.rs:33
  56:     0x7ff7c43a375e - async_std::rt::RUNTIME::{{closure}}::{{closure}}
                               at C:\Users\connor\.cargo\registry\src\github.com-1ecc6299db9ec823\async-std-1.6.2\src\rt\mod.rs:30
  57:     0x7ff7c43a61a9 - std::sys_common::backtrace::__rust_begin_short_backtrace<closure-2,()>
                               at C:\Users\connor\.rustup\toolchains\nightly-2020-06-22-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\sys_common\backtrace.rs:130
  58:     0x7ff7c43a2159 - std::thread::{{impl}}::spawn_unchecked::{{closure}}::{{closure}}<closure-2,()>
                               at C:\Users\connor\.rustup\toolchains\nightly-2020-06-22-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\thread\mod.rs:475
  59:     0x7ff7c439c369 - std::panic::{{impl}}::call_once<(),closure-0>
                               at C:\Users\connor\.rustup\toolchains\nightly-2020-06-22-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\panic.rs:318
  60:     0x7ff7c43a226d - std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure-0>,()>
                               at C:\Users\connor\.rustup\toolchains\nightly-2020-06-22-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\panicking.rs:296
  61:     0x7ff7c43a3a97 - async_std::rt::RUNTIME::{{closure}}
  62:     0x7ff7c43a21d7 - std::panicking::try<(),std::panic::AssertUnwindSafe<closure-0>>
                               at C:\Users\connor\.rustup\toolchains\nightly-2020-06-22-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\panicking.rs:273
  63:     0x7ff7c439c479 - std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()>
                               at C:\Users\connor\.rustup\toolchains\nightly-2020-06-22-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\panic.rs:394
  64:     0x7ff7c43a2005 - std::thread::{{impl}}::spawn_unchecked::{{closure}}<closure-2,()>
                               at C:\Users\connor\.rustup\toolchains\nightly-2020-06-22-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\thread\mod.rs:474
  65:     0x7ff7c439c518 - core::ops::function::FnOnce::call_once<closure-0,()>
                               at C:\Users\connor\.rustup\toolchains\nightly-2020-06-22-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libcore\ops\function.rs:232
  66:     0x7ff7c443c76a - alloc::boxed::{{impl}}::call_once
                               at /rustc/a8cf3991177f30694200002cd9479ffbbe6d9a1a\src\liballoc\boxed.rs:1076
  67:     0x7ff7c443c76a - alloc::boxed::{{impl}}::call_once
                               at /rustc/a8cf3991177f30694200002cd9479ffbbe6d9a1a\src\liballoc\boxed.rs:1076
  68:     0x7ff7c443c76a - std::sys::windows::thread::{{impl}}::new::thread_start
                               at /rustc/a8cf3991177f30694200002cd9479ffbbe6d9a1a\/src\libstd\sys\windows\thread.rs:56
  69:     0x7fff532d7bd4 - BaseThreadInitThunk
  70:     0x7fff53c2ce51 - RtlUserThreadStart
```

</details>

<details>
<summary>Validation Errors</summary>

```
[2020-06-25T18:46:03Z ERROR gfx_backend_vulkan] 
    VALIDATION [VUID-vkBindImageMemory-memoryOffset-01048 (0)] : vkBindImageMemory(): memoryOffset is 0x99500 but must be an integer multiple of the VkMemoryRequirements::alignment value 0x400, returned from a call to vkGetImageMemoryRequirements with image. The Vulkan spec states: memoryOffset must be an integer multiple of the alignment member of the VkMemoryRequirements structure returned from a call to vkGetImageMemoryRequirements with image (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-vkBindImageMemory-memoryOffset-01048)
    object info: (type: IMAGE, hndl: 197676797511336874)
    
[2020-06-25T18:46:03Z ERROR gfx_backend_vulkan] 
    VALIDATION [NVIDIA (1)] : vkBindImageMemory: memoryOffset 99500 is not aligned to 400
    object info: (type: IMAGE, hndl: 2225120488496)
    
```

</details>

**Platform**

Windows 10, nvidia 1080ti  
No other platform had this behavior.  

wgpu-rs master `90307b6715f5c591db3dc7a067b704a501756557` (from yesterday)  

Trace isn't viable as details are not recorded.

**Comment by cwfitzgerald** [comment]
gfx-memory at trace level: https://send.firefox.com/download/4b3829758e4cbf92/#nSEFZVe_I7PaWUCf7O1Txw

Note my application is multithreaded so there might be some interleaving of log info, though the last bit before it crashes threads are basically all banging on a single lock.

**Comment by cwfitzgerald** [comment]
Change looks promising! Different error this time!

<details>
<summary>Backtrace</summary>

```
thread 'async-std/runtime' panicked at 'assertion failed: `(left == right)`
  left: `1024`,
 right: `0`: Requested entry block size 50944 is not aligned to 1280', C:\Users\connor\.rustup\toolchains\nightly-2020-06-22-x86_64-pc-windows-msvc\lib/rustlib/src/rust\src\libstd\macros.rs:16:9
stack backtrace:
 <-- snip; panic stuff -->
  12:     0x7ff71279d4a6 - gfx_memory::allocator::general::GeneralAllocator<gfx_backend_vulkan::Backend>::alloc_from_entry<gfx_backend_vulkan::Backend>
                               at C:\Users\connor\.rustup\toolchains\nightly-2020-06-22-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\macros.rs:16
  13:     0x7ff712799d2e - gfx_memory::allocator::general::GeneralAllocator<gfx_backend_vulkan::Backend>::alloc_chunk<gfx_backend_vulkan::Backend>
                               at C:\Users\connor\.cargo\git\checkouts\gfx-extras-cd195c4211e13d1a\1937fe7\gfx-memory\src\allocator\general.rs:283
  14:     0x7ff71279d6a5 - gfx_memory::allocator::general::GeneralAllocator<gfx_backend_vulkan::Backend>::alloc_from_entry<gfx_backend_vulkan::Backend>
                               at C:\Users\connor\.cargo\git\checkouts\gfx-extras-cd195c4211e13d1a\1937fe7\gfx-memory\src\allocator\general.rs:373
  15:     0x7ff71279721a - gfx_memory::allocator::general::GeneralAllocator<gfx_backend_vulkan::Backend>::alloc_block<gfx_backend_vulkan::Backend>
                               at C:\Users\connor\.cargo\git\checkouts\gfx-extras-cd195c4211e13d1a\1937fe7\gfx-memory\src\allocator\general.rs:432
  16:     0x7ff7127a035c - gfx_memory::allocator::general::{{impl}}::alloc<gfx_backend_vulkan::Backend>
                               at C:\Users\connor\.cargo\git\checkouts\gfx-extras-cd195c4211e13d1a\1937fe7\gfx-memory\src\allocator\general.rs:515
  17:     0x7ff712a52193 - gfx_memory::heaps::memory_type::MemoryType<gfx_backend_vulkan::Backend>::alloc<gfx_backend_vulkan::Backend>
                               at C:\Users\connor\.cargo\git\checkouts\gfx-extras-cd195c4211e13d1a\1937fe7\gfx-memory\src\heaps\memory_type.rs:85
  18:     0x7ff712bd1096 - gfx_memory::heaps::Heaps<gfx_backend_vulkan::Backend>::allocate_from<gfx_backend_vulkan::Backend>
                               at C:\Users\connor\.cargo\git\checkouts\gfx-extras-cd195c4211e13d1a\1937fe7\gfx-memory\src\heaps\mod.rs:182
  19:     0x7ff712bd3436 - gfx_memory::heaps::Heaps<gfx_backend_vulkan::Backend>::allocate<gfx_backend_vulkan::Backend>
                               at C:\Users\connor\.cargo\git\checkouts\gfx-extras-cd195c4211e13d1a\1937fe7\gfx-memory\src\heaps\mod.rs:145
  20:     0x7ff712bbbf74 - wgpu_core::device::Device<gfx_backend_vulkan::Backend>::create_buffer<gfx_backend_vulkan::Backend>
                               at C:\Users\connor\.cargo\git\checkouts\wgpu-53e70f8674b08dd4\285b31a\wgpu-core\src\device\mod.rs:431
  21:     0x7ff712af2191 - wgpu_core::hub::Global<wgpu_core::hub::IdentityManagerFactory>::device_create_buffer<wgpu_core::hub::IdentityManagerFactory,gfx_backend_vulkan::Backend>
                               at C:\Users\connor\.cargo\git\checkouts\wgpu-53e70f8674b08dd4\285b31a\wgpu-core\src\device\mod.rs:687
  22:     0x7ff712b60b31 - wgpu::backend::direct::{{impl}}::device_create_buffer
                               at C:\Users\connor\.cargo\git\checkouts\wgpu-rs-40ea39809c03c5d8\90307b6\src\backend\direct.rs:623
  23:     0x7ff71286aecb - wgpu::Device::create_buffer
                               at C:\Users\connor\.cargo\git\checkouts\wgpu-rs-40ea39809c03c5d8\90307b6\src\lib.rs:1258
  24:     0x7ff71286b058 - wgpu::Device::create_buffer_with_data
                               at C:\Users\connor\.cargo\git\checkouts\wgpu-rs-40ea39809c03c5d8\90307b6\src\lib.rs:1268
  25:     0x7ff71259cae5 - bve_render::Renderer::add_mesh<usize>
                               at C:\Users\connor\Programming\bve-reborn\bve-render\src\mesh.rs:106
  26:     0x7ff712475f37 - bve_client::{{impl}}::add_mesh
                               at C:\Users\connor\Programming\bve-reborn\bve-client\src\main.rs:131
  27:     0x7ff71259845c - bve::runtime::cache::mesh::{{impl}}::load_mesh_impl::{{closure}}<bve_client::Client>
                               at C:\Users\connor\Programming\bve-reborn\bve\src\runtime\cache\mesh.rs:85
 <-- snip; async runtime stuff -->
```

</details>
