### ISSUE TITLE
pvkrun debug wgpu app appears to crash

### ISSUE THREAD

**Issue by m4b** [gfx-rs/wgpu#760]
It looks like running a wgpu app built in debug mode will crash when run with primus vk on linux. I believe there is something about the validation layers that someone down the call chain doesn't like (just a guess)? Running in release does not have this issue (hence my guess its something about validation layers).

```
#0  0x0000000000000000 in ?? ()
gfx-rs/wgpu-rs#1  0x00007ffff3a82199 in DispatchBeginCommandBuffer (commandBuffer=0x5555589664c0, pBeginInfo=<optimized out>)
    at /usr/src/debug/Vulkan-ValidationLayers-sdk-1.2.141.0/layers/generated/layer_chassis_dispatch.cpp:2550
gfx-rs/wgpu-rs#2  0x00007ffff39c3c59 in vulkan_layer_chassis::BeginCommandBuffer (commandBuffer=0x5555589664c0, pBeginInfo=0x7ffffffed290)
    at /usr/src/debug/Vulkan-ValidationLayers-sdk-1.2.141.0/layers/generated/chassis.cpp:2875
gfx-rs/wgpu-rs#3  0x00007ffff7683dea in ImageWorker::initImages(std::tuple<long, long, long>, VkSwapchainCreateInfoKHR const&) () from /usr/lib/libprimus_vk.so
gfx-rs/wgpu-rs#4  0x00007ffff7686031 in ImageWorker::ImageWorker(PrimusSwapchain&, VkImage_T*, VkSwapchainCreateInfoKHR const&, std::tuple<long, long, long>) ()
   from /usr/lib/libprimus_vk.so
gfx-rs/wgpu-rs#5  0x00007ffff768cca7 in void std::vector<ImageWorker, std::allocator<ImageWorker> >::_M_realloc_insert<PrimusSwapchain&, VkImage_T*&, VkSwapchainCreateInfoKHR const&, std::tuple<long, long, long>&>(__gnu_cxx::__normal_iterator<ImageWorker*, std::vector<ImageWorker, std::allocator<ImageWorker> > >, PrimusSwapchain&, VkImage_T*&, VkSwapchainCreateInfoKHR const&, std::tuple<long, long, long>&) () from /usr/lib/libprimus_vk.so
gfx-rs/wgpu-rs#6  0x00007ffff768d4d9 in PrimusSwapchain::PrimusSwapchain(VkDevice_T*, VkDevice_T*, VkSwapchainKHR_T*, VkSwapchainCreateInfoKHR const*, unsigned int, std::shared_ptr<CreateOtherDevice>&) () from /usr/lib/libprimus_vk.so
gfx-rs/wgpu-rs#7  0x00007ffff76894ed in PrimusVK_CreateSwapchainKHR(VkDevice_T*, VkSwapchainCreateInfoKHR const*, VkAllocationCallbacks const*, VkSwapchainKHR_T**) ()
   from /usr/lib/libprimus_vk.so
gfx-rs/wgpu-rs#8  0x0000555557201ba5 in ash::vk::KhrSwapchainFn::create_swapchain_khr (self=0x7ffffffed7f8, device=..., p_create_info=0x7ffffffed8a8, p_allocator=0x0, 
    p_swapchain=0x7ffffffed6c8) at /home/m4b/.cargo/registry/src/github.com-1ecc6299db9ec823/ash-0.30.0/src/vk.rs:56404
gfx-rs/wgpu-rs#9  0x00005555572073f1 in ash::extensions::khr::swapchain::Swapchain::create_swapchain (self=0x7ffffffed7f0, create_info=0x7ffffffed8a8, allocation_callbacks=...)
    at /home/m4b/.cargo/registry/src/github.com-1ecc6299db9ec823/ash-0.30.0/src/extensions/khr/swapchain.rs:76
gfx-rs/wgpu-rs#10 0x0000555557183e7f in gfx_backend_vulkan::device::<impl gfx_hal::device::Device<gfx_backend_vulkan::Backend> for gfx_backend_vulkan::Device>::create_swapchain (
    self=0x5555584a5460, surface=0x5555584128f8, config=..., provided_old_swapchain=...)
    at /home/m4b/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx-backend-vulkan-0.5.8/src/device.rs:2074
gfx-rs/wgpu-rs#11 0x00005555571e6f17 in <gfx_backend_vulkan::window::Surface as gfx_hal::window::PresentationSurface<gfx_backend_vulkan::Backend>>::configure_swapchain (
    self=0x5555584128f8, device=0x5555584a5460, config=...) at /home/m4b/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx-backend-vulkan-0.5.8/src/window.rs:455
gfx-rs/wgpu-rs#12 0x0000555556fabedb in wgpu_core::device::<impl wgpu_core::hub::Global<G>>::device_create_swap_chain (self=0x555557e6fd30, device_id=..., surface_id=..., 
    desc=0x7ffffffeedc0) at /home/m4b/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-core-0.5.5/src/device/mod.rs:2056
gfx-rs/wgpu-rs#13 0x0000555556f45c90 in wgpu_device_create_swap_chain (device_id=..., surface_id=..., desc=0x7ffffffeedc0)
    at /home/m4b/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-native-0.5.0/src/device.rs:356
gfx-rs/wgpu-rs#14 0x0000555556e9f30f in wgpu::Device::create_swap_chain (self=0x7ffffffefb70, surface=0x7ffffffefaa0, desc=0x7ffffffeedc0)
```

Here's some information on bumblebee / pvkrun: https://wiki.archlinux.org/index.php/Bumblebee

This is likely an upstream error (have no idea which library, ash, primus_vk, etc.), but putting it here in case just because it only appears to happen in wgpu debug binaries, which can be confusing.

This could also be my particular bumblebee + vulkan setup, I'm not sure.

**Comment by cwfitzgerald** [comment]
Going to close as stale, if this is still a problem, please refile!
