### ISSUE TITLE
Panic in `Storage::insert`

### ISSUE THREAD

**Issue by GabrielMajeri** [gfx-rs/wgpu#778]
**Description**
I was trying to update `wgpu-rs` to the latest revision of `wgpu-core` from Git.

When running `hello-triangle`, the following panic happens:
```
thread 'main' panicked at 'index out of bounds: the len is 1 but the index is 1', /home/gabriel/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/7d50827/wgpu-core/src/hub.rs:145:18
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1069
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1504
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:511
  11: rust_begin_unwind
             at src/libstd/panicking.rs:419
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:111
  13: core::panicking::panic_bounds_check
             at src/libcore/panicking.rs:69
  14: <usize as core::slice::SliceIndex<[T]>>::index_mut
             at /home/gabriel/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/slice/mod.rs:2878
  15: core::slice::<impl core::ops::index::IndexMut<I> for [T]>::index_mut
             at /home/gabriel/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/slice/mod.rs:2743
  16: <alloc::vec::Vec<T> as core::ops::index::IndexMut<I>>::index_mut
             at /home/gabriel/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/liballoc/vec.rs:1957
  17: wgpu_core::hub::Storage<T,I>::insert
             at /home/gabriel/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/7d50827/wgpu-core/src/hub.rs:145
  18: wgpu_core::hub::Registry<T,I,F>::register
             at /home/gabriel/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/7d50827/wgpu-core/src/hub.rs:381
  19: wgpu_core::hub::Registry<T,I,F>::register_identity
             at /home/gabriel/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/7d50827/wgpu-core/src/hub.rs:407
  20: wgpu_core::device::<impl wgpu_core::hub::Global<G>>::device_create_shader_module
             at /home/gabriel/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/7d50827/wgpu-core/src/device/mod.rs:1938
  21: wgpu::backend::direct::<impl wgpu::Context for wgpu_core::hub::Global<wgpu_core::hub::IdentityManagerFactory>>::device_create_shader_module
             at src/backend/direct.rs:514
  22: wgpu::Device::create_shader_module
             at src/lib.rs:1204
  23: hello_triangle::run::{{closure}}
             at examples/hello-triangle/main.rs:35
  24: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/gabriel/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/future/mod.rs:66
  25: futures_executor::local_pool::block_on::{{closure}}
             at /home/gabriel/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.5/src/local_pool.rs:317
  26: futures_executor::local_pool::run_executor::{{closure}}
             at /home/gabriel/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.5/src/local_pool.rs:87
  27: std::thread::local::LocalKey<T>::try_with
             at /home/gabriel/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/thread/local.rs:263
  28: std::thread::local::LocalKey<T>::with
             at /home/gabriel/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/thread/local.rs:239
  29: futures_executor::local_pool::run_executor
             at /home/gabriel/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.5/src/local_pool.rs:83
  30: futures_executor::local_pool::block_on
             at /home/gabriel/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.5/src/local_pool.rs:317
  31: hello_triangle::main
             at examples/hello-triangle/main.rs:145
  32: std::rt::lang_start::{{closure}}
             at /home/gabriel/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/rt.rs:67
  33: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  34: std::panicking::try::do_call
             at src/libstd/panicking.rs:331
  35: std::panicking::try
             at src/libstd/panicking.rs:274
  36: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  37: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  38: std::rt::lang_start
             at /home/gabriel/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/rt.rs:67
  39: main
  40: __libc_start_main
  41: _start
```

The problematic array slicing is around here:
https://github.com/gfx-rs/wgpu/blob/7d5082753b2a7d69914aaacb238b112d40c794a0/wgpu-core/src/hub.rs#L144-L146

**Repro steps**
Check out https://github.com/gfx-rs/wgpu-rs/pull/430

**Platform**
Linux, X11, Vulkan

**Comment by kvark** [comment]
Uh oh, this is a regression from #776 (cc @kunalmohan )

**Comment by kunalmohan** [comment]
Oops, looks like I misread the docs. Really sorry!!

**Comment by kvark** [comment]
@kunalmohan no worries! I missed that too during the review 😅
