### ISSUE TITLE
Panic with "entered unreachable code" on destroying BGL

### ISSUE THREAD

**Issue by tiberiusferreira** [gfx-rs/wgpu#823]
Platform: MacOS 10.15.6 (19G73)

To reproduce:
- git clone https://github.com/tiberiusferreira/gpu_compute
- cargo test --package gpu_compute --lib tensors::gpu_tensor::gpu_ops::compare::tests::compare_test -- --exact

Happy to provide any additional information.
```
internal error: entered unreachable code
thread 'tensors::gpu_tensor::gpu_ops::compare::tests::compare_test' panicked at 'internal error: entered unreachable code', /Users/tiberiodarferreira/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/3c6ee87/wgpu-core/src/lib.rs:163:18
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1076
   5: std::io::Write::write_fmt
             at /rustc/346aec9b02f3c74f3fce97fd6bda24709d220e49/src/libstd/io/mod.rs:1537
   6: std::io::impls::<impl std::io::Write for alloc::boxed::Box<W>>::write_fmt
             at src/libstd/io/impls.rs:176
   7: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   8: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   9: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
  10: std::panicking::default_hook
             at src/libstd/panicking.rs:214
  11: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:526
  12: std::panicking::begin_panic
             at src/libcore/alloc/layout.rs:364
  13: wgpu_core::MultiRefCount::dec
             at /Users/tiberiodarferreira/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/3c6ee87/wgpu-core/src/lib.rs:163
  14: wgpu_core::device::<impl wgpu_core::hub::Global<G>>::bind_group_layout_destroy
             at /Users/tiberiodarferreira/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/3c6ee87/wgpu-core/src/device/mod.rs:1320
  15: wgpu::backend::direct::<impl wgpu::Context for wgpu_core::hub::Global<wgpu_core::hub::IdentityManagerFactory>>::bind_group_layout_drop
             at /Users/tiberiodarferreira/.cargo/git/checkouts/wgpu-rs-40ea39809c03c5d8/d91d046/src/backend/direct.rs:919
  16: <wgpu::BindGroupLayout as core::ops::drop::Drop>::drop
             at /Users/tiberiodarferreira/.cargo/git/checkouts/wgpu-rs-40ea39809c03c5d8/d91d046/src/lib.rs:580
  17: core::ptr::drop_in_place
             at /Users/tiberiodarferreira/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore/ptr/mod.rs:184
  18: gpu_compute::gpu_internals::shader_runner::shader_runner::<impl gpu_compute::gpu_internals::GpuInstance>::run_shader
             at src/gpu_internals/shader_runner/shader_runner.rs:103
  19: gpu_compute::tensors::gpu_tensor::gpu_ops::clone::clone::{{closure}}
             at src/tensors/gpu_tensor/gpu_ops/clone/mod.rs:13
  20: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /Users/tiberiodarferreira/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore/future/mod.rs:78
  21: gpu_compute::tensors::gpu_tensor::gpu_ops::<impl gpu_compute::tensors::gpu_tensor::GpuTensor>::clone::{{closure}}
             at src/tensors/gpu_tensor/gpu_ops/mod.rs:41
  22: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /Users/tiberiodarferreira/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore/future/mod.rs:78
  23: gpu_compute::tensors::gpu_tensor::gpu_ops::compare::tests::compare_test::{{closure}}
             at src/tensors/gpu_tensor/gpu_ops/compare/tests.rs:9
  24: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /Users/tiberiodarferreira/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore/future/mod.rs:78
  25: futures_executor::local_pool::block_on::{{closure}}
             at /Users/tiberiodarferreira/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.5/src/local_pool.rs:317
  26: futures_executor::local_pool::run_executor::{{closure}}
             at /Users/tiberiodarferreira/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.5/src/local_pool.rs:87
  27: std::thread::local::LocalKey<T>::try_with
             at /Users/tiberiodarferreira/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/thread/local.rs:263
  28: std::thread::local::LocalKey<T>::with
             at /Users/tiberiodarferreira/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/thread/local.rs:239
  29: futures_executor::local_pool::run_executor
             at /Users/tiberiodarferreira/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.5/src/local_pool.rs:83
  30: futures_executor::local_pool::block_on
             at /Users/tiberiodarferreira/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.5/src/local_pool.rs:317
  31: gpu_compute::tensors::gpu_tensor::gpu_ops::compare::tests::compare_test
             at src/tensors/gpu_tensor/gpu_ops/compare/tests.rs:20
  32: gpu_compute::tensors::gpu_tensor::gpu_ops::compare::tests::compare_test::{{closure}}
             at src/tensors/gpu_tensor/gpu_ops/compare/tests.rs:4
  33: core::ops::function::FnOnce::call_once
             at /Users/tiberiodarferreira/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore/ops/function.rs:233
  34: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/346aec9b02f3c74f3fce97fd6bda24709d220e49/src/liballoc/boxed.rs:1081
  35: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/346aec9b02f3c74f3fce97fd6bda24709d220e49/src/libstd/panic.rs:318
  36: std::panicking::try::do_call
             at /rustc/346aec9b02f3c74f3fce97fd6bda24709d220e49/src/libstd/panicking.rs:348
  37: std::panicking::try
             at /rustc/346aec9b02f3c74f3fce97fd6bda24709d220e49/src/libstd/panicking.rs:325
  38: std::panic::catch_unwind
             at /rustc/346aec9b02f3c74f3fce97fd6bda24709d220e49/src/libstd/panic.rs:394
  39: test::run_test_in_process
             at src/libtest/lib.rs:541
  40: test::run_test::run_test_inner::{{closure}}
             at src/libtest/lib.rs:450
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by kvark** [comment]
On the first look at the issue, I'm seeing various kinds of memory corruption. Illegal access, aborts, etc.
I think what's happening is GPU stomping on main memory, and we need to first make it pass Vulkan validation.

**Comment by tiberiusferreira** [comment]
New traces with shader code matching buffer/uniform declarations [traces.zip](https://github.com/gfx-rs/wgpu/files/4955698/traces.zip)
