### ISSUE TITLE
BindGroupLayout[0] does not exist (sometimes)

### ISSUE THREAD

**Issue by tiberiusferreira** [gfx-rs/wgpu#834]
Sorry, this is one of those "sometimes crashes" bugs.

OS: MacOS 10.15.6
wgpu-rs version: e785b213e409460649da5c78068f653d2634bafc

Message:
```
---- tensors::gpu_tensor::gpu_ops::bmm::tests::simple_rank_2_mm stdout ----
thread 'tensors::gpu_tensor::gpu_ops::bmm::tests::simple_rank_2_mm' panicked at 'BindGroupLayout[0] does not exist', /Users/tiberiodarferreira/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/0591c48/wgpu-core/src/device/life.rs:560:20
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Metal validation does not report anything, see another instance below with Metal Validation:

```
running 25 tests
2020-07-24 05:43:34.407 gpu_compute-68282a59c1913004[19070:1079565] Metal API Validation Enabled
test tensors::gpu_tensor::gpu_ops::fill_with::tests::fill_with ... ok
test tensors::gpu_tensor::gpu_ops::clone::tests::can_clone ... FAILED
test tensors::gpu_tensor::gpu_ops::clone::tests::can_clone_non_uniform_shape ... ok
test tensors::gpu_tensor::gpu_ops::bmm::tests::simple_rank_2_mm ... ok
test tensors::gpu_tensor::indexing::index_to_dim_stride::allows_start_equals_end ... ok
test tensors::gpu_tensor::indexing::index_to_dim_stride::can_index ... ok
test tensors::gpu_tensor::indexing::index_to_dim_stride::can_index_edge_cases ... ok
test tensors::gpu_tensor::indexing::index_to_dim_stride::cant_index_more_elements_than_dimension_has ... ok
test tensors::gpu_tensor::indexing::index_to_dim_stride::doesnt_allow_end_smaller_than_start ... ok
test tensors::gpu_tensor::indexing::test ... ok
test tensors::gpu_tensor::shape_changing::broadcast_tests::broadcast_works_from_scalar ... ok
test tensors::gpu_tensor::shape_changing::broadcast_tests::broadcast_works_with_additional_unit_dim ... ok
test tensors::gpu_tensor::shape_changing::broadcast_tests::simple_broadcast_with_skipping_works ... ok
test tensors::gpu_tensor::shape_changing::broadcast_tests::simple_broadcast_works ... ok
test tensors::gpu_tensor::gpu_ops::bmm::tests::simple_rank_2_mm_different_dims ... ok
test tensors::gpu_tensor::gpu_ops::bmm::tests::mm_with_broadcasting ... ok
test tensors::gpu_tensor::tests::broadcast_work ... ok
test tensors::gpu_tensor::tests::strides_work ... ok
test tensors::gpu_tensor::utils::can_calc_strides_from_shape ... ok
test tensors::gpu_tensor::gpu_ops::assign::tests::simple_assign ... ok
test tensors::gpu_tensor::gpu_ops::relu::tests::leaky_relu ... ok
test tensors::gpu_tensor::gpu_ops::transpose::tests::can_transpose ... ok
test tensors::gpu_tensor::gpu_ops::make_contiguous::tests::can_create_contiguous_from_view ... ok
test tensors::gpu_tensor::shape_changing::slicing_tests::slice_works ... ok
test tensors::gpu_tensor::gpu_ops::compare::tests::compare_test ... ok

failures:

---- tensors::gpu_tensor::gpu_ops::clone::tests::can_clone stdout ----
thread 'tensors::gpu_tensor::gpu_ops::clone::tests::can_clone' panicked at 'BindGroupLayout[1] does not exist', /Users/tiberiodarferreira/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/0591c48/wgpu-core/src/device/life.rs:560:20
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    tensors::gpu_tensor::gpu_ops::clone::tests::can_clone

test result: FAILED. 24 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out

```
Happens randomly while running [this lib](https://github.com/tiberiusferreira/gpu_compute) tests. Does not always fail on the same test.
[traces.zip](https://github.com/gfx-rs/wgpu-rs/files/4970959/traces.zip)

**Comment by kvark** [comment]
Do you think we could reproduce it in an example instead of tests?

**Comment by kvark** [comment]
I tried to check out `gpu_compute` again and run the tests multiple times - no luck seeing this on macOS so far.

**Comment by tiberiusferreira** [comment]
It seems to be present when multiple threads are at play, hence why it was so difficult to reproduce with "simple" single threaded tests, but present when running multiple tests in parallel.

I added an example that should show the problem here: https://github.com/tiberiusferreira/gpu_compute/blob/master/examples/simple_crashing/main.rs

it crashes for me in at least 1 thread each time
same error: ```thread '<unnamed>' panicked at 'BindGroupLayout[0] does not exist'```

**Comment by kvark** [comment]
Interestingly, I'm seeing a crash in `addDebugMarker`:
```
#0	0x00007fff7059d33a in __pthread_kill ()
#1	0x0000000101e789bc in pthread_kill ()
#2	0x00007fff70524808 in abort ()
#3	0x00007fff7061a50b in malloc_vreport ()
#4	0x00007fff7061d40f in malloc_report ()
#5	0x00007fff3637ccc5 in -[__NSArrayM insertObject:atIndex:] ()
#6	0x00007fff5cf75a0b in -[MTLDebugBuffer addDebugMarker:range:] ()
#7	0x00000001007ae663 in _$LT$$LP$A$C$$u20$B$RP$$u20$as$u20$objc..message..MessageArguments$GT$::invoke::hf7ca6b081321e16a at /Users/dmalyshau/.cargo/registry/src/github.com-1ecc6299db9ec823/objc-0.2.7/src/message/mod.rs:128
#8	0x0000000100798f44 in objc::message::platform::send_unverified::hf30b8775796f3b08 at /Users/dmalyshau/.cargo/registry/src/github.com-1ecc6299db9ec823/objc-0.2.7/src/message/apple/mod.rs:27
#9	0x00000001007bd826 in objc::message::send_message::h606a654b7f862d85 [inlined] at /Users/dmalyshau/.cargo/registry/src/github.com-1ecc6299db9ec823/objc-0.2.7/src/message/mod.rs:178
#10	0x00000001007bd7e5 in metal::buffer::BufferRef::add_debug_marker::h173198670f01354a at /Users/dmalyshau/.cargo/registry/src/github.com-1ecc6299db9ec823/metal-0.20.0/src/buffer.rs:52
#11	0x00000001004af8ef in _$LT$gfx_backend_metal..device..Device$u20$as$u20$gfx_hal..device..Device$LT$gfx_backend_metal..Backend$GT$$GT$::bind_buffer_memory::hfaa978864f1c7833 at /Users/dmalyshau/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx-backend-metal-0.5.6/src/device.rs:2389
#12	0x000000010020b1f5 in wgpu_core::device::Device$LT$B$GT$::create_buffer::h4913beb8efc7433b at /Users/dmalyshau/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/78546f4/wgpu-core/src/device/mod.rs:451
#13	0x000000010008e1cb in wgpu_core::device::_$LT$impl$u20$wgpu_core..hub..Global$LT$G$GT$$GT$::device_create_buffer::hcf600ef927732ab6 at /Users/dmalyshau/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/78546f4/wgpu-core/src/device/mod.rs:783
#14	0x000000010025fd23 in _$LT$wgpu..backend..direct..Context$u20$as$u20$wgpu..Context$GT$::device_create_buffer::hb3e345c3335b963c at /Users/dmalyshau/.cargo/git/checkouts/wgpu-rs-40ea39809c03c5d8/7087e31/src/backend/direct.rs:782
#15	0x00000001001dd8ed in _$LT$wgpu..Device$u20$as$u20$wgpu..util..DeviceExt$GT$::create_buffer_init::haaf76e308d7384cd at /Users/dmalyshau/.cargo/git/checkouts/wgpu-rs-40ea39809c03c5d8/7087e31/src/util/mod.rs:82
#16	0x00000001000474c2 in gpu_compute::gpu_internals::gpu_buffers::_$LT$impl$u20$gpu_compute..gpu_internals..GpuInstance$GT$::new_gpu_buffer_from_data::h5b54f729db0a22de at /Users/dmalyshau/Code/gpu_compute/src/gpu_internals/gpu_buffers/mod.rs:123
#17	0x0000000100062df2 in gpu_compute::tensors::gpu_tensor::accessors_contructors::_$LT$impl$u20$gpu_compute..tensors..gpu_tensor..GpuTensor$GT$::from_data_with_gpu::hb19c618e3cb12311 at /Users/dmalyshau/Code/gpu_compute/src/tensors/gpu_tensor/accessors_contructors.rs:70
#18	0x00000001000630ef in gpu_compute::tensors::gpu_tensor::accessors_contructors::_$LT$impl$u20$gpu_compute..tensors..gpu_tensor..GpuTensor$GT$::from::h1a7bf475f9e58bb7 at /Users/dmalyshau/Code/gpu_compute/src/tensors/gpu_tensor/accessors_contructors.rs:98
#19	0x0000000100002ced in simple_crashing::main::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::h6c541cc5a8376597 at /Users/dmalyshau/Code/gpu_compute/examples/simple_crashing/main.rs:9
```
The string in question is not empty. Looks more like an allocator issue in Metal? I.e. multiple objects are trying to set their debug markers simultaneously, and the shared memory allocator is not locked or something like this.
