### ISSUE TITLE
vk: double render crash

### ISSUE THREAD

**Issue by unconed** [gfx-rs/wgpu#88]
Info: Windows 10, Vulkan, Nvidia Geforce 1080.

Submitting to the device twice in the same frame causes a crash. Easiest to reproduce by taking `cube.rs` 's `render()` function and repeating its contents verbatim inside a `{...}` block.

```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `Ok(())`,
 right: `Err(ErrorDeviceLost)`', C:\Projects\gfx\src\backend\vulkan\src\lib.rs:765:9
stack backtrace:
   0: std::sys::windows::backtrace::set_frames
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858\/src\libstd\sys\windows\backtrace\mod.rs:94
   1: std::sys::windows::backtrace::unwind_backtrace
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858\/src\libstd\sys\windows\backtrace\mod.rs:81
   2: std::sys_common::backtrace::_print
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858\/src\libstd\sys_common\backtrace.rs:70
   3: std::sys_common::backtrace::print
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858\/src\libstd\sys_common\backtrace.rs:58
   4: std::panicking::default_hook::{{closure}}
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858\/src\libstd\panicking.rs:200
   5: std::panicking::default_hook
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858\/src\libstd\panicking.rs:215
   6: std::panicking::rust_panic_with_hook
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858\/src\libstd\panicking.rs:478
   7: std::panicking::continue_panic_fmt
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858\/src\libstd\panicking.rs:385
   8: std::panicking::begin_panic_fmt
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858\/src\libstd\panicking.rs:340
   9: gfx_backend_vulkan::{{impl}}::submit<gfx_backend_vulkan::command::CommandBuffer,core::iter::FlatMap<core::slice::Iter<wgpu_native::hub::Id>, alloc::vec::Vec<gfx_backend_vulkan::command::CommandBuffer>*, closure>,gfx_backend_vulkan::native::Semaphore,core::iter::FlatMap<alloc::vec::IntoIter<wgpu_native::swap_chain::SwapChainLink<u16>>, core::option::Option<(gfx_backend_vulkan::native::Semaphore*, gfx_hal::pso::PipelineStage)>, closure>,slice<gfx_backend_vulkan::native::Semaphore>*>
             at <::std::macros::panic macros>:8
  10: wgpu_native::device::wgpu_queue_submit
             at C:\Projects\wgpu\wgpu-native\src\device.rs:1155
  11: wgpu::Queue::submit
             at C:\Projects\wgpu\wgpu-rs\src\lib.rs:787
  12: cube::{{impl}}::render
             at .\src\cube.rs:385
  13: cube::framework::run<cube::Example>
             at .\src\framework.rs:127
  14: cube::main
             at .\src\cube.rs:394
  15: std::rt::lang_start::{{closure}}<()>
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858\src\libstd\rt.rs:64
  16: std::rt::lang_start_internal::{{closure}}
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858\/src\libstd\rt.rs:49
  17: std::panicking::try::do_call<closure,i32>
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858\/src\libstd\panicking.rs:297
  18: panic_unwind::__rust_maybe_catch_panic
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858\/src\libpanic_unwind\lib.rs:92
  19: std::panicking::try
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858\/src\libstd\panicking.rs:276
  20: std::panic::catch_unwind
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858\/src\libstd\panic.rs:388
  21: std::rt::lang_start_internal
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858\/src\libstd\rt.rs:48
  22: std::rt::lang_start<()>
             at /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858\src\libstd\rt.rs:64
  23: main
  24: invoke_main
             at d:\agent\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  25: __scrt_common_main_seh
             at d:\agent\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  26: BaseThreadInitThunk
  27: RtlUserThreadStart
error: process didn't exit successfully: `C:\Projects\wgpu\target\debug\cube.exe` (exit code: 101)
```

**Comment by kvark** [comment]
I did as advised, wasn't able to reproduce :/
@msiglreith could you try please?

**Comment by msiglreith** [comment]
```
ERROR 2019-03-03T17:52:36Z: gfx_backend_vulkan: [Validation]  [ UNASSIGNED-CoreValidation-DrawState-QueueForwardProgress ] Object: 0x3 (Type = 5) | Queue 0x17af7bec118 is waiting on semaphore 0x3 that has no way to be signaled.
ERROR 2019-03-03T17:52:36Z: gfx_backend_vulkan: [Validation]  [ UNASSIGNED-CoreValidation-DrawState-QueueForwardProgress ] Object: 0x2a (Type = 5) | Queue 0x17af7bec118 is waiting on semaphore 0x2a that has no way to be signaled.
```

**Comment by unconed** [comment]
I'm seeing a similar issue with submitting multiple offscreen passes on Metal (Mojave, AMD Radeon R9 M370X).

Source code to reproduce here:
https://gist.github.com/unconed/04571ca0149d3a38fae95bd7171300c4

Doing multiple `device.submit(..)` in one frame causes a segfault on the 5th frame for me.

**Comment by kvark** [comment]
Thanks for the source! I'm not able to reproduce the problem on Mojave/Intel.

**Comment by hecrj** [comment]
I have been able to reproduce this issue. [Here is the code](https://gist.github.com/hecrj/cb3614ad8a1042cdd886a5459369f87d) (it's just the `cube` example with two identical render passes).

Arch Linux (5.0.5-arch1-1-ARCH), Vulkan, NVIDIA GTX 980 (Driver Version: 418.56)

**Comment by kvark** [comment]
Was able to reproduce on Linux with NV driver :tada: It annoyingly locks up the computer, but that's better than nothing.

**Comment by kvark** [comment]
If anyone wants to check out #120 solution, that would be helpful.
