### ISSUE TITLE
Crash Replaying Trace with Arrays of Textures

### ISSUE THREAD

**Issue by cwfitzgerald** [gfx-rs/wgpu#991]
**Description**

Running the following trace with wgpu master will cause a panic gfx-backend-vulkan.

https://cwfitz.com/yEcpla.zip

**Extra materials**

<details>
<summary>Backtrace</summary>

```
thread 'main' panicked at 'index out of bounds: the len is 1 but the index is 1', C:\Users\connor\.cargo\registry\src\github.com-1ecc6299db9ec823\gfx-backend-vulkan-0.6.4\src\device.rs:1709:31
stack backtrace:
   0:     0x7ff7354eaca9 - std::backtrace_rs::backtrace::dbghelp::trace
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\..\..\backtrace\src\backtrace\dbghelp.rs:98
   1:     0x7ff7354eaca9 - std::backtrace_rs::backtrace::trace_unsynchronized
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\..\..\backtrace\src\backtrace\mod.rs:66
   2:     0x7ff7354eaca9 - std::sys_common::backtrace::_print_fmt
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\sys_common\backtrace.rs:79
   3:     0x7ff7354eaca9 - std::sys_common::backtrace::_print::{{impl}}::fmt
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\sys_common\backtrace.rs:58
   4:     0x7ff7355014cb - core::fmt::write
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\core\src\fmt\mod.rs:1082
   5:     0x7ff7354e7c14 - std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\io\mod.rs:1514
   6:     0x7ff7354edd8b - std::sys_common::backtrace::_print
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\sys_common\backtrace.rs:61
   7:     0x7ff7354edd8b - std::sys_common::backtrace::print
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\sys_common\backtrace.rs:48
   8:     0x7ff7354edd8b - std::panicking::default_hook::{{closure}}
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\panicking.rs:200
   9:     0x7ff7354ed9c9 - std::panicking::default_hook
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\panicking.rs:219
  10:     0x7ff7354ee56f - std::panicking::rust_panic_with_hook
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\panicking.rs:569
  11:     0x7ff7354ee0d5 - std::panicking::begin_panic_handler::{{closure}}
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\panicking.rs:476
  12:     0x7ff7354eb55f - std::sys_common::backtrace::__rust_end_short_backtrace<closure-0,!>
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\sys_common\backtrace.rs:153
  13:     0x7ff7354ee089 - std::panicking::begin_panic_handler
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\panicking.rs:475
  14:     0x7ff7354fef40 - core::panicking::panic_fmt
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\core\src\panicking.rs:85
  15:     0x7ff7354fef07 - core::panicking::panic_bounds_check
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\core\src\panicking.rs:62
  16:     0x7ff734c9fef3 - core::slice::{{impl}}::index<gfx_hal::pso::descriptor::DescriptorSetLayoutBinding>
                               at C:\Users\connor\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\slice\mod.rs:3282
  17:     0x7ff7347ba872 - core::slice::{{impl}}::index<gfx_hal::pso::descriptor::DescriptorSetLayoutBinding,usize>
                               at C:\Users\connor\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\slice\mod.rs:3123
  18:     0x7ff734b3c222 - alloc::vec::{{impl}}::index<gfx_hal::pso::descriptor::DescriptorSetLayoutBinding,usize>
                               at C:\Users\connor\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\alloc\src\vec.rs:2000
  19:     0x7ff734d8a6ec - gfx_backend_vulkan::device::{{impl}}::write_descriptor_sets<alloc::vec::Vec<gfx_hal::pso::descriptor::DescriptorSetWrite<gfx_backend_vulkan::Backend, smallvec::SmallVec<[gfx_hal::pso::descriptor::Descriptor<gfx_backend_vulkan::Backend>; 1
]>>>,smallvec::Sm
                               at C:\Users\connor\.cargo\registry\src\github.com-1ecc6299db9ec823\gfx-backend-vulkan-0.6.4\src\device.rs:1709
  20:     0x7ff7346a954f - wgpu_core::hub::Global<player::IdentityPassThroughFactory>::device_create_bind_group<player::IdentityPassThroughFactory,gfx_backend_vulkan::Backend>
                               at C:\Users\connor\Programming\wgpu\wgpu-core\src\device\mod.rs:2182
  21:     0x7ff73461751a - player::{{impl}}::process<gfx_backend_vulkan::Backend>
                               at C:\Users\connor\Programming\wgpu\player\src\lib.rs:195
  22:     0x7ff734d0757f - play::main::{{closure}}
                               at C:\Users\connor\Programming\wgpu\player\src\bin\play.rs:143
  23:     0x7ff7349c7208 - winit::platform_impl::platform::event_loop::{{impl}}::run_return::{{closure}}<tuple<>,closure-1>
                               at C:\Users\connor\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.2\src\platform_impl\windows\event_loop.rs:200
  24:     0x7ff73509cd73 - alloc::boxed::{{impl}}::call_mut<tuple<winit::event::Event<tuple<>>, mut winit::event_loop::ControlFlow*>,FnMut<tuple<winit::event::Event<tuple<>>, mut winit::event_loop::ControlFlow*>>>
                               at C:\Users\connor\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\alloc\src\boxed.rs:1049
  25:     0x7ff7350bafbb - winit::platform_impl::platform::event_loop::runner::{{impl}}::call_event_handler::{{closure}}<tuple<>>
                               at C:\Users\connor\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.2\src\platform_impl\windows\event_loop\runner.rs:239
  26:     0x7ff7350ae096 - std::panic::{{impl}}::call_once<tuple<>,closure-0>
                               at C:\Users\connor\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\panic.rs:308
  27:     0x7ff735082230 - std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure-0>,tuple<>>
                               at C:\Users\connor\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\panicking.rs:373
  28:     0x7ff735086097 - winit::window::{{impl}}::clone
  29:     0x7ff73508206a - std::panicking::try<tuple<>,std::panic::AssertUnwindSafe<closure-0>>
                               at C:\Users\connor\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\panicking.rs:337
  30:     0x7ff7350ae176 - std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure-0>,tuple<>>
                               at C:\Users\connor\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\panic.rs:379
  31:     0x7ff7350b9ff9 - winit::platform_impl::platform::event_loop::runner::EventLoopRunner<tuple<>>::catch_unwind<tuple<>,tuple<>,closure-0>
                               at C:\Users\connor\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.2\src\platform_impl\windows\event_loop\runner.rs:150
  32:     0x7ff7350bad51 - winit::platform_impl::platform::event_loop::runner::EventLoopRunner<tuple<>>::call_event_handler<tuple<>>
                               at C:\Users\connor\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.2\src\platform_impl\windows\event_loop\runner.rs:233
  33:     0x7ff7350baae7 - winit::platform_impl::platform::event_loop::runner::EventLoopRunner<tuple<>>::send_event<tuple<>>
                               at C:\Users\connor\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.2\src\platform_impl\windows\event_loop\runner.rs:208
  34:     0x7ff7349c735a - winit::platform_impl::platform::event_loop::SubclassInput<tuple<>>::send_event<tuple<>>
                               at C:\Users\connor\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.2\src\platform_impl\windows\event_loop.rs:90
  35:     0x7ff7349c7d02 - winit::platform_impl::platform::event_loop::public_window_callback::{{closure}}<tuple<>>
                               at C:\Users\connor\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.2\src\platform_impl\windows\event_loop.rs:819
  36:     0x7ff734c35187 - core::ops::function::FnOnce::call_once<closure-0,tuple<>>
                               at C:\Users\connor\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\ops\function.rs:227
  37:     0x7ff734d82b23 - std::panic::{{impl}}::call_once<isize,closure-0>
                               at C:\Users\connor\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\panic.rs:308
  38:     0x7ff7345a966e - std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure-0>,isize>
                               at C:\Users\connor\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\panicking.rs:373
  39:     0x7ff7345a9777 - std::panicking::try::do_catch<std::panic::AssertUnwindSafe<closure-0>,isize>
  40:     0x7ff7345a9563 - std::panicking::try<isize,std::panic::AssertUnwindSafe<closure-0>>
                               at C:\Users\connor\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\panicking.rs:337
  41:     0x7ff734d82b7e - std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure-0>,isize>
                               at C:\Users\connor\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\panic.rs:379
  42:     0x7ff734741dd3 - winit::platform_impl::platform::event_loop::runner::EventLoopRunner<tuple<>>::catch_unwind<tuple<>,isize,closure-0>
                               at C:\Users\connor\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.2\src\platform_impl\windows\event_loop\runner.rs:150
  43:     0x7ff7349c750f - winit::platform_impl::platform::event_loop::public_window_callback<tuple<>>
                               at C:\Users\connor\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.2\src\platform_impl\windows\event_loop.rs:1893
  44:     0x7ff97c8ab762 - DefSubclassProc
  45:     0x7ff97c8ab625 - DefSubclassProc
  46:     0x7ff9a0845c7d - CallWindowProcW
  47:     0x7ff9a084584c - DispatchMessageW
  48:     0x7ff9a0851fe3 - IsWindowVisible
  49:     0x7ff9a147fde4 - KiUserCallbackDispatcher
  50:     0x7ff99e671764 - NtUserDispatchMessage
  51:     0x7ff9a084575c - DispatchMessageW
  52:     0x7ff7349c6eda - winit::platform_impl::platform::event_loop::EventLoop<tuple<>>::run_return<tuple<>,closure-1>
                               at C:\Users\connor\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.2\src\platform_impl\windows\event_loop.rs:215
  53:     0x7ff7349c7286 - winit::platform_impl::platform::event_loop::EventLoop<tuple<>>::run<tuple<>,closure-1>
                               at C:\Users\connor\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.2\src\platform_impl\windows\event_loop.rs:185
  54:     0x7ff7349c681d - winit::event_loop::EventLoop<tuple<>>::run<tuple<>,closure-1>
                               at C:\Users\connor\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.2\src\event_loop.rs:149
  55:     0x7ff734c78ede - play::main
                               at C:\Users\connor\Programming\wgpu\player\src\bin\play.rs:119
  56:     0x7ff734c350eb - core::ops::function::FnOnce::call_once<fn(),tuple<>>
                               at C:\Users\connor\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\ops\function.rs:227
  57:     0x7ff7349c642b - std::sys_common::backtrace::__rust_begin_short_backtrace<fn(),tuple<>>
                               at C:\Users\connor\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\sys_common\backtrace.rs:137
  58:     0x7ff734a11151 - std::rt::lang_start::{{closure}}<tuple<>>
                               at C:\Users\connor\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\rt.rs:66
  59:     0x7ff7354ee886 - core::ops::function::impls::{{impl}}::call_once
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\library\core\src\ops\function.rs:280
  60:     0x7ff7354ee886 - std::panicking::try::do_call
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\panicking.rs:373
  61:     0x7ff7354ee886 - std::panicking::try
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\panicking.rs:337
  62:     0x7ff7354ee886 - std::panic::catch_unwind
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\panic.rs:379
  63:     0x7ff7354ee886 - std::rt::lang_start_internal
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\rt.rs:51
  64:     0x7ff734a11123 - std::rt::lang_start<tuple<>>
                               at C:\Users\connor\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\rt.rs:65
  65:     0x7ff734c79290 - main
  66:     0x7ff735748780 - invoke_main
                               at d:\agent\_work\5\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  67:     0x7ff735748780 - __scrt_common_main_seh
                               at d:\agent\_work\5\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  68:     0x7ff9a0777bd4 - BaseThreadInitThunk
  69:     0x7ff9a144ce51 - RtlUserThreadStart
```

</details>

**Comment by cwfitzgerald** [comment]
Fixed in gfx-backend-vulkan 0.6.5
