### ISSUE TITLE
Access violation or debug assertion when using dx12

### ISSUE THREAD

**Issue by Dinnerbone** [gfx-rs/wgpu#993]
**Description**
I'm still not sure exactly what causes this, but when we use dx12 "enough" then we either run into a debug assertion and panic, or crash with an access violation. This doesn't appear to happen on vulkan, and we can't test dx11 on our application yet.

Whilst monitoring system resources during the provided repo sample, memory (pc or gpu) does not significantly climb and doesn't appear to come anywhere near my limits, so I do not believe this is a lack of resources.

**Repro steps**
- Download and extract [this collection of swfs](https://1drv.ms/u/s!Ahj0cdXAjtcmqTHE0TVT-88Fnj2b?e=WsPjSg)
- Clone [Ruffle](https://github.com/ruffle-rs/ruffle/)
- Run: `cargo run --package exporter -- ./newgrounds_bigger_sample/ ./out -g dx12`
- Observe a panic after about 105 swfs.

**Expected vs observed behavior**
I expect to remain calm and orderly, with minimal panics.

**Extra materials**
```
thread 'main' panicked at 'assertion failed: !self.is_null()', C:\Users\dinne\.cargo\registry\src\github.com-1ecc6299db9ec823\d3d12-0.3.2\src\com.rs:75:9
stack backtrace:
   0: std::panicking::begin_panic<str*>
             at C:\Users\dinne\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\panicking.rs:497
   1: d3d12::com::{{impl}}::deref<winapi::um::d3d12::ID3D12DescriptorHeap>
             at C:\Users\dinne\.cargo\registry\src\github.com-1ecc6299db9ec823\d3d12-0.3.2\src\com.rs:75
   2: d3d12::com::WeakPtr<winapi::um::d3d12::ID3D12DescriptorHeap>::start_cpu_descriptor
             at C:\Users\dinne\.cargo\registry\src\github.com-1ecc6299db9ec823\d3d12-0.3.2\src\descriptor.rs:33
   3: gfx_backend_dx12::descriptors_cpu::Heap::new
             at C:\Users\dinne\.cargo\registry\src\github.com-1ecc6299db9ec823\gfx-backend-dx12-0.6.8\src\descriptors_cpu.rs:89
   4: gfx_backend_dx12::descriptors_cpu::{{impl}}::alloc_handle::{{closure}}
             at C:\Users\dinne\.cargo\registry\src\github.com-1ecc6299db9ec823\gfx-backend-dx12-0.6.8\src\descriptors_cpu.rs:142
   5: core::option::Option<usize>::unwrap_or_else<usize,closure-0>
             at C:\Users\dinne\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\option.rs:411
   6: gfx_backend_dx12::descriptors_cpu::DescriptorCpuPool::alloc_handle
             at C:\Users\dinne\.cargo\registry\src\github.com-1ecc6299db9ec823\gfx-backend-dx12-0.6.8\src\descriptors_cpu.rs:139
   7: gfx_backend_dx12::device::{{impl}}::bind_buffer_memory
             at C:\Users\dinne\.cargo\registry\src\github.com-1ecc6299db9ec823\gfx-backend-dx12-0.6.8\src\device.rs:2257
   8: wgpu_core::device::Device<gfx_backend_dx12::Backend>::create_buffer<gfx_backend_dx12::Backend>
             at C:\Users\dinne\.cargo\git\checkouts\wgpu-53e70f8674b08dd4\7ac706f\wgpu-core\src\device\mod.rs:486
   9: wgpu_core::hub::Global<wgpu_core::hub::IdentityManagerFactory>::device_create_buffer<wgpu_core::hub::IdentityManagerFactory,gfx_backend_dx12::Backend>
             at C:\Users\dinne\.cargo\git\checkouts\wgpu-53e70f8674b08dd4\7ac706f\wgpu-core\src\device\mod.rs:1022
  10: wgpu::backend::direct::{{impl}}::device_create_buffer
             at C:\Users\dinne\.cargo\git\checkouts\wgpu-rs-40ea39809c03c5d8\e3eadca\src\backend\direct.rs:894
  11: wgpu::Device::create_buffer
             at C:\Users\dinne\.cargo\git\checkouts\wgpu-rs-40ea39809c03c5d8\e3eadca\src\lib.rs:1518
  12: ruffle_render_wgpu::WgpuRenderBackend<ruffle_render_wgpu::target::TextureTarget>::register_shape_internal<ruffle_render_wgpu::target::TextureTarget>
             at .\render\wgpu\src\lib.rs:283
  13: ruffle_render_wgpu::{{impl}}::register_shape<ruffle_render_wgpu::target::TextureTarget>
             at .\render\wgpu\src\lib.rs:802
  14: ruffle_core::display_object::graphic::Graphic::from_swf_tag
             at .\core\src\display_object\graphic.rs:23
  15: ruffle_core::display_object::movie_clip::MovieClipData::define_shape
             at .\core\src\display_object\movie_clip.rs:2201
  16: ruffle_core::display_object::movie_clip::{{impl}}::preload::{{closure}}
             at .\core\src\display_object\movie_clip.rs:268
  17: ruffle_core::tag_utils::decode_tags<slice<u8>*,closure-0>
             at .\core\src\tag_utils.rs:304
  18: ruffle_core::display_object::movie_clip::MovieClip::preload
             at .\core\src\display_object\movie_clip.rs:392
  19: ruffle_core::player::{{impl}}::preload::{{closure}}
             at .\core\src\player.rs:795
  20: ruffle_core::player::{{impl}}::mutate_with_update_context::{{closure}}<closure-0,tuple<>>
             at .\core\src\player.rs:1153
  21: ruffle_core::player::GcArena::mutate<closure-0,tuple<>>
             at C:\Users\dinne\.cargo\registry\src\github.com-1ecc6299db9ec823\gc-arena-0.2.0\src\arena.rs:161
  22: ruffle_core::player::Player::mutate_with_update_context<closure-0,tuple<>>
             at .\core\src\player.rs:1100
  23: ruffle_core::player::Player::preload
             at .\core\src\player.rs:792
  24: ruffle_core::player::Player::set_root_movie
             at .\core\src\player.rs:413
  25: exporter::take_screenshot
             at .\exporter\src\main.rs:120
  26: exporter::capture_multiple_swfs
             at .\exporter\src\main.rs:292
  27: exporter::main
             at .\exporter\src\main.rs:396
  28: core::ops::function::FnOnce::call_once<fn() -> core::result::Result<tuple<>, alloc::boxed::Box<Error>>,tuple<>>
             at C:\Users\dinne\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\ops\function.rs:227
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: process didn't exit successfully: `target\debug\exporter.exe W:\swfs\crash\newgrounds_sample out -g dx12` (exit code: 0xc0000409, STATUS_STACK_BUFFER_OVERRUN)
```

**Platform**
Windows 10 Enterprise, 64 bit
DirectX 12 backend
GeForce RTX 2080 TI on driver 452.06 (downgraded to ensure this isn't related to #983)

**Comment by kvark** [comment]
Interestingly, it doesn't fail on DX12/Intel. I do have an idea of what is going wrong there: dx12 backend didn't know how to free descriptors at all. I'm addressing this in https://github.com/gfx-rs/gfx/pull/3418

**Comment by kvark** [comment]
The updated DX12 backend is now published. Please feel free to re-open if this is still happening!
